### ISSUE TITLE
hyperlink inactive in [shrink] option

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#100]
Originally reported by: **Anonymous**

----------------------------------------

Dear rivanvx, 
I found that return button cannot work if I add [shrink] in the beginning of frame..This is sample:

    
    #!latex
    
    \frame**[shrink]**{\frametitle{Primers}
    \hfill\hyperlink{fragments}{\beamergotobutton{Back}}
    \begin{table}[ht]
    ....
    }
    
    
BUT, if I remove **[shrink]**, I can press the Back button...
Please help me how to solve it as I need both [shrink] and hyperlink to back to my main frame.
Thank you...  
-Hendri-

----------------------------------------
- Bitbucket: https://bitbucket.org/rivanvx/beamer/issue/100

**Comment by josephwright** [comment]
*Original comment by* **Vedran Miletić (Bitbucket: [rivanvx](https://bitbucket.org/rivanvx), GitHub: Unknown)**:

----------------------------------------

I'm not sure that using [shrink] is good idea in general, as Till mentions in the manual.

Joseph, can you take a look and see if anything can be done?

**Comment by josephwright** [comment]
*Original comment by* **Joseph Wright (Bitbucket: [josephwright](https://bitbucket.org/josephwright), GitHub: [josephwright](https://github.com/josephwright))**:

----------------------------------------

This is 'works for me' with minimal example
    
    #!latex
    
    \documentclass{beamer}
    \begin{document}
    \begin{frame}{Frame one}
    \end{frame}
    \begin{frame}[shrink]{Frame two}
    \hyperlink{test}{\beamergotobutton{Back}}
    \end{frame}
    \end{document}
    
    
I'll close on this basis: reopen if you can provide an example showing the behaviour using the latest release.

**Comment by josephwright** [comment]
*Original comment by* **Anonymous**:

----------------------------------------

Hello, I need some help from you. I want to add \begin{frame}[shrink] [label=ii] to shrink the frame and  hyperlink in the same frame  but there is a problem. Can you help me. Thank you everybody.

**Comment by liar666** [comment]
Same problem here.

In fact, it's not that the link is inactive, but that the **clickable area for the link is way out of
the text for the link**... Shrinking does not seem to apply identically to the clickable area and the text.

MWE: If you apply `org-beamer-export-to-pdf` to the following `org` file:
[test.org.txt](https://github.com/josephwright/beamer/files/12703565/test.org.txt)
you get the following `tex` file:
[test.tex.txt](https://github.com/josephwright/beamer/files/12703566/test.tex.txt)
If you open it in Evince or PDF.js (or any other PDF viewer), you'll find that the clickable areas are generally slightly above the text of the link (at least with shrink=10).
