### ISSUE TITLE
Header/footer and vertical centering of the body text

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#13]
Originally reported by: **Nico Schlömer (Bitbucket: [nschloe](https://bitbucket.org/nschloe), GitHub: [nschloe](https://github.com/nschloe))**

----------------------------------------

Hi,

when putting a, say, 3cm high image at the footer of each page, the body text still gets vertically centered in the middle of the page. It should however be vertically centered between the top and 3cm above the bottom line.

Not sure if there's any way already to tell beamer about the vertical centering manually somehow.

Cheers,
Nico

----------------------------------------
- Bitbucket: https://bitbucket.org/rivanvx/beamer/issue/13

**Comment by josephwright** [comment]
*Original comment by* **Vedran Miletić (Bitbucket: [rivanvx](https://bitbucket.org/rivanvx), GitHub: Unknown)**:

----------------------------------------

I'm not sure this is how things work or should work, because beamer understand picture on each page as being "in background".

Also, this can be worked around with \vspace{3cm} after text on each slide. Is this OK with you?

**Comment by josephwright** [comment]
*Original comment by* **Vedran Miletić (Bitbucket: [rivanvx](https://bitbucket.org/rivanvx), GitHub: Unknown)**:

----------------------------------------

Also, you can try putting `\hbox{\vbox{}}` around your image, it might do the trick.

**Comment by josephwright** [comment]
*Original comment by* **Nico Schlömer (Bitbucket: [nschloe](https://bitbucket.org/nschloe), GitHub: [nschloe](https://github.com/nschloe))**:

----------------------------------------

I tried `\hbox{\vbox{}}` to no avail. The image is incorporated into the theme via
    
    \pgftext[right,bottom,at=\uWavePos]{\pgfuseimage{wave}}
    
where 'wave' is declared earlier as
    
    \pgfdeclareimage[width=\wavewidth,height=\waveheight]{wave}{bottomwave}
    
Not sure if this has to do with the issue.

**Comment by samcarter** [comment]
It seems this has been fixed in the meantime

```
\documentclass{beamer}

\setbeamertemplate{footline}{\includegraphics[height=5cm]{example-image-duck}}

\begin{document}
	
\begin{frame}
	abc
\end{frame}	
	
\end{document}
```

![document](https://user-images.githubusercontent.com/43832342/225895124-d64b8872-1d43-4fa3-b296-32ef9572b5cd.png)
