### ISSUE TITLE
ignorenonframetext and include

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#130]
Originally reported by: **Niccolo_M (Bitbucket: [Niccolo_M](https://bitbucket.org/Niccolo_M), GitHub: Unknown)**

----------------------------------------

If the option `ignorenonframetext` is used, then all `\include`/`\import` statements are ignored, too. Therefore it is impossible to break larger talks, like a series of lectures into several files.

`\include`/`\import` should always work, even in `ignorenonframetext`-mode.

----------------------------------------
- Bitbucket: https://bitbucket.org/rivanvx/beamer/issue/130

**Comment by josephwright** [comment]
*Original comment by* **Vedran Miletić (Bitbucket: [rivanvx](https://bitbucket.org/rivanvx), GitHub: Unknown)**:

----------------------------------------

Sure, that would be useful, although I'm not sure it's easy to do.

**Comment by josephwright** [comment]
*Original comment by* **Anonymous**:

----------------------------------------

Hi. See also my new update to bug #90

**Comment by josephwright** [comment]
*Original comment by* **Joseph Wright (Bitbucket: [josephwright](https://bitbucket.org/josephwright), GitHub: [josephwright](https://github.com/josephwright))**:

----------------------------------------

For the moment, I'm making this a feature request, so I can keep a track of the real bugs.

**Comment by josephwright** [comment]
@FrankMittelbach asked about `\input`, which is in the same area and is core LaTeX (I'm less sure about the idea of having `\include` in a presentation or even lecture series). I'll certainly look at this for the next release.

**Comment by FrankMittelbach** [comment]
I think `\include` is in the same category really (though I have no idea whether or not people would really use `\include` in beamer sources) beasically both are document structuring methods and should somehow be transparent to `ignorenonframetext` in my opinion.

**Comment by josephwright** [comment]
@FrankMittelbach  Yes agreed: I'll look to cover the LaTeX core concepts (`\input` and `\include`) for the next release.

**Comment by FrankMittelbach** [comment]
There is perhaps one more:  `\endinput`. Not sure this is "proper" LaTeX, but then it is really convenient to have a trash area in a file where you can park unused material and for me that is usually after `\endinput`.

Of course one can write 
```latex 
\mode<all>{\endinput}
```
but that doesn't have the same look and feel :-)

**Comment by josephwright** [comment]
Dealing with `\input` is rather easier than dealing with `\include` ...

**Comment by josephwright** [comment]
From Frank by mail:

> Dealing with `\input` is rather easier than dealing with `\include` ...

why does this make a difference? Isn't it mainly recognizing the token at the beginning of the line and then executing the line?

Haven't tried things with \include but anything else always works by add `\mode<all>` in front (which could be an easier way as that means just a little documentation

**Comment by josephwright** [comment]
@FrankMittelbach `\input` is relatively simple as nothing follows the primitive step internally (in the 'success' case). On the other hand, for `\include` there are things that happen after the underlying primitive. Currently, I'm worrying about the `filehook` package and some odd issues with the name of the `.aux` file used (seem to be 'leaking' the mode save/restore stack into the name!). It's all solvable, I'm sure ...

**Comment by josephwright** [comment]
OK, for the present I'm going to do just `\input`: `beamer` doesn't have `\chapter` so `\include` is likely not that useful.

**Comment by josephwright** [comment]
Hmm, had to back that out: I'll look again for v3.38!
