### ISSUE TITLE
footcite in a beamer slide

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#132]
Originally reported by: **Anonymous**

----------------------------------------

It seems that beamer doesn't support the footbib package. Is there any way to make the cited references appear in the footnote area?
Thank you a lot!

----------------------------------------
- Bitbucket: https://bitbucket.org/rivanvx/beamer/issue/132

**Comment by josephwright** [comment]
*Original comment by* **Joseph Wright (Bitbucket: [josephwright](https://bitbucket.org/josephwright), GitHub: [josephwright](https://github.com/josephwright))**:

----------------------------------------

This is doable with biblatex
    
    #!latex
    \begin{filecontents}{\jobname.bib}
    @article{Test,
      authors = "Other, A. N.",
      journal = "J.~Irrep. Res.",
      year    = "2011",
      pages   = "1-10"
    }
    \end{filecontents}
    \documentclass{beamer}
    \usepackage{biblatex}
    \addbibresource{\jobname.bib}
    \begin{document}
    \begin{frame}
    Test\footfullcite{Test}
    \end{frame}
    \end{document}
    
Unless there is a very good reason, I'll close this bug as using biblatex is probably a cleaner approach all-round than using footcite.

**Comment by josephwright** [comment]
*Original comment by* **Joseph Wright (Bitbucket: [josephwright](https://bitbucket.org/josephwright), GitHub: [josephwright](https://github.com/josephwright))**:

----------------------------------------

No further feedback, closing as I said before.

**Comment by ghost** [comment]
citing the same key twice with \footfullcite creates two citations :-(
