### ISSUE TITLE
XeLaTeX and multimedia package not compatible

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#135]
Originally reported by: **jeutzsch (Bitbucket: [jeutzsch](https://bitbucket.org/jeutzsch), GitHub: [jeutzsch](https://github.com/jeutzsch))**

----------------------------------------

As a linguist regularly using many non-standard characters, I am very happy with XeLaTeX's ability to understand Unicode. However, I was hoping to create a presentation with multimedia sound files linked into it using beamer class, and was very disappointed that the multimedia package is not compatible with XeLaTeX.
Are there any work-arounds for this? Or plans to include XeLaTeX and multimedia compatibility in the future?
I'm not sure if this should be considered a bug or an enhancement...

----------------------------------------
- Bitbucket: https://bitbucket.org/rivanvx/beamer/issue/135

**Comment by josephwright** [comment]
*Original comment by* **Joseph Wright (Bitbucket: [josephwright](https://bitbucket.org/josephwright), GitHub: [josephwright](https://github.com/josephwright))**:

----------------------------------------

This is a complex one, as it relates to the low-level drivers needed for inclusion. I'm not sure how easy or even doable this is, but will leave it open as it fits into a set of XeTeX-related bugs.

**Comment by josephwright** [comment]
*Original comment by* **Joseph Wright (Bitbucket: [josephwright](https://bitbucket.org/josephwright), GitHub: [josephwright](https://github.com/josephwright))**:

----------------------------------------

I wonder if this is covered by the [`media9`](http://ctan.org/pkg/media9) package, which uses Flash (Acrobat only) to embed media. The problem for me with this issue is that the whole area of media inclusion is specialist, and looks better handled by a package rather than `beamer`.

**Comment by josephwright** [comment]
*Original comment by* **jeutzsch (Bitbucket: [jeutzsch](https://bitbucket.org/jeutzsch), GitHub: [jeutzsch](https://github.com/jeutzsch))**:

----------------------------------------

Media9 is indeed my current workaround, and it does a ok job (I've only used it for audio files). However, as Joseph points out, it uses Flash, and thus only works with Acrobat as the pdf-viewer.

**Comment by josephwright** [comment]
*Original comment by* **Joseph Wright (Bitbucket: [josephwright](https://bitbucket.org/josephwright), GitHub: [josephwright](https://github.com/josephwright))**:

----------------------------------------

The reason for the WONTFIX is that there _is_ no general solution that works with all PDF viewers, and it's also very much on the borderline of `beamer`'s scope (Till wrote `multimedia` some years ago, and the situation now is very different regarding availability of support for media inclusion).

**Comment by SFr682k** [comment]
@jeutzsch
Actually, it seems that the problem is due to `multimedia` using some of pdfLaTeX's extended primitives missing in XeLaTeX and LuaLaTeX

Actually I don't know whether there is a workaround for XeLaTeX, but with LuaLaTeX, using the `luatex85` packages solves this issue (at least for the `\movie` command)
