### ISSUE TITLE
Using beamer defined colors within beamerarticle

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#144]
Originally reported by: **ignasi (Bitbucket: [ignasi](https://bitbucket.org/ignasi), GitHub: [ignasi](https://github.com/ignasi))**

----------------------------------------

I would like to use beamer colors with `beamerarticle`. This way I could change `beamertheme` and obtain a `beamerarticle` with similar look.

Attached file shows what I would like. If you compile it you will get a slide, but changing `\documentclass{beamer}` by `\documentclass{article}` +
`\usepackage{beamerarticle}`

I get
```
! Package xcolor Error: Undefined color `fg'.

See the xcolor package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.16 ..., fill=bg!50!white] (0,0) rectangle (5,3);
```
Thank you

Ignasi

```
\documentclass[ignorenonframetext]{beamer}

%\documentclass{article}
%\usepackage{beamerarticle}

\usepackage{tikz}
\usecolortheme{beaver}

\listfiles
\begin{document}

This is some text outside any frame.

\begin{frame}{Frame}
\begin{alertblock}{Block}
\usebeamercolor[fg]{example text}
\begin{tikzpicture}
\filldraw[color=., fill=example text.bg!50!white] (0,0) rectangle (5,3);
\draw[line width=5mm] (1,1)--(2,2);
\end{tikzpicture}
\end{alertblock}
\end{frame}
\end{document}
```

----------------------------------------
- Bitbucket: https://bitbucket.org/rivanvx/beamer/issue/144

**Comment by louisstuart96** [comment]
Partly fixed in https://github.com/josephwright/beamer/commit/719445d574c1779698a1f1360fe1e31661126643.
