### ISSUE TITLE
Error in documentation: "bibliography entry journal"

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#155]
Originally reported by: **Nicola Tuveri (Bitbucket: [romen](https://bitbucket.org/romen), GitHub: [romen](https://github.com/romen))**

----------------------------------------

The beamer user manual reports that the template/color/font setting for text after the 2nd newblock of a bib entry is named "bibliography entry journal", while looking at the code it's called "bibliography entry location", hence setting anything using "journal" has no effect at all.

Actually I would say that, from a logical POV the documentation name is more fitting so it might be better to call it "journal" raplacing "location" with "journal" in the underlying code.

----------------------------------------
- Bitbucket: https://bitbucket.org/rivanvx/beamer/issue/155

**Comment by josephwright** [comment]
*Original comment by* **Joseph Wright (Bitbucket: [josephwright](https://bitbucket.org/josephwright), GitHub: [josephwright](https://github.com/josephwright))**:

----------------------------------------

This seems to be correct in the current source. While I'd agree the name is odd, I'm reluctant to alter it now.

**Comment by asr** [comment]
> While I'd agree the name is odd, I'm reluctant to alter it now.

Did you change your mind?

The documentation for Beamer 3.46 says:

```
Four templates govern the appearance of the author, title, journal, and note text.
...
Beamer-Template/-Color/-Font bibliography entry author
...
Beamer-Template/-Color/-Font bibliography entry title
...
Beamer-Template/-Color/-Font bibliography entry location
...
Beamer-Template/-Color/-Font bibliography entry note
```

which seems unnecessarily confusing.

**Comment by asr** [comment]
The same happens in the documentation for 3.47.
