### ISSUE TITLE
Don't count appendix in total frame count

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#174]
Originally reported by: **Nikolaus Rath (Bitbucket: [nikratio](https://bitbucket.org/nikratio), GitHub: [nikratio](https://github.com/nikratio))**

----------------------------------------

It would be nice if http://cpbl.econ.ubc.ca/web/software/latex/appendixnumberbeamer.sty could become a standard beamer option rather than a separate package. I think there's interest in this functionality from quite a few people, http://stackoverflow.com/questions/732902/ignoring-page-numbers-in-backup-slides.

----------------------------------------
- Bitbucket: https://bitbucket.org/rivanvx/beamer/issue/174

**Comment by josephwright** [comment]
Code linked has vanished :( I'm happy to look at this, but might not be that soon unless I've got something to work from.

**Comment by ghost** [comment]
The linked code probably was https://www.ctan.org/tex-archive/macros/latex/contrib/beamer-contrib/appendixnumberbeamer

**Comment by josephwright** [comment]
@samcarter8 Ah, likely: I'll add this to the 'soon-ish' release schedule then (need to talk to the package author, etc.).

**Comment by ghost** [comment]
basically solved by https://github.com/josephwright/beamer/commit/0a7af8a222ac680946df60ee3afa6328cfa6e2ba
