### ISSUE TITLE
Using `bibunits' with beamer?

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#179]
Originally reported by: **Anonymous**

----------------------------------------

Hi!

Is it possible to have something like per-chapter bibliography with beamer?

I tried it like this: http://pastebin.ca/2127960

However, it fails:
```
[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}] (./bu1.aux)

LaTeX Warning: Citation `blub123' on page 2 undefined on input line 16.

(./bu1.bbl (/usr/share/texmf-texlive/tex/latex/amsfonts/umsa.fd)
(/usr/share/texmf-texlive/tex/latex/amsfonts/umsb.fd)) (./bu1.aux

! LaTeX Error: Can be used only in preamble.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.4 ...{blub123}{\hyperlink {beamerbibblub123}{1}}
```

It would be very nice to have usual bibliography macros. However, the manual seems to suggest to manually place the `\bibitems` into the text. Any chance to get these two to work together?

Thanks,
Jan-Benedict Glaw

----------------------------------------
- Bitbucket: https://bitbucket.org/rivanvx/beamer/issue/179

**Comment by josephwright** [comment]
*Original comment by* **Anonymous**:

----------------------------------------

This was testes with Debian unstable. It seems to currently ship (quite aged) beamer-3.10. Any chance that this is fixed in current versions?

**Comment by josephwright** [comment]
*Original comment by* **Joseph Wright (Bitbucket: [josephwright](https://bitbucket.org/josephwright), GitHub: [josephwright](https://github.com/josephwright))**:

----------------------------------------

I'm marking this as a feature request: bibliography support is rather limited in beamer, and I am not sure how much work would be needed to get this to work. I would suggest you take a look at biblatex, which does work with beamer and which is able to do bibliographies split by chapter/section and so on.

**Comment by josephwright** [comment]
I'm putting this down for release-after-next and will make a decision whether to support at all at that stage.

**Comment by samcarter** [comment]
Beamer works fine now with `bibunits`:

```
\documentclass{beamer}
\usepackage{bibunits}
\begin{document}

\begin{bibunit}[plain]
\begin{frame}
\cite{knuth:ct}
\cite{aristotle:physics}
\end{frame}
\begin{frame}
\putbib[biblatex-examples]
\end{frame}
\end{bibunit}

\begin{bibunit}[alpha]
\begin{frame}
\cite{weinberg}
\end{frame}
\begin{frame}
\putbib[biblatex-examples]
\end{frame}
\end{bibunit}

\end{document}
```

![Screen Shot 2019-11-28 at 12 20 47](https://user-images.githubusercontent.com/43832342/69802295-8b3fa180-11d9-11ea-99a3-de276fc134e0.png)
