### ISSUE TITLE
miniframes and smoothbars don't show progress markers without subsections

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#218]
Originally reported by: **idleroux (Bitbucket: [idleroux](https://bitbucket.org/idleroux), GitHub: Unknown)**

----------------------------------------

The outer themes `miniframes` and `smoothbars` normally display a row of filled and empty circles to show progress through the current subsection.  However, if the document contains no subsections, this display is missing, even if the option `subsection=false` is used to suppress the display of subsection information.  Example:

    \documentclass{beamer}
    
    \useoutertheme[subsection=false]{miniframes}
    % \useoutertheme[subsection=false]{smoothbars}
    \usecolortheme{whale}
    
    \begin{document}
    
    \section{Section}
    \subsection{Subsection}
    \begin{frame}{A slide}
      With content
    \end{frame}
    
    \begin{frame}{Another slide}
      Different content
    \end{frame}
    
    \end{document}
    
    

With the dummy `\subsection` command, the resulting slides have a progress indicator.  Removing this line has no visible effect on the document structure, but the progress indicator disappears.

-- IDL

----------------------------------------
- Bitbucket: https://bitbucket.org/rivanvx/beamer/issue/218

**Comment by josephwright** [comment]
*Original comment by* **Joseph Wright (Bitbucket: [josephwright](https://bitbucket.org/josephwright), GitHub: [josephwright](https://github.com/josephwright))**:

----------------------------------------

OK, this is one of those 'What did Till actually intend?' problems: the current definition of `\slideentry` simply ignores the case where there are no subsections. I need to think about the correct change here: Till was pretty inconsistent with respect to sections.

**Comment by josephwright** [comment]
*Original comment by* **Michael Anselmi (Bitbucket: [compuserved](https://bitbucket.org/compuserved), GitHub: Unknown)**:

----------------------------------------

I just came across this problem/inconsistency as well. I look forward to seeing how this is resolved.

**Comment by josephwright** [comment]
OK, I know where the _problem_ is: the 'balls' are created by `\slideentry`, and it doesn't account for the 'no subsections' case. However, the bigger issue is that not all of the necessary data is passed in a systematic way. That's part of the wider '`beamer` is not really consistent with (sub)(sub)section support' problem. A larger project is going to be needed to sort this.

**Comment by louisstuart96** [comment]
Modifying `\slideentry` do show those frames 'without a subsection', but in a weird way. Perhaps the entries used in 'miniframes' need re-implementation.
```
  % \ifnum#6=\c@part\ifnum#2>0\ifnum#3>0 % The original code
  \ifnum#6=\c@part\ifnum#3>0%
```
