### ISSUE TITLE
wrong pdf labels per page when using notes on second screen

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#228]
Originally reported by: **Andreas B (Bitbucket: [abilke](https://bitbucket.org/abilke), GitHub: Unknown)**

----------------------------------------

When using the option:

```
#!latex

\setbeameroption{show notes on second screen}
```

the labels in the PDF get messed up.

Minimal example:

```
#!latex

\documentclass{beamer}
\usepackage{pgfpages}
\setbeameroption{show notes on second screen}

\begin{document}
\begin{frame}{First slide}
\end{frame}

\begin{frame}{Second slide}
\begin{itemize}%[<+->]
\item first item
\item second item
\end{itemize}
\end{frame}

\end{document}
```

As a result the page labels are first page: 2, second page: 3. I would expect labels 1 and 2. When using also overlays it gets even worse. The page labels are then first page (no overlays): 2, second page (with overlay): 2(!), third page (overlay): 4. I would expect the labels as: 1, 2, 2.

I am using the following beamer version (from TeXlive 2012):

revision:    28273
cat-version: 3.23
cat-date:    2012-10-28 22:48:15 +0100

----------------------------------------
- Bitbucket: https://bitbucket.org/rivanvx/beamer/issue/228

**Comment by josephwright** [comment]
*Original comment by* **Joseph Wright (Bitbucket: [josephwright](https://bitbucket.org/josephwright), GitHub: [josephwright](https://github.com/josephwright))**:

----------------------------------------

Regrettably, this is an issue at the `pgfpages` end (or one could argue with the way PDFs work). As such, it's INVALID for `beamer` itself.

**Comment by josephwright** [comment]
*Original comment by* **Bastian Sauert (Bitbucket: [sauert](https://bitbucket.org/sauert), GitHub: Unknown)**:

----------------------------------------

Still not an issue of beamer, but I had the same problem and just developed a patch for pgfpages which I commited to the pgf-users mailing list: http://sourceforge.net/mailarchive/forum.php?thread_name=51B3A1E4.80004%40gmx.net&forum_name=pgf-users

**Comment by Cimbali** [comment]
I’ve found a [working link to the mailing list](https://pgf-users.narkive.com/qVOR3uel/patch-for-wrong-pdfpagelabels-with-pgfpages), however the attached patch disappeared. Do @sauert or anyone else still have the patch? Pasting it here for reference would be very useful.

**Comment by samcarter** [comment]
@Cimbali  Probably this code: https://tex.stackexchange.com/a/118299/36296
