### ISSUE TITLE
miniframes don't render without subsection

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#240]
Originally reported by: **rauh (Bitbucket: [rauh](https://bitbucket.org/rauh), GitHub: [rauh](https://github.com/rauh))**

----------------------------------------

(Using the latest commit from 3/22 2013):
The miniframes won't render at all unless I have at least one subsection:
```
#!latex
\documentclass{beamer}
% Doesnt matter if subsection is true or false. Both wont render any mini
% frames for the first section
%\useoutertheme[subsection=false]{miniframes}
\useoutertheme[subsection=true]{miniframes}

\listfiles%Using: de9f4ac828a9 from 3/22/2013

\begin{document}
\section{Section only}
\frame{}
\frame{}
\section{Two subsec}
\subsection{ss 1}
\frame{}
\frame{}
\subsection{ss 2}
\frame{}
\frame{}
\section{No subsec}
\subsection*{}%Workaround
\frame{}
\frame{}
\frame{}

\end{document}
```
Here is the result, for both `subsection=false` and `true`:
![beamer bug](http://i.imgur.com/AD8WWcX.png)

There has been this report before
Issue #172 

But I really think it's not intuitive if I cannot mix section/subsection. I think it's often that the Introduction/Review will have no subsection and then the meat of the talk will have a few.  
Right now, sections w/o subsection simply will never be rendered. No matter what I set `subsection` to.  
Even if I remove all subsection commands, it won't display me any miniframes at all then.  

Cheers & thanks for all the great work! :)

----------------------------------------
- Bitbucket: https://bitbucket.org/rivanvx/beamer/issue/240

**Comment by josephwright** [comment]
*Original comment by* **Joseph Wright (Bitbucket: [josephwright](https://bitbucket.org/josephwright), GitHub: [josephwright](https://github.com/josephwright))**:

----------------------------------------

Duplicate of #172.

**Comment by josephwright** [comment]
*Original comment by* **Joseph Wright (Bitbucket: [josephwright](https://bitbucket.org/josephwright), GitHub: [josephwright](https://github.com/josephwright))**:

----------------------------------------

As detailed in the linked issue, this is now documented. Underlying this is the fact that Till really did not make supporting subsections particularly easy, and without a complete rewrite of large blocks of internal code this is not fixable.

**Comment by louisstuart96** [comment]
New bugs happen since changes to `\slideentry`. See 'beamerugouterthememiniframes.pdf'.

**Comment by louisstuart96** [comment]
Currently ([3cfdd45](https://github.com/josephwright/beamer/commit/3cfdd45042b7b704628fdfbae41e08a0a4c7b717)) miniframes are rendered without subsections, but are suppressed without sections.
