### ISSUE TITLE
Biblatex and block title

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#271]
Originally reported by: **Maieul (Bitbucket: [Maieul](https://bitbucket.org/Maieul), GitHub: [Maieul](https://github.com/Maieul))**

----------------------------------------

Hi,

the following example:

```
#!latex

		\begin{block}{\cite{Tourneau}}
			\enquote{
				\begin{enumerate}
					\item Texte prétendument écrit par un apôtre, mais dont seul des initiés avaient connaissances.
				\end{enumerate}
			}
		\end{block}
```

With beamer 3.6, we obtain a blue on blue (Darmdastd)

Should it be possible to disable the automatic switch of color on bibitem when we are in block title ?

----------------------------------------
- Bitbucket: https://bitbucket.org/rivanvx/beamer/issue/271

**Comment by josephwright** [comment]
Looking at this again, any chance of an example? (A quick mock-up doesn't show it for me.) A while ago, I realise ...

**Comment by samcarter** [comment]
I can't reproduce the problem with the following simple example:

```
\documentclass{beamer}
\usetheme{Darmstadt}

\usepackage{csquotes}

\usepackage[style=authoryear]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\begin{frame}

\begin{block}{title}
content...
\end{block}


\begin{block}{\cite{knuth:ct}}
	\enquote{
		\begin{enumerate}
			\item Texte prétendument écrit par un apôtre, mais dont seul des initiés avaient connaissances.
		\end{enumerate}
	}
\end{block}

\printbibliography

\end{frame}
\end{document} 
```
