### ISSUE TITLE
Linefeed with \\\\ in caption does not work anymore

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#303]
Originally reported by: **Anonymous**

----------------------------------------

When using \\\\ for a linefeed in a figure caption, LaTeX crashes with 

! LaTeX Error: Something's wrong--perhaps a missing \item.

This used to work in earlier versions of Beamer. Now, \newline must be used instead.

A MWE is

```
#!latex

\documentclass{beamer}
\usepackage{graphicx}

\begin{document}

\begin{frame}{text}
\begin{figure}
  \includegraphics[scale=0.4]{test.pdf}
 \caption{Some Text\\
 Some Text}
\end{figure}
\end{frame}

\end{document}

```

----------------------------------------
- Bitbucket: https://bitbucket.org/rivanvx/beamer/issue/303

**Comment by josephwright** [comment]
*Original comment by* **Joseph Wright (Bitbucket: [josephwright](https://bitbucket.org/josephwright), GitHub: [josephwright](https://github.com/josephwright))**:

----------------------------------------

`beamer` sets captions using `\raggedright` assuming the default template. You see the same error if you try to use ``\\`` inside a `\caption` where `\raggedright` is active with say the `article` class. As such, this is 'one of those things'.

**Comment by sbrl** [comment]
Umm this was closed as completed @josephwright, but it seems that given nothing has been done to fix this bug it is more of a won'tfix?

I'd suggest updating this to not be completed.

**Comment by samcarter** [comment]
@sbrl You can work around the problem by loading the `caption` package:

```
\documentclass{beamer}
\usepackage{caption}

\begin{document}

\begin{frame}{text}
\begin{figure}
  \includegraphics[scale=0.4]{example-image-duck}
 \caption{Some Text\\ Some Text}
\end{figure}
\end{frame}

\end{document}
```

(If I remember correctly, github only introduced the differentiation between "completed" and "won't fix" a couple of years ago. You'll probably see most (all?) of the old issues marked as "completed". This does not really mean anything)

**Comment by sbrl** [comment]
@samcarter Thanks for the suggestion! Unfortunately I already have the `caption` package loaded and I am still encountering this issue.

**Comment by samcarter** [comment]
> @samcarter Thanks for the suggestion! Unfortunately I already have the `caption` package loaded and I am still encountering this issue.

Can you make a small test document with the caption package that allows to reproduce the problem?
