### ISSUE TITLE
Themes (at least "Dresden") should have a "page numbers" option

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#314]
Originally reported by: **jondo (Bitbucket: [jondo](https://bitbucket.org/jondo), GitHub: [jondo](https://github.com/jondo))**

----------------------------------------

I would like to use `\usetheme{Dresden}`, but with page numbers in the bottom right corner.

[This code](http://www.latex-community.org/forum/viewtopic.php?f=4&t=873#p4644) somehow works when replacing `\insertshortauthor` with `\insertshorttitle`. However, it leaves the footer lines unaligned at the left.

Let me therefore suggest to have an additional option, s.t. I can simply write `\usetheme[pagenumbers]{Dresden}`.

----------------------------------------
- Bitbucket: https://bitbucket.org/rivanvx/beamer/issue/314

**Comment by ghost** [comment]
With https://github.com/josephwright/beamer/pull/463 one could simply add frame numbers to the Dresden theme like this:

```

\documentclass{beamer}

\usetheme{Dresden}
\setbeamertemplate{page number in head/foot}[totalframenumber]

\begin{document}
\begin{frame}

\end{frame}
\end{document}
```
