### ISSUE TITLE
LaTeX/beamer -> video with notes as speech

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#318]
Originally reported by: **Arne Henningsen (Bitbucket: [arne_henningsen](https://bitbucket.org/arne_henningsen), GitHub: Unknown)**

----------------------------------------

I think that it would be really amazing, if one could use LaTeX with the "beamer" class and a text-to-speech (ttf) software to create a video with the slides and the (beamer) notes as speech. Then, I could replace the keywords in my notes (in the tex files for my LaTeX/beamer slides) by full sentences, compile it to a video and put it on-line for my students. If I want to change something (e.g. a single word on the slides or in the speech), I could just change the tex file and re-compile it. If I talk myself to the slides while capturing the screen and my speech, I would have to record the entire thing again or cut out a part, record this part again and then put all parts together, every single time I want to change a tiny little thing. I know that this proposal goes beyond the beamer class but it would start with the beamer class to somehow put the notes into a file (e.g. extended PDF), perhaps with additional markups for emphasizing some words, making pauses, etc. Then, a ttf software could take the notes and convert them to speech and creating a video with the slides and the speech synchronized.

----------------------------------------
- Bitbucket: https://bitbucket.org/rivanvx/beamer/issue/318

**Comment by josephwright** [comment]
This goes well outside of what `beamer` can reasonably do, sorry.

**Comment by vincenzoml** [comment]
@josephwright  If it can be done with a computer, it can be done with latex it seems:

https://github.com/kisonecat/beaudiomer

One still needs to generate the audio using a separate tts software but probably that can also be launched using special commands directly in latex before the \audio command.
