### ISSUE TITLE
Second level itemize resets font size to normal

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#32]
Originally reported by: **mregine (Bitbucket: [mregine](https://bitbucket.org/mregine), GitHub: Unknown)**

----------------------------------------

Here is a MWE. It's ok with article, but in beamer the 1st and 3rd occurence have the same font size.

\documentclass{article}

%\documentclass{beamer}

\begin{document}

%\begin{frame}
  
\begin{itemize}

  \item The quick brown fox jumps easily over the fat and lazy dog. (1)\\

    \begin{tiny}

      The quick brown fox jumps easily over the fat and lazy dog. (2)

      \begin{itemize}

      \item The quick brown fox jumps easily over the fat and lazy dog (3).

      \end{itemize}

    \end{tiny}

  \item The quick brown fox jumps easily over the fat and lazy dog.

  \end{itemize}

%\end{frame}

\end{document}

----------------------------------------
- Bitbucket: https://bitbucket.org/rivanvx/beamer/issue/32

**Comment by josephwright** [comment]
*Original comment by* **Vedran Miletić (Bitbucket: [rivanvx](https://bitbucket.org/rivanvx), GitHub: Unknown)**:

----------------------------------------

Thank you for your report. This has been discussed before. It's actually the way beamer works. If you have a better way of implementing this that you can suggest, please add a comment to other bug.

Duplicate of #4.

**Comment by dbitouze** [comment]
I've looked at #4 but, IMHO, manually having to deal with ` \setbeamerfont{itemize/enumerate (sub)subbody}{...}` as in the following 3rd frame is a pain and should be automatized in frames as the 2nd one:

```latex
\documentclass[t]{beamer}

\setbeamertemplate{footline}[page number]
\setbeamertemplate{navigation symbols}{}

\newcommand{\test}{%
  \begin{enumerate}
  \item The quick brown fox jumps easily over the fat and lazy dog.
    \begin{enumerate}
    \item The quick brown fox jumps easily over the fat and lazy dog.
      \begin{enumerate}
      \item The quick brown fox jumps easily over the fat and lazy dog.
      \end{enumerate}
    \end{enumerate}
  \end{enumerate}
}

\begin{document}
\begin{frame}
  \frametitle{Default surrounding font size}
  \framesubtitle{Default itemize/enumerate (sub)subbody font sizes}
  \test
\end{frame}

\begin{frame}
  \frametitle{\alert{Non} default surrounding font size}
  \framesubtitle{Default itemize/enumerate (sub)subbody font sizes}
  \scriptsize%
  \test
\end{frame}

\begin{frame}
  \frametitle{\alert{Non} default surrounding font size}
  \framesubtitle{\alert{Non} default itemize/enumerate (sub)subbody font sizes}
  \setbeamerfont{itemize/enumerate subbody}{size=\tiny}%
  \setbeamerfont{itemize/enumerate subsubbody}{size=\Tiny}%
  %
  \scriptsize%
  \test
\end{frame}
\end{document}
```
![test](https://user-images.githubusercontent.com/1032633/72260245-b27bf200-3612-11ea-96f2-f5554610e49d.gif)
