### ISSUE TITLE
Frame title escapes into article text with beamerarticle

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#321]
Originally reported by: **Daniel Bosk (Bitbucket: [dbosk](https://bitbucket.org/dbosk), GitHub: [dbosk](https://github.com/dbosk))**

----------------------------------------

In some cases the frame title escapes into the article text when using `beamerarticle`.  A minimal working example is:

```LaTeX
\documentclass{article}
\usepackage{beamerarticle}
\begin{document}
  \begin{frame}<presentation>{Title text}
    \begin{figure}
      % whatever
      \caption{Figure caption}
    \end{figure}
  \end{frame}
\end{document}
```
The text "Title text" will show up in the article printed in italics.  The same happens with `\frametitle`.  But since this frame is set to <presentation> it shouldn't show up in <article>.

A workaround is to wrap the `\frametitle` in `\mode<presentation>{\frametitle{Frame title}}`.

----------------------------------------
- Bitbucket: https://bitbucket.org/rivanvx/beamer/issue/321

**Comment by josephwright** [comment]
Simply `\frametitle<presentation>{Title text}` works. I'll need to check the docs on this one: not sure what is to be expected!

**Comment by louisstuart96** [comment]
@josephwright In current version (v3.42), this MWE will trigger a `\@parmoderr` when typesetting the float. This is caused by `\setbox` in the `\beamer@donoframe` macro.
