### ISSUE TITLE
`beamer` documentation wrongly says `\frame` command and `frame` environment are equivalent

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#329]
Originally reported by: **denisbitouze (Bitbucket: [denisbitouze](https://bitbucket.org/denisbitouze), GitHub: Unknown)**

----------------------------------------

Page 58, `beamer`'s documentation says:

> You create a frame using the command `\frame` or the environment `frame`, which do the same.

But page 127, it says:

>  If you wish to use a `{verbatim}` environment in a frame, you have to add the option `[fragile]` to the `{frame}`
environment. In this case, you really have to use the `{frame}` environment (not the `\frame` command) [...]

IMHO, the former should be something like:

> You create a frame using the command `\frame` or, preferably,  the environment `frame`, which do (almost\footnote{Except if a {verbatim} environment is used in a frame}) the same.

----------------------------------------
- Bitbucket: https://bitbucket.org/rivanvx/beamer/issue/329

**Comment by josephwright** [comment]
I regard the `\frame` command as deprecated (it's not a good plan): I'll modify accordingly.

**Comment by dbitouze** [comment]
`\frame` is still cited at several places in the documentation.
