### ISSUE TITLE
Bullets in navigation bar in miniframes with XeLaTeX

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#332]
Originally reported by: **Zou Hu (Bitbucket: [zohooo](https://bitbucket.org/zohooo), GitHub: [zohooo](https://github.com/zohooo))**

----------------------------------------

After compiling a presentation using **miniframes** outer theme with **pdflatex**, we could jump to some slide by clicking its corresponding bullet in navigation bar.

But when using **xelatex**, we could not click the bullets in navigation bar.

I think this bug may be related to issue #136.

----------------------------------------
- Bitbucket: https://bitbucket.org/rivanvx/beamer/issue/332

**Comment by josephwright** [comment]
@zohooo Can you provide an example here? As indicated by the tracker, #136 is meant to be fixed ...

**Comment by ghost** [comment]
sounds related: http://tex.stackexchange.com/questions/296332/beamer-my-subsection-bullets-in-navigation-bar-doesnt-jump-by-clicking-when-i

**Comment by josephwright** [comment]
@samcarter8 Thanks: useful to have somewhere to work from.

**Comment by ghost** [comment]
one more question about this: https://tex.stackexchange.com/questions/274828/xelatex-and-beamer-miniframes-not-compatible

**Comment by josephwright** [comment]
From memory isn't the fundamental issue here with `xdvipdfmx`?

**Comment by ghost** [comment]
The strange thing: links to the sections etc. work fine - they use `\hyperlink` directly. The miniframes, which use `beamer@link` don't work, but `beamer@link` itself uses `\hyperlink` - if I'm not mistaken.

**Comment by louisstuart96** [comment]
Any non-text hyperlink (\vrule, \tikz circles, etc.) is incorrect in PDF generated by XeLaTeX(xdvipdfmx).

MWE:
```
\documentclass[a4paper,10pt]{article}
\usepackage{tikz}
\usepackage[colorlinks]{hyperref}

\begin{document}

\leavevmode\hyperlink{tar}{Reference to target as a normal text.}

This rule \hyperlink{tar}{\vrule height \ht\strutbox depth \dp\strutbox width 1em} is linked to target.

This circle \hyperlink{tar}{\begin{tikzpicture}{\draw (0,0) circle [radius=1ex];}\end{tikzpicture}} is linked to target.

\newpage
\leavevmode\hypertarget{tar}{Target}

\end{document}
```

The same problem happens in dvipdfmx driver.

**Comment by josephwright** [comment]
This is INVALID not WONTFIX I think: it's simply not a bug in `beamer` (I'm not saying it's not a bug _at all_, but the issue lies with `xdvipdfmx`).

**Comment by u-fischer** [comment]
Newer xdvipdfmx (texlive 2021, already available on windows) have extended specials which allow to force annotation areas also for non-text objects:

~~~~
\documentclass[a4paper,10pt]{article}
\usepackage{tikz}
\usepackage{hyperref}

\begin{document}
\showoutput
\leavevmode\hyperlink{tar}{Reference to target as a normal text.}

This rule \hyperlink{tar}{%
 \special{pdf:xann width \the\fontdimen6\font\space height \the\ht\strutbox\space depth \the\dp\strutbox}%
 \vrule height \ht\strutbox depth \dp\strutbox width 1em} is linked to target.

This circle 
\special{dvipdfmx:catch_phantom true height 10pt depth 0cm}%
\hyperlink{tar}{%
\begin{tikzpicture}{\draw (0,0) circle [radius=1ex];}\end{tikzpicture}} is linked to target.

\newpage
\leavevmode\hypertarget{tar}{Target}

\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/107145425-a8c1dc80-6941-11eb-883e-1642f173e755.png)

`\special{dvipdfmx:catch_phantom true}` should work too, but has a bug currently.

**Comment by samcarter** [comment]
One could use the same hack as in 

https://github.com/josephwright/beamer/blob/620462b6f3820d88c563e00a2dfdc9abade4d343/base/beamerbasenavigation.sty#L217-L219

```
% !TeX TS-program = xelatex
\documentclass[compress]{beamer}
\usetheme{Dresden}

\newcommand{\foo}{%
\begingroup\expandafter\expandafter\expandafter\endgroup
  \expandafter\ifx\csname XeTeXrevision\endcsname\relax
\else%
  \pgfsetfillopacity{0}
  \pgftext[x=0.1cm,y=0.05cm]{.}
\fi%
}


\setbeamertemplate{mini frame}{%
  \begin{pgfpicture}{0pt}{0pt}{0.1cm}{0.1cm}
    \pgfpathcircle{\pgfpoint{0.05cm}{0.05cm}}{0.05cm}
    \pgfusepath{fill,stroke}
    \foo
  \end{pgfpicture}%
}

\setbeamertemplate{mini frame in current section}{%
  \begin{pgfpicture}{0pt}{0pt}{0.1cm}{0.1cm}
    \pgfpathcircle{\pgfpoint{0.05cm}{0.05cm}}{0.05cm}
    \pgfusepath{stroke}
    \foo
  \end{pgfpicture}%
}

\setbeamertemplate{mini frame in current subsection}{%
  \begin{pgfpicture}{0pt}{0pt}{0.1cm}{0.1cm}
    \pgfpathcircle{\pgfpoint{0.05cm}{0.05cm}}{0.05cm}
    \pgfusepath{stroke}
    \foo
  \end{pgfpicture}%
}


\begin{document}

\section{SecA}
\subsection{sub1}
\frame{Hello01}

\subsection{sub2}
\frame{Hello02}

\end{document}
```
