### ISSUE TITLE
provide a way to insert overlay counter in footline

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#336]
Originally reported by: **flupp (Bitbucket: [flupp](https://bitbucket.org/flupp), GitHub: [flupp](https://github.com/flupp))**

----------------------------------------

It would be nice to have a convenient way to insert the current overlay counter into the foot line, e.g. by a command `\insertslideinframe`.

You cannot use `\the\beamer@slideinframe` directly, because it seems it is incremented before the foot line is rendered, except for the last slide of a frame.

Also, the difference between `\insertpagenumber` and `\insertframestartpage` plus `1` is not sufficient, because it does not work if some overlays are filtered.

The following example illustrates the problems.

```
#!latex
\documentclass{beamer}

\makeatletter

\newcounter{@slideinframe}%
\newcommand*{\insertslideinframe}{\begingroup%
	\setcounter{@slideinframe}{\insertpagenumber}%
	\addtocounter{@slideinframe}{-\insertframestartpage}%
	\stepcounter{@slideinframe}%
	\the@slideinframe%
\endgroup}

\newcommand*{\stuff}{%
	slideinframe~\the\beamer@slideinframe{}
	---
	only~\only<1>{1}\only<2>{2}\only<3>{3}\only<4>{4}\only<5>{5}\only<6>{6}
	---
	\(\text{pagenumber} - \text{framestartpage} + 1 = \insertslideinframe\)
}

\setbeamertemplate{footline}
{
	\hspace*{2ex}%
	\stuff
	\hspace{0pt plus 1 filll}%
	(\insertframenumber.\insertslideinframe{})%
	\hspace*{2ex}%
	\insertpagenumber{} / \insertpresentationendpage%
	\hspace*{2ex}%
}

\makeatother


\begin{document}
	\begin{frame}<1-2,5-6>[label=test]{A Frame --- \stuff}
		\stuff
	\end{frame}

	\againframe<3-4>{test}
\end{document}
```

----------------------------------------
- Bitbucket: https://bitbucket.org/rivanvx/beamer/issue/336

**Comment by louisstuart96** [comment]
I've tried to define both `\insertslideinframe` (which will probably be named `\insertslidenumber` later) and `\inserttotalslidenumber`. 

There are something to be concerned in defining the latter: `\inserttotalslidenumber` must be updated every time a single slide is typeset and `\beamer@slideinframe` steps, just like `\beamer@frameendpage`. It is incorrect to simply calculate it by `endpage-startpage+1` when overlay specifications are used in a `frame` environment.

**Comment by louisstuart96** [comment]
In commit [44a3090](https://github.com/josephwright/beamer/commit/44a30905a6c99b9359a9dbad708a9c1b4a4de61c) two new `\insert`s are introduced. They work well in the following MWE:

```
\documentclass{beamer}

\setbeamertemplate{footline}{%
  \leavevmode\hbox{%
  \begin{beamercolorbox}[wd=.5\paperwidth,ht=2.65ex,dp=1.5ex]{section in head/foot}%
    \usebeamerfont{section in head/foot}%
    \hspace*{2em}\insertframenumber\ - \insertslidenumber\ [\insertoverlaynumber]
  \end{beamercolorbox}}\vskip0pt%
}

\begin{document}

\begin{frame}<1-2,5-6>[label=test]{New inserts}
  Test
\end{frame}
\againframe<3-4>{test}

\end{document}
```
