### ISSUE TITLE
Beamer itemize not aligned when in blocks in columns

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#339]
Originally reported by: **Vadim Kantorov (Bitbucket: [vadimkantorov](https://bitbucket.org/vadimkantorov), GitHub: [vadimkantorov](https://github.com/vadimkantorov))**

----------------------------------------

While making a poster, I've got two columns with blocks with itemize inside them. They wouldn't vertically align (I added the baselines): ![beamerbug.png](https://bitbucket.org/repo/7z9LG/images/3576221669-beamerbug.png)

The issue is similar to https://bitbucket.org/rivanvx/beamer/issues/78/lost-alignment-between-columns, but this one happens when itemize is in blocks. I repro the bug both on a recent download of Beamer from CTAN and on ShareLaTeX.

MWE:

```
#!latex

\documentclass[final]{beamer}
\mode<presentation>{}

\usepackage{times}
\usepackage{amsmath,amssymb}
\usepackage[english]{babel}
\usepackage[latin1]{inputenc}

\begin{document}
\begin{frame}[t]{} 

%\leavevmode
\begin{columns}[t, onlytextwidth]
\begin{column}{.5\linewidth}
\begin{block}{Contributions}
\begin{itemize}
\item First Item
\item Second Item
\end{itemize}
\end{block}
\end{column}
\begin{column}{.5\linewidth}
\begin{block}{Approach}
\begin{itemize}
\item First Item
\item Second Item
\end{itemize}
\end{block}
\end{column}
\end{columns}

\end{frame}
\end{document}
```

----------------------------------------
- Bitbucket: https://bitbucket.org/rivanvx/beamer/issue/339

**Comment by josephwright** [comment]
*Original comment by* **Vadim Kantorov (Bitbucket: [vadimkantorov](https://bitbucket.org/vadimkantorov), GitHub: [vadimkantorov](https://github.com/vadimkantorov))**:

----------------------------------------

Paul Gaborit provided a workaround on http://tex.stackexchange.com/questions/332463/beamer-itemize-not-aligned-when-in-blocks but it seems like a bug anyway

**Comment by louisstuart96** [comment]
At last I decided not to fix this...
