### ISSUE TITLE
Remove the period following proof name

### ISSUE THREAD

**Issue by dbitouze** [josephwright/beamer#346]
The following MWE points out that, unlike the other "theorem" environments names, proof name is followed by a period. IMHO, this should be homogenized (by removing the period following proof name).
```
\documentclass{beamer}
\usetheme{PaloAlto}
\begin{document}
\begin{frame}
  \begin{theorem}
    Foo
  \end{theorem}
  \begin{proof}
    Bar
  \end{proof}
\end{frame}
\end{document}
```

**Comment by louisstuart96** [comment]
The label of proof environment is defined by `\insertproofname`. You can redefine it at any time.
The style with a period is inherited from `amsthm` package.

The related information has been added to the newest version of documentation.

**Comment by dbitouze** [comment]
Sigh... Still too bad some unfortunate design choices cannot be reversed by a, say, `new-beamer` class, or as done by Joseph for `siunitx`, by a version 2 of `beamer`.
