### ISSUE TITLE
setbeamercolor

### ISSUE THREAD

**Issue by fdagnat** [josephwright/beamer#351]
with beamer 2017/01/01 v3.37
the following file
```latex
\documentclass{beamer}
\setbeamercolor{itemize item}{fg=red,bg=yellow}
\begin{document}
 \begin{frame}{test}
   \begin{itemize}
   \item tutu
   \item tata
   \end{itemize}
 \end{frame}
\end{document}
```
does not get the itemize symbol modified (its color is still black)
I have tried to revert to beamer 3.36 but I'm not able to get it to work in my local texmf directory (the rcs Header does not work `beamer.cls:13: File ended while scanning use of \beamer@parseid`). Noticed that the file from the texlive does not have the rcs Header but I do not know to expand them...

**Comment by josephwright** [comment]
OK, this is to do with the fixes for https://github.com/josephwright/beamer/issues/138: I had a feeling this was going to be tricky!

**Comment by josephwright** [comment]
On the RCS business: the older set up used Mercurial keywords to generate `$Id` lines, but that relied on having the correct set up. It's unsupported by Git and was a pain anyway, so I've dropped it, but there's nothing I can do about the historical code. Just press ENTER to go past the errors ...
