### ISSUE TITLE
Overlay in blocks

### ISSUE THREAD

**Issue by jakobmoss** [josephwright/beamer#355]
After updating my TeXlive packages (including beamer to v3.38), the overlays in my beamer presentations started to misbehave. I use overlays in blocks and it has never been an issue before.

After some debugging, it shows up as a problem when I use rounded blocks. When I don't set the template, the overlays work just fine. When the template is activated, the overlays messes up.

Is it a bug or am I unaware of some changed behaviour in the new version of the package?

I have included a MWE:
```
\documentclass[10pt]{beamer}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[english]{babel}

\definecolor{auBlue}{cmyk}{1,0.8,0,0.15}

\usetheme[compress]{Singapore}
\usecolortheme[named=auBlue]{structure}
\usecolortheme{orchid}
%\setbeamertemplate{blocks}[rounded]  % <----

\begin{document}

\begin{frame}
  \frametitle{Some title}
 
  \begin{block}{Here is a block}<1->
    \begin{itemize}
    \item<2-> A line of text
    \item<2-> Another line of text
    \end{itemize}
  \end{block}
\end{frame}

\end{document}
```

With rounded blocks:
<img width="452" alt="with_rounded" src="https://cloud.githubusercontent.com/assets/9656902/21780377/a759e82e-d6ab-11e6-9794-f820ef7ffc4b.png">

Without rounded blocks:
<img width="465" alt="without_rounded" src="https://cloud.githubusercontent.com/assets/9656902/21780376/a759d3a2-d6ab-11e6-9558-696b72ef9bdc.png">

**Comment by josephwright** [comment]
The issue is caused by aff6bf4: I'm looking at it.

**Comment by josephwright** [comment]
The reason this only comes up with rounded blocks is https://github.com/josephwright/beamer/issues/349: different (seemingly similar) templates use different low-level constructs.
