### ISSUE TITLE
Check whether patch for \beamer@(sub)section is needed

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#358]
In `beamerbasecompatibility` there is a section starting
```latex
%
% Heiko's fix for correct generation of section* and subsection* bookmarks
%
```
but it's not clear why the main definitions do not use this code. When checking over the sectioning code, this should be looked at: may be that it's easier done the current way (mode considerations).

**Comment by louisstuart96** [comment]
Heiko didn't patch this in standard classes. If a blank title is used in `\section` macro, a 'blank' bookmark will be generated, which is totally clickable. There's nothing abnormal about this.
