### ISSUE TITLE
(Firsts) Highlighted items are not properly highlighted within blocks

### ISSUE THREAD

**Issue by dbitouze** [josephwright/beamer#361]
(Tested version : d1f4d36.)

The following example points out that firsts automatically highlighted items of a list are not properly highlighted within blocks:
- on page 1 (within a block), only the item marker is colored,
- on page 4 (not within a block), both the item marker and the text are colored).
```latex
\documentclass{beamer}
\usetheme{PaloAlto}
\begin{document}
\begin{frame}
  \begin{block}{Test}
    \begin{itemize}[<+-| alert@+>]
    \item Foo
    \item Bar
    \item Baz
    \end{itemize}
  \end{block}
\end{frame}
\begin{frame}
  \begin{itemize}[<+-| alert@+>]
  \item Foo
  \item Bar
  \item Baz
  \end{itemize}
\end{frame}
\end{document}
```

**Comment by josephwright** [comment]
Mumble, this is to do with #107 (again)
