### ISSUE TITLE
Columns do not work properly on title page

### ISSUE THREAD

**Issue by svitalsky** [josephwright/beamer#363]
With beamer from TeXLive 2016 (currently: “beamer 2017/01/22 v3.40”) there is a problem when using columns on the title page. For more details please see this MWE (it has been created by cutting off stuff from a colleague's  beamer presentation):
```
\documentclass[xcolor=dvipsnames,10pt]{beamer}

\usefonttheme{structurebold}
\usetheme{Madrid}
% \usetheme{Singapore} % with this theme no problem
\useinnertheme{circles}

\setbeamerfont{frametitle}{series=\bfseries}
\setbeamerfont{framesubtitle}{series=\bfseries}

\setbeamertemplate{navigation symbols}{}
\setbeamertemplate{footline}{}

\setbeamertemplate{title page}{
    \centering
    \begin{beamercolorbox}[rounded=true,shadow=true,sep=8pt,center]{title}
        \usebeamerfont{title}\inserttitle\par
        \vskip .5em
        \usebeamerfont{subtitle}\usebeamercolor[fg]{subtitle}\insertsubtitle\par
    \end{beamercolorbox}
    \vspace{7mm}

    \begin{beamercolorbox}{author}
        \begin{columns}[T]
            % \column{.01\textwidth}%  % temporary workaround
            \column{.25\textwidth}%
                \centering
                \usebeamerfont{author}Author One\\
                often.NOT@visible.nok
            \column{.25\textwidth}%
                \centering
                \usebeamerfont{author}Author Two\\
                is.always@visible.ok
            % \column{.01\textwidth}%  % temporary workaround
        \end{columns}
    \end{beamercolorbox}
    \vfill
}

\title{Some Title}
\subtitle{\url{http://www.some.url/}}

\begin{document}
\begin{frame}
\maketitle
\end{frame}

\begin{frame}{Std frame}
\begin{columns}[T]
    \column{.25\textwidth}%
        \centering
        \usebeamerfont{author}Author One\\
        often.NOT@visible.nok
    \column{.25\textwidth}%
        \centering
        \usebeamerfont{author}Author Two\\
        is.always@visible.ok
\end{columns}
\end{frame}
\end{document}
```

The result looks like this:
![beamer-error](https://cloud.githubusercontent.com/assets/17103067/22203710/9cdd87ca-e16e-11e6-9498-48146f30e92a.png)

As suggested in the comments in the MWE, this problem occurs with some themes only, but not with others. With beamer from the TeXLive 2015 (latest update of it) the problem did not occur, it's new in TL2016.

**Comment by josephwright** [comment]
This is the fix for #107 (again), which I'd backed-out in development but not in 'urgent' releases. I've moved https://github.com/josephwright/beamer/commit/d8541c78ed3744501f515de46dab8373e41991ea into the stable code and will update CTAN today.

**Comment by ghost** [comment]
Is there an estimated time of arrival of the bugfix on CTAN? I am just asking because meanwhile questions are piling up:
- http://tex.stackexchange.com/questions/350309/strange-interaction-between-beamer-and-tcolorbox
- http://tex.stackexchange.com/questions/350704/how-to-avoid-problems-with-the-juanlespins-theme-and-textsc
- http://tex.stackexchange.com/questions/350764/itemize-overlay-not-working-properly-in-beamer
- http://tex.stackexchange.com/questions/350776/issue-with-changing-font-color-in-enumerated-lists-using-beamer

**Comment by josephwright** [comment]
@samcarter8 Had a PC change at work that's held up a few things: will go this evening or tomorrow morning.

**Comment by josephwright** [comment]
@samcarter8  I've submitted v3.41 to CTAN (sorry for the delay)

**Comment by svitalsky** [comment]
Just FMI, would you happen to know what time does it usually take from submitting a fix to CTAN till it being included in TeXLive update? Just roughly: hours, days, weeks? Thx. (I have no experience with this.)

**Comment by josephwright** [comment]
@svitalsky Around 48 h.

**Comment by svitalsky** [comment]
This was swift! :-) Thx.

**Comment by ghost** [comment]
Thank you!
