### ISSUE TITLE
`\beamer@sectionintoc` is undefined in `beamerarticle`

### ISSUE THREAD

**Issue by dbitouze** [josephwright/beamer#368]
As of 46e6c3d, `\beamer@sectionintoc` is undefined in `beamerarticle`, as pointed out by the following MCE, compiled:

1. firstly with `beamer` class,
1. subsequently with `article` class and `beamerarticle` package.
```latex
\documentclass[ignorenonframetext]{beamer}
% \documentclass{article}\usepackage{beamerarticle}
%
\begin{document}
\begin{frame}
  \frametitle{Outline}
  \tableofcontents
\end{frame}
\section{Foo}
\begin{frame}
  Foo.
\end{frame}
\section{Bar}
\begin{frame}
  Bar.
\end{frame}
\end{document}
```

**Comment by josephwright** [comment]
This is introduced by 67d11de674c68e864402f17c66b78824559ad39a.
