### ISSUE TITLE
Text of `enumerate`'s mini template not displayed as is

### ISSUE THREAD

**Issue by dbitouze** [josephwright/beamer#369]
(Not sure wether it is a bug or a feature due to a recent fix.) With `beamer` version `2017/01/23 v3.41` (CTAN release), the `enumerate` lists with mini template specified don't look the same way as with `beamer` 5e1604f. In the latter case, the text of the mini template isn't displayed as is, but looks the same as the default (e.g. for `PaloAlto` theme, in blue balls), as pointed out by the following MCE (BTW, notice the indentation significantly different for the `(a)` mini template).
```latex
\documentclass{beamer}
%
\usetheme{PaloAlto}
%
\begin{document}
\begin{frame}
  \begin{enumerate}
  \item Bar
  \item Baz
  \end{enumerate}
  \begin{enumerate}[(a)]
  \item Bar
  \item Baz
  \end{enumerate}
  \begin{enumerate}[(i)]
  \item Bar
  \item Baz
  \end{enumerate}
\end{frame}
\end{document}
```

**Comment by josephwright** [comment]
This change is by design and is caused by fixing https://github.com/josephwright/beamer/issues/366 (commit https://github.com/josephwright/beamer/commit/561ebfeca410a68c57179bd8ed1fdb85c9b703d2). The old situation didn't apply the template to all enumerate types, whereas once fixed it does. So now you only change what one would expect: the text of the label itself not the formatting of the label.

**Comment by dbitouze** [comment]
Okay. What about the indentation significantly different for the (a) mini template?

**Comment by josephwright** [comment]
@dbitouze  Good question: not at all obvious! I'll reopen and try to track that down later on (I don't think this is a 'new' issue in that sense).

**Comment by louisstuart96** [comment]
This glitch is actually brought by the `enumerate` package itself. You can just try your case in the `article` class.
Leaving out this piece of code in the definition of `\beamer@@@enum@` will do nicely:
```
\expandafter\settowidth
           \csname leftmargin\romannumeral\@enumdepth\endcsname
            {\the\@enLab\hspace{\labelsep}}%
```

**Comment by ghost** [comment]
@louisstuart96  Leaving out these code lines is also the way David Carlisle suggested: https://tex.stackexchange.com/a/378012/36296

**Comment by dbitouze** [comment]
This issue has been closed but the OP still shows a trouble with the (a) mini template.

**Comment by josephwright** [comment]
@louisstuart96 I see you closed but I'm not sure why ...

**Comment by louisstuart96** [comment]
I'm wondering if we truely need to fix this because it's the problem (or feature) of `enumerate` package itself.

**Comment by dbitouze** [comment]
>t's the problem (or feature) of enumerate package itself.

Indeed: the following MWE:
```latex
\documentclass{article}
\usepackage{enumerate}
\begin{document}
\begin{enumerate}
\item Bar
\item Baz
\end{enumerate}
\begin{enumerate}[(a)]
\item Bar
\item Baz
\end{enumerate}
\begin{enumerate}[(i)]
\item Bar
\item Baz
\end{enumerate}
\end{document}
```
leads to:

![test](https://user-images.githubusercontent.com/1032633/29610256-eedf9f40-87f9-11e7-83df-c6d5f6f220c0.png)

**Comment by FrankMittelbach** [comment]
looks like one for David then

**Comment by louisstuart96** [comment]
See #453 .
