### ISSUE TITLE
Error with overlay in Madrid Theme

### ISSUE THREAD

**Issue by craffael** [josephwright/beamer#371]
Somehow the overlays of the Madrid theme don't work as expected:

    \documentclass[10pt]{beamer}
    \usetheme{Madrid}
    \begin{document}
    \begin{frame}{Table of contents}
      \begin{block}<1->{bug}
        \begin{itemize}
          \item<2-> abc
        \end{itemize}
      \end{block}
    \end{frame}
    \end{document}

This produced the following two slides: [beamer_bug.pdf](https://github.com/josephwright/beamer/files/741967/beamer_bug.pdf)

The two slides are completely wrong: Slide 1 contains everything (event though it should not contain the list item) and slide 2 doesn't contain anything. The code works as expected if the theme "default" is used.

This was compiled with MikTex 2.9.6210 (64-bit) and beamer 3.40.

**Comment by josephwright** [comment]
I can see this with v3.38 but not with v3.40: should be fixed. Can you add `\listfiles` to your source and post the resulting file list?

**Comment by craffael** [comment]
You are right. I got confused by the machine wide installation and the user specific installation of package in MikTex. Turns out that I had Beamer version 3.37 and not 3.40. Updating to 3.41 resolved the issue.
Thanks a lot!
