### ISSUE TITLE
\beamer@endpause (?) no more defined

### ISSUE THREAD

**Issue by dbitouze** [josephwright/beamer#377]
As of 58c0299, the compilation of the following MWE, coming from the documentation example in section 23.6 "Uncovering a Table Columnwise", fails with the error:
```
! Undefined control sequence.
\beamerx@\beamer@noargsonslide ...beamer@endpause 
                                                  \alt #1{\beamer@spacingcov...
```

```latex
\documentclass[xcolor=table]{beamer}
\begin{document}
\begin{frame}
  \begin{tabular}{l!{\vrule}c<{\onslide<2->}c<{\onslide<3->}c<{\onslide<4->}c<{\onslide}c}
    Class & A & B & C & D \\
    X     & 1 & 2 & 3 & 4 \\
    Y     & 3 & 4 & 5 & 6 \\
    Z     & 5 & 6 & 7 & 8
  \end{tabular}
\end{frame}
\end{document}
```

**Comment by josephwright** [comment]
Not a recent change: a quick search back shows this pops up in v2.99 (earliest easy-to-access version I have in the repo).

**Comment by dbitouze** [comment]
Still doesn't work: the example compiles but produces only one page with only the first two columns.

**Comment by josephwright** [comment]
@dbitouze  It's outside of a `frame`: I'm happy that this should not yield an internal error but there are no overlays available for such cases.

**Comment by dbitouze** [comment]
Sorry for the noise: it works as expected if the tabular is within a `frame`.
