### ISSUE TITLE
Vertical position of align environment is changed when beamercolor of math text is not empty

### ISSUE THREAD

**Issue by e-kwsm** [josephwright/beamer#380]
I noticed this issue when I tried to overlay color of equations to emphasize.
I believe that `\setbeamercolor{math text}` is preferable to `\color` for coloring equations, but MWE
```tex
\documentclass{beamer}
\begin{document}
\begin{frame}{}{}
  \only<1>{default}
  \only<2>{fg=red \setbeamercolor{math text}{fg=red}}
  \begin{align}
    E = mc^2
  \end{align}
\end{frame}
\end{document}
```
gives
![mwe](https://cloud.githubusercontent.com/assets/11627708/23459293/16ad0942-fec3-11e6-96bb-79fd80b58d0e.gif)
even if `fg=black`.

Environment:
- engine: all of them has this issue
  - LuaLaTeX 0.95.0 (TeX Live 2016)
  - PDFLaTeX 3.14159265-2.6-1.40.17 (TeX Live 2016)
  - XeLaTeX 3.14159265-2.6-0.99996 (TeX Live 2016)
- beamer 2017/01/23 v3.41
- xcolor 2016/05/11 v2.12

**Comment by e-kwsm** [comment]
This works fine:
```tex
\begin{frame}{}{}
  \only<1>{default}
  \only<2>{red \color{red}}
  \begin{align}
    E = mc^2
  \end{align}
\end{frame}
```

**Comment by ghost** [comment]
maybe related: http://tex.stackexchange.com/questions/348611/odd-spacing-in-beamers-display-math-with-everydisplay-and-color/348614#comment855960_348611

**Comment by josephwright** [comment]
As already commented, this is due to some low-level issues which are not `beamer`'s fault: a solution will need an entirely different approach to current LaTeX in handling color whatsits (so-called `xgalley`).

**Comment by e-kwsm** [comment]
@josephwright Thank you for your reply.
But this behaviour is undesirable and not fully documented: in §17.3 "The Color of Mathematical Text",
> The setup of this color is somewhat fragile, use at your own risk. 

How about adding something like "the setup changes vertical space"?

Then my questions are:
1. Does `\setbeamercolor` of other elements than `math text (displayed)` have the similar behaviour?
2. What is the current best way to color equations? One posted by @samcarter8 ?
