### ISSUE TITLE
Tiny horizontal space inserted by `\alert`

### ISSUE THREAD

**Issue by dbitouze** [josephwright/beamer#383]
The following MCE points out that `\alert` inserts a tiny horizontal space.
```latex
\documentclass{beamer}
\begin{document}
\begin{frame}
  \only<1>{Foo}%
  \only<2>{F\alert{o}o}%
\end{frame}
\end{document}
```

**Comment by FrankMittelbach** [comment]
Am 08.03.17 um 08:36 schrieb Denis Bitouzé:
> The following MCE points out that |\alert| inserts a tiny horizontal space
>
> \documentclass{beamer}
> \begin{document}
> \begin{frame}
>   \only<1>{Foo}%
>   \only<2>{F\alert{o}o}%
> \end{frame}
> \end{document}

that doesn't surprise me --- without checking: my guess is that the font 
does have kerning between F and o (and perhaps  o and o) and if you 
alert you essentially change the font -> no kerning no ligatures

TeX only does these microtypographic adjustments if there isn't any 
intervention whatsoever:  F{o}o is probably giving you the same "spaces"

**Comment by dbitouze** [comment]
Indeed, you're (once more! :) right.
