### ISSUE TITLE
Is the space after the vertical bar for mode specification actually required?

### ISSUE THREAD

**Issue by dbitouze** [josephwright/beamer#384]
Page 203, `beamer`'s documentation says:

> As explained in Section 9.2, a mode specification is written alongside the normal overlay specification inside the pointed brackets. It is separated from the normal specification by a vertical bar and a space. 

But, as pointed out by the following MWE, the space after the vertical bar seems to not be required:

```latex
\documentclass[trans]{beamer}
\begin{document}
\begin{frame}
  \begin{itemize}
  \item Foo.\only<1|trans:0>{ Not shown on transparencies.}
  \item Foo.\only<1| trans:0>{ Not shown on transparencies.}
  \end{itemize}
\end{frame}
\end{document}
```
![test](https://cloud.githubusercontent.com/assets/1032633/23755126/ade306b4-04df-11e7-933a-9acda4e3e0b7.png)

**Comment by louisstuart96** [comment]
Seems true. In `beamer`'s overlay/mode specification parser, spaces in specification codes are removed using `\zap@space` macro.

**Comment by dbitouze** [comment]
Thanks for the investigation! So, is it just a matter of documentation fix?

**Comment by louisstuart96** [comment]
Throughout the documentation it is emphasized that 'any vertical bar must be followed by a space'. I wonder if the old implementation of overlay/mode/action specification parser involved space tokens.

**Comment by josephwright** [comment]
@louisstuart96 I _think_ it goes back a long way: when I looked at this I couldn't see why Till said it, so it may predate the history I have access to. I guess a doc fix is in order. (I need to do a release I suspect.)
