### ISSUE TITLE
Is it necessary to add `\normalsize` to the definition of `\usebeamerfont*`?

### ISSUE THREAD

**Issue by louisstuart96** [josephwright/beamer#385]
Currently `\usebeamerfont*` uses `\reset@font` to reset font settings, but only NFSS family, series and shape are reset, it has nothing to do with font size.

**Comment by josephwright** [comment]
Interesting question: I suppose it _might_ have been a good idea once, but would it be risky to change now?

**Comment by samcarter** [comment]
@josephwright  Should the documentation then be edited to remove the normalsize?

<img width="878" alt="Screenshot 2023-01-27 at 13 50 57" src="https://user-images.githubusercontent.com/43832342/215091293-3b1b899a-923f-470b-aa3d-2e3ea22b2c06.png">

**Comment by josephwright** [comment]
I guess!

**Comment by samcarter** [comment]
Ok, I'll make a PR
