### ISSUE TITLE
Possibility to load only specific template from a theme

### ISSUE THREAD

**Issue by ghost** [josephwright/beamer#388]
@josephwright  May I ask you for your opinion concerning the following idea? Is it worth the effort to look further into this?

Many of the `beamer` questions on tex.stackexchange are of the kind "I use `theme X` but I'd like to have the footer/header/whatever from `theme Y`". 

Normally they will get the an answer with `\setbeamertemplate{...}{ some code copied from theme Y }` -- which works fine, but I was wondering if some mechanism to load only a specific template from a theme would make life easier for many users?

To demonstrate how this might work a mock-up example using the `catchfilebetweentags` package and using a modified version of the infolines outer theme [mybeamerouterthemeinfolines.sty.zip](https://github.com/josephwright/beamer/files/936164/mybeamerouterthemeinfolines.sty.zip).

The command `\fromoutertheme{infolines}{footline:infolines}` will load only the footline from the infolines theme.

```
\documentclass{beamer}

\usecolortheme{whale}
\useoutertheme{split}

\usepackage{catchfilebetweentags}
\newcommand\fromtheme[2]{\ExecuteMetaData[mybeamertheme#1.sty]{#2}}
\newcommand\fromcolortheme[2]{\ExecuteMetaData[mybeamercolortheme#1.sty]{#2}}  
\newcommand\fromfonttheme[2]{\ExecuteMetaData[mybeamerfonttheme#1.sty]{#2}}  
\newcommand\fromoutertheme[2]{\ExecuteMetaData[mybeameroutertheme#1.sty]{#2}}
\newcommand\frominnertheme[2]{\ExecuteMetaData[mybeamerinnertheme#1.sty]{#2}}  

\fromoutertheme{infolines}{footline:infolines}

\begin{document}
	\begin{frame}
		Test
	\end{frame}
\end{document}
```

I know this method is far from perfect (see incomplete list below), but this is just a first try, maybe the problems can be solved.

### Problems of the above Ansatz ###

- comments of the form `%<*footline:infolines>` , `%</footline:infolines>` would have to be inserted in the code, custom made themes would probably not do this and user would be confused for which templates it would work and for which ones not.
- I know just loading a specific template will break as soon as the template tries to use something defined within the theme, but outside the template, for example things like `\pgfdeclareverticalshading{beamer@topshade}{...}` would have to be inside the `<*tag>...</tag>`
- of course it would be more convenient if one would not have to know in which sub-theme the template is defined, but could just insert the general theme and this command would recursivly search the loaded sub-themes for a given tag.
- I have not yet thought about how optional arguments of themes would fit into this...
- ....

---

Meanwhile I opened a question at [https://tex.stackexchange.com/questions/365949/load-specific-template-from-another-theme](https://tex.stackexchange.com/questions/365949/load-specific-template-from-another-theme), maybe someone will have a good idea how one could do this

**Comment by louisstuart96** [comment]
The inner and outer themes use `\defbeamertemplate*` instead of `\defbeampertemplate` in order to execute settings immediately after they're defined.

Untested code:
```
\let\beamer@original@defbeamertemplate\beamer@defbeamertemplate
\def\beamer@defbeamertemplate{\@ifstar{\beamer@sbtoo}{\beamer@sbtoo}}
\useoutertheme{...}
\useoutertheme{...}
\setbeamertemplate{headline}[...] 
% This \set must be done manually, 
% since generally theme names have nothing to do with file names
\let\beamer@defbeamertemplate\beamer@original@defbeamertemplate
```

**Comment by samcarter8** [comment]
@louisstuart96 Your code actually works very well! Thank you for posting it!

As it let's beamer do all the theme loading, things like resistivity and handling of optional arguments are working out of the box.

**Comment by ghost** [comment]
@louisstuart96 Thanks for your reply - your idea is very good, it would solve the problems with recrusivity and theme options.

However I struggle to make it work, I tried the following MWE:

```
\documentclass{beamer}

\usecolortheme{whale}
\useoutertheme{split}

\makeatletter
\let\beamer@original@defbeamertemplate\beamer@defbeamertemplate
\def\beamer@defbeamertemplate{\@ifstar{\beamer@sbtoo}{\beamer@sbtoo}}
\useoutertheme{infolines}
\setbeamertemplate{footline}[infolines theme] 
% This \set must be done manually, 
% since generally theme names have nothing to do with file names
\let\beamer@defbeamertemplate\beamer@original@defbeamertemplate
\makeatother

\begin{document}
	\begin{frame}
		Test
	\end{frame}
\end{document}
```

but it not only sets the footline from `infolines`, but also all the other things like the headline - in other words, just like calling `\useothertheme{infolines}`.

Do you have any ideas what I am doing wrong?

**Comment by louisstuart96** [comment]
Ooooops...I forgot something. This case might work. 
However, making a custom theme file is a better way.

```
\documentclass{beamer}

\usecolortheme{whale}
\useoutertheme{split}

\makeatletter
\let\beamer@original@defbeamertemplate\beamer@defbeamertemplate
\def\beamer@defbeamertemplate{\beamer@sbtfalse\@ifstar{\beamer@sbtoo}{\beamer@sbtoo}}
\useoutertheme{infolines}
\setbeamertemplate{footline}[infolines theme] 
% This \set must be done manually, 
% since generally theme names have nothing to do with file names
\let\beamer@defbeamertemplate\beamer@original@defbeamertemplate
\makeatother

\begin{document}
	\begin{frame}
		Test
	\end{frame}
\end{document}
```

**Comment by ghost** [comment]
@louisstuart96 Making a custom theme falls for me in the same category as the usual answers with `\setbeamertemplate...`, the user would have to now how to look up the original code and track down which themes call which subthemes - this is exactly what I try to avoid. 

I thought a bit about possible test cases and came up with 3 ones (see end of my question at https://tex.stackexchange.com/q/365949/36296) which should cover a broad spectrum of possible use cases.

With your code:

- Test case 1 -> works fine

- Test case 2 -> works fine, with the slight disadvantage is that things like colours will be overwritten by the theme

- Test case 3: -> works fine

In case you have an account at TeX.Stackexchange: Would you like to add your solution there? Then all replies I received would be collected in one place.

**Comment by josephwright** [comment]
I'm unlikely to add this to `beamer`. Till designed themes to have some sense of structure and in some senses to work like (well-designed) classes: they are single 'complete' files rather than to be taken as _ad hoc_ 'pick and mix' sources. That's _why_ one has open source material: users can make new themes which take subsets where appropriate.

**Comment by ghost** [comment]
@josephwright Thanks for your feedback!
