### ISSUE TITLE
Frames containing fragile content ignore \beamerdefaultoverlayspecification

### ISSUE THREAD

**Issue by dbitouze** [josephwright/beamer#390]
The following MCE shows that, if a frame contains fragile content, it ignores `\beamerdefaultoverlayspecification{<+->}` specification. As a workaround, one can add the option `<+->` to lists environments but that's not satisfactory.

```latex
\documentclass{beamer}
\setbeamertemplate{footline}[frame number]
\beamerdefaultoverlayspecification{<+->}
\begin{document}
\begin{frame}
  \begin{itemize}
  \item Foo
  \item Bar
  \end{itemize}
\end{frame}
%
\begin{frame}[fragile]
  \begin{itemize}
  \item Foo
  \item Bar
  \end{itemize}
\end{frame}
%
\begin{frame}[fragile]
  \begin{itemize}[<+->]
  \item Foo
  \item Bar
  \end{itemize}
\end{frame}
\end{document}

```

**Comment by dbitouze** [comment]
The patch introduces an extra `\pause` in some circumstances: in the following MCE, the document has:

- 2 pages (only) without the patch,
- 3 pages with the patch.

```latex
\documentclass{beamer}

\makeatletter
% \def\beamer@@frameinput<#1>[{\@ifnextchar<{\beamer@@@@frameinput<#1>[}%
%   {\edef\beamer@temp{\noexpand\beamer@@@frameinput<#1>[\beamer@defaultospec][}%
%     \beamer@temp}}
\makeatother

\beamerdefaultoverlayspecification{<+->}

\begin{document}
\begin{frame}[fragile]
  \begin{block}{Foo}
    Bar
  \end{block}
  \pause{}%

  Baz
\end{frame}
\end{document}
```

**Comment by josephwright** [comment]
Isn't that the same as without the `fragile` option anyway?

**Comment by dbitouze** [comment]
Indeed: without the `fragile` option, there is an extra `\pause`, regardless the patch is applied or not.

**Comment by dbitouze** [comment]
Indeed: without the `fragile` option, there is an extra `\pause`, regardless the patch is applied or not.

**Comment by dbitouze** [comment]
**Edit:** a new issue (https://github.com/josephwright/beamer/issues/398) has been open for this bug.

Should I open a new issue for the extra page (3 pages instead of the expected 2) in the following MCE (now with or without the patch :$)?

```latex
\documentclass{beamer}

\makeatletter
% \def\beamer@@frameinput<#1>[{\@ifnextchar<{\beamer@@@@frameinput<#1>[}%
%   {\edef\beamer@temp{\noexpand\beamer@@@frameinput<#1>[\beamer@defaultospec][}%
%     \beamer@temp}}
\makeatother

\beamerdefaultoverlayspecification{<+->}

\begin{document}
\begin{frame}
  \begin{block}{Foo}
    Bar
  \end{block}
  \pause{}%
  Baz
\end{frame}
\end{document}
```

**Comment by dbitouze** [comment]
This issue has been closed but, even with `beamer.cls    2017/08/22 v3.4`, the following MWE still contains an extra page (3 pages instead of the expected 2).

```latex
\documentclass{beamer}

\beamerdefaultoverlayspecification{<+->}

\begin{document}
\begin{frame}
  \begin{block}{Foo}
    Bar
  \end{block}
  \pause{}%

  Baz
\end{frame}
\end{document}
```

**Comment by josephwright** [comment]
@dbitouze The fact you get an 'extra' page is as I've said elsewhere a logical result of applying a default spec.
