### ISSUE TITLE
Documentation says \alert and {alertenv} are equivalent: true but not in the usual use

### ISSUE THREAD

**Issue by dbitouze** [josephwright/beamer#391]
Documentation says (page 115):

>`\alert<⟨overlay specification⟩>{⟨highlighted text⟩}`
[...]
Internally, this command [(`\alert`)] just puts the highlighted text inside an `alertenv`.

AFAICS, that's true but only if the `alertenv` environment is used in a unusual way (3rd frame), otherwise it inserts horizontal spaces (2nd frame) that `\alert` doesn't insert (1st frame):

```latex
\documentclass{beamer}
\setbeamertemplate{footline}[frame number]
\setbeamertemplate{navigation symbols}{}
\begin{document}
\begin{frame}
  Foo \alert{bar} baz
\end{frame}

\begin{frame}
  Foo
  \begin{alertenv}
    bar
  \end{alertenv}
  baz
\end{frame}

\begin{frame}
  Foo \begin{alertenv}bar\end{alertenv} baz
\end{frame}
\end{document}
```
![test](https://cloud.githubusercontent.com/assets/1032633/26283474/6df7082c-3e21-11e7-9d3e-bac3001be48a.gif)

Same remark for `\structure` vs `structureenv` environment.

**Comment by davidcarlisle** [comment]
It seems to me that this is exactly as documented, it does not "insert
horizontal space" it just does not remove the space that you have added

\alert{bar}

is documented as working like

\begin{alertenv}bar\end{alertenv}


and similarly

\alert{
    bar
    }

works like

\begin{alertenv}
    bar
  \end{alertenv}

David

**Comment by louisstuart96** [comment]
Both usages are identical in **vertical mode**. In **horizontal mode**, as in your case, the carriage returns after `\begin{alertenv}` and `bar` will bring additional spaces into the environment.

BTW, I've found another bug in `alertenv` and `structureenv`...

**Comment by dbitouze** [comment]
@davidcarlisle and @louisstuart96 Okay but isn't it pretty unusual to use an `environment` in the `\begin{environment}...\end{environment}` form? Maybe the `beamer`'s documentation should warn the user about this potential (not so) spurious space with `alertenv` and `structureenv` environments.
