### ISSUE TITLE
\inst is not in sans serif when professionalfonts is used

### ISSUE THREAD

**Issue by e-kwsm** [josephwright/beamer#394]
When `professionalfonts` theme is used, a superscript text of `\inst` is not in sans serif but in roman.

```tex
\documentclass{beamer}
\usefonttheme{professionalfonts}
% \inst are printed as ${}^1$ and ${}^a$, resp.
\author{John Smith\inst{1} \and Jane Doe\inst{a}}
\institute{\inst{1}Somewhere \and \inst{a}Another}
\begin{document}
\frame{\titlepage}
\end{document}
```

Is this a feature?
Actually I use `\textsuperscript{1}` instead to force sans serif.

**Comment by louisstuart96** [comment]
Beamer's `\inst` is a small math formula, e.g., `\inst{1}` typesets something like `$^{1}$`.

**Comment by e-kwsm** [comment]
In default font theme, `\inst` is in sans serif.
`\inst` should be in sans serif regardless of font theme, if easy to fix.
