### ISSUE TITLE
[Feature Request] description body template

### ISSUE THREAD

**Issue by e-kwsm** [josephwright/beamer#395]
`description` environment has fewer beamer-templates than `itemize` and `enumerate`.
`itemize/enumerate body` is the template to modify bodies of `itemize` and `enumerate`, while `description body` is not provided, so we have to manually insert font and/or color modifiers, e.g. `\large`, in `description`.

Is there any reason not to support this?

**Comment by josephwright** [comment]
I suspect that Till was imagining people using `description` only rarely (see various other apparent gaps in support): I'll take a look.
