### ISSUE TITLE
Extra \pause after block environments in case of \beamerdefaultoverlayspecification{<+->}

### ISSUE THREAD

**Issue by dbitouze** [josephwright/beamer#398]
The following MCE behaves as expected (gives a 2 pages document) but, as soon as `\beamerdefaultoverlayspecification{<+->}` is uncommented, an extra `\pause` is inserted at the end of the `block` environment (gives a 3 pages document):

```latex
\documentclass{beamer}
% \beamerdefaultoverlayspecification{<+->}
\begin{document}
\begin{frame}
  \begin{block}{Foo}
    Bar
  \end{block}
  \pause
  Baz
\end{frame}
\end{document}
```

**Comment by josephwright** [comment]
Isn't it the same though as
```latex
\documentclass{beamer}
%\beamerdefaultoverlayspecification{<+->}
\begin{document}
\begin{frame}
  \begin{block}<+->{Foo}
    Bar
  \end{block}
  \pause
  Baz
\end{frame}
\end{document}
```
which whilst perhaps unexpected to the unwary _is_ what setting the default spec does.

**Comment by dbitouze** [comment]
> Isn't it the same though as [...]

Indeed.

But the point is, you probably won't enable the `+-` behavior locally for a block if you want to insert a `\pause` after it, but you may want to globally enable the `+-` behavior e.g. for lists and, then, you are bitten by this bug.

BTW, as a workaround, `\pause[\thebeamerpauses]` could be used instead of `\pause`:
```latex
\documentclass{beamer}
\beamerdefaultoverlayspecification{<+->}
\begin{document}
\begin{frame}
  \begin{block}<+->{Foo}
    Bar
  \end{block}
  \pause[\thebeamerpauses]
  Baz
\end{frame}
\end{document}
```
but that's not very handy.

> which whilst perhaps unexpected to the unwary is what setting the default spec does.

Anyway, I guess an expected behavior is preferable :)

**Comment by louisstuart96** [comment]
I've investigated the counter `beamerpauses` and its behavior in overlay.

1. At the beginning of a frame, set `beamerpauses` counter  to 1;
2. When an overlay specification with `+` is encountered, substitute `+` by the counter's value (probably with some offset; see page 90 on the manual), and then step this counter;
3. When `\pause` is used without an optional argument, step this counter **first**, and then  `\onslide<\thebeamerpauses->` is performed.

Because `beamerpauses` is a LaTeX counter, any operations like setting, adding and stepping will be global.

A possible idea is that, first perform `\onslide<{\thebeamerpauses+1}->`, and then step the counter.

**Comment by josephwright** [comment]
@louisstuart96 All true. As I've already noted, whilst some people might be caught out by the current behaviour, it is what should be expected given how a default spec is meant to work.

**Comment by josephwright** [comment]
@louisstuart96  Are you sure changing the behaviour of `\pause` is a good plan? Does it leave the equivalence I pointed out earlier unchanged? (That `\beamerdefaultoverlayspecification{<+->}` should be exactly the same as written out `<+->` in every place that an overlay can apply to.)

**Comment by louisstuart96** [comment]
I've made a mistake here.. Maybe another revert, sigh.

**Comment by louisstuart96** [comment]
@josephwright Another idea is to initialize `beamerpauses` counter to zero, and change the process of parsing `+` and `.`.

**Comment by FrankMittelbach** [comment]
Am 08.07.17 um 15:14 schrieb Joseph Wright:
> @louisstuart96 <https://github.com/louisstuart96> Are you sure changing 
> the behaviour of |\pause| is a good plan? Does it leave the equivalence 
> I pointed out earlier unchanged? (That 
> |\beamerdefaultoverlayspecification{<+->}| should be exactly the same as 
> written out |<+->| in every place that an overlay can apply to.)

sounds to me like a really dangerous move which is most likely producing 
grief. There are so many presentations out there and people expect that 
they will continue to produce exactly the same sequence of overlays, so 
any change in that space would need to guarantee that all major (and 
minor) behaviors are left unchanged.

So in my opinion that space would need a rigorous test suite first, 
before there is any attempt to change anything.

**Comment by dbitouze** [comment]
This issue has been closed but, even with `beamer.cls    2017/08/22 v3.43`, the trouble reported in the OP persists.

**Comment by josephwright** [comment]
@dbitouze  That's because this is by-design.

**Comment by dbitouze** [comment]
Okay. Too bad, but okay :)
