### ISSUE TITLE
Could not write document properties pdftitle and pdfauthor to PDF file

### ISSUE THREAD

**Issue by zohooo** [josephwright/beamer#401]
With the following minimal example

    \documentclass{beamer}
    \begin{document}
    \title{Title}
    \author{Author}
    \maketitle
    \end{document}

`beamer` could not write document properties `pdftitle` and `pdfauthor` to PDF files.

![pdftitle](https://user-images.githubusercontent.com/1684992/27637061-f913c444-5c40-11e7-9c32-eef5bafb7f59.png)

If I move `\title` and `\author` commands to the preamble, `beamer` writes document properties correctly.

**Comment by samcarter8** [comment]
Use `\title{Title}
\author{Author}` before `\begin{document}`

**Comment by ghost** [comment]
@zohooo  The pdf properties are written at the begin of the document, if you change them only after `\begin{document}` the (empty) ones have already been written to the pdf. 

See https://tex.stackexchange.com/a/93705/36296 (the last sentence is relevant, as `beamer` uses `hyperref` for the pdf meta data)

**Comment by zohooo** [comment]
@samcarter8 By default `hyperref` write pdf properties at the output of the first page. Therefore the following example writes  pdf properties correctly:

    \documentclass{article}
    \usepackage{hyperref}
    \begin{document}
    \hypersetup{pdftitle={My Title},pdfauthor={My Author}}
    Hello TeX!    
    \end{document}

But `beamer` passes option `implicit=false` to `hypreref` and causes this problem. See
[hyperref with implicit=false gives a warning](https://tex.stackexchange.com/a/95034/8956)

There may be some situations when users could not put `\title` in the preamble. For example, maybe users need to use `CJK` package with `beamer`.

**Comment by louisstuart96** [comment]
Currently `beamer` uses `usepdftitle` option to control the behavior, that is, setting this to `false` will avoid setting `pdftitle` in `\AtBeginDocument` hook.
Nonetheless, I feel it necessary to avoid it when `\title` command isn't used at preamble.

**Comment by josephwright** [comment]
I think this is 'by design': the title, _etc._ are meta-data so belong in the preamble not the document body.

**Comment by dbitouze** [comment]
But can be troublesome for French documents where, if title content is set in the preamble, the (horizontal space before the) punctuation marks may be wrong (because of some settings made at begin document by the `frenchb` `babel`'s module):
```latex
\documentclass[french]{beamer}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\title{La crise, quelle crise ?} % Wrong (too big) space
\begin{document}
\author{La crise, quelle crise ?} % Right space
\maketitle
\end{document}
```
![document](https://user-images.githubusercontent.com/1032633/35010184-57001e4e-fb02-11e7-906f-f65b8f18ff51.png)

**Comment by dbitouze** [comment]
Another trouble with this restriction: suppose you have a presentation made from different child files that you collect, depending on the audience: you may want to add to the metadata of the resulting PDF the keywords of the presentation which is the collection of the keywords attached to the each of the child files (let say, with an `expl3's` `clist` ;). But the whole list is known only at the end of the document.

This is possible with standard classes, e.g.:
```latex
\documentclass{article}
\usepackage{xparse}
\usepackage{hyperref}

\ExplSyntaxOn
\clist_new:N \g_keywords_clist
\clist_gset:Nn \g_keywords_clist {a,b}
\NewDocumentCommand{\keywords}{ m }{
  \clist_put_right:Nn \g_keywords_clist {#1}
}
\AtEndDocument{
  \hypersetup{pdfkeywords={\clist_use:Nn \g_keywords_clist { ,~ }}}
}
\ExplSyntaxOff

\begin{document}
Foo.
\keywords{c,d,e,f}
Bar.
\keywords{g,h,i,j}
\end{document}
```
which leads to:
```bash
$ pdfinfo test.pdf | grep Keywords 
Keywords:       a, b, c, d, e, f, g, h, i, j
```
It would be nice for this to be possible with `beamer` as well.
