### ISSUE TITLE
Failed to build PDF using Makefile in `example` folder

### ISSUE THREAD

**Issue by louisstuart96** [josephwright/beamer#403]
In `example` folder, `Makefile` seems to run `pdftex` like this:
```
pdflatex a-lecture/beamerexample-lecture-print-version
```
`a-lecture\beamerexample-lecture-style.tex` cannot be found by TeX, resulting in errors like: 
```
! LaTeX error: File 'beamerexample-lecture-style.tex' not found.
```

**Comment by louisstuart96** [comment]
This error happens in MSYS2 environment. I'll try it under a Linux distribution later.

**Comment by josephwright** [comment]
Looks like it works there. To be honest, I'm keen to switch to a platform-neutral system: we are extending `l3build`  and fingers-crossed it will be able to cover everything soon-ish.

**Comment by josephwright** [comment]
Hmm, my new PC has the same issue: I'll need to fix to do a release!

**Comment by josephwright** [comment]
I've worked out why this happens: there's an assumption that you'll have added the `beamer` dev location to `TEXINPUTS` (that's how I am set up for development, for example, as there is no convenient 'localinstall' target). For the present, that's the best approach I suspect as we  really need to set up a better build script: one that doesn't rely on Unix would be best. I'll work on that.
