### ISSUE TITLE
beamer uses bitmap fonts at small size with T1-encoding

### ISSUE THREAD

**Issue by u-fischer** [josephwright/beamer#408]
beamer has changed the `\EC@family` definition in beamerbasefont.sty. It now includes also the sizes `<3>` and `<4>`.

 ```
 \def\EC@family#1#2#3#4#5{%
  \DeclareFontShape{#1}{#2}{#3}{#4}%
  {<3><4><5><6><7><8><9><10><10.95><12><14.4>%
   <17.28><20.74><24.88><29.86><35.83><42.99><51.59>genb*#5}{}}
```

This avoid messages about size substituations but as there is no `sfss0400.pfb` in the cm-super package and no entry for  `ecss0400` in the `pdftex.map` this means that bitmap fonts are used at this size:

```
\documentclass{beamer}
\usepackage[T1]{fontenc}
\begin{document}
\begin{frame}
abc \Tiny abc 
\end{frame}
\end{document}
```

       ..../.texlive2017/texmf-var/fonts/pk/ljfour/jknappen/ec/ecss0400.600pk>

It would be imho better to define the small sizes as `<3-5>ecss0500`.

**Comment by louisstuart96** [comment]
It looks like introducing `extsizes` into `beamer` brings a lot of troubles (annoying warnings, actually) to fixed-size EC family fonts.

In `texmf/tex/latex/base` directory, All the font definition files with `T1` and `TS1` font encoding use `\EC@family` macro, while `beamer` redefines `t1cmr` and `t1cmss`. Things are different in cyrillic font encodings like `T2A` and `X2`, where the minimal font size is 8. 

I wonder if it's necessary to add redefinitions of `ts1cmr` and `ts1cmss`.

**Comment by eg9** [comment]
In my opinion, `fix-cm.sty` should be used instead of doing those declarations. It allows *any* font size, while keeping optical design.

**Comment by u-fischer** [comment]
I'm not sure if fix-cm is the best idea. For beamer the very small font sizes (\tiny \Tiny) are useful and sensible sizes, and as fonts in design size of 0500, 0600 and 0700 exists for cmss/ecss in cm-super it should imho use it. (3 and 4 is naturally wrong).

**Comment by eg9** [comment]
@u-fischer One should ask Frank Mittelbach why only sizes from ecss0800 up are used for sans serif in `fix-cm`. Anyway, it would be quite easy to modify *those* choices to use also ecss0500, ecss0600 and ecss0700.

**Comment by FrankMittelbach** [comment]
@u-fischer @eg9 not sure I know that, the packages wasn't developed back then by us but by Walter. Anyhow what I think I remember is that at least initially the sans family wasn't available in sizes smaller than 8pt.

**Comment by u-fischer** [comment]
The bug has been resolved only partly for the T1-encoded fonts. But the following two OT1-declarations in beamerbasefont  are still wrong and led to bitmap fonts or even to missing tfm-messages:

       \DeclareFontShape{OT1}{cmr}{m}{n}%

       \DeclareFontShape{OT1}{cmr}{bx}{n}

```
\documentclass{beamer}
\begin{document}
\begin{frame}
\fontfamily{cmr}\Tiny abc

\fontfamily{cmr}\fontseries{bx}\Tiny abc

\end{frame}
\end{document}
```

**Comment by louisstuart96** [comment]
@u-fischer A new commit [3bac00a](https://github.com/josephwright/beamer/commit/3bac00a7a4d95067ccb6e6aac0f0be1c9f802a1a) has fixed this. Though a solution like `fix-cm` may be better. That is for @josephwright to decide.
