### ISSUE TITLE
Problem with \end{frame} in verbatim environment

### ISSUE THREAD

**Issue by ivokabadshow** [josephwright/beamer#410]
The following MWE does not compile with beamer 2017/07/13 v3.42 from TeXLive 2017-20170807:

```
\documentclass{beamer}

\begin{document}
\begin{frame}[fragile]
  \begin{verbatim}
    \end{frame}
  \end{verbatim}
\end{frame}
\end{document}
```

The problem only occurs when `\end{frame}` is used within the verbatim environment, despite the use of `[fragile]`. A different text does not cause the problem. The error produced by lualatex is the following:

```
Runaway argument?
! File ended while scanning use of \@xverbatim.
```
However, an older version (e.g. 3.36) of latex beamer from TeXLive 2016-20160801 does compile the MWE correctly without errors.

Further investigation showed that it looks like a regression from commit 0c387de (Fix for issue #326).

**Comment by ivokabadshow** [comment]
Since this was answered on [stackoverflow](https://tex.stackexchange.com/questions/385810/latex-beamer-verbatim-problem-with-endframe-in-texlive-2017/385813#385813) just now, and it seems the old versions just worked by accident, the issue can be closed.

**Comment by josephwright** [comment]
Indeed: something has to 'give' in terms of allowing indented material with verbatim or the very special case of documenting `beamer` itself.
