### ISSUE TITLE
Beamer v3.37 introduces error when using \label within sectioning commands

### ISSUE THREAD

**Issue by jorgesca** [josephwright/beamer#411]
I make use of [rst2beamer](https://github.com/myint/rst2beamer.git), which allows me to prepare simple beamer presentations from ReStructuredText. 
rst2beamer produces sections with labels defined within the sectioning command: e.g. 
```latex
\section{Section 1%
  \label{section-1}%
}
```
Older versions of beamer up to v3.36 manage this correctly. From v3.37 up, however, an error appears when compiling the latex code (in my case with pdflatex).
Below there is a minimal working example that, although not very useful for a beamer presentation, exhibits what I described above:
```latex
\documentclass[t]{beamer}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}

\begin{document}

\section{Section 1%
  \label{section-1}%
}

This is a test

\end{document}
```
I poked around the code, but my limited knowledge of beamer's internals didn't allow me to find the specific change introduced in v3.37 causing this behavior.

**Comment by josephwright** [comment]
I'll have a look, but I would suggest not having the label in the section heading but rather following it
```latex
\section{Section 1}%
\label{section-1}%
```

**Comment by jorgesca** [comment]
OK, I'll check if/how rst2beamer can be made to do this. I asked here just to check if this was a bug in beamer. I mean, my initial feeling upon seeing this placing of labels was the same as yours, but then I checked with the article class and it didn't complain at all.

**Comment by josephwright** [comment]
Issue will be fixed in the next release: later today if I can!

**Comment by jorgesca** [comment]
I can confirm that v3.43 fixes this issue for me. That was quick! Thank you very much!

**Comment by louisstuart96** [comment]
Can we make these commands (with optional overlay specifications) more robust? Or, more precisely, do we need to do so?
