### ISSUE TITLE
shadow color is abnormal

### ISSUE THREAD

**Issue by jszhao** [josephwright/beamer#412]
The following code will show the shadow color in the current release that is different with v3.41. In v3.41, the shadow color is gray (?) and changed gradually. In current version, the shadow color is solid, and as same as the frame box.

```
\documentclass{beamer}
\usetheme{Madrid}
\title{A test}

\begin{document}

\begin{frame}[plain]
\maketitle
\end{frame}

\end{document}
```

**Comment by ghost** [comment]
Problem seems to be the changes in `beamercolorbox`. Seems to work fine with the version before the commit https://github.com/josephwright/beamer/commit/7f21ca3cd8d7d749b4d255811b5a8c726be06933
