### ISSUE TITLE
The shadow of the title became very ugly in Madrid theme with beamer 3.43.

### ISSUE THREAD

**Issue by hair-splitter** [josephwright/beamer#413]
I have got a beamer presentation with Madrid theme, any other theme (color, outer, etc) is not included. In Madrid theme the title is framed and shadowed. I compilered this tex code with the beamer 3.43, and the shadow became very ugly. Previously this code worked perfectly. Try the following:

\documentclass{beamer}
\usetheme{Madrid}
\begin{document}
\title{Title}
\maketitle
\end{document}

**Comment by ghost** [comment]
see https://github.com/josephwright/beamer/issues/412

**Comment by josephwright** [comment]
This is a dupe of #412: I'll arrange to do a release later today to address it.
