### ISSUE TITLE
\temporal broken when used in conjunction with \colorcell of package colortbl (since Beamer 3.42)

### ISSUE THREAD

**Issue by ftronel** [josephwright/beamer#414]
The following snippet of code used to work as expected with Beamer 3.41:

    \documentclass[xcolor=table]{beamer}
    \usepackage{colortbl}

    \begin{document}

    \begin{frame}
    \begin{tabular}{|c | c | c | c |}
    \hline
     X
     & \only<2>{\cellcolor{yellow}}1 
     & \only<3>{\cellcolor{yellow}}2 
     & \only<4>{\cellcolor{yellow}}3 \\
    \hline
     Y
     & \temporal<2>{\invisible{A}}{\cellcolor{yellow}A}{A} 
     & \temporal<3>{\invisible{B}}{\cellcolor{yellow}B}{B}  
     & \temporal<4>{\invisible{C}}{\cellcolor{yellow}C}{C}   \\
    \hline
    \end{tabular}
    \end{frame}

    \end{document}

The expected behaviour is as follows:
Slide 1: A,B and C are invisible
Slide 2: A appears in column 1 whose background is now yellow
Slide 3: A remains visible, B appears in the second column whose background is now yellow
Slide 4: A and B are still visible and C appears in the last column whose background is now yellow.

However, since Beamer 3.42, this snippet doesn't work as expected: in slide 2, A disappears and will reappear in the last slide.

Using git bisect between 3.41 and 3.42 seems to point the following commit as responsible for this regression:
https://github.com/josephwright/beamer/commit/82365786006b941c8e5211cec678dbf4ce5a1e7f whose comment is the following one:

> Drop \ifbeamer@localanotherframe. 
> 
> This seems to be entirely redundant: only used by \temporal, which works fine without it!

Best regards,

Frédéric

**Comment by josephwright** [comment]
I guess we can just leave the code in then: I'll revert.

**Comment by louisstuart96** [comment]
This simple MWE works well. Why does this bug happen in a tabular? Does it involve `\protected`?
```
\documentclass{beamer}

\begin{document}

\begin{frame}{Test temporal}

\temporal<2>{\invisible{A}}{{\color{yellow}A}}{A} \par
\temporal<3>{\invisible{B}}{{\color{blue}B}}{B} \par
\temporal<4>{\invisible{C}}{{\color{red}C}}{C} \par

\end{frame}

\end{document}
```
Edit: this is the only overlay command using `\beamer@ifanotherslide`. This bug is because these 'another slide' states conflict with one another. But why this MWE is correct confuses me.

Edit again: These 'another slide' states do conflict. I adjust the sequence of these three `\temporal`s and it goes wrong:
```
\documentclass{beamer}

\begin{document}

\begin{frame}{Test temporal}

\temporal<3>{\invisible{B}}{{\color{blue}B}}{B} \par
\temporal<4>{\invisible{C}}{{\color{red}C}}{C} \par
\temporal<2>{\invisible{A}}{{\color{yellow}A}}{A} \par

\end{frame}

\end{document}
```

**Comment by josephwright** [comment]
It's a bit more complicated than backing out that one change: it doesn't entirely fix things. I'm working on it!

**Comment by louisstuart96** [comment]
Here's a full example to analyze this bug:
```
\documentclass{beamer}

\makeatletter
\def\showanotherslidemark{\ifbeamer@anotherslide (Need)\else(Not)\fi}
\makeatother

\begin{document}

\begin{frame}{Test temporal}

\temporal<2>{-}{{\color{yellow}A}}{A} \showanotherslidemark\par
\temporal<5>{=}{{\color{blue}B}}{B} \showanotherslidemark\par
\temporal<7>{*}{{\color{red}C}}{C} \showanotherslidemark\par

\end{frame}

\begin{frame}{Test temporal with different sequence}

\temporal<5>{-}{{\color{blue}B}}{B} \showanotherslidemark\par
\temporal<7>{=}{{\color{red}C}}{C} \showanotherslidemark\par
\temporal<2>{*}{{\color{yellow}A}}{A} \showanotherslidemark\par

\end{frame}


\begin{frame}{Test temporal in tabular}

\begin{tabular}{|c | c | c | c |}
\hline
 X
 & \only<2>{\color{yellow}}1 
 & \only<5>{\color{blue}}2 
 & \only<7>{\color{red}}3 \\
\hline
 Y
 & \temporal<2>{-}{{\color{yellow}A}}{A} \showanotherslidemark 
 & \temporal<5>{=}{{\color{blue}B}}{B} \showanotherslidemark 
 & \temporal<7>{*}{{\color{red}C}}{C} \showanotherslidemark \\
\hline
\end{tabular}
\end{frame}

\end{document}
```
