### ISSUE TITLE
beamerinnerthemedefault.sty throwing errors

### ISSUE THREAD

**Issue by millerj870** [josephwright/beamer#416]
I have a new vanilla install of MacTeX and am re-compiling an old beamer document (8 years old).  When I do so, I get "undefined control sequence" errors that trace back to beamerinnerthemedefaul.sty and its use of \pgfdeclareimage (lines 16 through 36, for me).  This persists even after cutting back all content and preamble to the bare minimum.

I've updated my beamer files to the latest.  Problem still persists.

**Comment by josephwright** [comment]
I'll need a minimal example here: `beamer` does work generally!

**Comment by millerj870** [comment]
Joseph,

Thanks for the quick email.  I’m at a loss for how to troubleshoot this.

Here’s the original presentation I was trying to compile (with both pdflatex and latex):

	https://goo.gl/ENNMTf

It compiles fine on ShareLaTeX.  I’ve just updated my entire TeX installation to have the newest versions of everything (via MacTeX on OS X Sierra).  I’ve compiled through TeXShop, TextMate, and the console.

Event when I comment out all non-essential content from my source file, latex pukes on me.

Here’s the console output when I compile:

	https://goo.gl/s5K8Gk

Thanks in advance for whatever pointers you can give.  I expect the problem is on my end.  I’m just stumped.

Jason

================================================================
Jason E. Miller, Ph.D.
http://about.me/jasonemiller
http://www.google.com/profiles/millerj870
C: 660-234-5028

A person is entitled to his own opinions, but not his own facts.
--Daniel Patrick Moynahan

**Comment by josephwright** [comment]
Your `.log` shows you have some files in your local tree (~/Library/texmf`). Almost certainly you have conflicting versions there compared with your main tree. The local files won't be affected by updating your main TeX system.

**Comment by millerj870** [comment]
OK, I see that.  I trashed anything in my local tree that might conflict.  Then it appears I’m trading that problem (which appears to be fixed), for this one:

	https://goo.gl/yndxgs

Jason

**Comment by millerj870** [comment]
OK.  Found the culprit.  All was user error.  Thank you so much for pointing me in the right direction that helped me solve the problem!

Best,
Jason

==================================
Jason Miller, Ph.D.
Professor of Mathematics
California State University Channel Islands
jason.miller@csuci.edu
W:  805-437-xxxx
