### ISSUE TITLE
Duplicate labels caused by `\againframe`

### ISSUE THREAD

**Issue by louisstuart96** [josephwright/beamer#418]
The frames generated by `\againframe` use the same `\beamer@againname` as the original frames, therefore this piece of code may generate duplicate labels:

```
% beamerbaseframe.sty, lines 97-105
      % Insert labels if necessary:
      \ifx\beamer@againname\@empty\else%
        \nointerlineskip\vbox to0pt{\vss%
        \label<\the\beamer@slideinframe>{\beamer@againname<\the\beamer@slideinframe>}%
        \ifnum\beamer@slideinframe=1\relax%
          \label<1>{\beamer@againname}%
        \fi%
        }\nointerlineskip%
      \fi%
```

**Comment by louisstuart96** [comment]
Perhaps we shall write some notice for this in the documentation, rather than really fixing this?

Edit: The latter one `\label<1>{\beamer@againname}` can be handled using a switch like `\ifbeamer@isagainframe`, but the former ones are much more complicated.

**Comment by jagjordi** [comment]
How can the duplicated label messages be supressed from the logs?

**Comment by samcarter** [comment]
> How can the duplicated label messages be supressed from the logs?

Not a good idea and it might remove also warnings that don't come from againframe, but if you insist:

```
\documentclass{beamer}

\usepackage{silence}

\WarningFilter{latex}{Label `}

\begin{document}
	
\begin{frame}[label=foo]
	abc
\end{frame}	

\againframe{foo}
	
\end{document}
```

**Comment by jagjordi** [comment]
I found that doing `\againframe<10>{foo}` supresses the warning also, not sure if it has any unwanted effects
