### ISSUE TITLE
alert does not work in the first item of itemize within a block

### ISSUE THREAD

**Issue by silvansievers** [josephwright/beamer#419]
Using the following minimal example, the text "not in red" is not shown in red although it should:
```
\documentclass{beamer}
\usetheme{Frankfurt}

\begin{document}
\begin{frame}{Title}
  \begin{block}{Block}
    \begin{itemize}
      \item \alert{not in red} some text \alert{in red} more text

      \item \alert{in red}
    \end{itemize}
  \end{block}
\end{frame}
\end{document}
```

As soon as I insert anything before `\alert{not in red}`, even something like `\hspace{-3pt}`, it works as intended. (See also a person at stackexchange having the same problem: https://tex.stackexchange.com/questions/386092/beamer-how-to-use-alert-in-itemize-inside-a-block who suggests that this only arises with the Frankfurt template.)

pdflatex version
```
pdfTeX 3.14159265-2.6-1.40.17 (TeX Live 2016/Debian)
kpathsea version 6.2.2
Copyright 2016 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.28; using libpng 1.6.28
Compiled with zlib 1.2.8; using zlib 1.2.11
Compiled with poppler version 0.48.0
```

beamer version: 
```
\ProvidesClass{beamer}
  [2017/01/22 v3.40 A class for typesetting presentations]
```

This problem does not arise with older versions (such as on Ubuntu 16.04, where beamer based on commit `8a39122e1f63 2015/01/05 22:01:48` is used). Unfortunately, I cannot easily test this with the latest version of latex.

**Comment by louisstuart96** [comment]
Your MWE seems OK in the newest version of beamer(v3.43). I'm trying to check out if we have fixed it somewhere.

**Comment by louisstuart96** [comment]
see #361 .

**Comment by silvansievers** [comment]
Thanks and sorry for not finding that issue before.

**Comment by louisstuart96** [comment]
You can download our release and replace the original codes in your TeX Live distribution, and then execute `mktexlsr` command.
