### ISSUE TITLE
Trying to add shading to frametitle.

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#42]
Originally reported by: **mattbellis (Bitbucket: [mattbellis](https://bitbucket.org/mattbellis), GitHub: [mattbellis](https://github.com/mattbellis))**

----------------------------------------

Hi all, 
   
  This is more a general question for the beamer community than a bug (I think). 

   I'm trying to add the color fading that used in the Singapore theme for the head to a different section of a frame. I don't use a head, but I'd like to use that effect for the frametitle for my own .sty. 

   The easiest way to show you what I'm trying to do is for you to add these lines to the end of the Copenhagen theme. The end of beamerthemeCopenhagen.sty then looks like this for me. 

    
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Added this
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    \AtBeginDocument{%
        {
         \usebeamercolor{frametitle}
        }
        \pgfdeclareverticalshading{beamer@frametitlefade}{\paperwidth}
        {%
         color(0.0cm)=(bg);
         color(1.00cm)=(frametitle.bg)%
        }
        \setbeamercolor{frametitle}{bg=}
    }
    \addtobeamertemplate{frametitle}{\pgfuseshading{beamer@frametitlefade}\vskip-1.15cm}{}
    \beamertemplatedotitem
    
    
    \mode
    <all>
    

   I admit I kind of hacked it together after reading the user guide and trying to understand what was happening in the Singapore theme. My Latex compiles and I get the fading effect but there's a blank white space on the left of the frame title about an inch or so wide. I've been trying to find out where that's coming from, but no luck.  

   The fading looks pretty good if I could just get this last part swinging! Any help is greatly appreciated. 

   Beamer is awesome.  :)

Matt

----------------------------------------
- Bitbucket: https://bitbucket.org/rivanvx/beamer/issue/42

**Comment by josephwright** [comment]
*Original comment by* **Vedran Miletić (Bitbucket: [rivanvx](https://bitbucket.org/rivanvx), GitHub: Unknown)**:

----------------------------------------

Wow, never thought of this.

**Comment by samcarter** [comment]
@mattbellis You get the blank space because (unlike the headline) the frametitle takes into account the left text margin. You can verify this with the following quick example.

```
\documentclass{beamer}

\setbeamertemplate{headline}{!!!!!}
\setbeamertemplate{frametitle}{????}

\begin{document}
\begin{frame}
	\frametitle{title}
	abc
\end{frame}
\end{document}
```

Most themes that have frametitles that span the whole page correct for this. For example the Copenhagen theme  you mention in your question uses something like `\hskip-\Gm@lmargin\hbox{...}` in its frametitle. 

Because `\addtobeamertemplate{frametitle}{...}{...}` adds the shading before the theme starts the frametitle, you have to repeat these correction yourself:

```
\documentclass{beamer}

\usetheme{Copenhagen}

\makeatletter
\AtBeginDocument{%
    {\usebeamercolor{frametitle}}
    \pgfdeclareverticalshading{beamer@frametitlefade}{\paperwidth}{%
     color(0.0cm)=(bg);
     color(1.00cm)=(frametitle.bg)%
    }%
    \setbeamercolor{frametitle}{bg=}%
}
\addtobeamertemplate{frametitle}{\hspace*{-\Gm@lmargin}\pgfuseshading{beamer@frametitlefade}\vskip-1.15cm}{}
\makeatother

\begin{document}
	
\begin{frame}
\frametitle{title}
	abc
\end{frame}	
	
\end{document}
```
![Screen Shot 2019-11-22 at 22 55 16](https://user-images.githubusercontent.com/43832342/69463152-36380180-0d7b-11ea-976e-500ad0f9b556.png)
