### ISSUE TITLE
Introduce `sansmathfonts` as default sans-serif math font

### ISSUE THREAD

**Issue by louisstuart96** [josephwright/beamer#421]
Current `beamer` math font settings are complicated and not self-consistent. Using outline fonts brought by `sansmathfonts` package we can get a unified math font scheme.

**Comment by josephwright** [comment]
That would change a _lot_ of output, no?

**Comment by louisstuart96** [comment]
Indeed. Current math font settings are a combination of sans-serif letters/numbers and serif math symbols.

**Comment by louisstuart96** [comment]
Discussed in #375 .
