### ISSUE TITLE
Bug: \href after a \pause is shown on both slides

### ISSUE THREAD

**Issue by nim65s** [josephwright/beamer#422]
Hi,

As discussed in pdfpc/pdfpc/issues/299, we use `\href` to show videos ; and when we put an `\href` after a `\pause` to get a video on the second slide, it appears on both slides in the pdf.

Here is a minimal exemple:
```latex
\documentclass{beamer}
\begin{document}
\begin{frame}
    test
    \pause
    \href{run:apollo17.avi}{\includegraphics[width=\linewidth]{apollo17.jpg}}
\end{frame}
\end{document}
```

The image apollo17.jgp appears only on the second slide, but the link to the apollo17.avi video is present on both.

**Comment by louisstuart96** [comment]
Seems it's a feature rather than a bug: `\pause` works like `\uncover`, that is, the `\href` link indeed exists on the first slide, but in a covered state.

**Comment by louisstuart96** [comment]
For now, our suggestion is using detailed control command like `\only` instead of `\pause`.
