### ISSUE TITLE
Default special notes for allowframebreaks: Do not show the Roman number `I` if there is no actual break taking place

### ISSUE THREAD

**Issue by xuhdev** [josephwright/beamer#423]
Currently, when using `allowframebreaks` for bibliography, the special note Roman number `I` still shows even there is no actual break taking place. It is probably better to not show the Roman number if there is no real break.

**Comment by louisstuart96** [comment]
Currently there is a way to hide the continuation number at the first page:
```
\setbeamertemplate{frametitle continuation}[from second][\insertcontinuationcountroman]
```
But it will hide the number all the time, no matter if break happens or not.

I guess you want this: "hide number when there is no break; show **all** numbers when there is." It might be complicated to do so, I'm checking it.

**Comment by xuhdev** [comment]
Your guess is exactly what I meant. Thanks for looking into this.

**Comment by HolgerGerhardt** [comment]
Inspired by https://tex.stackexchange.com/questions/275044/how-do-i-insert-the-total-continuation-count-in-the-allowframbreaks-frame-title, here’s some code that implements the function “hide number when there is no break; show all numbers when there is”:

```
\newcounter{totalcontinuationcount}
\makeatletter
\setbeamertemplate{frametitle continuation}{%
    \setcounter{totalcontinuationcount}{\beamer@endpageofframe}%
    \addtocounter{totalcontinuationcount}{1}%
    \addtocounter{totalcontinuationcount}{-\beamer@startpageofframe}%
    \ifnum \value{totalcontinuationcount} > 1
        \textmd{(\insertcontinuationcount/\arabic{totalcontinuationcount})}%
    \fi
}
\makeatother
```

**Comment by oliviercailloux** [comment]
I simplified the code a bit.

```latex
\makeatletter
\defbeamertemplate*{frametitle continuation}{only if multiple}{%
    \ifnum \numexpr \beamer@endpageofframe+1-\beamer@startpageofframe\relax > 1
        \insertcontinuationcountroman%
    \fi
}
\makeatother
```

Indeed `\setbeamertemplate{frametitle continuation}[from second][\insertcontinuationcountroman]` is unsatisfactory, for the reason already mentioned.
But `\setbeamertemplate{frametitle continuation}[from second]` solves the problem equally well, IMHO.

**Comment by HolgerGerhardt** [comment]
Thanks, [Olivier](https://github.com/oliviercailloux)!

If you would like to also include the “total continuation count” in the frame title, you can use the following extension of [Olivier’s code](https://github.com/josephwright/beamer/issues/423#issuecomment-456494500):

```latex
\makeatletter
\defbeamertemplate*{frametitle continuation}{only if multiple}{%
    \ifnum \numexpr\beamer@endpageofframe+1-\beamer@startpageofframe\relax > 1
        \textmd{(%
            \insertcontinuationcount/%
            \the\numexpr\beamer@endpageofframe+1-\beamer@startpageofframe%
        )}%
    \fi%
}
\makeatother
```

This will add, for instance, “(1/3),” “(2/3),” and “(3/3)” to the frame titles _if_ frame breaks occur.

**Comment by oliviercailloux** [comment]
… that said, I can’t guarantee that my code will cause no hidden problem or that it follows best practices, as I am no expert in TeX/LaTeX. I just reused bits of code gathered here and there, with no deep understanding of what I am doing.

**Comment by shivangpatel** [comment]
@HolgerGerhardt You need to remove the last line `\makeatother`.  Otherwise, next time when your frame breaks, frame numbers will not be appearing. I know, you already fixed it.  😄 

@oliviercailloux Your code working perfectly fine for me.

**Comment by HolgerGerhardt** [comment]
@shivangpatel: I don’t understand your comment that one should remove the line `\makeatother`. To understand the meaning of `\makeatletter` and `\makeatother`, see https://tex.stackexchange.com/a/8353/156280.

I just checked that the code section(s) posted above work as intended. Here is my minimal working example:

```latex
\documentclass{beamer}


\usetheme{Boadilla}
\usecolortheme{beaver}

%\newcounter{totalcontinuationcount}
%\makeatletter
%\setbeamertemplate{frametitle continuation}{%
%    \setcounter{totalcontinuationcount}{\beamer@endpageofframe}%
%    \addtocounter{totalcontinuationcount}{1}%
%    \addtocounter{totalcontinuationcount}{-\beamer@startpageofframe}%
%    \ifnum \value{totalcontinuationcount} > 1
%        \textmd{(\insertcontinuationcount/\arabic{totalcontinuationcount})}%
%    \fi
%}
%\makeatother

\makeatletter
\defbeamertemplate*{frametitle continuation}{only if multiple}{%
    \ifnum \numexpr\beamer@endpageofframe+1-\beamer@startpageofframe\relax > 1
        \textmd{(%
            \insertcontinuationcount/%
            \the\numexpr\beamer@endpageofframe+1-\beamer@startpageofframe%
        )}%
    \fi%
}
\makeatother


\begin{document}

\newcommand{\testframe}{%
	Test.\par Test.\par Test.\par Test.\par Test.\par Test.\par Test.\par Test.\par Test.\par Test.\par Test.\par
}

\begin{frame}[allowframebreaks]{First: Not full, no number}
	\testframe
\end{frame}

\begin{frame}[allowframebreaks]{Second: Full}
	\testframe
	\testframe
\end{frame}

\begin{frame}[allowframebreaks]{Third: Full}
	\testframe
	\testframe
\end{frame}

\begin{frame}[allowframebreaks]{Fourth: Not full, no number}
	\testframe
\end{frame}

\begin{frame}[allowframebreaks]{Fifth: Full}
	\testframe
	\testframe
\end{frame}

\end{document}
```

**Comment by samcarter** [comment]
One could pre-define a new template that can be customized by the user to add things like parenthesis or total number of breaks. 

```
\documentclass{beamer}


\usetheme{Boadilla}
\usecolortheme{beaver}

\makeatletter
\defbeamertemplate{frametitle continuation}{singleframecheck}[1][\insertcontinuationcountroman]{%
    \ifnum \numexpr\beamer@endpageofframe+1-\beamer@startpageofframe\relax > 1
      #1
    \fi%
}
\makeatother

\setbeamertemplate{frametitle continuation}[singleframecheck]

\makeatletter
\setbeamertemplate{frametitle continuation}[singleframecheck][(\the\beamer@autobreakcount/\the\numexpr\beamer@endpageofframe+1-\beamer@startpageofframe)]
\makeatother


\begin{document}

\newcommand{\testframe}{%
	Test.\par Test.\par Test.\par Test.\par Test.\par Test.\par Test.\par Test.\par Test.\par Test.\par Test.\par
}

\begin{frame}[allowframebreaks]{First: Not full, no number}
	\testframe
\end{frame}

\begin{frame}[allowframebreaks]{Second: Full}
	\testframe
	\testframe
\end{frame}

\begin{frame}[allowframebreaks]{Third: Full}
	\testframe
	\testframe
\end{frame}

\begin{frame}[allowframebreaks]{Fourth: Not full, no number}
	\testframe
\end{frame}

\begin{frame}[allowframebreaks]{Fifth: Full}
	\testframe
	\testframe
\end{frame}

\end{document}
```

**Comment by shivangpatel** [comment]
> @shivangpatel: I don’t understand your comment that one should remove the line `\makeatother`. To understand the meaning of `\makeatletter` and `\makeatother`, see https://tex.stackexchange.com/a/8353/156280.
> 
> I just checked that the code section(s) posted above work as intended. Here is my minimal working example:
> 
> ```
> \documentclass{beamer}
> 
> 
> \usetheme{Boadilla}
> \usecolortheme{beaver}
> 
> %\newcounter{totalcontinuationcount}
> %\makeatletter
> %\setbeamertemplate{frametitle continuation}{%
> %    \setcounter{totalcontinuationcount}{\beamer@endpageofframe}%
> %    \addtocounter{totalcontinuationcount}{1}%
> %    \addtocounter{totalcontinuationcount}{-\beamer@startpageofframe}%
> %    \ifnum \value{totalcontinuationcount} > 1
> %        \textmd{(\insertcontinuationcount/\arabic{totalcontinuationcount})}%
> %    \fi
> %}
> %\makeatother
> 
> \makeatletter
> \defbeamertemplate*{frametitle continuation}{only if multiple}{%
>     \ifnum \numexpr\beamer@endpageofframe+1-\beamer@startpageofframe\relax > 1
>         \textmd{(%
>             \insertcontinuationcount/%
>             \the\numexpr\beamer@endpageofframe+1-\beamer@startpageofframe%
>         )}%
>     \fi%
> }
> \makeatother
> 
> 
> \begin{document}
> 
> \newcommand{\testframe}{%
> 	Test.\par Test.\par Test.\par Test.\par Test.\par Test.\par Test.\par Test.\par Test.\par Test.\par Test.\par
> }
> 
> \begin{frame}[allowframebreaks]{First: Not full, no number}
> 	\testframe
> \end{frame}
> 
> \begin{frame}[allowframebreaks]{Second: Full}
> 	\testframe
> 	\testframe
> \end{frame}
> 
> \begin{frame}[allowframebreaks]{Third: Full}
> 	\testframe
> 	\testframe
> \end{frame}
> 
> \begin{frame}[allowframebreaks]{Fourth: Not full, no number}
> 	\testframe
> \end{frame}
> 
> \begin{frame}[allowframebreaks]{Fifth: Full}
> 	\testframe
> 	\testframe
> \end{frame}
> 
> \end{document}
> ```

Sorry! My mistake. Compilation issue from my site.

**Comment by HolgerGerhardt** [comment]
Here is an example that creates a non-boldface continuation counter in square brackets (for instance, “[1&#8239;|&#8239;3]”, “[2&#8239;|&#8239;3]”, “[3&#8239;|&#8239;3]”):
```latex
\makeatletter
\setbeamertemplate{frametitle continuation}[singleframecheck][%
	\textmd{%
		{[}\the\beamer@autobreakcount\,\textbar\,%
		\the\numexpr\beamer@endpageofframe+1-\beamer@startpageofframe{]}%
	}%
]
\makeatother
```
I’m providing this example because the square brackets which are supposed to show up in the frame title as part of the continuation counter need to be escaped, given that they are now part of an optional argument to `\setbeamertemplate`.

**Comment by samcarter** [comment]
@HolgerGerhardt In your specific case, you don't need special treatment for the square brackets because they are inside `\textmd{}` 

```
\documentclass{beamer}


\usetheme{Boadilla}
\usecolortheme{beaver}

%\setbeamertemplate{frametitle continuation}[from second]

%\setbeamertemplate{frametitle continuation}[singleframecheck]


\makeatletter
\setbeamertemplate{frametitle continuation}[singleframecheck][%
	\textmd{%
		[\the\beamer@autobreakcount\,\textbar\,%
		\the\numexpr\beamer@endpageofframe+1-\beamer@startpageofframe]%
	}%
]
\makeatother
\begin{document}

\newcommand{\testframe}{%
	Test.\par Test.\par Test.\par Test.\par Test.\par Test.\par Test.\par Test.\par Test.\par Test.\par Test.\par
}

\begin{frame}[allowframebreaks]{First: Not full, no number}
	\testframe
\end{frame}

\begin{frame}[allowframebreaks]{Second: Full}
	\testframe
	\testframe
\end{frame}

\begin{frame}[allowframebreaks]{Third: Full}
	\testframe
	\testframe
\end{frame}

\begin{frame}[allowframebreaks]{Fourth: Not full, no number}
	\testframe
\end{frame}

\begin{frame}[allowframebreaks]{Fifth: Full}
	\testframe
	\testframe
\end{frame}

\end{document}
```

**Comment by HolgerGerhardt** [comment]
> In your specific case, you don't need special treatment for the square brackets because they are inside `\textmd{}`

Ah, sorry, thanks for pointing this out. You’re right.

I initially used `\mdseries` instead of `\textmd{...}`. In that case I did need to surround the square brackets with curly braces (both individually `{[} ... {]}` and as a whole `{[...]}` work).
