### ISSUE TITLE
User guide not present

### ISSUE THREAD

**Issue by JesApp** [josephwright/beamer#426]
`README.md` claims that a user manual is present at `doc/beameruserguide.pdf`. It's not there.

**Comment by josephwright** [comment]
It's there: http://mirrors.ctan.org/macros/latex/contrib/beamer/doc/beameruserguide.pdf

**Comment by JesApp** [comment]
Thanks for the link! I read 

>See the documentation in doc/beameruserguide.pdf for a user manual.

in `README.md` as referring to `https://github.com/josephwright/beamer/blob/master/doc/beameruserguide.pdf`, which is not there.

**Comment by josephwright** [comment]
@JesApp  Yes, but remember that the README is what is used by CTAN: that's the release version, this is just a development repo. On CTAN the relative location is entirely correct. (In a development repo it would be bad style to check in a derived binary file.)

**Comment by josephwright** [comment]
That said, probably the README could be updated.

**Comment by JesApp** [comment]
@josephwright I agree, checking in binaries isn't a good idea. I don't quite remember why I got here first rather than CTAN, but I think it would be a good idea to just have a straight link to the pdf doc.

I'd make a pull request, but I guess it would be more work for you to handle that than to just make the changes on your own.

**Comment by louisstuart96** [comment]
I've added hyperlinks (to CTAN) in commit [b3aa70d](https://github.com/josephwright/beamer/commit/b3aa70d39c3924ed561964c46f75aa388f35b02c). You can check the new `README.md` in the `stable` branch.

**Comment by JesApp** [comment]
Looks good, thanks. :)
