### ISSUE TITLE
What's the usage of `beamerbaseexercise.sty`?

### ISSUE THREAD

**Issue by louisstuart96** [josephwright/beamer#427]
This seems to be something left behind after some update, as well as counters like `ExNo` and `SubExNo`, which exist in the context of `\resetoverlaycounters`.

**Comment by SFr682k** [comment]
This file modifies some commands defined by the `exerquiz` package (part of the `AcroTeX` bundle, only included in MiKTeX; see [CTAN](https://ctan.org/pkg/exerquiz))  
However, it seems like `beamerbaseexercise.sty` is never loaded by `beamer` anywhere (adding a "fake package file" printing a frame at the begin of the document to the working directory doesn't have any effect until `\usepackage{beamerbaseexercise}` is added to the preamble).

**Comment by josephwright** [comment]
Added by Till in  9ff2d67c3d7e616fb48e9df2b82e0a3e4c75aaaa, empty log message.
