### ISSUE TITLE
Package multimedia requires luatex85 with lualatex

### ISSUE THREAD

**Issue by Socob** [josephwright/beamer#428]
This issue has previously been brought up by someone on TeX.SX: [“Undefined pdfannot in beamer when using lualatex - multimedia”](https://tex.stackexchange.com/q/337142).

Using the `\movie` command from the `multimedia` package with `lualatex` results in an error message:
>     Undefined control sequence.
>     <argument> \pdfannot 
>               width \@tempdima height \@tempdimb depth \@tempdimc { /Subtype /Movie

This can be remedied by including the package `luatex85` (see [comment by Ulrike Fischer](https://tex.stackexchange.com/q/337142#comment826680_337142)), indicating that the use of `pdflatex`-specific commands in the `multimedia` package has not yet been updated for compatibility with newer versions of `luatex`.

**Comment by davidcarlisle** [comment]
It would be much better to update multimedia.sty to use current luatex commands rather than force the loading of luatex85 compatibility.

**Comment by Socob** [comment]
@davidcarlisle Indeed, that was the intention behind my report. Although I have to admit that the current solution is better than nothing, and arguably easier to implement.
