### ISSUE TITLE
Footline is inserted on top of (above) frame contents

### ISSUE THREAD

**Issue by Socob** [josephwright/beamer#430]
Looking at the [TeX.SX question “How does beamer build the frame?”](https://tex.stackexchange.com/a/27302), we can see that the topmost “layer” in a `beamer` frame is the `footline`, and (as it turns out) it is inserted even above the frame contents. Personally, I think this is problematic for some use cases without providing a clear benefit. This is why I recently asked [whether it is possible to insert the footline further in the background instead of in the foreground](https://tex.stackexchange.com/q/402474), but the answer seems to be “no” (the only response so far involves hacking the `sidebar canvas left` to achieve a `footline`-like effect).

The issue I have with the current behavior is that it is sometimes desirable to position content on top of the other frame parts, *including* the footline. For example, when inserting an image absolutely on a frame (in a “stamp-like” fashion), it is vital that parts of the image are not hidden behind the footline. But also for themes with a rather tall footline, while not ideal, it can be useful to have the content overlap the footline when including very tall images or diagrams with small details (such as plots).

**Comment by louisstuart96** [comment]
As far as I know, `beamer` will pre-typeset the headline and footline before any frames are typeset, and then measure their heights to adjust the vertical size of body. This is done by `\beamer@calculateheadfoot`. Therefore, things like 'parts of the image are hidden behind the footline' will not happen under ordinary situations, I think.
This is for the fact that headlines or/and footlines may not be fixed-size, such as headlines used in `miniframes` and `split` outer theme.

**Comment by louisstuart96** [comment]
You're telling about situations when the contents of one slide exceed normal height of body. In this case I prefer adjusting the contents rather than dealing with footlines.
It's natrual to typeset headline, body and footline sequentially in a slide(page).

**Comment by ghost** [comment]
My personal opinion: If the content of your slide comes in the vicinity of the footline, this is a clear sign that the slide is too full. If the content cannot be changed, a plain frame would maybe better in this situation.

**Comment by Socob** [comment]
It seems like I need to give another example to make this clearer. This is **not** just about slides which are too full. Consider this example:

```latex
\documentclass{beamer}
\usetheme{Berlin}
\usepackage{tikz}

\begin{document}
\begin{frame}
	Frame contents

	\vspace{1.5cm}

	More frame contents

	\vspace{1.5cm}

	\dots

	\vspace{2cm}

	\Large
	$\Rightarrow$ Some proposal or other contents at the bottom
	which will be ``stamped over"

	\begin{tikzpicture}[remember picture, overlay]
		\node[draw, rotate=30] at (5em, 4ex)
			{\color{red!60}\huge\bfseries APPROVED};
	\end{tikzpicture}
\end{frame}
\end{document}
```

![beamer_stamp_example](https://user-images.githubusercontent.com/1915511/33207591-9675dbd6-d10e-11e7-9c06-0946ca94ff7c.png)

This doesn’t work because the box with the text “APPROVED” is cut off by the footline. I suspect that this hasn’t really come up before because most built-in beamer themes don’t have a tall footline (“Berlin” and “Ilmenau” have the tallest ones I could find).

@samcarter8 Plain frames have neither a footline **nor** a headline, so they are too inflexible. And, in any case, depending on the prominence of the footline within the theme, it may still be better to keep the footline even if contents overlap it. In any case, this doesn’t address the example I gave above.

I do realize that this “bug” is not clear-cut and the immediate reaction is to see the flaws in the user’s approach itself. But ask yourself this: What is the actual *advantage* of the current behavior (footline on top)? I have mentioned a lot of use cases which would benefit from a background footline. What use cases are there which need a footline in the foreground?

**Comment by e-kwsm** [comment]
How about this?
```tex
\documentclass{beamer}
\usetheme{Berlin}
\usepackage{tikz}

\makeatletter

\def\ft@overlay{}

\addtobeamertemplate{footline}{}{%
  \lineskiplimit0pt
  \begin{tikzpicture}[remember picture,overlay]%
  \ft@overlay
  \end{tikzpicture}%
  \gdef\ft@overlay{}%
}

\newcommand{\addtooverlay}[1]{%
  \expandafter\gdef\expandafter\ft@overlay\expandafter{\ft@overlay #1}%
}

\makeatother

\begin{document}
\usebackgroundtemplate{
  \begin{tikzpicture}[remember picture, overlay]
  \end{tikzpicture}
}
\begin{frame}
  Frame contents

  \vspace{1.5cm}

  More frame contents

  \vspace{1.5cm}

  \dots

  \vspace{2cm}

  \Large
  $\Rightarrow$ Some proposal or other contents at the bottom
  which will be ``stamped over"

  \addtooverlay{%
    \node[at=(current page.south west), anchor=south west, draw, rotate=30, xshift=9em, yshift=-8mm]
      {\color{red!60}\huge\bfseries APPROVED};
  }
\end{frame}
\end{document}
```
![img](https://user-images.githubusercontent.com/11627708/33208615-950604d2-d155-11e7-815c-1b8902faec3f.png)

ref:
* https://tex.stackexchange.com/questions/45420/overlay-an-entire-slide-with-a-semitransparent-rectangle-in-beamer

**Comment by Socob** [comment]
@e-kwsm Well, of course, with enough knowledge, one can do anything in TeX. But then, you don’t need packages or classes.

This is missing the point. I’m not saying it’s not **possible** to work around this in beamer. I’m saying that **the current behavior is undesirable and should be changed** (or at least a simple option should be provided if backwards-compatibility is a concern). I think beamer should be as simple and obvious to use as possible, with minimal necessity for hacks (like adding content to the `footline` template to put it in the foreground, as in your example). We have enough of that in LaTeX already, don’t you think?

**Comment by u-fischer** [comment]
It can't be avoided that things are typeset in a certain order. The output routine of latex builds a page by first typesetting the header,  then the textbody and then the footer. 
This means that the content of the footer will always overwrite everything else. 

And this means that the only way to get the footline "in the background" is to add it to the header template (which is possible). This is not a trivial change and would have the side effect that content in the text body now could overwrite the footline.

**Comment by Socob** [comment]
@u-fischer Hm, I thought beamer was based on PGF? If the whole frame is laid out using a PGF picture, controlling and changing the order in which the different frame layers appear is quite simple. But maybe my imagination of how beamer works internally is incorrect.

**Comment by louisstuart96** [comment]
@Socob Not that much. Most of `beamer`'s functions are based on LaTeX2e kernel, plus a lot of procedures involving boxes and overlays. As for headlines and footlines, they make use of kernel macros like `\@oddhead` and `\@oddfoot`.
