### ISSUE TITLE
Excluded frame (via mode specification) produces an error for the slide contents

### ISSUE THREAD

**Issue by NicoleRauch** [josephwright/beamer#431]
This minimal example renders perfectly well and produces 2 slides:

```
\documentclass[utf8]{beamer}

\begin{document}

\begin{frame}[fragile]{Title}

\begin{itemize}
\onslide+<2->
\item Some text
\end{itemize}

\end{frame}

\end{document}
```

When I exclude the frame via the mode specification `<0>`, I get an error message, though:

```
\documentclass[utf8]{beamer}

\begin{document}

\begin{frame}<0>[fragile]{Title}

\begin{itemize}
\onslide+<2->
\item Some text
\end{itemize}

\end{frame}

\end{document}
```

The error message is:

```
! LaTeX Error: Something's wrong--perhaps a missing \item.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.9 \item S
           ome text
```

I can fix this by either inserting an `\item` before the `\onslide` or by removing the `\onslide`, but that doesn't help me here (my goal is to be able to programmatically extract partial slide decks from a big slide deck, so I'd need to exclude slides without manually modifying them).

NB: And yes, I need the `[fragile]` because I use lots of `lstlisting` in my slides.

Did I do something wrong here? Or is this a bug in the mode specification?
Thanks for any insights!

**Comment by louisstuart96** [comment]
There is a bug in dealing with `\onslide` in your situation when no actual frame is typeset. I'm looking at it.

**Comment by NicoleRauch** [comment]
Thank you!
