### ISSUE TITLE
Items are not set to circle by LuaLaTeX and XeLaTeX

### ISSUE THREAD

**Issue by e-kwsm** [josephwright/beamer#432]
Consider the following MWE:
```tex
\documentclass{beamer}
\setbeamertemplate{itemize items}[circle]
\begin{document}
\begin{frame}
  \begin{itemize}
    \item X
  \end{itemize}
\end{frame}
\end{document}
```
PDFLaTeX works fine, namely the item marker is circle, but LuaLaTeX and XeLaTeX give square marker:
![items-circle](https://user-images.githubusercontent.com/11627708/33422569-7bc46d4e-d5f9-11e7-8346-8f8af8a68639.png)

My environment:
* beamer: 2017/11/10 v3.44
* PDFLaTeX: 3.14159265-2.6-1.40.18 (TeX Live 2017)
* LuaLaTeX: 1.0.4 (TeX Live 2017)
* XeLaTeX: 3.14159265-2.6-0.99998 (TeX Live 2017)

**Comment by louisstuart96** [comment]
The 'circle' glyph in Latin Modern Sans OpenType font (U+2022) happens to be a rectangle.
```TeX
% XeTeX or LuaTeX
\ifx\directlua\undefined\else
\input luaotfload.sty
\fi

\font\1="LMSans10-Regular"
\1\char"2022 

\font\2="LMRoman10-Regular"
\2\char"2022 

\bye
```
Edit: Latin Modern Type1 fonts (in TS1 encoding) have the same problem.

**Comment by josephwright** [comment]
@louisstuart96 So  'not our fault'? Raise with the font people?

**Comment by louisstuart96** [comment]
@josephwright Seems true. One solution would be replacing `\textbullet` with math symbol `$\bullet$`.

**Comment by leo-liu** [comment]
I think the key to the problem is that the bullet font should be unrelated with the text font.

Recently a MS dev and I talked a similar issue of PowerPoint. The solution of PPT is to typeset the bullet and list text separately. A circled bullet in PPT is always typeset with Arial. That is the solution.

**Comment by josephwright** [comment]
@leo-liu Hmm, not sure about that: probably it should not actually be from a _font_ at all: it's a graphical element, not a letter ...

**Comment by josephwright** [comment]
@leo-liu Font is still 'wrong' if the glyph has the incorrect appearance

**Comment by josephwright** [comment]
@louisstuart96 We could go with a low-level `pgf` circle construct: would be font-independent.

**Comment by leo-liu** [comment]
It is quite acceptable if the font is constant.

**Comment by josephwright** [comment]
@leo-liu I was thinking of two aspects. First, semantically t list marker is not the same as a bullet: the latter is a math symbol. Secondly, there is no particular reason to assume that the font is consistent: the body text and design of the slide are (or should be) separate.
