### ISSUE TITLE
latest update breaks compatibility with paralist

### ISSUE THREAD

**Issue by norbusan** [josephwright/beamer#435]
Hi Joseph,
I just updated my TL two days ago which brought a new beamer, and now several of my slides don't compile anymore, because `paralist` cannot be used any more, MNWE:
```latex
\documentclass{beamer}
\usepackage{paralist}
\begin{document}
\begin{frame}
Hello
\begin{itemize}
\item foobar
\end{itemize}
\end{frame}
\end{document}
```
gives:
```latex
! Undefined control sequence.
<argument> .../enumerate \beameritemnestingprefix 
                                                  body end
l.9 \end{frame}
```
Just FYI.

Norbert

**Comment by josephwright** [comment]
I'll take a look unless @louisstuart96 beats me to it: probably an update will be needed today.

**Comment by norbusan** [comment]
Thanks, no hurry. For my talk on Monday I can live without it ;-) You see, I prepare always last minute!

**Comment by josephwright** [comment]
It's been there for a few releases: 58c02995ff1222e1f3e0b618d85e72e441a626e0 introduces it.

**Comment by josephwright** [comment]
This has been around for a little while, so I think the fix (backing out the earlier change) can wait a few days. Fixed in the source repo so closing.

**Comment by norbusan** [comment]
Thanks, no hurry!

**Comment by louisstuart96** [comment]
Functions of `paralist` is incompatible with `beamer` in this MWE:

```
\documentclass{beamer}
\usepackage{paralist}

\begin{document}
\begin{frame}{Test frame}
\begin{itemize}[$\star$]
  \item Test
  \item Test
  \item Test
\end{itemize}
\end{frame}
\end{document}
```

Current patch only restores `itemize` environment to `beamer` version, therefore the optional argument can only be a `beamer` overlay specification.

I'll be working on a patch file for this. It will be published as a seperate file named `beamerpatchparalist.sty`, which will be automatically loaded in `\AtBeginDocument` hook if `paralist` is loaded. If patches for other packages are required. they'll also be named in the same way.

**Comment by josephwright** [comment]
@louisstuart96 Depending on the form of the code, wouldn't `beamerbasecompatibility.sty` be a 'natural' place?

**Comment by louisstuart96** [comment]
@josephwright For now, `beamerbasecompatibility.sty` contains mostly deprecated `beamer` commands. It's OK to include patch codes directly in this file, but a specialzed `patch` directory is more structured. This solution is inspired by `luatexja` package.

**Comment by josephwright** [comment]
@louisstuart96 I see your point: my only (slight) concern is that having lots of files tends to be slightly more tricky (e.g. reading the log) than having fewer larger ones ...

**Comment by louisstuart96** [comment]
One last step: load patch file in `\AtBeginDocument` hook (or `\beamer@lastminutepatches`).

**Comment by norbusan** [comment]
Thanks!

**Comment by norbusan** [comment]
Hi @josephwright @louisstuart96 
it somehow reappeared in current up2date TeX Live 2019 when using `compactitem` in a beamer frame  ... again just a few hours before my talk ;-)

**Comment by josephwright** [comment]
Could you open a new issue with a MWE and `\listfiles`?
