### ISSUE TITLE
Suggestions for automated testing

### ISSUE THREAD

**Issue by ghost** [josephwright/beamer#440]
Over the last year beamer underwent quite a few changes, code clean up and simplifications. To improve the stability I would love if a few things would be tested before new versions are released. Below is a list with suggestions of packages/themes which might be worth testing.

I do realise that the list is very long, but I hope it can be used as a starting point  to narrow it down to a manageable number of test scripts.

## Packages by beamer
Please test the first 3 packages in any case.

```
multimedia
beamerarticle
xmpmulti

beamerprosper
beamerseminar
beamerfoils
beamertexpower
```

## Packages suggested in beamer user guide
The following package are suggested at one place or another in the beamer user guide. A test including `pgfpages` would probably be very useful.

```
pgfpages

arev
avant
bookman
chancery
charter
euler
helvet
lmodern
mathtime
mathptm
mathptmx
newcent
palatino
pifont
utopia
```

## Themes provided by beamer
```
beamerthemeAnnArbor.sty
beamerthemeAntibes.sty
beamerthemeBergen.sty
beamerthemeBerkeley.sty
beamerthemeBerlin.sty
beamerthemeBoadilla.sty
beamerthemeboxes.sty
beamerthemeCambridgeUS.sty
beamerthemeCopenhagen.sty
beamerthemeDarmstadt.sty
beamerthemedefault.sty
beamerthemeDresden.sty
beamerthemeEastLansing.sty
beamerthemeFrankfurt.sty
beamerthemeGoettingen.sty
beamerthemeHannover.sty
beamerthemeIlmenau.sty
beamerthemeJuanLesPins.sty
beamerthemeLuebeck.sty
beamerthemeMadrid.sty
beamerthemeMalmoe.sty
beamerthemeMarburg.sty
beamerthemeMontpellier.sty
beamerthemePaloAlto.sty
beamerthemePittsburgh.sty
beamerthemeRochester.sty
beamerthemeSingapore.sty
beamerthemeSzeged.sty
beamerthemeWarsaw.sty
```

## other often used themes/packages
Of course beamer is not responsible if third party packages/themes do strange things and thus break compatibility with beamer, but if these problems are caught during testing, this could at least give the opportunity to contact the authors and give them a head start to fix things before users actually suffer from the problem. 

```
metropolis
beamerposter
media9
```

# beamer themes and packages on CTAN
Testing for all these goes probably way beyond the scope of beamer testing, I just wanted to add this (incomplete) list somewhere in case it may be useful for something or another in the future.

```
beamerthemeVerona.sty
beameraudience
beamercolorthemeowl.sty
beamercolorthemecormorant.sty
beamercolorthemefrigatebird.sty
beamercolorthememagpie.sty
beamersubframe
beamerswitch
beamerthemeCuerna.sty
beamerthemeDetlevCM.sty
beamerthemeepyt.sty
beamerthemePhnomPenh.sty
beamerthemeSaintPetersburg.sty
beamercolorthemegoeagles.sty
beamercolorthemepenn.sty
beamerthemeJLTree.sty
beamerthemenirma.sty
beamerthemeTorinoTh.sty
soton-beamer
beamerthemeUR.sty
beamerthemehohenheim.sty
beamerthemefibeamer.sty
medstarbeamer
```

In case it would be helpful, I can offer to create small .tex files that use the above mentioned packages/themes.

**Comment by louisstuart96** [comment]
I'm working on a minimal benchmark case in my repository: https://github.com/louisstuart96/beamer-benchmark/ . Any suggestions will be helpful.
