### ISSUE TITLE
block env cannot hide title or body with negative vspace since v3.43

### ISSUE THREAD

**Issue by ivokabadshow** [josephwright/beamer#441]
It seems the behavior of a `beamercolorbox` has changed unexpectedly in commit 7f21ca3c.

For rectangular boxes in the block environment `block`, `alertblock` and `exampleblock`, both title and body cannot be "hidden" by using negative `\vspace` anymore, if one of the elements is empty.

1. An empty body leads to a small block of background color at the beginning of the body.
2. An empty title leads to a block of fixed height that cannot be reduced with space.

Here is an MWE
```
\documentclass{beamer}
\usetheme{Rochester}
\begin{document}
\begin{frame}

\begin{block}{Title OK}
Body OK
\end{block}

\begin{block}{Title only, cannot hide block body}
\vspace{-1em}
\end{block}

\begin{block}{\vspace{-1em}}
Body only, cannot hide block title height
\end{block}
\end{frame}
\end{document}
```

Commit 92474f83 produces this
[working.pdf](https://github.com/josephwright/beamer/files/1550328/working.pdf)

Commit 7f21ca3c produces this
[notworking.pdf](https://github.com/josephwright/beamer/files/1550325/notworking.pdf)

Is this behavior wanted? If so, is there a workaround to achieve the expected behavior?

**Comment by louisstuart96** [comment]
In the current implementation of `beamercolorbox` environment, this behavior is to be expected. If a `beamercolorbox` is used with `colsep*` option, and background color is not empty, the colorbox will be typeset around an empty box. 
I'm investigating how the old implementation 'hides' these boxes.

**Comment by ghost** [comment]
@ivokabadshow As a workaround for empty title, you could use the first solution from https://tex.stackexchange.com/a/377781/36296

For the empty body you could do the same, just temporarily change the body background colour to the one from the title. 

```
\documentclass{beamer}
\usetheme{Rochester}

\usepackage{xstring}

\setbeamertemplate{block begin}
{
  \par\vskip\medskipamount%
  \IfStrEq{\insertblocktitle}{}{}{
      \begin{beamercolorbox}[colsep*=.75ex]{block title}
        \usebeamerfont*{block title}\insertblocktitle%
      \end{beamercolorbox}%
  }
  {\parskip0pt\par}%
  \ifbeamercolorempty[bg]{block title}
  {}
  {\ifbeamercolorempty[bg]{block body}{}{\nointerlineskip\vskip-0.5pt}}%
  \usebeamerfont{block body}%
  \begin{beamercolorbox}[colsep*=.75ex,vmode]{block body}%
    \ifbeamercolorempty[bg]{block body}{\vskip-.25ex}{\vskip-.75ex}\vbox{}%
}

\begin{document}
\begin{frame}
\begin{block}{Title OK}
Body OK
\end{block}

{
\setbeamercolor{block body}{bg=block title.bg, fg=block title.fg}
\begin{block}{}
Title only, cannot hide block body
\end{block}
}

\begin{block}{}
Body only, cannot hide block title height
\end{block}

\end{frame}
\end{document}
```
![document](https://user-images.githubusercontent.com/8226363/33889172-95ef5a94-df4f-11e7-82b7-0da7ce4f6664.png)

**Comment by louisstuart96** [comment]
The old implementation adds `colsep*` directly into the inner box, thus can be canceled by negative skip; the new implementation adds `colsep*` to the background color box (a `\vrule`), and the nested inner box has at lest zero height+depth, thus the background box can never be eliminated.

I've restored the old way in https://github.com/josephwright/beamer/commit/c426ee626ba733c2cec0e9f319f0647f8805a396 (though I somehow don't like it..)

**Comment by louisstuart96** [comment]
In the commit https://github.com/josephwright/beamer/commit/6b2d6418bb060e5b91471d2c4a859afbe56873a5, `colsep*` is still added to the background, but the inner box can have negative height+depth.

@samcarter8 Can you help us test this change? I wonder if this brings more bugs or not.

Edit: reverted.
