### ISSUE TITLE
biblatex has problems with nav files

### ISSUE THREAD

**Issue by moewew** [josephwright/beamer#442]
Apologies for 'abusing' the `beamer` bugtracker for what is essentially a `biblatex` problem. But I hope that you might have an idea what do to here.

The problem is described in https://github.com/plk/biblatex/issues/544. Here is a recap of the most important bits.
The MWE
```
\documentclass{beamer}
\usepackage[backend=biber]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\newrefsection
\nocite{sigfridsson}
\printbibliography
\end{document}
```
writes
```
<bcf:citekey order="1">\blx@keyaliases@1 </bcf:citekey>
```
to the `.bcf` where it should actually write the elements of the list `\blx@keyaliases@0`.

I think I have chased the problem down to the following core.

With https://github.com/plk/biblatex/blob/5169d2a64777090aa29d38df7543301f5c8b876b/tex/latex/biblatex/biblatex.sty#L418-L423 `biblatex` patches `\addtocontents` to set the `refesction` counter to the current value whenever it writes something. This is needed so that citations in toc/lof/... do not belong to the refsection in which the toc/lof/... is printed, but to the refsection in which the citations were written to the `.toc`/`.lof`/... files.

Normally this does not seem to be a problem since the standard files written to with `\addtocontents` are read in a group.
`beamer` writes to the `.nav` file with `\addtocontents`, but that file is not read in a group, so the wrong refsection counter value leaks out at the very beginning of the document. This causes the `refsection` counter to have the wrong value.

A simple solution from the `biblatex` side would be
```
\g@addto@macro\beamer@lastminutepatches{\c@refsection\z@}
```
but that feels ad hoc. Is there something better that `biblatex` should do?

**Comment by josephwright** [comment]
I guess you are asking if we should group reading the `.nav` file?

**Comment by moewew** [comment]
That would be ideal from `biblatex`'s point of view, I think. But if there is a good idea that makes the entire thing more robust on the `biblatex` side that be would great as well. `biblatex` is susceptible to these problems with all aux files that are written with `\addtocontents` and not read in a group.

**Comment by josephwright** [comment]
@moewew  Yes: I suspect that's a long-standing oversight rather than a deliberate move. @louisstuart96 do you see any problems with the proposed change?

**Comment by louisstuart96** [comment]
@josephwright I'm not familiar with `biblatex` and all the related things. It will spend long for me to look into this.

**Comment by josephwright** [comment]
@louisstuart96 It's not really a `biblatex` question :) The key point is that if `beamer` read the `.nav` file in a group then the issue would go away ...

**Comment by louisstuart96** [comment]
@josephwright I consider changing the behavior of reading `.nav` file in a patch exclusively for `biblatex`.

**Comment by moewew** [comment]
I had a quick look at what is written to the `.nav`. And it seems only `\headcommand`s go to that file. Since the definition of `\headcommand` uses `\global` and `\gdef`

https://github.com/josephwright/beamer/blob/a5b601498b51f2a17b327e230e928293349ebf7d/base/beamerbasemisc.sty#L25-L26

I'm lead to believe that it would be OK to read the `.nav` in a group. Indeed, the definitions of `\headcommand` and `\dohead` seem to suggest this was planned anyway.

From my point of view it would not be ideal to change the `.nav` behaviour exclusively for `biblatex`. If there are doubts about reading the `.nav` in a group I'd rather not do it at all than only for `biblatex`. Special behaviour for `biblatex` will make things much harder to debug.

**Comment by louisstuart96** [comment]
@moewew Does this fix problems with `biblatex`? If so, then I'll close this issue.

**Comment by moewew** [comment]
Yes it does. From my point of view the issue is resolved.
