### ISSUE TITLE
Missing release of 3.47

### ISSUE THREAD

**Issue by asr** [josephwright/beamer#445]
I Just updated my TeX Live installation and it reports I'm using Beamer 3.47:

```
$ pdflatex test.tex
...
*File List*
  beamer.cls    2017/12/16 v3.47 A class for typesetting presentations
```

However the latest version in the [releases](https://github.com/josephwright/beamer/releases) link is 3.46. Why wasn't 3.47 "released"?

**Comment by josephwright** [comment]
The GitHub 'releases' are just tags: I must have forgotten to push the CTAN to GitHub. Should be sorted now.

**Comment by asr** [comment]
Thanks!
