### ISSUE TITLE
text is not vertical centered in the info line

### ISSUE THREAD

**Issue by jszhao** [josephwright/beamer#446]
Hi there,

Merry Christmas and Happy New Year!

In the output of the following code, you will notice that the texts in the info line (bottom of the page) is not vertical centered as in the previous version (at least the date before Dec. 15). They are moved above to touch the top of line. Is it a bug?  

Thanks in advance.

```
\documentclass{beamer}
\usetheme{Madrid}

\title[title]{The Title}
\author[author]{The Author}
\institute[2017]{Address}
\date[ffgghh]{\today}

\begin{document}
\begin{frame}
   \maketitle
\end{frame}
\end{document}
```

**Comment by louisstuart96** [comment]
This bug seems to be fixed in https://github.com/josephwright/beamer/commit/f09629cdc88bcceb4e0446f16966489733bf6914 (or not? I need more tests.)

**Comment by josephwright** [comment]
I'm going to a release ASAP (I tried yesterday, but there was something up with the CTAN upload process, and I don't like to bother them today ...)

**Comment by josephwright** [comment]
Should now be released and so fixed: can you update and check?

**Comment by jszhao** [comment]
The commit fixed the bug. Thanks & Happy new year!
