### ISSUE TITLE
Wrong frame numbering when using "fragile" and "noframenumbering" together

### ISSUE THREAD

**Issue by ubruhin** [josephwright/beamer#450]
Hi, 

I hope this is the right place for this report ;)

It seems that when using `fragile` and `noframenumbering` together, the frame numbering is wrong. Instead of having the same number as the previous frame, the number is decremented by one. In addition, the total frame count is also decremented by one, so it's also wrong.

Here a minimal working example:
```
\documentclass{beamer}
\usetheme{Madrid}

\begin{document}

\begin{frame}{foo}
  frame number is correct: \insertframenumber
\end{frame}

\begin{frame}[fragile,noframenumbering]{bar}
  frame number is wrong: \insertframenumber
\end{frame}

\end{document}
```

It produces following output:
![auswahl_017](https://user-images.githubusercontent.com/5374821/34583251-50fad210-f197-11e7-952b-90477f7d20b8.png)

When removing either `fragile` or `noframenumbering`, the frame numbering is as expected, so only the combination of both leads to wrong numbering.

I'm using the official `texlive-*` packages from Ubuntu 16.04, which may not be the latest version but I don't know how to easily test it with the latest version. Maybe someone else could try to reproduce this with the latest version?

Btw, is it possible that there is no documentation about `noframenumbering`? ;)

**Comment by josephwright** [comment]
Looking at the code and the docs (or lack thereof), I think this is one of those compatibility things. We have a few of them (`containsverbatim` would be one): they are present where they come from the historical code but don't show up in stuff written (relatively) recently.

I think before taking any action I could do with a 'real' use case here, demonstrating why `noframenumbering` is needed (and so should also be documented).

**Comment by josephwright** [comment]
Ah, seems `noframenumbering` was added by Vedran: ff70090f36b631667b472cfe675fc3514fe46f7e. So it presumably should be documented, and thus work here ... I guess I'll look at it.

**Comment by josephwright** [comment]
It seems that https://github.com/josephwright/beamer/commit/0a7af8a222ac680946df60ee3afa6328cfa6e2ba is a better approach to the problem that `noframenumber` was meant to solve (issue #6). I suspect it would be better to remove `noframenumber` in favour of the new approach: @louisstuart96, @samcarter8, thoughts?

**Comment by ghost** [comment]
I totally agree that #6 is solved much better with `\insertmainframenumber`. However I also see good use cases for the `noframenumber` option, i.e. to get an unnumbered title page. This seems to be something many users do, some example from tex.se: 

- https://tex.stackexchange.com/q/398806/36296 
- https://tex.stackexchange.com/a/275720/36296
- https://tex.stackexchange.com/q/335371/36296
- https://tex.stackexchange.com/q/205044/36296 
- https://tex.stackexchange.com/q/143117/36296
- https://tex.stackexchange.com/q/281105/36296

.... (this are only some I found when searching though questions to which I added an answer, so probably a biased sample and far from complete)

**Comment by ghost** [comment]
Another problem with `noframenumbering` is the incompatibility with `allowframebreaks`. 

```
\documentclass{beamer}
\usetheme{Madrid}

\usepackage{lipsum}

\begin{document}

\begin{frame}[allowframebreaks,noframenumbering]
\lipsum
\end{frame}

\end{document}
```

**Comment by ghost** [comment]
@ubruhin In case you need a quick hack to workaround this problem:

```
\documentclass{beamer}
\usetheme{Madrid}

\begin{document}

\begin{frame}{foo}
  frame number is correct: \insertframenumber
\end{frame}

\stepcounter{framenumber}
\begin{frame}[fragile,noframenumbering]{bar}
  frame number is wrong: \insertframenumber
\end{frame}

\begin{frame}{foo}
  frame number is correct: \insertframenumber
\end{frame}

\end{document}
```

**Comment by ubruhin** [comment]
Thanks for your fast response and the workaround, it works for me! :+1:

**Comment by louisstuart96** [comment]
A fragile frame is processed twice, so that the `framenumber` counter is stepped twice. A correction is made when the `.vrb` file is read to typeset the slide. However, `noframenumbering` makes the `framenumber` counter not stepped at all.

**Comment by louisstuart96** [comment]
Commit 52e32b2 possibly fixes this problem. I need more tests, including `fragile=singleslide` option.
