### ISSUE TITLE
Release v3.48 missing on CTAN

### ISSUE THREAD

**Issue by SFr682k** [josephwright/beamer#451]
The development repo contains `v3.48` of `beamer` since December 24.  
However, the current version available on CTAN is `v3.47`.

Since `v3.47` contains some bugs resulting in badly typeset head and footlines (see Pt. III of the user's guide currently available on CTAN), the patches made in `v3.48` should be rolled out soon.

**Comment by josephwright** [comment]
The upload went some days ago: there were a few issues with the CTAN upload form, but I did think in the end it got sorted. I'll send the update again, to be on the safe side.

**Comment by josephwright** [comment]
It's definitely uploaded this time: I'll leave the question open until I see that CTAN install it.

**Comment by SFr682k** [comment]
The version has been installed and distributed over the CTAN mirrors.  
Closing the issue.
