### ISSUE TITLE
Templates for "section page" and "subsection page" are not in the user guide

### ISSUE THREAD

**Issue by goekce** [josephwright/beamer#454]
The Beamer-Templates _section page_ and _subsection page_ define how the title slides in front of sections/subsections are layouted. These two templates cannot be found in the documentation, but the template _part page_ is already documented.

**Comment by ghost** [comment]
They are briefly mentioned at the end of 10.2

![screen shot 2018-01-25 at 23 49 16](https://user-images.githubusercontent.com/8226363/35416724-796eb844-022a-11e8-8d83-8655ee2d77ac.png)

Maybe it would be good to add `Beamer-Template section page` below this paragraph?
