### ISSUE TITLE
Change initial definition of \insertmainframenumber

### ISSUE THREAD

**Issue by SFr682k** [josephwright/beamer#457]
Commit 0a7af8a222ac680946df60ee3afa6328cfa6e2ba introduced an `\insertmainframenumber` command.  
It is initialized with the value `1`. (code: `\def\insertmainframenumber{1}` in [`beamerbasemisc.sty`, line 44](https://github.com/josephwright/beamer/blob/b304bd8cb063be57362a91597c1cb2088f2a4d70/base/beamerbasemisc.sty#L44)).

However, since it is only set to the correct value when the `\appendix` command is used (via writing out the current frame number to the `.nav`-file, [`beamerbasesection.sty`, line 374](https://github.com/josephwright/beamer/blob/b304bd8cb063be57362a91597c1cb2088f2a4d70/base/beamerbasesection.sty#L374) ff.), a nasty glitch occurs:  
**When the `\appendix` command is *not* used, `\insertmainframenumber` keeps the value `1`, although more slides are present in the main part.**  

MWE (compile with the current repo version):

    \documentclass{beamer}
    \usetheme{CambridgeUS}
    \setbeamertemplate{page number in head/foot}[appendixframenumber]
    \begin{document}
        \frame{1}
        \frame{2}
        \frame{3}
        \frame{4}
    \end{document}

This behavior should be changed by initializing `\insertmainframenumber` in [`beamerbasemisc.sty`, line 44](https://github.com/josephwright/beamer/blob/b304bd8cb063be57362a91597c1cb2088f2a4d70/base/beamerbasemisc.sty#L44) as follows:  
`\def\insertmainframenumber{\inserttotalframenumber}`

**Comment by louisstuart96** [comment]
Good question; I'll fix it right now, but it still needs some optimization.
