### ISSUE TITLE
\appendix plus ignorenonframetext leads to infinit loop

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#464]
With MWE
```latex
\documentclass[ignorenonframetext]{beamer}

\begin{document}

    \begin{frame}
        Stuff!
    \end{frame}

    \appendix
    \begin{frame}
        Time for questions.
    \end{frame}

\end{document}
```
Introduced by https://github.com/josephwright/beamer/commit/9961645d5dcf84a3a01907d64c5045c31d232533

**Comment by u-fischer** [comment]
Something like this seems to work:

```
\documentclass[ignorenonframetext]{beamer}
\makeatletter
\newcommand\beamer@resetappendix{\global\let\appendix\beamer@appendix}
\renewcommand<>\appendix{%
  \only#1{\part{\appendixname}%
  \addtocontents{nav}{\protect\headcommand{\protect\beamer@appendixpages{\the\c@page}}}%
  }%
  \beamer@resetappendix
  }

\begin{document}

    \begin{frame}
        Stuff!
    \end{frame}

   \appendix
    \begin{frame}
        Time for questions.
    \end{frame}
  
\end{document}
```

**Comment by josephwright** [comment]
@u-fischer  Looks good to me: I'll wait to see if there are any comments from @louisstuart96

**Comment by louisstuart96** [comment]
The `\beamer@resetappendix` macro is not in the scope of `\only` parameter. Seems like it will always have effect no matter what the current mode is.

**Comment by louisstuart96** [comment]
I'll leave it open to find out what happended here.

**Comment by josephwright** [comment]
@louisstuart96 I agree it's a bit odd but at the same time I'm not sure it's worth pursuing too much: up to you!

**Comment by u-fischer** [comment]
I looked only very shortly at the code but imho the problem is that when ignorenonframetext is active beamer looks (in `\beamer@treat` (beamerbasemodes.sty)) for a number of command names that nevertheless shouldn't be ignored outside frames and handles them, and when it finds inside \appendix again the word "\appendix" it enters a loop.

**Comment by cfr42** [comment]
Is there a workaround which won't change the way the appendix is formatted? If I'm using the article class, for example, I expect it to switch to alphabetic numbering and I don't expect it to start a numbered \part or typeset \appendixname, because that's not what happens in articles usually.

**Comment by cfr42** [comment]
Incidentally, this used to work fine. In November, this code compiled, for example. So something has changed between then and now.

**Comment by josephwright** [comment]
I'm closing here: we have fixed the problem ...
