### ISSUE TITLE
Bullets reappearing in heading

### ISSUE THREAD

**Issue by Nauhaie** [josephwright/beamer#468]
Hi, I'm using

```
\useoutertheme[subsection=false,shadow]{miniframes}

\setbeamertemplate{headline}
{%
  \begin{beamercolorbox}[colsep=1.5pt]{upper separation line head}
  \end{beamercolorbox}
  \begin{beamercolorbox}{section in head/foot}
    \vskip2pt\insertnavigation{\paperwidth}\vskip1pt
  \end{beamercolorbox}%
  \ifbeamer@theme@subsection%
    \begin{beamercolorbox}[colsep=1.5pt]{middle separation line head}
    \end{beamercolorbox}
    \begin{beamercolorbox}[ht=2.5ex,dp=1.125ex,%
      leftskip=.3cm,rightskip=.3cm plus1fil]{subsection in head/foot}
      \usebeamerfont{subsection in head/foot}\insertsubsectionhead
    \end{beamercolorbox}%
  \fi%
  \begin{beamercolorbox}[colsep=0.5pt]{lower separation line head}
  \end{beamercolorbox}
}
```

in order to have the section titles in the heading but not the bullets under them. This used to work perfectly! But then I upgraded to MacTex 2017, and now the bullets reappeared in all my presentations! I guess something is wrong... Or is there a new way of disabling them? Thanks a lot...

**Comment by ghost** [comment]
Would 
```
\setbeamertemplate{mini frame}{}
\setbeamertemplate{mini frame in current subsection}{}
```
be a workaround? 

MWE:

```
\documentclass{beamer}
\useoutertheme[subsection=false,shadow]{miniframes}

\setbeamertemplate{mini frame}{}
\setbeamertemplate{mini frame in current subsection}{}

\begin{document}
\section{test}
\begin{frame}
\end{frame}

\begin{frame}
\end{frame}

\section{testt}
\begin{frame}
\end{frame}
\end{document}
```

**Comment by Nauhaie** [comment]
Thanks! That's a good step in the right direction. The bullets are gone, but the height of the headings remains the same as with the bullets... Is there a way of reducing it?

**Comment by ghost** [comment]
if this is your goal, I suggest to use `\insertsectionnavigationhorizontal` instead of `\insertnavigation`. See https://tex.stackexchange.com/a/404219/36296 for an example.

**Comment by Nauhaie** [comment]
Perfect, this indeed does the trick! Many thanks again!

**Comment by louisstuart96** [comment]
So this is the side effect of changing behaviors of `mini frames` templates (or not?)
