### ISSUE TITLE
Beamer's ToCs displaying/hidding subsections not at the same vertical position despite the `t` option

### ISSUE THREAD

**Issue by dbitouze** [josephwright/beamer#470]
As pointed out in [this question](https://tex.stackexchange.com/q/421945/18401), `beamer`'s ToCs displaying/hiding subsections are not at the same vertical position despite the `t` option. 

This can be avoided by replacing `\vfill` by `\vskip1.5em` in `\beamer@sectionintoc`. 

Moreover, adding before the TOCs a negative space of `1em` (magic length?), the top of them doesn't have any vertical offset compared to "normal" `[t]` frames:

```latex
\documentclass[t]{beamer}
\usepackage{etoolbox}%
%
\newcommand{\test}[1]{%
  \begin{frame}
    \frametitle{#1}
    Section 1
  \end{frame}
  \begin{frame}
    \frametitle{#1}
    \tableofcontents
  \end{frame}
  \begin{frame}
    \frametitle{#1}
    \tableofcontents[hideallsubsections]
  \end{frame}
}
%
\begin{document}
\section{Section 1}
\subsection{Subsection 1 of section 1}
\subsection{Subsection 2 of section 1}
\section{Section 2}
\subsection{Subsection 1 of section 2}
\subsection{Subsection 2 of section 2}
%
\test{Default behavior}
%
\makeatletter
\patchcmd{\beamer@sectionintoc}{\vfill}{\vskip1.5em}{}{}
\makeatother
%
\test{"verb" $\to$ "vskip1.5em"}
%
\pretocmd{\tableofcontents}{\vspace{-1em}}{}{}
%
\test{"verb" $\to$ "vskip1.5em" plus "-1em" vspace  before ToCs}
\end{document}
```

Shouldn't it be this last positioning be the default in case of `[t]` frames?

**Comment by louisstuart96** [comment]
I feel that all the configurations here might be by design, although not documented in the user guide. Some explanations are already given in the answer:
1. in normal mode, there is a `\vfill` before each section entry, and a `\vfill` at the end of TOC, making the entire TOC center-aligned despite the [t] option.
2. The "magical length" comes from `\vspace*{-.5em}` at the beginning of TOC, and `\vskip 1.5em` before the first section entry.

**Comment by dbitouze** [comment]
>I feel that all the configurations here might be by design

Too bad some unfortunate design choices cannot be reversed by a, say, `new-beamer` class, or as done by Joseph for `siunitx`, by a version 2 of `beamer`.

**Comment by josephwright** [comment]
It's tricky here altering existing designs. To be fair, I suspect we are likely OK here: the TOC is not likely to be on a page with other elements.

**Comment by dbitouze** [comment]
>To be fair, I suspect we are likely OK here

What about the following use case?

```latex
\documentclass[t]{beamer}
\AtBeginSection{%
  \begin{frame}
  \frametitle{Let us focus on the following \alert{section}}
    \tableofcontents[currentsection]
  \end{frame}
}
\AtBeginSubsection{%
  \begin{frame}
  \frametitle{Let us focus on the following \alert{subsection}}
    \tableofcontents[subsectionstyle=show/shaded/hide]
  \end{frame}
}
%
\setbeamertemplate{footline}[frame number]{}
\setbeamertemplate{navigation symbols}{}
%
\title{My Nice Talk}
\author{John Doe}
%
\begin{document}
\begin{frame}[plain]
  \maketitle
\end{frame}
%
\begin{frame}
  \frametitle{Outline of the talk}
  \tableofcontents[hideallsubsections]
\end{frame}
%
\section{Section 1}
%
\subsection{Subsection 1 of section 1}
\begin{frame}
  \frametitle{Foo11}
\end{frame}
%
\subsection{Subsection 2 of section 1}
\begin{frame}
  \frametitle{Foo12}
\end{frame}
%
\section{Section 2}
%
\subsection{Subsection 1 of section 2}
\begin{frame}
  \frametitle{Foo21}
\end{frame}
%
\subsection{Subsection 2 of section 2}
\begin{frame}
  \frametitle{Foo22}
\end{frame}
%
\end{document}
```
![test](https://user-images.githubusercontent.com/1032633/45734447-ebee4a00-bbe4-11e8-8db1-c9e959c52579.gif)
