### ISSUE TITLE
Short section titles are not saved in nav file

### ISSUE THREAD

**Issue by AlexisBRENON** [josephwright/beamer#472]
Hi everyone,

I used Beamer 3.44 and override the `\sectionentry` command to print the long title of different sections in section pages (relying on `\dohead` command).
However this does not work with Beamer 3.46 and above (I tested on 3.50 also). In fact the lines in the `.nav` file does not record the short section title.

Here is a MWE:

````
\documentclass{beamer}

\begin{document}

\section[1]{One}
\begin{frame}
\insertsection

\insertsectionhead
\end{frame}

\end{document}
````

Here is the corresponding `nav` file:

````
\headcommand {\beamer@sectionpages {1}{0}}
\headcommand {\beamer@subsectionpages {1}{0}}
\headcommand {\sectionentry {1}{1}{1}{1}{0}}
\headcommand {\slideentry {1}{0}{1}{1/1}{}{0}}
\headcommand {\beamer@framepages {1}{1}}
\headcommand {\beamer@partpages {1}{1}}
\headcommand {\beamer@subsectionpages {1}{1}}
\headcommand {\beamer@sectionpages {1}{1}}
\headcommand {\beamer@documentpages {1}}
\headcommand {\gdef \inserttotalframenumber {1}}
````
Expected line 3 should be: `\headcommand {\sectionentry {1}{1}{1}{One}{0}}`

Finally, the log file: https://gist.github.com/AlexisBRENON/8fd3befc5bfebad589b9cb1a1c2450f2

This impact the @gauthelo's thesis defense ;-)

Kind regards,
Alexis.

**Comment by josephwright** [comment]
Relates I guess to https://github.com/josephwright/beamer/issues/471 and discussion there (though it is separate).

**Comment by josephwright** [comment]
@louisstuart96 I guess you've seen this one?

**Comment by AlexisBRENON** [comment]
Hi, I run a `git bisect` to find the first commit introducing this regression. It is 8cbb0bf and not 7eb050b as linked in #471.
[Here](https://github.com/josephwright/beamer/commit/8cbb0bf47b6e4fc770c47f766e6cd169a2590c33#diff-f2cdad43f09509756c2b8c3df07c83fcR199) is the faulty change (reverting it, fix my bug, but maybe re-open others).
I would be glad to open a PR for this, but I don't know the differences between `\lastsection` and `\secname`, and the probable implications of interchanging both. Any clue (other issues, tests, use cases ?) of what to check before PR ?

Kind,
Alexis.

**Comment by louisstuart96** [comment]
From `beameruserguide.pdf` v3.50, Section 10.2, page 94:
>  By default the ⟨section name⟩ is shown in the table of contents and
in the navigation bars; if ⟨short section name⟩ is specified, it will be used in the navigation bars instead. 

In `beamer`'s redefinition of `\section`, the mandatory argument is passed to `\secname`, and the optional argument (if exists) is passed to `\lastsection`. 

As for `\sectionentry`, the optional argument of `\section` command is directly passed to the second argument in this macro, while the fourth argument used to be `\secname`, but it's rarely used in codes for typesetting navigations (in fact never used in any `beamer`'s navigation). Now that someone requires this 'feature', I will revert it.

@josephwright Here definitions of `\secname` and `\lastsection` is for expansions in `\hyperlink`, am I right?
