### ISSUE TITLE
Extra overlay between columns in case of \beamerdefaultoverlayspecification{<+->}

### ISSUE THREAD

**Issue by dbitouze** [josephwright/beamer#473]
This issue is probably related to [Extra \pause after block environments in case of \beamerdefaultoverlayspecification{<+->}](https://github.com/josephwright/beamer/issues/398).

The following MCE points out an extra between columns in case of `\beamerdefaultoverlayspecification{<+->}`: there is a sort of `\pause` command automatically inserted before each column of a `columns` environment. Is it by-design?

```latex
\documentclass{beamer}

\beamerdefaultoverlayspecification{<+->}

\begin{document}

\begin{frame}
  \begin{columns}
    \column{.45\linewidth}{Foo}
    \column{.45\linewidth}{Bar}
  \end{columns}
\end{frame}

\begin{frame}
  \begin{columns}
    \begin{column}{.45\linewidth}%
      Foo
    \end{column}
    \begin{column}{.45\linewidth}%
      Bar
    \end{column}
  \end{columns}
\end{frame}
```

**Comment by josephwright** [comment]
As I've said before, `\beamerdefaultoverlayspecification` applies _everywhere_ that takes an action argument ...

**Comment by dbitouze** [comment]
@josephwright  What does mean "that takes an action argument"?

**Comment by josephwright** [comment]
You can do `\begin{column}<+->` to pause columns, so the default spec applies.

**Comment by dbitouze** [comment]
OK, thanks.

**Comment by dbitouze** [comment]
AFAICS, the documentation doesn't specify `column` takes an action argument.
