### ISSUE TITLE
Overlay Alignment

### ISSUE THREAD

**Issue by SdotVdot** [josephwright/beamer#475]
Beamer is not aligning correctly the figures.

MWE
```
\documentclass{beamer}
\title{Foo}  
 
\begin{document}
\begin{frame}[t]\frametitle{Foo}
	\begin{figure}
		\includegraphics<1>{figure1.pdf}
		\includegraphics<2>{figure2.pdf}
		\includegraphics<3>{figure3.pdf}
		\includegraphics<4>{figure4.pdf}
		\includegraphics<5>{figure5.pdf}			
		\includegraphics<6>{figure6.pdf}
	\end{figure}	
\end{frame}
\end{document}
```

**Comment by josephwright** [comment]
Without the images themselves this is going to be hard to diagnose: can you add them?

**Comment by ghost** [comment]
cross-post: https://tex.stackexchange.com/questions/428579/is-there-any-problem-with-beamer-3-50

**Comment by samcarter8** [comment]
cross-post: https://tex.stackexchange.com/questions/428579/is-there-any-problem-with-beamer-3-50

**Comment by davidcarlisle** [comment]
don't you want `%` at the end of each of those lines?

**Comment by SdotVdot** [comment]
@davidcarlisle It works with `%`. Is it mandatory? It wasn't necessary before.

**Comment by samcarter** [comment]
Note to self: the behaviour changed between TL2017 and 18 with this commit https://github.com/josephwright/beamer/commit/581f1849869e70f0e116c752ddc2d2db8f8b1937

Test file:
```
\RequirePackage[2019/01/01]{latexrelease}
\documentclass{beamer}

\begin{document}
\begin{frame}
\includegraphics[width=2cm]{example-image}
\includegraphics[width=2cm]{example-image}
\end{frame}
\end{document}
```

previous output:
![document_old](https://user-images.githubusercontent.com/43832342/150320694-dee994f6-8eb6-482f-9b97-4678d87f117f.png)

current output:
![document_new](https://user-images.githubusercontent.com/43832342/150320726-67f5e9bb-58da-4f44-9f89-180fdb035095.png)
