### ISSUE TITLE
Add "RTL" option for right to left languages      

### ISSUE THREAD

**Issue by seloumi** [josephwright/beamer#479]
## This is  a feature request.

I am used to use beamer for my presentations,  and I find myself  comfortable in case of latin presentations (left to right) in contrast with arabic presentations (right to left).

For every theme  you need to redefine a  couple of templates (add some commands) which becomes troublesome with time  

My aim is adding an option "RTL" which simplify the procedures  and  change alignement of text in frame  components 

Example of desired feature

```latex
\documentclass[RTL]{beamer} 
\usefonttheme{serif}
\usetheme{Madrid}

\begin{document}

\begin{frame}{hello world}

\setRTL

hello world
\begin{enumerate}
\item 
first item
\item
second item
\end{enumerate}

\end{frame}

\end{document}
```
 
![capture](https://user-images.githubusercontent.com/8249073/41246641-f602c606-6dab-11e8-9f58-fab1abda2294.PNG)

**Comment by josephwright** [comment]
I'm sympathetic, but there is a lot of work needed to get RTL right, and the current `beamer` codebase is not really the ideal starting point.

**Comment by seloumi** [comment]
Can you show me guidlines to obtain style for right to left   presentations based on beamer ( perhaps creating new class "rl-beamer" with modification on beamer sty files )

**Comment by seloumi** [comment]
@josephwright  take a look to 
https://github.com/seloumi/rl-beamer
In your opinion creat new class from beamer  only for right to left presentations or  improving  changes (not yet complete)  and add "rtl" option to beamer ?

**Comment by josephwright** [comment]
@seloumi You are of course free to fork `beamer` (though for a public release you'll need to rename all files). I'm wary of providing a  'simple' option to the class because RTL is complicated and there are lots of assumptions in `beamer` and elsewhere about text running LTR. I'd also want to test against `bidi`, _etc._

Probably the best approach in my mind is for you to make a pull request against `beamer` in a separate branch, with a reasonably wide set of demos for different things. I can then take a proper look and we can then agree a merge plan with an idea of what is (and isn't) expected to work for users.

**Comment by josephwright** [comment]
(BTW, one fundamental problem is that RTL only really works properly in LuaTeX, at least from a conceptual POV, as the RTL support in pdfTeX/XeTeX only works in hmode and is at the engine level a hack. And yes I know lots of people use RTL with pdfTeX/XeTeX ...)

**Comment by josephwright** [comment]
@seloumi I notice your repo isn't based on the `beamer` one, it's a new one with the files checked in. That makes it very tricky for me to pick stuff up: really would be easier if you start from a fork.

**Comment by scottkosty** [comment]
@seloumi just wanted to make sure you saw the comment above. Thanks for your work on it!

**Comment by seloumi** [comment]
I need help to patch beamer commands and templates for right to left presentation, the patch work with "bidi" I have some issues with alignement inside beamercolorbox  can you help me to redefine the environment to obtain text aligned to the right 

``` latex
\newenvironment{beamercolorbox}[2][]{%
  \def\beamer@vmode{\leavevmode}%
  \setkeys{beamercolbox}{wd=\textwidth,ht={},dp={},%
    leftskip=0pt,rightskip=0pt plus1fil,%
    sep=0pt,colsep=0pt,colsep*=0pt,%
    shadow=false,rounded=false,ignorebg=false}%
  \setkeys{beamercolbox}{#1}%
  \ifbeamercolorempty[bg]{#2}{\@tempswafalse}{\@tempswatrue}%
  \ifbeamer@colbox@ignorebg\@tempswafalse\fi%
  \def\beamer@colbox@color{#2}%
  \setbox\beamer@tempbox=\hbox\bgroup\color@begingroup
    \ifbeamer@colbox@ignorebg%
      \colorlet{beamer@temp@color}{bg}%
      \usebeamercolor[fg]{#2}%
      \colorlet{bg}{beamer@temp@color}%
    \else%
      \usebeamercolor[fg]{#2}%
    \fi%
    \vbox\bgroup%
    \hsize=\beamer@colbox@wd%
    \@arrayparboxrestore%
    \leftskip=\beamer@colbox@ls%
    \ifdim\beamer@colbox@sep>\z@\advance\leftskip\beamer@colbox@sep\fi%
    \rightskip=\beamer@colbox@rs%
    \ifdim\beamer@colbox@sep>\z@\advance\rightskip\beamer@colbox@sep\fi%
    \if@tempswa\ifdim\beamer@colbox@colsep>\z@%
      \advance\leftskip by\beamer@colbox@colsep%
      \advance\rightskip by\beamer@colbox@colsep%
      \vskip\beamer@colbox@colsep%
    \fi%
      \ifdim\beamer@colbox@colseps>\z@\vskip\beamer@colbox@colseps\fi%
    \fi%
    \ifdim\beamer@colbox@sep>\z@\vskip\beamer@colbox@sep\fi%
    \beamer@vmode\ignorespaces}{%
    \ifdim\beamer@colbox@sep>\z@\vskip\beamer@colbox@sep\fi%
    \if@tempswa
      \ifdim\beamer@colbox@colsep>\z@\vskip\beamer@colbox@colsep\fi%
      \ifdim\beamer@colbox@colseps>\z@\vskip\beamer@colbox@colseps\fi%
    \fi%
  \egroup\color@endgroup\egroup%
  \ifx\beamer@colbox@ht\@empty\else\ht\beamer@tempbox=\beamer@colbox@ht\fi%
  \ifx\beamer@colbox@dp\@empty\else\dp\beamer@tempbox=\beamer@colbox@dp\fi%
  \ifbeamer@colbox@rounded%
    \if@tempswa%
      \begin{beamerboxesrounded}[%
        shadow=\beamer@colbox@shadow,%
        lower=\beamer@colbox@color,%
        upper=normal text,%
        width=\beamer@colbox@wd]{}%
        \box\beamer@tempbox%
      \end{beamerboxesrounded}%
    \else%
      \ifdim\wd\beamer@tempbox>\textwidth%
        \setbox\beamer@tempbox=\hbox to\textwidth{\hss\box\beamer@tempbox\hss}%
      \fi%
      \box\beamer@tempbox%
    \fi%
  \else%
    \if@tempswa\setbox\beamer@tempbox=\hbox{%
      \usebeamercolor{\beamer@colbox@color}%
      \hskip-\beamer@colbox@colseps%
      \fboxsep=\z@\colorbox{bg}{%
        \hskip\beamer@colbox@colseps%
        \box\beamer@tempbox%
        \hskip\beamer@colbox@colseps%
      }%
      \hskip-\beamer@colbox@colseps%
      }\fi%
    \ifdim\wd\beamer@tempbox>\textwidth%
      \setbox\beamer@tempbox=\hbox to\textwidth{\hskip0pt minus\beamer@leftmargin\relax\box\beamer@tempbox\hskip0pt minus\beamer@leftmargin\relax}%
    \fi%
    \box\beamer@tempbox%
  \fi%
}

```

**Comment by samcarter** [comment]
Related: `bidi` now has extensive support for RTL in beamer, see this talk from the TUG22 conference 

https://www.youtube.com/watch?v=C_1G7IltJYs
