### ISSUE TITLE
ignorenonframetext with \mode<all> can't \include

### ISSUE THREAD

**Issue by wspr** [josephwright/beamer#480]
I'm using up-to-date TL2018. Trying to create compiled lecture notes from a bunch of presentations, would like to work towards having "article" handouts so students receive proper notes, not just copies of the slides. This is related to #130 but appears to be a separate bug.

Consider:

    \begin{filecontents}{topic-0.tex}
    \mode*
    \section{one}
    \begin{frame}{hello}
      slide 1
    \end{frame}
    article content
    \end{filecontents}
    
    \begin{filecontents}{topic-1.tex}
    \mode*
    \section{two}
    \begin{frame}{hello hello}
      slide 2
    \end{frame}
    article content
    \end{filecontents}
    
    \documentclass[ignorenonframetext]{beamer}
    \begin{document}
    \mode<all>\include{topic-0}
    \mode<all>\include{topic-1}
    \end{document}

(Note the manual says not to put `\include` inside the argument to `\mode` and hence use the syntax I've used above.)

This works for one include only and then throws the following error:

    ./beamertopics.tex:21: LaTeX Error: \include cannot be nested.

However, running this example with beamerarticle worked:

    \documentclass{article}
    \usepackage{beamerarticle}
    \begin{document}
    \mode<all>\include{topic-0}
    \mode<all>\include{topic-1}
    \end{document}

So it looks like I hit upon the correct solution at the end here, except that I'm hitting the ‘nesting `\include`’ error.

The caveat to all this is that `\input` works where `\include` does not, so that's what I'm doing for now. The main reason for using `\include` being that I can later use `\includeonly`. If this approach is not supported, perhaps beamer should indicate this.

**Comment by louisstuart96** [comment]
I've pushed ba9f803 to add these commands into exclusion list. Hope that this can fix the problem. I don't have plenty of time to test it.

**Comment by louisstuart96** [comment]
@wspr This MWE can work if you put `\mode<all>` at the end of each seperated file. (Of course this breaks the function of `\mode*`.)

The problem is that `\mode*` gobbles a lot of tokens inside `\include`:
```latex
% definitions of \@include, used by \include:
\def\@include#1 {%
  \clearpage
  \if@filesw
    \immediate\write\@mainaux{\string\@input{#1.aux}}%
  \fi
  \@tempswatrue
  \if@partsw
    \@tempswafalse
    \edef\reserved@b{#1}%
    \@for\reserved@a:=\@partlist\do
      {\ifx\reserved@a\reserved@b\@tempswatrue\fi}%
  \fi
  \if@tempswa
    \let\@auxout\@partaux
    \if@filesw
      \immediate\openout\@partaux #1.aux
      \immediate\write\@partaux{\relax}%
    \fi
    \@input@{#1.tex}%
    % From here, ALL tokens will be gobbled by `\mode*`
    % To confirm this, check `topic-0.aux`
    \clearpage
    \@writeckpt{#1}%
    \if@filesw
      \immediate\closeout\@partaux
    \fi
  \else
    \deadcycles\z@
    \@nameuse{cp@#1}%
  \fi
  % This line causes the error
  \let\@auxout\@mainaux}
```

The `\input` command is redefined by LaTeX2e kernel to deal with safe input, thus some tokens may also be swallowed although files may be succesfully included.

@josephwright Perhaps the best way is to design a fully expandable `\beamerinput` macro to deal with all tokens that could be influenced by `beamer`'s mechanism.

**Comment by louisstuart96** [comment]
Actually, Prof. Tantau showed an example on Page 212 in `beameruserguide.pdf`:
```latex
\begin{filecontents}{a.tex}
\mode*
\section{First section}
Extra text in article version.
\begin{frame}
Some text.
\end{frame}
\mode<all>
\end{filecontents}
% b.tex likewise

\documentclass[ignorenonframetext]{beamer}
\begin{document}
This is star mode stuff.
Let’s include files:
\mode<all>
\include{a}
\include{b}
\mode*
Back to star mode
\end{document}
```

Throughout the entire document one must control the mode manually using `\mode*` and `\mode<all>`, especilly using `\mode<all>` at the end of each included file.
