### ISSUE TITLE
`noxcolor` option of `beamerarticle` causes error

### ISSUE THREAD

**Issue by ghost** [josephwright/beamer#483]
Based on the question https://tex.stackexchange.com/q/440176/36296

The following MWE

```
\documentclass{article}
\usepackage[noxcolor]{beamerarticle}
\begin{document}
test
\end{document}
```

causes the error 
```
! Undefined control sequence.
<argument>  \colorlet 
                      {fg}{black} \colorlet {bg}{white} 
l.117 }
```

since the commit https://github.com/josephwright/beamer/commit/719445d574c1779698a1f1360fe1e31661126643#diff-adb611a8e4bdf2c7a8b624e9c8b7ed4f

-----

Should

```
\mode
<all>
{
  \colorlet{fg}{black}
  \colorlet{bg}{white}
}
```

in `beamerbasecolor.sty` be changed into 

```
\mode
<presentation>
{
  \colorlet{fg}{black}
  \colorlet{bg}{white}
}
```

to fix this? And some conditional that beamerarticle defined these colour if `noxcolor` is not used:

```
\ifbeamer@articlexcolor
  \RequirePackage[override]{xcolor}
  \colorlet{fg}{black}
  \colorlet{bg}{white}
\fi
```

**Comment by louisstuart96** [comment]
@samcarter8 I remember someone reported an issue of failing to use some beamer templates in `article` mode because the lack of these definitions. I did not noticed the `noxcolor` option in `beamerarticle.sty` then.

**Comment by ghost** [comment]
@louisstuart96 Please have a look at my PR #486 -- In its current form it does not work because `\colorlet{fg}{black}
  \colorlet{bg}{white}` are executed in every mode, which include article, which will fail for the `noxcolor` option. I propose to execute them only in `presentation` mode and let `beamerarticle` do them if `xcolor` is loaded.

This should cover most possibilities except if `xcolor` is loaded separately

```
\documentclass{article}
\usepackage[noxcolor]{beamerarticle}

\usepackage{xcolor}

\begin{document}
test
\end{document}
```

This will still work, `bg` and `fg` are just not available.

**Comment by ghost** [comment]
@louisstuart96 Thanks for merging!

**Comment by louisstuart96** [comment]
@samcarter8 I don't remember why was it necessary to define `fg` and `bg` colors in the article mode. Could you help me find the historical issue related to this?

**Comment by ghost** [comment]
`fg` and `bg` where added to the article mode in https://github.com/josephwright/beamer/commit/719445d574c1779698a1f1360fe1e31661126643 (you'll have to ask the author of this commit to find out why :)

I don't think they are necessary for the xcolor using article mode, but I don't think they hurt either. That's why I only remove them from the noxcolor article mode (where they hurt) and left them in normal article mode.

If you think they cause any problems, I would not be opposed to removing them. One advantage I see though is that users can be a bit more sloppy when they use these colours in custom macros and don't have to distinguish between different modes (for example the metropolis has some peculiarities which make it necessary to explicitly use the background colour some images, if `bg` and `fg` is available in article mode, one can simply use the same code for images).

**Comment by louisstuart96** [comment]
@samcarter8 Under normal circumstances all colors in `beamer`'s templates should be used by `\usebeamercolor` command rather than directly by `\color` command; the former itself is redefined in article mode. I remember one issue involves direct use of `\color`, which is why I commit this change.

**Comment by ghost** [comment]
@louisstuart96 I agree for beamer templates, but there are other things users can have on slides, for example `tikzpicture`s and other things where using beamer colours is not always practical.
