### ISSUE TITLE
note page: the mini slide in the upper right corner is not the same as the last slide.

### ISSUE THREAD

**Issue by jszhao** [josephwright/beamer#485]
Here is a mini example. you will see the info lines above and below of the last slide is lost in the mini slide in the upper right corner of the note page. Is it a feature of \note or a bug?

```
\documentclass[notes]{beamer}
\usetheme[secheader]{Madrid}

\title[short title]{long title}
\author[author]{someone}
\institute[institue]{somewhere}

\begin{document}

\section{section One}
\subsection{abc}

\begin{frame}
\frametitle{a test}
This is a test.
\end{frame}

\note{this is a note test}

\end{document}
```

**Comment by louisstuart96** [comment]
All right, this seems to be a `feature': 
1. The mini slide only contains the content of the slide itself (including frame title). The `headline` and `footline` are placed inside the header and footer (the place controlled by usual LaTeX command `\pagestyle`). Actually, the following templates are note part of a content box: 
  - background and background canvas
  - sidebar (left and right) and canvas
  - headline
  - footline
  - navigation bars (usually inside the right sidebar)
2. The mini slide is typeset in the following way: first draw a white rectangle of .25\paperwidth * .25\paperheight, then put the scaled content box at the right position.

Currently the only thing we can do is to note this in the documentation @josephwright.
