### ISSUE TITLE
Reserve all `beamerug*.pdf`s in the `doc` directory

### ISSUE THREAD

**Issue by louisstuart96** [josephwright/beamer#490]
These PDFs are distributed in the package before the old building script is replaced by `build.lua`. Since not all the themes are demonstrated in the documentation, it is better to include them so that people may know the effects of these themes in a convenient way.

**Comment by josephwright** [comment]
Probably we should fix the docs so all of the themes do show up.

**Comment by louisstuart96** [comment]
My bad, now all themes do show up in the documentation.
