### ISSUE TITLE
Inline verbatim overflows out of margins (and sometimes out of page)

### ISSUE THREAD

**Issue by mlazaric** [josephwright/beamer#491]
While reading http://ctan.ijs.si/tex-archive/macros/latex/contrib/beamer/doc/beameruserguide.pdf, I have noticed overflows in a couple places. Although the ones that only overflow into the margins are not too noticeable, the couple places that overflow out of page are, but since I am not sure how to fix it, I thought the next best thing would be to report it here. :smile: 

#### Page 26

![image](https://user-images.githubusercontent.com/3049847/44860853-8529e080-ac77-11e8-985a-fce4b9b6f624.png)

#### Page 65

![image](https://user-images.githubusercontent.com/3049847/44860934-b3a7bb80-ac77-11e8-9676-022206ad6697.png)

#### Page 109

![image](https://user-images.githubusercontent.com/3049847/44861061-084b3680-ac78-11e8-996c-d6745449fcfc.png)

**Comment by ghost** [comment]
I just had a look at all the remaining `Overfull \hbox` warnings and for all of them the full text is still  completely visible within the margin.
