### ISSUE TITLE
After Miktex Update: beamercolorbox doesn't ignore background color anymore

### ISSUE THREAD

**Issue by thewaywewalk** [josephwright/beamer#493]
Hello,

after a recent Miktex-Update an always working feature now refuses to work.
I was used to include a background image (here substituted by a colored background canvas) and use beamercolorboxes in my custom templates. In the past I could set the background color of the beamercolorbox to `bg=` or use the argument `ignorebg` and the background color was ignored. That does not work anymore.

In my example I have a red background, with the overlaying beamercolorbox it becomes white, but it should remain red. I'm pretty sure this worked until recently.

Thank you very much!

```
\documentclass{beamer}
\usepackage{tikz}

\setbeamercolor{background canvas}{bg=red,fg=white}%
\setbeamercolor{title background canvas}{bg=,fg=white}%

\defbeamertemplate{title page}{start}{%
    \begin{beamercolorbox}[wd=\paperwidth,ht=\paperheight,ignorebg]{title background canvas}
	Inside beamercolorbox    
    \end{beamercolorbox}%  
}

\begin{document}

\setbeamertemplate{title page}[start]

\begin{frame}
\titlepage
\end{frame}

\setbeamertemplate{background canvas}[default]
\setbeamertemplate{title page}[default]

\begin{frame}
test main
\end{frame}

\end{document}
```

**Comment by josephwright** [comment]
@louisstuart96 This one fixed by https://github.com/josephwright/beamer/commit/594db5d8f027c781c4ecc2b38907e04d2b16f043? If so, I'll get a release out.

**Comment by louisstuart96** [comment]
@josephwright Indeed. Perhaps a miner version like 3.52b?

**Comment by josephwright** [comment]
OK, uploaded: closing.
