### ISSUE TITLE
document: \usebeamertemplate is listed under "Inserts" in the Index

### ISSUE THREAD

**Issue by e-kwsm** [josephwright/beamer#500]
#455 (48ca4d2)

https://github.com/josephwright/beamer/blob/1382cfd12fc07f50cb53a692be0c2ed96bead68a/doc/beamerug-frames.tex#L468

causes `\usebeamertemplate*{page number in head/foot}` listed under "Inserts" in the Index of `beameruserguide.pdf` (page 240):

![beamerug-index-240](https://user-images.githubusercontent.com/11627708/45678982-94af9180-bb72-11e8-8ec9-5ab3ffd27e5a.png)

Is this intended?

Also, the permission of the file was changed from 644 to 755.

**Comment by ghost** [comment]
Should all be fixed now. Thanks for reporting!

**Comment by e-kwsm** [comment]
Confirmed. Thank you.
