### ISSUE TITLE
Vertical aligment of lists in combination with allowframebreaks 

### ISSUE THREAD

**Issue by ghost** [josephwright/beamer#506]
The recent commit https://github.com/josephwright/beamer/commit/fd369b715b9c8738da88d1589785fe48ecff1031 fixed the problem of vertical alignment for normal text in `allowframebreaks` slides (Thanks a lot @louisstuart96 !!!)

For lists the alignment is still inconsistent. This often causes problems for bibliographies which are a typical use case for `allowframebreaks`

MWE:

```
\documentclass{beamer}

\begin{document}

\begin{frame}[t,allowframebreaks]
\frametitle{Frame Title}

\begin{itemize}
\item Test
\item Test
\item Test
\item Test
\item Test
\item Test
\item Test
\item Test
\item Test
\item Test
\item Test
\item Test
\item Test
\item Test
\item Test
\item Test
\item Test
\end{itemize}

\end{frame}

\end{document}
```

![document](https://user-images.githubusercontent.com/8226363/45821036-871c1800-bce8-11e8-973e-f58839805c8e.gif)

Some related post from TeX.SE:

- https://tex.stackexchange.com/questions/357717/beamer-allowframebreaks-option-and-vertical-spacing-when-using-lists-itemize
- https://tex.stackexchange.com/questions/277473/align-beamer-slides-with-frame-breaks (only the first part)
- https://tex.stackexchange.com/questions/275872/first-slide-of-references-in-beamer-starts-one-line-further-down

**Comment by louisstuart96** [comment]
This comes from extra glues by list items: `\topsep` (plus `\partopsep` mostly) before the first item, and `\itemsep` before the others. Therefore, the glue on top of 'part of a list' may differ from a whole list.

MWE:
```latex
\documentclass{beamer}
\begin{document}
\begin{frame}[t]
\frametitle{Test title}
\begin{itemize}[<only@+>]
  \item First item (has `topsep' and `partopsep' glue above)
  \item Second (has `itemsep' above)
  \item Third 
\end{itemize}
\end{frame}
\end{document}
```

**Comment by louisstuart96** [comment]
A patch for `enumitem` package (#342) may allow users to alter the glues. This is the next work (and challenge!)
The default settings are better not altered, since a list has not more than 10 items most of the time (usually 3-6 items) so there is no need to break a list.

**Comment by louisstuart96** [comment]
Some glues like `\itemsep` may be lost during the process of page breaking. Thus we cannot insist on aligning these cross-page lists perfectly.
