### ISSUE TITLE
\showoutput does nothing in a beamer document...

### ISSUE THREAD

**Issue by jfbu** [josephwright/beamer#507]
Surely it does not qualify as bug but signaling nevertheless `\showoutput` is effect less in a beamer document.

```latex
\documentclass{beamer}
\showboxdepth\maxdimen
\showboxbreadth\maxdimen
\usetheme{Warsaw}
\usefonttheme{professionalfonts}
\usepackage{libertinus}
\newbox\mybox
\begin{document}
\begin{frame}{Frame name}
\begin{itemize}
\item This is text.
\item Rightarrow (\setbox\mybox\hbox to 0pt{$\Rightarrow$})
\end{itemize}
\end{frame}
\showoutput % ne fait rien!
\end{document}
```

Sometimes it is nice to use it to examine the shipped out page.

**Comment by louisstuart96** [comment]
`\showoutput` should be placed before the content of a document, for example, before the first frame.

**Comment by jfbu** [comment]
@louisstuart96 Indeed! Sorry for noise here, I should have posted on a user-group list rather... now closing.
