### ISSUE TITLE
Add libertinus package to list of professional font packages

### ISSUE THREAD

**Issue by kfeuerherm** [josephwright/beamer#508]
As per [this stackexchange discussion,](https://tex.stackexchange.com/questions/452001/math-arrows-dont-display-with-beamer-xelatexmk-libertinus?noredirect=1#comment1136428_452001) math symbols (in this instance, arrows) are not treated properly by beamer when libertinus is loaded.

Adding \usefonttheme{professionalfonts} cures the problem but is likely not obvious for many people. Perhaps it is worth adding libertinus to the packages which case this option to be invoked automatically?

[Note that the same problem does not occur with the older libertine package, and in fact only with certain compilation combinations, as outlined in the link.]

**Comment by louisstuart96** [comment]
Seems all the unicode fonts are affected, so the substitution mechanism is turned off if `unicode-math` is loaded.
