### ISSUE TITLE
beamerarticle and frame options

### ISSUE THREAD

**Issue by jspitz** [josephwright/beamer#509]
If a frame uses all possible options (`<overlay>[<standard overlay>][frame options]`), the frame options will be printed verbatim to the PDF in beamerarticle.

If you omit the standard overlay option, it works. It seems the option parser only checks for one option delimited with bracket.

Testcase:

```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{beamerarticle}
\begin{document}
	
\begin{frame}<-3>[<+->][label=foo]{Title}
\begin{itemize}
\item one
\item two
\item three
\item four
\end{itemize}
\end{frame}
	
\end{document}
```

**Comment by louisstuart96** [comment]
Please check the latest commit c7e608f to see if the bug is fixed.

**Comment by jspitz** [comment]
Yes, I tested several combinations, and the issue seems gone. Thanks for the quick fix!
