### ISSUE TITLE
Problem using \newcolumntype with beamer's [table] option

### ISSUE THREAD

**Issue by rhstanton** [josephwright/beamer#521]
If I create and use a new column type in a tabular environment, it used to work with beamer fine, but starting a few days ago I get an error message if I load beamer with the table option. Here's a simple LaTeX file that shows the problem (note that it works fine without the table option:

\documentclass[table]{beamer}

\usepackage{array}
\newcolumntype{L}[1]{>{\raggedright\let\newline\\\arraybackslash\hspace{0pt}}m{#1}}

\begin{document}

\begin{frame}{Test Frame}
\begin{tabular}{L{1cm} L{1cm}}
  A & B \\
  D & E 
\end{tabular}          
\end{frame}

When processed with pdfLaTeX, I get lots of errors, beginning with:

./beamerbug.tex:15: Use of \@startpbox doesn't match its definition.
<inserted text> \@startpbox {
                             L{1cm} L{1cm}}
l.15 \end{frame}
                
./beamerbug.tex:15: Extra }, or forgotten \endgroup.
\@mkpream ...after \@startpbox \expandafter {#1}}}
                                                  \let \@endpbox \relax \let...l.15 \end{frame}
                
./beamerbug.tex:15: Use of \@startpbox doesn't match its definition.
<argument> ...box \ar@mcellbox \vbox \@startpbox {
                                                  \@nextchar }\insert@column...l.15 \end{frame}
                
./beamerbug.tex:15: Extra }, or forgotten \endgroup.
<argument> ...\@endpbox \do@row@strut \fi \egroup 
                                                  \egroup \begingroup \CT@se...l.15 \end{frame}
                
./beamerbug.tex:15: Extra }, or forgotten \endgroup.
<argument> ...x \do@row@strut \fi \egroup \egroup 
                                                  \begingroup \CT@setup \CT@...l.15 \end{frame}
                
./beamerbug.tex:15: Incompatible list can't be unboxed.
<argument> ... \@tempdima \@width \z@ \unhbox \z@ 
                                                  
l.15 \end{frame}
                
./beamerbug.tex:15: Extra }, or forgotten \endgroup.
\@addtopreamble ...xdef \@preamble {\@preamble #1}
                                                  
l.15 \end{frame}

**Comment by davidcarlisle** [comment]
Sorry about that, you need an updated colortbl, which is already on ctan or will be in texlive/miktex probably tomorrow, depending on your mirror.

**Comment by rhstanton** [comment]
Thanks, David.
