### ISSUE TITLE
Shadow problems when transparent package is included

### ISSUE THREAD

**Issue by peremen** [josephwright/beamer#527]
Beamer version: 3.51

When a transparent package [1] is included, the shadow of title and blocks are becoming solid black. I discovered this when I wanted to put an SVG graphic with svg package [2] then the shadow turns black, but it turned out that the svg package was not a problem, the package included by default with that (transparent) was a problem.

[1] https://ctan.org/pkg/transparent
[2] https://github.com/mrpiggi/svg

Minimal working example:
```
\documentclass[aspectratio=169]{beamer}
\usepackage{transparent}
\usetheme{Madrid}
\usecolortheme{beaver}
\begin{document}
\begin{frame}
  \titlepage
\end{frame}
\end{document}
```
Normal rendering should be:
![test_correct](https://user-images.githubusercontent.com/735016/52961073-6bea2d00-339a-11e9-86bf-0f12b5e5bcc8.png)

When a transparent package is included, the rendering becomes:
![test_error](https://user-images.githubusercontent.com/735016/52961074-6c82c380-339a-11e9-9b12-5905100e2221.png)

**Comment by samcarter** [comment]
I'm having trouble reproducing this problem. Can you please add which engine you are using to compie your document? pdflatex or something else? It would also be helpful to see the`.log` file of your example document

**Comment by peremen** [comment]
I have upgraded the system since then and couldn't reproduce it anymore, but not sure what had fixed the problem. Thanks anyway.
