### ISSUE TITLE
Can't change textbox size for slide title when using PaloAlto theme

### ISSUE THREAD

**Issue by MCM-Math** [josephwright/beamer#528]
I can change the font size of the slide title, but I would like to know how to shrink the actual text box for the slide title, as it takes up too much space.  If possible, please give me a link to where there is a complete listing for all dimensions and settings for a beamer page, because I keep finding only limited collections, and it really limits the actual applicability of this format in practice.

**Comment by samcarter** [comment]
Quick way to change the height of the frame title:

```
\documentclass{beamer}

\PassOptionsToPackage{height=1cm}{beamerouterthemesidebar}
\usetheme{Paloalto}

\begin{document}
	
\begin{frame}
	\frametitle{title}
\end{frame}	
	
\end{document}
```

(the complete list of options applicable to the sidebar outer theme can be found in the beamer user guide, p. 169)

**Comment by MCM-Math** [comment]
I used the

```
\makeatletter
\setlength{\beamer@headheight}{.5cm}
\makeatother
```

solution, since it worked within my R Markdown preamble.

> (the complete list of options applicable to the sidebar outer theme can be found in the beamer user guide, p. 169)

Is this the most recent one: http://mirrors.rit.edu/CTAN/macros/latex/contrib/beamer/doc/beameruserguide.pdf ?

**Comment by samcarter** [comment]
@MCM-Math Yes,  v. 3.55 is the current version. The item list at the top of the page gives the available options of the sidebar outer theme, including the `height` key relevant for this question

**Comment by samcarter** [comment]
@MCM-Math Yes,  v. 3.55 is the current version. The item list at the top of the page gives the available options of the sidebar outer theme, including the `height` key relevant for this question
