### ISSUE TITLE
Singepore theme: Indicating dots in the header (to be removed)

### ISSUE THREAD

**Issue by ErwinHo** [josephwright/beamer#534]
The theme 'Singapore' displays the section in the header followed by empty and filled dots (in the next) line indicating the frame. The last behaviour could be disabled in previous versions of beamer (prior 3.55) using the command

`\beamertemplatenavigationsymbolsempty`

which is not supported anymore. The alternative solution

`\setbeamertemplate{navigation symbols}{}`

doest not work either. Any possibility to retain the previous capability?

Regards.
--eh.

**Comment by samcarter** [comment]
`navigation symbols` are the symbols at the bottom right of the frame, what you want to disable are the `miniframes`. Easiest way is redefining the headline:

```
\documentclass{beamer}

\usetheme{Singapore}

\makeatletter
\setbeamertemplate{headline}{%
  \begin{beamercolorbox}[colsep=1.5pt]{upper separation line head}
  \end{beamercolorbox}
  \begin{beamercolorbox}{section in head/foot}
    \vskip2pt\insertsectionnavigation{\paperwidth}\vskip2pt
  \end{beamercolorbox}%
  \ifbeamer@theme@subsection%
    \begin{beamercolorbox}[colsep=1.5pt]{middle separation line head}
    \end{beamercolorbox}
    \begin{beamercolorbox}[ht=2.5ex,dp=1.125ex,%
      leftskip=.3cm,rightskip=.3cm plus1fil]{subsection in head/foot}
      \usebeamerfont{subsection in head/foot}\insertsubsectionhead
    \end{beamercolorbox}%
  \fi%
  \begin{beamercolorbox}[colsep=1.5pt]{lower separation line head}
  \end{beamercolorbox}
}
\addtoheadtemplate{\pgfuseshading{beamer@headfade}\vskip-1.25cm}{}
\makeatother

\begin{document}
	
\section{title}
\begin{frame}
	your notes
\end{frame}	
	
\end{document}
```

![Screen Shot 2019-04-04 at 12 49 35](https://user-images.githubusercontent.com/43832342/55550293-2b3f3c80-56d8-11e9-86dc-ad15c6d41223.png)

**Comment by ErwinHo** [comment]
Yupp. Navigation symbols are bottom right. Removal still works; I'm actually referring to navigation symbols in the header. 

Regarding the header  .... your workaround solves my issue; but is destroying the whole layout of the Singapore theme.  

Given the documentation of beamer 3.55, the Singapore theme refers to "15.5 Presentation Themes with a Mini Frame Navigation", providing some options like 

`[compress]`

Though it is not mentioned explicitly for Singapore in the docs; it has no effect - of course. Sorry.

**Comment by ErwinHo** [comment]
I changed to TeX-Live 2015 and everything is working as expected. Very annoying. I have certainly about 1000 beamer presentations which are hand-crafted in layout.

**Comment by samcarter** [comment]
@ErwinHo  You don't need to use the `compress` option with the `Singapore` theme, it uses it automatically. Otherwise you would get multiple lines of `miniframes` for the different subsections.

**Comment by Overcraft90** [comment]
Is this solution still valid? Unfortunately, I was attempting to do so in `Tex Live 2025` and it appears to not be working correctly... Specifically, I wish to both remove navigating dots and sections from the `\titlepage`.

**Comment by samcarter** [comment]
@Overcraft90  If you have a different question, you should ask a separate question (preferably on one of the Q&A sites for latex questions)
