### ISSUE TITLE
Bug with \includeonlyframes, itemize and the <.-> overlay specification

### ISSUE THREAD

**Issue by devillemereuil** [josephwright/beamer#538]
This MWE with two frames, and only one (labelled "current") is specified to be compiled by Beamer (see second line), compiles with error:

```LaTeX
\documentclass{beamer}
\includeonlyframes{current}

\usepackage[utf8]{inputenc}
\usetheme{default}

\begin{document}

  \begin{frame}
    \onslide<+->{Text 1}
    \onslide<+->{Text 2}
    
    \begin{itemize}[<.->]
      \item Item 1
      \item Item 2
      \item Item 3
    \end{itemize}
    
  \end{frame}
  
  \begin{frame}[label = current]
    Test
  \end{frame}

\end{document}
```

The thrown errors are:
```
! Missing = inserted for \ifnum.
<to be read again> 
                   -
! Missing number, treated as zero.
<to be read again> 
                   >
```

This is linked to this particular example using the `<.->` overlay specification. Replacing this overlay with `<+->` or `<.>` works (but changes the PDF when all slides are included of course, so not a good workaround). Using `\item<.->` instead of `[<.->]` still produces the bug.

The only workaround I found that produces the same PDF is encapsulating the whole itemize environment within onslide, which seems to work:

```LaTeX
    \onslide<.->{
      \begin{itemize}
        \item Item 1
        \item Item 2
        \item Item 3
      \end{itemize}
    }
```

This on a fairly recent (TexLive 2018 on openSUSE Tumbleweed), but not totally up-to-date version of Beamer:
```LaTeX
\ProvidesClass{beamer}
  [2018/02/20 v3.50 A class for typesetting presentations]
```

I hope the bug is not already outdated, if it is, sorry for the noise. I'm unaware of any way to test more recent versions of Beamer without meddling with my own TexLive install.

**Comment by samcarter** [comment]
> I hope the bug is not already outdated, if it is, sorry for the noise. I'm unaware of any way to test more recent versions of Beamer without meddling with my own TexLive install.

I can reproduce this behaviour with the current beamer version of 2018/12/02 v3.55

**Comment by devillemereuil** [comment]
Thanks for testing!

I just found out another structure that triggers a similar bug (though the error message is a bit simpler, so probably related, but maybe not the same bug):

```LaTeX
    \only<.-.(1)>{
      \begin{itemize}
        \item Item 1
        \item Item 2
        \item Item 3
      \end{itemize}
    }
```
yields the following error:
```
! Missing = inserted for \ifnum.
<to be read again> 
                   -
```

But:
```LaTeX
    \only<-.(1)>{
      \begin{itemize}
        \item Item 1
        \item Item 2
        \item Item 3
      \end{itemize}
    }
```
and
```LaTeX
    \onslide<.-.(1)>{
      \begin{itemize}
        \item Item 1
        \item Item 2
        \item Item 3
      \end{itemize}
    }
```
Both work fine.

Weird, uh?

**Comment by louisstuart96** [comment]
Seems the parser for overlay specification has something wrong in your case. When parsing tokens like `+` and `.`, it replaces these tokens with actual numbers. In a regular frame it works well, but in a hidden frame it may generate wrong results like this:
```
  \begin{frame}
    \only<-1->{Test single frame}
      Single frame
  \end{frame}
```

So far I have reduced the MWE to the following and it may take times to check where the bug is.
```
\documentclass{beamer}
\begin{document}
\begin{frame}<0>
  \only<.->{Test}
\end{frame}
\end{document}

**Comment by louisstuart96** [comment]
The parser itself needs to be updated to hold the extreme condition like this:
```
\begin{document}
\begin{frame}
  \only<+->{Test 1}
  \only<.(-7)->{Test 2}
\end{frame}
\end{document}
```

**Comment by devillemereuil** [comment]
I can confirm that patching with https://github.com/josephwright/beamer/commit/840b7ba07481e24263b6cd60dd828570b165e138 fixes the examples I've shown above, but doesn't fix cases where a negative reference like `.(-3)` is performed. This is also true in my "real life" scripts, as far as I can see (only occurences of the bug seem to contain such negative references).

**Comment by louisstuart96** [comment]
@devillemereuil try 8a5a7d4.

**Comment by devillemereuil** [comment]
I can confirm that it works on my "real life" scripts and some minimal examples, yes. Thanks!
