### ISSUE TITLE
beameruserguide.pdf compilation/table of contents

### ISSUE THREAD

**Issue by jyrc** [josephwright/beamer#540]
After compilation using ../build.lua, the table of contents lists incorrect page numbers. However, beameruserguide.toc appears to have the right numbers. I would be happy to explore this, but I need some guidance from someone more experienced about where to look.

**Comment by josephwright** [comment]
Probably I need another cycle ...

**Comment by josephwright** [comment]
Try with the latest commit

**Comment by jyrc** [comment]
Worked perfectly. Thanks!
