### ISSUE TITLE
Extra }, or forgotten \endgroup with mode specification and exampleblock or alertblock

### ISSUE THREAD

**Issue by ysalmon** [josephwright/beamer#543]
The following code gives an error

   ```
 \documentclass{beamer}
    \begin{document}
    \begin{frame}
    \mode
    <presentation>
    some text
    
    \mode
    <article>
    
    \begin{exampleblock}{Exemple}
    tttttt
    \end{exampleblock}
    
    \mode
    <all>
    
    
    \end{frame}

    \end{document}
```
It seems to be related to the ``exampleblock`` : if I replace it with a ``block``, there is no error. But due to the ``\mode`` specification, beamer is supposed to be in gobbling state when reading that line. Plus, if I remove the ``\mode`` specifications, there is also no error.

I suspect this is a bug in beamer. I just upgraded via tlmgr to the latest version : it still happens. I also tried the master version by cloning the repo in my local texmf, to no avail.

(one might wonder why I use blocks in article mode ; this is because I am not going to be able to show a whole series of examples in the presentation but I still want to have them all in the beamerarticle version, and I want consistency of appearance there)

**Comment by louisstuart96** [comment]
The problem is caused by the `\mode` command in the definition of `alertblock` and `exampleblock` environments. Using `\mode` command inside a frame will not make `beamer` process the subsequent contents line-by-line; instead it will put everything inside a box and leave the box alone. Therefore the `\mode` command in the environment (thus in the box) may have confilct with the others.

@josephwright Are these `\mode` commands really necessary in these two blocks?

**Comment by josephwright** [comment]
@louisstuart96 Code predates me (Till in 672b0bc6). I'd say the idea is to avoid repetition in the definitions, but this issue probably got missed. The easiest fix is likely just to duplicate the definitions inside a conditional `\mode` block.

**Comment by ysalmon** [comment]
I stumbled on another problem related to modes and one user at TeX.SX pointed out that it may be a new incarnation of the same bug :
```latex
\documentclass{beamer}
\newenvironment{machin}{begdef}{enddef}
\begin{document}
  \begin{frame}
    \begin{exampleblock}{Exemples}
      \mode
      <article>
        \begin{machin}
        whatever
      \mode
      <all>
      blabla
      \mode
      <article>
        whatever
        \end{machin}
      \mode
      <all>
    \end{exampleblock}
  \end{frame}
\end{document}
```
Compiling this leads to ``Extra }, or forgotten \endgroup. \end{frame}`` at line 20.

Compiling this with the ``machin`` environments commented out is fine.

Compiling this, including the ``machin`` environments, with class ``scrartcl`` and package ``beamerarticle`` also works.

I noticed this also happens when the frame has the ``fragile`` option (my original code had ``listings`` snippets, that's how I found out). Do you think it would be possible to tackle that bug at least for ``fragile`` frames, by tweaking the procedures that generate or re-read the ``vrb`` file ?

**Comment by samcarter** [comment]
@ysalmon Maybe you can workaround this problem with something like

```
%\documentclass{beamer}

\documentclass{article}
\usepackage{beamerarticle}

\newenvironment{machin}{}{}
\mode<article>{\renewenvironment{machin}{begdef}{enddef}}

\begin{document}
  \begin{frame}
    \begin{exampleblock}{Exemples}
        \begin{machin}
        \only<article>{whatever}
      blabla
        \only<article>{whatever}
        \end{machin}
    \end{exampleblock}
  \end{frame}
\end{document}
```

**Comment by ysalmon** [comment]
Thanks a lot : this works ! I was under the impression that this sort of environment begin/end trickery would be easier to manage with the \mode flavor that processes things at a more "crude" level, and did not even try this.

**Comment by msgc** [comment]
For whatever it may be worth. I debugged unsuccessfully. Then noticed that in my work machine I did not have this problem. Simply removed TeXworks and reinstall it. Took me about 15 minutes and it works without those errors.
