### ISSUE TITLE
usepdftitle is not overlay-aware

### ISSUE THREAD

**Issue by ysalmon** [josephwright/beamer#544]
I am producing a document with beamer and beamerarticle, and because of differing layout constraints on both outputs, I need to say
```latex
\title{Instructions de base\\<article> en programmation impérative}
```
The title appears nicely in the documents themselves, but the PDF-title in the presentation version has the word ``<article>``.
It is also not possible to override the automatic setting of pdftitle with an ``\hypersetup`` command.

Of course I can say
```latex
\mode<article>
\title{Instructions de base\\en programmation impérative}
\mode
<presentation>
\title{Instructions de base en programmation impérative}
\mode
<all>
```
but it is clumsier.

**Comment by samcarter** [comment]
Personally I would avoid putting formatting instructions like `\\` inside the title argument. Instead you could adjust the format of the `\maketitle` to match your needs. For example

```
\documentclass{article}
\usepackage{beamerarticle}

\title{Instructions de base en programmation impérative}

\makeatletter
\def\@maketitle{%
  \newpage
  \null
  \vskip 2em%
  \begin{center}%
  \let \footnote \thanks
    {\LARGE \parbox{7cm}{\centering\@title} \par}%
    \vskip 1.5em%
    {\large
      \lineskip .5em%
      \begin{tabular}[t]{c}%
        \@author
      \end{tabular}\par}%
    \vskip 1em%
    {\large \@date}%
  \end{center}%
  \par
  \vskip 1.5em}
\makeatother


\begin{document}
	
\maketitle
	
\end{document}
```

**Comment by ysalmon** [comment]
I am not sure, since sometimes one wants to let the title break at a point which is both visually and semantically pleasing. For example breaking before "en" is preferable to after for grammatical reasons.

**Comment by josephwright** [comment]
I think  given the visual nature of `beamer` material it's hard to avoid manual line breaks, but at the same time it's  not really possible to know if they are 'required' in a title in article mode or not. The 'repeat the title' approach is likely the only reasonable one: programmatically we can't tell that one is to be preferred.

**Comment by louisstuart96** [comment]
`\\` itself is redefined by `beamer` to be overlay-aware. To disable it in the context of a PDF label, one must use `\renewcommand<>` to redefine it, so that it expands to the same thing whether the overlay specification exists or not. `beamer` has simply patched it to be `\ ` (control space), but it can be overwritten via the following code:
```
\makeatletter
\g@addto@macro\beamer@firstminutepatches{%
  \pdfstringdefDisableCommands{%
    \renewcommand<>\\{\ }%
  }%
}
\makeatother
```

Though it is better to avoid using commands with optional arguments in PDF string.
