### ISSUE TITLE
Problem beamer with xcolor

### ISSUE THREAD

**Issue by redakorik** [josephwright/beamer#545]
Problem with beamer class,
 ! Package xcolor Error: Undefined color `n'.

\documentclass[10pt]{beamer}

\usetheme{PaloAlto)
% theme général du diaporama% paquets pour le français
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\begin{document}
\begin{frame}Cette diapositive est beaucoup moins sexyqu’un ours en peluche.
\end{frame}
\end{document}

This is pdfTeX, Version 3.14159265-2.6-1.40.20 (MiKTeX 2.9.7140 64-bit)
entering extended mode
(beam.tex
LaTeX2e <2018-12-01>
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/latex/beamer\beamer.cls"
Document Class: beamer 2019/07/23 v3.56 A class for typesetting presentations

("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/latex/beamer\beamerbasemo
des.sty"
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/latex/etoolbox\etoolbox.s
ty")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/latex/beamer\beamerbasede
code.sty"))
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/oberdiek\ifpdf.st
y")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/latex/beamer\beamerbaseop
tions.sty"
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/latex/graphics\keyval.sty
"))
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/latex/geometry\geometry.s
ty"
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/oberdiek\ifvtex.s
ty")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/ifxetex\ifxetex.s
ty")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/latex/geometry\geometry.c
fg"))
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/latex/base\size10.clo")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/latex/pgf/basiclayer\pgfc
ore.sty"
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/latex/graphics\graphicx.s
ty"
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/latex/graphics\graphics.s
ty"
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/latex/graphics\trig.sty")

("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/latex/graphics-cfg\graphi
cs.cfg")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/latex/graphics-def\dvips.
def")))
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/latex/pgf/systemlayer\pgf
sys.sty"
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/latex/pgf/utilities\pgfrc
s.sty"
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/utilities\pgf
util-common.tex"
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/utilities\pgf
util-common-lists.tex"))
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/utilities\pgf
util-latex.def"
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/latex/ms\everyshi.sty"))
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/utilities\pgf
rcs.code.tex"
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf\pgf.revision.
tex")))
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/systemlayer\p
gfsys.code.tex"
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/utilities\pgf
keys.code.tex"
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/utilities\pgf
keysfiltered.code.tex"))
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/systemlayer\p
gf.cfg")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/systemlayer\p
gfsys-dvips.def"
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/systemlayer\p
gfsys-common-postscript.def")))
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/systemlayer\p
gfsyssoftpath.code.tex")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/systemlayer\p
gfsysprotocol.code.tex")) (xcolor.sty
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/latex/graphics-cfg\color.
cfg"))
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/basiclayer\pg
fcore.code.tex"
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/math\pgfmath.
code.tex"
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/math\pgfmathc
alc.code.tex"
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/math\pgfmathu
til.code.tex")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/math\pgfmathp
arser.code.tex")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/math\pgfmathf
unctions.code.tex"
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/math\pgfmathf
unctions.basic.code.tex")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/math\pgfmathf
unctions.trigonometric.code.tex")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/math\pgfmathf
unctions.random.code.tex")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/math\pgfmathf
unctions.comparison.code.tex")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/math\pgfmathf
unctions.base.code.tex")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/math\pgfmathf
unctions.round.code.tex")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/math\pgfmathf
unctions.misc.code.tex")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/math\pgfmathf
unctions.integerarithmetics.code.tex")))
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/math\pgfmathf
loat.code.tex"))
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/math\pgfint.c
ode.tex")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/basiclayer\pg
fcorepoints.code.tex")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/basiclayer\pg
fcorepathconstruct.code.tex")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/basiclayer\pg
fcorepathusage.code.tex")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/basiclayer\pg
fcorescopes.code.tex")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/basiclayer\pg
fcoregraphicstate.code.tex")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/basiclayer\pg
fcoretransformations.code.tex")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/basiclayer\pg
fcorequick.code.tex")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/basiclayer\pg
fcoreobjects.code.tex")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/basiclayer\pg
fcorepathprocessing.code.tex")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/basiclayer\pg
fcorearrows.code.tex")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/basiclayer\pg
fcoreshade.code.tex")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/basiclayer\pg
fcoreimage.code.tex"
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/basiclayer\pg
fcoreexternal.code.tex"))
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/basiclayer\pg
fcorelayers.code.tex")
("C:\Users\reda\AppData\Local\Programs\MiKTeX 2.9\tex/generic/pgf/basiclayer\pg
fcoretransparency.code.tex"

! Package xcolor Error: Undefined color `n'.

See the xcolor package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.113 \pgfutil@colorlet{pgftransparent}{black}
                                              
? 

Process has been terminated ...

**Comment by samcarter** [comment]
There is a typo, it should be `\usetheme{PaloAlto}` i.e. with a curly parenthesis

**Comment by redakorik** [comment]
Yes I corrected this error but even I always have the same thing:
! Package xcolor Error: Undefined color `n '.

**Comment by louisstuart96** [comment]
Seems you need to update the related packages like `pgf` and `xcolor` to the latest versions.

**Comment by samcarter** [comment]
@redakorik Can you add `\listfiles` to your document and show the resulting list of package versions from your log file?

**Comment by samcarter** [comment]
I'm voting to close this issue. Without feedback from the OP if updating the tex distribution helped or at least a list of package versions, the error is hard to reproduce
