### ISSUE TITLE
Is this the official repo of beamer?

### ISSUE THREAD

**Issue by bookug** [josephwright/beamer#556]
By the way, if I want to add a theme XXX to beamer, how can I do it?
Then, others can write   \usetheme{XXX} to use my theme.

**Comment by josephwright** [comment]
If you want to add a theme, you just need files with the correct names: this should be pretty clear from the core ones.

**Comment by josephwright** [comment]
In terms of the repo: yes, this one is the master site for `beamer`.

**Comment by louisstuart96** [comment]
All you need is to write your own theme in a LaTeX package file entitled `beamerthemeXXX.sty`. The code `\usetheme{XXX}` just behaves like `\usepackage{beamerthemeXXX}`.
Many third-party themes have been published on CTAN, like `beamertheme-cuerna` and `beamertheme-metropolis`. You can refer to these packages if you wish to create your own.
