### ISSUE TITLE
\alert used in a "paragraph" column of a tabular ruins layout

### ISSUE THREAD

**Issue by dbitouze** [josephwright/beamer#557]
As pointed out by the following MCE, `\alert` used in a "paragraph" column of a tabular ruins layout.

```latex
\documentclass[t]{beamer}
\begin{document}
\begin{frame}
  \begin{tabular}{rl}
    aaaaa & bbbbb\\
    aaaaa & \alert{bbbbb}
  \end{tabular}
\end{frame}

\begin{frame}
  \begin{tabular}{rp{5cm}}
    aaaaa & bbbbb\\
    aaaaa & \alert{bbbbb}
  \end{tabular}
\end{frame}
\end{document}
```
![test](https://user-images.githubusercontent.com/1032633/69360226-766b8700-0c8a-11ea-81ac-16925601c0a3.gif)

**Comment by samcarter** [comment]
I think this boils down to

```
\documentclass{article}

\usepackage{xcolor}

\begin{document}

  \begin{tabular}{rp{7cm}}
    aaaaa & bbbbb\\
    aaaaa & \color{red} bbbbb
  \end{tabular}

\end{document}
```

![Screen Shot 2019-11-21 at 18 21 33](https://user-images.githubusercontent.com/43832342/69361008-dd3d7000-0c8b-11ea-9b3a-b984f2f341bd.png)

**Comment by samcarter** [comment]
Workaround from https://tex.stackexchange.com/a/328044:

```
\documentclass[t]{beamer}

\begin{document}
\begin{frame}
  \begin{tabular}{rl}
    aaaaa & bbbbb\\
    aaaaa & \alert{bbbbb}
  \end{tabular}
\end{frame}

\begin{frame}
  \begin{tabular}{rp{7cm}}
    aaaaa & bbbbb\\
    aaaaa & \leavevmode\alert{bbbbb}
  \end{tabular}
\end{frame}
\end{document}
```

Some further explanation can be found at https://tex.stackexchange.com/a/347323/36296

**Comment by dbitouze** [comment]
What about incorporating `\leavevmode` into `\alert` (and `\structure`, etc.)?

**Comment by samcarter** [comment]
I vaguely remember having once seen a question where `\textcolor` caused some spacing problems. I'll try to find this question again as it might be a good test case to see if `\leavemode` breaks anything

**Comment by davidcarlisle** [comment]
@samcarter  it would break something (that's why `\color` doesn't add `\leavevmode` by default.

The problem isn't just with `\alert` or `\color`  `\label`  would do the same putting a node at the top of  vbox moves the reference point of the box to above the first line which is almost never desired.

but forcing these nodes always into hmode will generate spurious white paragraphs in all cases where they are not immediately followed by text.
