### ISSUE TITLE
spruce color theme: alert not in red

### ISSUE THREAD

**Issue by dbitouze** [josephwright/beamer#562]
With the `spruce` color theme `alert`:
- is not in red,
- behaves as `structure`:
```latex
\documentclass{beamer}
\usecolortheme{spruce}
\begin{document}
\begin{frame}
  \begin{description}
  \item[structure:] \structure{structure}
  \item[alert:] \structure{alert}
  \end{description}
\end{frame}
\end{document}
```
![test](https://user-images.githubusercontent.com/1032633/69854799-458ee180-128a-11ea-9e7b-ba4a9139274d.png)

I know `beamer`'s doc doesn't say `alert` is systematically red:

>The given text is highlighted, _typically_ by coloring the text red.

but is it the intentional behavior?

BTW, [I couldn't find the `spruce` definition](https://github.com/josephwright/beamer/search?q=spruce&unscoped_q=spruce).

**Comment by samcarter** [comment]
I think this is indented behaviour. The [spruce colour theme ](https://github.com/josephwright/beamer/blob/master/base/themes/color/beamercolorthemespruce.sty) explicitly sets `\setbeamercolor{alerted text}{fg=MSUgreen!80!white}`. The colours are based on the colors of Michigan State University, I think this explains the "untypical" choice for the alert colour.

@dbitouze I assume you mean `\item[alert:] \alert{alert}` in your example? Then I get green and *not* the same colour as structure

```
\documentclass{beamer}
\usecolortheme{spruce}
\begin{document}
\begin{frame}
  \begin{description}
  \item[structure:] \structure{structure}
  \item[alert:] \alert{alert}
  \end{description}
\end{frame}
\end{document}
```

![Screen Shot 2019-11-29 at 10 38 55](https://user-images.githubusercontent.com/43832342/69859477-85f35d00-1294-11ea-860b-9f8f72b37e0e.png)

**Comment by dbitouze** [comment]
@samcarter Ooops, sorry for the noise about `alert` = `structure`: I'll change this issue's title.

And I missed the `beamercolorthemespruce.sty` because I originally search for the string `spruce` in files' contents (and not in the files' names) in my local repository of `beamer` (BTW, with [`ripgrep`](https://github.com/BurntSushi/ripgrep) (`rg`), much faster and nicer than `grep`) and the `.sty` file which defines this color theme even doesn't contain its name :)

For the record, about the  "untypical" choice for the alert color, `red` is the most frequent one (see `beamercolorthemedefault.sty` below), but not the only one:
```
rg "\\\setbeamercolor\{alerted text"
doc/beamerug-color.tex
276:  \example |\setbeamercolor{alerted text}{fg=red!80!black}|

base/themes/color/beamercolorthemebeaver.sty
15:\setbeamercolor{alerted text}{fg=darkred!80!gray}

base/themes/color/beamercolorthemespruce.sty
17:\setbeamercolor{alerted text}{fg=MSUgreen!80!white}

base/themes/color/beamercolorthemedefault.sty
17:\setbeamercolor{alerted text}{fg=red}

base/themes/color/beamercolorthemebeetle.sty
15:\setbeamercolor{alerted text}{fg=red!85!black}

base/themes/color/beamercolorthemewolverine.sty
14:\setbeamercolor{alerted text}{fg=darkblue!80!yellow}

base/themes/color/beamercolorthemefly.sty
15:\setbeamercolor{alerted text}{fg=red!85!black}
```

Thanks!
