### ISSUE TITLE
\pause{} instead of \pause in the documentation?

### ISSUE THREAD

**Issue by dbitouze** [josephwright/beamer#566]
The `\pause` command, used without its optional argument, gobbles the space after it, as shown by the following MCE. Shouldn't the `beamer`'s documentation suggest to add e.g. an empty curly brace after this command if used without its optional argument?

For instance, instead of (page 80):

> However, for many simple cases the `\pause` command is sufficient.

it could be written:

> However, for many simple cases the `\pause{}` command is sufficient.

```latex
\documentclass{beamer}
\begin{document}
\begin{frame}
  Foo\pause[2] Bar
\end{frame}
\begin{frame}
  Foo\pause Bar
\end{frame}
\end{document}
```

**Comment by samcarter** [comment]
I'm not sure this is a good idea. 

- this is a basic property of all latex macros, so most users should be aware of this

- users might misleadingly think the `{}` is required and part of the macro and thus use it everywhere, which can lead to problems, e.g.

```
foo
\pause{} 
test
```

- if one were to do this for `\pause`, one would also have to change this for the hunderts of other macros like `\insertpresentationstartpage`

**Comment by dbitouze** [comment]
Indeed. Sorry for the noise.
