### ISSUE TITLE
How can I use beamer

### ISSUE THREAD

**Issue by sleeeeeeper** [josephwright/beamer#570]
I'm using windows and telive, and how can i use beamer in my Tex file (! LaTeX Error: File `beamer.sty' not found.)? Like clone this to my latex folder or something?

**Comment by samcarter** [comment]
The safest way to install beamer is to let your tex distribution, e.g. texlive, install it for you. This way the many dependencies of beamer will also be installed.

In texlive you can install additional package with the tlmgr, see https://www.tug.org/texlive/doc/texlive-en/texlive-en.html#x1-430005 for more details.

Another approach would be to install a full version of texlive, this includes all package (including beamer)

**Comment by davidcarlisle** [comment]
Beamer is a class not a package your error message shows that you are
trying to load it as a package

**Comment by josephwright** [comment]
Also, note that `beamer` is a class:
```latex
\documentclass{beamer}
```
not
```latex
\usepackage{beamer}
```
