### ISSUE TITLE
stop to use filehook ...

### ISSUE THREAD

**Issue by u-fischer** [josephwright/beamer#572]
It still breaks if scrlfile is loaded and an update is not in view (https://bitbucket.org/martin_scharrer/filehook/issues/1/latex-will-change-definition-of). 

So for example this fails:

~~~~
\documentclass{beamer}
\usepackage{chemmacros}
\begin{document}
Test
\end{document}
~~~~

**Comment by samcarter** [comment]
Note to myself: the filehook package is not directly loaded by beamer, but by the `sansmathaccent` package

The following code works because it sets `\beamer@sansmathfalse` and thus does not load the `samsmathaccent` package 

```
\documentclass[serif]{beamer}
\usepackage{chemmacros}

\begin{document}
Test
\end{document}
```

**Comment by samcarter** [comment]
The relevant code from the `sansmathaccent` package is

```
	% Ensure proper placement of accents with bm
	% but don't waste a mathgroup unless we will in fact use
	% bm and pureletters
	\IfFileExists{filehook.sty}{
		\RequirePackage{filehook}
		\AtBeginOfFile{bm.sty}{		
			\beamer@font@check \ifbeamer@suppressreplacements\else
			\DeclareSymbolFont{pureletters}{OT1}{mathkerncmss}{m}{sl}
			\SetSymbolFont{pureletters}{bold}{OT1}{mathkerncmss}{bx}{sl}
			\fi
		}
	}{
		\DeclareSymbolFont{pureletters}{OT1}{mathkerncmss}{m}{sl}
		\SetSymbolFont{pureletters}{bold}{OT1}{mathkerncmss}{bx}{sl}
		\PackageWarning{sansmathaccent}{Could not find 'filehooks' package: one mathgroup may be wasted}
	}
```

It seems the package would still be functional without using filehook, "just" one mathgroup might be wasted.

**Comment by josephwright** [comment]
The issue that math group, of course: if we drop the test, we are bound to get serious complaints.

**Comment by louisstuart96** [comment]
The step of loading `sansmathaccent` package shall be suppressed if professional fonts are used.

**Comment by samcarter** [comment]
@louisstuart96 `sansmathaccent` takes `\beamer@suppressreplacements` into account

**Comment by u-fischer** [comment]
Well it doesn't look as something will happen. So I suggest to contact the sansmathaccent author and to ask that the code uses scrlfile instead of filehook:


~~~~
	\IfFileExists{scrlfile.sty}{
		\RequirePackage{scrlfile}
		\BeforeFile{bm.sty}{		
			\beamer@font@check \ifbeamer@suppressreplacements\else
			\DeclareSymbolFont{pureletters}{OT1}{mathkerncmss}{m}{sl}
			\SetSymbolFont{pureletters}{bold}{OT1}{mathkerncmss}{bx}{sl}
			\fi
		}
	}{
		\DeclareSymbolFont{pureletters}{OT1}{mathkerncmss}{m}{sl}
		\SetSymbolFont{pureletters}{bold}{OT1}{mathkerncmss}{bx}{sl}
		\PackageWarning{sansmathaccent}{Could not find 'filehooks' package: one mathgroup may be wasted}
	}
~~~~

**Comment by samcarter** [comment]
The sansmathaccent author was so nice to sent an updated version of the package to ctan. 

With sansmathaccent version `2020/01/31` the problem is avoided.
