### ISSUE TITLE
Line above footline

### ISSUE THREAD

**Issue by Dana-L** [josephwright/beamer#575]
The command for inserting a line above the footline (and thus also above the text in the footline), e.g.,

```
\addtobeamertemplate{footline}{\rule{\paperwidth}{3pt}}{}
```

now places the line lower, in the place reserved for the text, and the text does not appear at all anymore. This command worked properly until several months ago, as shown, e.g., in the MWE, by Medina at the bottom of 
https://tex.stackexchange.com/questions/160988/how-to-add-insert-a-rule-in-the-headline-and-footline .

**Comment by samcarter** [comment]
There is a `\par` missing after the rule:

```
\documentclass[compress]{beamer}
\usetheme{Montpellier}
\useoutertheme{infolines}

\author{The Author}
\title{The Title}
\institute{The Institute}

\addtobeamertemplate{footline}{\rule{\paperwidth}{3pt}\par}{}

\begin{document}

\begin{frame}
test
\end{frame}

\end{document}
```

![Screen Shot 2020-01-31 at 11 24 19](https://user-images.githubusercontent.com/43832342/73532115-496ee980-441c-11ea-86a5-ff78e3e292ea.png)

**Comment by samcarter** [comment]
Another approch could be to start with the `Szeged` theme, which has lines by default, and modify this theme to meet your requirements:

```
\documentclass{beamer}
\usetheme{Szeged}

\author{The Author}
\title{The Title}
\institute{The Institute}

\begin{document}
\begin{frame}
Test
\end{frame}
\end{document}
```
