### ISSUE TITLE
Consider adding compiled (pdf) user guide to releases

### ISSUE THREAD

**Issue by equaeghe** [josephwright/beamer#577]
The releases currently do not contain a compiled pdf for the user guide. I assume that it is supposed to be created upon installation. However, not all downstream projects (e.g., Gentoo Linux) will do this (see, e.g., https://bugs.gentoo.org/697788). The consequence is that the user guide will not be (readily) available for the users of that project. Therefore, please consider adding a compiled pdf user guide to the releases.

**Comment by josephwright** [comment]
The standard release does have the PDF documentation: I suspect that the issue is packaging by third-parties.

**Comment by equaeghe** [comment]
> The standard release does have the PDF documentation: I suspect that the issue is packaging by third-parties.

The releases here, such as the latest at https://github.com/josephwright/beamer/releases/tag/v3.57 do not contain a compiled pdf, unless I missed it. The bundles on CTAN do, but those are unversioned. So the ones here are used.

**Comment by josephwright** [comment]
GitHub automatically creates a zip of the source repo whenever a tag is pushed: that's what these files  are. It's possible to do automated deployment to GitHub, but that's only really worth it in LaTeX terms where it saves a lot of time: true for https://github.com/latex3/latex2e and https://github.com/latex3/latex3 but not really for much else. Even then, those zips are used to download then send to CTAN: the version on CTAN *is* the definitive release.

I'm not sure what you mean about versioning: CTAN's database tells one the current release and matches the files they've installed.

**Comment by equaeghe** [comment]
> GitHub automatically creates a zip of the source repo whenever a tag is pushed: that's what these files are. It's possible to do automated deployment to GitHub, […].

That is reasonable.

> Even then, those zips are used to download then send to CTAN: the version on CTAN _is_ the definitive release.

Yes, but it is not stable: http://mirrors.ctan.org/macros/latex/contrib/beamer.zip may point to one release today and another one tomorrow. These may have changed dependencies and the like. Distributions like Gentoo need to be able to have a versioned release, to make sure that dependencies are and functionality is as expected.

> I'm not sure what you mean about versioning: CTAN's database tells one the current release and matches the files they've installed.

AFAICT, there is no way to download releases from CTAN that are not the latest uploaded there. That is problematic for distributions like Gentoo, whose packages are wrappers around tarballs, essentially (see https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-tex/latex-beamer/latex-beamer-3.56-r1.ebuild, for example).

**Comment by josephwright** [comment]
I'm concerned that this is a more general question which finds itself in the `beamer` issues list. For almost all LaTeX packages, the version on CTAN is the definitive release. In particular, both MiKTeX and TeX Live pick up from there, so I'd be very concerned about the (essentially) developer versions of `beamer` here being the source for end-user installations. When I point people to 'ready to install' zips for LaTeX3, for example, I do so on CTAN not on GitHub.

CTAN's approach with zip naming is quite deliberate, as it means that there is exactly one 'official' release at a time. It also means that one always knows what file name to look for and thus to over-write when downloading. I'm not familiar with how TeX Live or MiKTeX check for changes, though `rsync` is what immediately comes to mind. (CTAN is an archive in the 'they have one of everything' rather than 'a history of things' sense; again, this fits well with the idea that there is one 'true' version of any file at any point.)

**Comment by josephwright** [comment]
I'm not seeing the link between how Gentoo, or whatever, packs it's distribution files and how they are picked up from the developers. (I'm also a bit confused as Gentoo is a Linux distro, so I'd expect it to have a re-packaged version of TeX Live at some fixed release date.)

**Comment by equaeghe** [comment]
> I'm not seeing the link between how Gentoo, or whatever, packs it's distribution files and how they are picked up from the developers.

Gentoo just has ‘ebuild’ files that describe how to obtain & compile software. There are almost no distribution files. The sources are usually downloaded directly from, e.g., Github repos, although those bundles can be mirrored on Gentoo servers to keep ‘old’ versions available.

> (I'm also a bit confused as Gentoo is a Linux distro, so I'd expect it to have a re-packaged version of TeX Live at some fixed release date.)

Yes, TeX Live is used, but not for all TeX-related packages. Beamer in Gentoo does not have TeX Live as its upstream, but this repository. (One could say this mixed way of doing things is the cause of this issue.)

In any case, I now agree with you that this is not your issue.
