### ISSUE TITLE
Sounds in Beamer are distorted

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#58]
Originally reported by: **ian_fin (Bitbucket: [ian_fin](https://bitbucket.org/ian_fin), GitHub: Unknown)**

----------------------------------------

I'm trying to add sounds to slides for the first time and when I play them in Adobe Reader, the audio is getting distorted.

I've been trying to trace the problem back and as far as I can see it's happening when the .tex file is being built. I've tried my PDF on a couple of machines, as well as comparing with someone else's script which worked for them. Also tried changing between .au and .aiff, as well as double (triple, quadruple...) checking that the specs of the format I used match the default arguments of \sound.

It builds without error, so doesn't seem to be a problem with what's there.

    
    #!LaTeX
    
    \documentclass{beamer}
    \mode<presentation>
    \usepackage{multimedia}
    \begin{document}
    \begin{frame}
    
    \sound[inlinesound,automute]{Substitution}{substitution.aiff}
    
    \end{frame}
    \end{document}
    

Building in Windows 7 in TeXnicCenter, using MiKTeX

----------------------------------------
- Bitbucket: https://bitbucket.org/rivanvx/beamer/issue/58

**Comment by josephwright** [comment]
*Original comment by* **fmms (Bitbucket: [fmms](https://bitbucket.org/fmms), GitHub: [fmms](https://github.com/fmms))**:

----------------------------------------

it would certainly help if you could attach the soundfile too...

**Comment by josephwright** [comment]
*Original comment by* **ian_fin (Bitbucket: [ian_fin](https://bitbucket.org/ian_fin), GitHub: Unknown)**:

----------------------------------------

Gave it a try on a machine running Linux and the sound works... I'm guessing it's a problem with the software that various PDF viewers use to play media, and Beamer is not to blame.

***Closed***

**Comment by josephwright** [comment]
*Original comment by* **psibre (Bitbucket: [psibre](https://bitbucket.org/psibre), GitHub: [psibre](https://github.com/psibre))**:

----------------------------------------

I'm afraid the issue is by no means solved.

Consider the following small, self-contained, correct example:
    
    \documentclass{beamer}
    
    \mode<presentation>
    \usepackage{multimedia}
    
    \begin{document}
    
    \begin{frame}
    \sound[inlinesound,encoding=Signed]{Click me!}{Glass.raw}
    \end{frame}
    
    \end{document}
    

With MacTeX 2009, which packs pdfTeX 3.1415926-1.40.10-2.2 (TeX Live 2009), everything works fine. However, after an upgrade to MacTeX 2010, which packs pdfTeX 3.1415926-1.40.11-2.2 (TeX Live 2010), the same example generates a pdf file in which the sound is played back distorted.

To be precise:
    
    /usr/local/texlive/2009/bin/universal-darwin/pdflatex sound_issue
    
produces sound_issue_2009.pdf, while
    
    /usr/local/texlive/2010/bin/universal-darwin/pdflatex sound_issue
    
produces sound_issue_2010.pdf (which has distorted sound).

This seems to strongly indicate that TeXLive 2010 ships with a pdftex version which handles beamer's multimedia sound differently than the version in TeXLive 2009, and causes the sound to be distorted in the PDF viewer.

**Comment by josephwright** [comment]
*Original comment by* **Vedran Miletić (Bitbucket: [rivanvx](https://bitbucket.org/rivanvx), GitHub: Unknown)**:

----------------------------------------

I'm not sure that this is a Beamer issue. Can you check if the same thing happens with \documentclass{article}?

**Comment by josephwright** [comment]
*Original comment by* **psibre (Bitbucket: [psibre](https://bitbucket.org/psibre), GitHub: [psibre](https://github.com/psibre))**:

----------------------------------------

Indeed,
    
    
    \documentclass{article}
    
    \usepackage{hyperref, multimedia}
    
    \begin{document}
    
    \sound[inlinesound,encoding=Signed]{Click me!}{Glass.raw}
    
    \end{document}
    
    
produces the same distorted audio with MacTeX 2010, but works normally with MacTeX 2009. So it's not an issue with beamer per se, but as far as I can tell, multimedia is a sub-package of beamer, right?

I can't help but notice that the version of pdfTeX that comes with TeXLive 2010 is a newer version than the current stable release at http://www.tug.org/applications/pdftex/ (3.1415926-1.40.10-2.2), so maybe the TeXLive people built the bundled binaries using unstable code... I'll check over there and report back.

**Comment by josephwright** [comment]
*Original comment by* **Vedran Miletić (Bitbucket: [rivanvx](https://bitbucket.org/rivanvx), GitHub: Unknown)**:

----------------------------------------

I haven't changed anything in multimedia.sty, aside from moving it to a different location. Perhaps pdfTeX changed in some way.

I doubt that unstable version is actually shipped; it's probably that webpage isn't maintained.

**Comment by josephwright** [comment]
*Original comment by* **Anonymous**:

----------------------------------------

I got a sound correctly reproduced by specifying some encoding properties in the code (and also converting the sound either to .aiff or .au, with .wav doesn't work). ex:

    
    #!latex
    
    \sound[inlinesound,encoding=signed,channels=2]{Play the sound!}{test.aiff}

**Comment by josephwright** [comment]
*Original comment by* **ian_fin (Bitbucket: [ian_fin](https://bitbucket.org/ian_fin), GitHub: Unknown)**:

----------------------------------------

I've encountered the problem again in Linux using TexLive 2010.

It only happens with the newer version of PDFLaTeX (3.1415926-1.40.11-2.2; I have an old version of Ubuntu which happens to have 3.1415926-1.40.10-2.2, and it works fine). The obvious response is of course to put the blame on PDFLaTeX, but I've never had any problems with the audio when including videos using the flashmovie package.

**Comment by josephwright** [comment]
*Original comment by* **ian_fin (Bitbucket: [ian_fin](https://bitbucket.org/ian_fin), GitHub: Unknown)**:

----------------------------------------

Further update: I get the same problem when trying to build with LuaLaTeX as well.

**Comment by josephwright** [comment]
*Original comment by* **Joseph Wright (Bitbucket: [josephwright](https://bitbucket.org/josephwright), GitHub: [josephwright](https://github.com/josephwright))**:

----------------------------------------

Sound playback is the job of the PDF viewer, and indeed insertion into the output is an engine job. beamer has not control over this other than saying 'include sound here' => not a beamer bug.

**Comment by martin-frbg** [comment]
Necroposting as we just had occasion to retry getting lecture notes with audio commentary working cross-platform. Of course this _is_ ultimately an Adobe Reader bug in that it needs to be fed all audio parameters while okular etc. get everything from the embedded audio file itself. However my experiments show that transplanting a very old beamer package into a current pdftex environment is sufficient to get clear .au audio with a Win10 Reader installation where
current releases of both produce only static noise and "old" pdftex with "current" beamerstyle 
a barely discernible voice amid "motorboat" sounds.
I intend to try to narrow this down to a minimal diff, but unfortunately the currently "known good" version is what came with a vintage opensuse 10.3 in 2007 so a naive `diff -uwr` is 230k ~~and obviously there is no git history going back that far.~~ (multimedia.sty bears a CVS tag from october 2004, beamer.cls is identified as v1.67 of october 23, 2005 and declares the beamer version as 3.06) 
EDIT: actually I realize now that 3.06 is indeed tagged here so will bisect after the weekend.

**Comment by martin-frbg** [comment]
Not sure yet if this makes sense, but git bisect led me there...

82eafc03fd598d77b59f8ad60f7861c109b1d06f is the first bad commit
commit 82eafc03fd598d77b59f8ad60f7861c109b1d06f
Author: Till Tantau <tantau@tcs.uni-luebeck.de>
Date:   Wed Nov 9 15:45:54 2005 +0000

    fixed ifnextchar problem
(reverting this in either 82eafc or an intermediate version like 9fc10a22 (v3.40) did not fix the sound, so either there is/was multiple breakage or the sound handling in acroread is just extremely fragile)

**Comment by martin-frbg** [comment]
Sorry, got confused by the varying location of multimedia&friends between versions, so the earlier bisect run was entirely futile. Actually the only salient change is a one-liner in line 234 of multimedia.sty itself, which unfortunately was affected by one huge code reversal seven years ago so the motivation for that change is not easy for me to establish. Here it is in patch format,
I'll create a proper PR for this in a minute.
```
--- a/base/multimedia/multimedia.sty
+++ b/base/multimedia/multimedia.sty
@@ -231,7 +231,7 @@
     \else%
       \ifmm@inline%
         \beamer@pdfobj stream
-        attr {/Type /Sound \mm@r\space \mm@c\space \mm@b\space}
+        attr {\mm@r\space \mm@c\space \mm@b\space \mm@e\space}
         file {#3}%
         \beamer@pdfrefobj \beamer@pdflastobj%
       \else

```
