### ISSUE TITLE
How to deal with the the formating problems of biblatex?

### ISSUE THREAD

**Issue by samcarter** [josephwright/beamer#581]
What is the best strategy to deal with the problems between biblatex and beamer? 

### Recap

There are two main problems when using biblatex with beamer

- missing labels for styles that rely on the label to identify the entry, e.g. `numeric` and `alphabetic`

- incorrect left margin and indention for styles without label, e.g. `authoryear` and `authortitle`

### Suggestion 1

Try to get biblatex to add a few small fixes to the core `.bbx` files (`numeric`, `authoryear`, `authortitle`, `verbose`), for example like: https://github.com/samcarter/biblatex/commit/2da72185a255486e44b299b5a9946328db4c1735

Advantages: 

- If the changes are done in the 4 core `.bbx` files, they will automatically propagate to derived styles. For example fixing `numeric.bbx` will also fix `numeric-verb.bbx`, `numeric-comp.bbx` and third party styles

- The changes are done while loading the biblatex package, this means that user can further customise things in their preamble

Disadvantages:

- biblatex will have to agree

### Suggestion 1a

As an experiment I tried to hook into the .bbx files to apply the fixes, but this seems difficult, see https://topanswers.xyz/tex?q=730 for discussion

Disadvantage:

- hacky...

### Suggestion 1b

[@u-fischer suggested](https://github.com/josephwright/beamer/issues/581#issuecomment-590785205) that one could ask biblatex to add a hook and document how packages and classes could use it to modify a style.

For example if biblatex were to make the following adjustments https://github.com/samcarter/biblatex/commit/47369010670fbb0f70b577de666ff50579327629 beamer could simply define 

```
\newcommand{\biblatexendofnumericbbxhook}{\mode<presentation>{\setbeamertemplate{bibliography item}{\insertbiblabel}}}
\newcommand{\biblatexendofalphabeticbbxhook}{\mode<presentation>{\setbeamertemplate{bibliography item}{\insertbiblabel}}}
\newcommand{\biblatexendofauthoryearbbxhook}{\mode<presentation>{%
    \newlength{\beamer@bibiconwidth}
    \settowidth\beamer@bibiconwidth{\usebeamertemplate*{bibliography item}}
    \setlength{\labelwidth}{-\beamer@bibiconwidth}
    \addtolength{\labelwidth}{2\labelsep}
    \addtolength{\bibhang}{\labelsep}
}}
\newcommand{\biblatexendofauthortitlebbxhook}{\mode<presentation>{%
    \newlength{\beamer@bibiconwidth}
    \settowidth\beamer@bibiconwidth{\usebeamertemplate*{bibliography item}}
    \setlength{\labelwidth}{-\beamer@bibiconwidth}
    \addtolength{\labelwidth}{2\labelsep}
    \addtolength{\bibhang}{\labelsep}
}}
```

Advantages:

- Changes are done in the 4 core `.bbx` files, they will automatically propagate to derived styles. 

- user can further customise things in their preamble

- can easily be undone if a user prefers the current behaviour by redefining the command

### Suggestion 2

Beamer could try to make some adjustments at begin document, for example like https://github.com/samcarter/beamer/commit/c5fe3d76e7b995c0a023791f1a7464c5e8fe9fa0

Disadvantages:

- Trying to guess from the name alone from which core style something is derived from is not really reliable. The alternative is to test for every style individually, but biblatex alone already comes with 27 styles, so this list gets long without even thinking on any third party styles

- patching things at begin document bereaves the users of the possibility to customise things in the preamble

 ### Suggestion 3

This is an idea from @u-fischer 

beamer could create its own biblatex styles, for example

numeric-beamer.bbx:

```
\ProvidesFile{numeric-beamer.bbx}
[\abx@bbxid]

\RequireBibliographyStyle{numeric}

\@ifclassloaded{beamer}
  {\mode<presentation>{\setbeamertemplate{bibliography item}{\insertbiblabel}}}
  {}%

\endinput
```

Advantages: 

- The changes are done while loading the biblatex package, this means that user can further customise things in their preamble

- beamer can say "not my fault" if the users uses "normal styles"

Disadvantages

- each style would have to be threaded separately, no propagation from the core styles

- How to get the users to use these styles? Add a warning if a "normal" style is detected at begin document? Many will simply ignore the warning.

### Suggestion 4

Also an idea by @u-fischer

Add a beamer option to disable beamers changes to the bibliography. 

Advantages:

- beamer can say "not my fault" if the users does not use it

Disadvantage:

- Using this option will remove the little icons, which I find very helpful to quickly see what type of document something is.

- will also remove the possibility to things via beamer templates, -colour, -fonts etc.

- How to make the users aware of this option? Add a warning? Many will simply ignore the warning.

### related discussions:

- https://github.com/josephwright/beamer/issues/531
- https://github.com/josephwright/beamer/issues/347

Any opinions or other suggestions?

**Comment by Rmano** [comment]
I think that suggestion 1 is the most sound. You could try to do a PR and see what happens...

**Comment by u-fischer** [comment]
@Rmano I don't agree. Code involving `\@ifclassloaded{XXXX}`  are almost always problematic, and even more if is uses internal commands of the class (`\beamer@bibiconwidth`). It would mean that biblatex would have to monitor beamer, in case it changes something, and beamer would have to remember that the internal command is used elsewhere. 

A better way for biblatex to support something here would be if it would add e.g. at the end of numeric.bbx a command `\csname biblatexendofnumericbbxhook\endcsname` and document how interested third party packages and classes could make use of it to modify a style. 

(Side remark: improved hook management is something we are working on too, see e.g. the discussion here https://github.com/latex3/latex3/issues/681).

**Comment by samcarter** [comment]
@u-fischer 

> even more if is uses internal commands of the class (\beamer@bibiconwidth)

just a small comment: `\beamer@bibiconwidth` is defined within the ifclassloaded code block and only used there, not within beamer. It can be replaced by any other name, e.g. some temporary lenght, I just wanted to be sure to not interefere with anything used by biblatex.

I love the idea of a hook!

**Comment by u-fischer** [comment]
@samcarter  ah sorry, I misread the code. But my dislike of `\@ifclassloaded` and similar stays - they have a tendency to get forgotten or outdated and then you have to hunt them down.

**Comment by Rmano** [comment]
> A better way for biblatex to support something here would be if it would add e.g. at the end of numeric.bbx a command `\csname biblatexendofnumericbbxhook\endcsname` and document how interested third party packages and classes could make use of it to modify a style.

Yes, I agree, that would be much better. Documented hooks are a good idea!

**Comment by samcarter** [comment]
Added the hook idea as "Suggestion 1b"

**Comment by samcarter** [comment]
@moewew @plk Pinging you in case you are interested in this discussion

**Comment by plk** [comment]
I am happy to add new hooks since beamer is such a significant package - @moewew - what do you think?

**Comment by moewew** [comment]
I'm all for new hooks (god knows I have been pestering people about adding them to their packages/classes).

(*But*) I would like to avoid a situation where `biblatex` style authors have to add something new to their styles. Certainly when it is class-dependent code that might change or that a `biblatex` style author might not necessarily (want to) know about (like internal `@` `beamer` commands, even if they are defined internally, https://github.com/samcarter/biblatex/commit/2da72185a255486e44b299b5a9946328db4c1735; for lack of expertise I can't say I share Ulrike's disliking for `\@ifclassloaded` the way she does, but I have my own reservations against it). The adjustments in https://github.com/samcarter/biblatex/commit/47369010670fbb0f70b577de666ff50579327629 are less problematic in that they don't require specific code from `biblatex` style authors, but it still requires a seemingly unmotivated piece of code in their styles. True, many style authors might not be affected, because their style inherits from one of the standard styles, but those who don't inherit will have to decide what to do. Ideally style authors would not have to add code like this to their styles.

I can think of two very different possible ways out of this dilemma that try to tackle the issue on different levels.
1. An official hook for 1a. Then there would be support for injecting code for each possible file at load-time. You would probably support the standard files and would catch all styles that inherit from them.

2. It appears to me that you don't want to insert code for particular styles, you want to insert code for certain style families. The code for numeric styles is different from authoryear styles. We could invent a sort of classification system for style authors. Instead of having authors put a seemingly unmotivated hook like `\csname biblatexendofnumericbbxhook\endcsname` (what should `biblatex-ieee` put `\csname biblatexendofieeebbxhook\endcsname` or `\csname biblatexendofnumericbbxhook\endcsname` because it is a numeric style) they would have to classify their styles with one of the style family (types) and the code for the style family would be executed after loading the style. Of course that still requires compliance by style authors, but it would feel more ... motivated to me than a simple `\csname ...\endcsname`.

**Comment by u-fischer** [comment]
@moewew I'm not quite sure why you think that it *requires* style author to add code to their styles. If an author doesn't add a hook, then beamer can't adjust the style - which isn't a great problem. beamer could simply document that it adds its color code etc to the styles A, B, C, D, and if the user wants to use an unsupported style they should do something similar manually. 

But it doesn't have to be a manual hook in a bbx.  If biblatex would add a general "file hook system" that allows to add code at the end of  every bbx/cbx loading it would fine too. (And the naming can be improved, I used such a long convulated name only as example ;-))

**Comment by moewew** [comment]
Sure, read the "required" and "have to" etc as *required/have to if they want their style to support `beamer` (if their style does not inherit from a standard style that has been patched already)*. The actual impact of these change is quite probably limited as mentioned already, but my general point is of a more aesthetic nature and - I believe - still stands.

Yes, a general file hook would appear to be much cleaner to me. But I'd like to understand first if that would really solve the issue.

**Comment by samcarter** [comment]
@moewew 

> It appears to me that you don't want to insert code for particular styles, you want to insert code for certain style families. [...]

I would prefer to patch individual files instead of defining families. This would also allow to patch some minor problems with specific styles, for example https://github.com/josephwright/beamer/issues/348

With some general "file hook system", as @u-fischer suggested in her previous comment, one could also tackle those problems

**Comment by moewew** [comment]
A first attempt at the file hook implementation can be found in https://github.com/moewew/biblatex/tree/filehooks (https://github.com/plk/biblatex/compare/dev...moewew:filehooks). A drop-in replacement for v3.14's `biblatex.sty` for easy testing is at https://gist.github.com/moewew/0472e4ddc65a0569402a0adbdae1cc50.

Example
```latex
\documentclass[british]{beamer}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage{etoolbox}
\csappto{blx@filehook@postload@numeric.bbx}{%
  \mode<presentation>{\setbeamertemplate{bibliography item}{\insertbiblabel}}}

\usepackage[style=numeric, backend=biber]{biblatex}


\addbibresource{biblatex-examples.bib}


\begin{document}
\begin{frame}
\cite{sigfridsson,kant:kpv}
\end{frame}
\begin{frame}
\printbibliography
\end{frame}
\end{document}
```

Nothing here is final. Let me know what you think.

**Comment by samcarter** [comment]
@moewew Thanks a lot for this code! I tested with https://github.com/samcarter/beamer/commit/30aaa6b897a1a8198aba5f6c78fe2c33f35ad23d and it works really great!

**Comment by moewew** [comment]
If the file hooks do it for you, then I'll look into getting them into the next `biblatex` version.

I'm not quite happy with the special handling for `.lbx` files here, so if anyone has an idea what to do or an intuition how things should be I'd love to hear about it.

I'm also very insecure about naming things, so if you have a better idea for the names of the hooks, I'll be all ears.

Any other comments on https://github.com/plk/biblatex/compare/dev...moewew:filehooks are of course also very much appreciated.

**Comment by samcarter** [comment]
@moewew 

> If the file hooks do it for you, then I'll look into getting them into the next biblatex version.

I'm looking forward to this! I'll add the necessary changes to beamer once this is available in biblatex.

> I'm also very insecure about naming things, so if you have a better idea for the names of the hooks, I'll be all ears.

I think the name is fine. It makes it clear where the hook is applied.

**Comment by moewew** [comment]
See https://github.com/plk/biblatex/pull/973. 

As mentioned there and above, there is an extra interface for `.lbx` files, which is a bit meh. So if anyone has an idea what to do here, I'm all ears.

Comments are very welcome.

**Comment by moewew** [comment]
PR https://github.com/plk/biblatex/pull/973 was just merged, so you can expect

* `\blx@filehook@preload@<filename>`,
*  `\blx@filehook@postload@<filename>` and
* `\blx@filehook@failure@<filename>`

in the next release. I'm still a bit unhappy with the `.lbx` thingy, but if no one has any idea how to deal with it, it will remain as-is. (But that shouldn't concern your main use case, which patches `.bbx` files.)

**Comment by samcarter** [comment]
@moewew  Thanks a lot for adding the hooks!
