### ISSUE TITLE
\\<article> ceases to work

### ISSUE THREAD

**Issue by jspitz** [josephwright/beamer#582]
In current beamer release (`beamerarticle 2019/09/29 v3.57`), the `<article>` mode specifier to `\\` doesn't seem to work any longer.

MWE:
```tex
\documentclass[11pt]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{beamerarticle}
\begin{document}
\begin{frame}
One\\<article>two

Three\only<article>{\newline}four
\end{frame}
\end{document}
```

**Comment by josephwright** [comment]
This is not due to a `beamer` change, rather it's a side-effect of changes to the LaTeX kernel. I'll have to check exactly where the mismatch arises.
