### ISSUE TITLE
Invisible frames increase total frame number

### ISSUE THREAD

**Issue by samcarter** [josephwright/beamer#592]
```
\documentclass{beamer}

\begin{document}

\begin{frame}
\inserttotalframenumber
\end{frame}

\begin{frame}<0>
\inserttotalframenumber
\end{frame}

\begin{frame}
\inserttotalframenumber
\end{frame}

\end{document}
```

(problem surfaced in https://texnique.fr/osqa/questions/8453/changer-lordre-des-overlays-dans-beamer/8457)

**Comment by louisstuart96** [comment]
This seems not a bug:
`\inserttotalframenumber` is set equal to the value of counter `framenumber` at the very end of the document. `framenumber` is stepped in every frame, and setting overlay spec to `<0>` will not affect the counter. 
The documentation says (on page 59), 'The `<overlay spec>` dictates which slides of a frame are to be shown', not 'whether a frame is to be accounted for'.

**Comment by louisstuart96** [comment]
To make a frame not accounted for, the best way is to present it in a seperated mode:
```
\documentclass{beamer}

\begin{document}

\begin{frame}
\inserttotalframenumber
\end{frame}

\mode<handout>{
\begin{frame} // \begin{frame}<handout> does not work
\inserttotalframenumber
\end{frame}
}

\begin{frame}
\inserttotalframenumber
\end{frame}

\end{document}
```

**Comment by dbitouze** [comment]
> To make a frame not accounted for, the best way is to present it in a separated mode:

But in case you want this frame to not be displayed in any mode? I agree this could look weird but it is the only workaround that came to my mind to answer the question pointed by @samcarter and that I translate now for the sake of completeness.

# Question:
In `beamer`, it is possible to display only certain overlays of a frame: 
```latex
\documentclass{beamer}    
\begin{document}
\begin{frame}<1>   %% only overlay 1
  \frametitle{test}
  \only<1>{Page 1}
  \only<2>{Page 2}
\end{frame}
\end{document}
```
I would like to use this option (or another one?) to be able to change the order of the overlays: by specifying `<2,1>` I would like the second overlay to appear before the first one:
```latex
\documentclass{beamer}    
\begin{document}
\begin{frame}<2,1>  %% overlay 2 then 1?
  \frametitle{test}
  \only<1>{Page 2}
  \only<2>{Page 1}
\end{frame}
\end{document}
```
But that doesn't work. Do you know an easy way to achieve that?
# (My) Answer:
Here is a solution where the `noframenumbering` option is necessary, otherwise the frame numbering includes the invisible one (`<0>`):
```latex
\documentclass{beamer}
\usetheme{CambridgeUS}
\begin{document}
\begin{frame}<0>[label=foobar,noframenumbering]  %% overlay 2 then 1 ?
  \frametitle{test}
  \only<1>{Page 1}
  \only<2>{Page 2}
\end{frame}

\againframe<2>{foobar}
\againframe<1>{foobar}
\end{document}
```
It would have been nicer to be able to write `\againframe<2,1>{foobar}` instead of repeating `\againframe<...>{foobar}` but it doesn't seem to be working.

**Comment by louisstuart96** [comment]
> by specifying <2,1> I would like the second overlay to appear before the first one...

It is impossible to do that due to the mechanism of overlay. An overlay spec is a set rather than a list. That is, when `beamer` decides to show or hide a slide, it checks if this slide is in the specified overlay set. The order in an overlay spec is irrelevant.

**Comment by samcarter** [comment]
With https://github.com/samcarter/beamer/commit/bcc5719ee7d286a90f8be137c22b1e882a93cd30 one could avoid counting invisible frames -- the question is just what else will it break?

**Comment by samcarter** [comment]
... thinking about it, normal `noframenumbering` frames also don't break that many things (at least that I know of), so this fix might not be too dangerous (this will make famous last words if beamer explodes :) ).

Just need to understand why noframenumbering uses `\stepcounter{framenumber}` for fragile frames. Why is this necessary? 

```
  \ifbeamer@noframenumbering%
    \ifbeamer@isfragile%Fragile frames will be processed twice
      \stepcounter{framenumber}%
    \fi%
  \else%
    \stepcounter{framenumber}%do not set \label here - it interferes with AtBegin*
  \fi%
```

Maybe invisible fragile frames should do the same? Something like 

```
  \ifbeamer@isfragile%Fragile frames will be processed twice
    \stepcounter{framenumber}%do not set \label here - it interferes with AtBegin*
  \else%  
    \ifx\beamer@whichframes\beamer@testzero\else
      \ifbeamer@noframenumbering\else%
        \stepcounter{framenumber}%do not set \label here - it interferes with AtBegin*
      \fi%
    \fi%
  \fi%
```

?

**Comment by samcarter** [comment]
(... and obviously the above fix only works for frames hidden in all mods `<0>` and not `<current mode:0>`)
