### ISSUE TITLE
installation in linux

### ISSUE THREAD

**Issue by semihozlemlinuxuser** [josephwright/beamer#593]
Hi I am unable to get beamer to work in a linux system
Other than copying the unzipped version of the beamer folder in texmf tree what else needs to be done
Is there a particular texmf path where the folder needs to be placed

Thank you ahead of time

**Comment by samcarter** [comment]
@semihozlemlinuxuser The easiest way to install beamer is through the package manager of your tex distribution (texlive, miktex etc.). Beamer has  tons of dependencies and the package manager will take care to install of them.
