### ISSUE TITLE
Blocks cannot be alerted

### ISSUE THREAD

**Issue by christianlupus** [josephwright/beamer#596]
I recently opened [this issue on TeX - LaTeX Stack Exchange](https://tex.stackexchange.com/questions/542931/how-to-alert-a-block-using-overlays?noredirect=1#comment1371465_542931 "beamer - How to alert a block using overlays? - TeX - LaTeX Stack Exchange"). I consider the behavior a bug and report it here thus.

Lond story short, I want to alert a block using an overlay specification like `<2-| alert@3>`.

My understanding is that this should generate the same representation as an `alertblock`. However, I do not see *any* change in the appearance.

Here is a minimal example:
```
\documentclass[10pt]{beamer}
\usetheme{Frankfurt}

% block
\setbeamercolor{block title}{fg=black,bg=blue!50!black}
\setbeamercolor{block body}{fg=green!50!black,bg=green!50!black!30!white}

% alertblock
\setbeamercolor{block title alerted}{fg=black,bg=green!50!white}
\setbeamercolor{block body alerted}{fg=green,bg=green!30!white}
\begin{document}
\begin{frame}{ABC}

% Just to verify that alert is working in general
\begin{itemize}[<+->]
 \item a
 \item<+-| alert@2> b
 \item c
\end{itemize}

\begin{block}<alert@2>{Test block}
This block should be alerted in overlay 2.
\end{block}

\begin{alertblock}<alert@1>{foo}
Example of an alert block.
\end{alertblock}

\end{frame}
\end{document}
```
I added even the hint in [this issue](https://github.com/josephwright/beamer/issues/187#issuecomment-559484016) as I was not sure if the `block X alerted` style and the `alertblock` environment are related.

![slides](https://user-images.githubusercontent.com/8202922/81533768-0f8c7800-9367-11ea-8be7-017e1a740a9b.gif)

**Comment by samcarter** [comment]
I think the `alert` action specification for blocks is not meant to produce an `alert block` but to alert items within the block:

```
\documentclass[10pt]{beamer}
\usetheme{Frankfurt}

\begin{document}
\begin{frame}

\begin{block}<alert@2>{Test block}
\begin{itemize}
 \item a
 \item b
 \item c
\end{itemize}
\end{block}

\end{frame}
\end{document}
```

**Comment by christianlupus** [comment]
Even there seems to be an issue: I modified my example to reflect that:

```
\documentclass[10pt]{beamer}
\usetheme{Frankfurt}

% block
\setbeamercolor{block title}{fg=black,bg=blue!50!black}
\setbeamercolor{block body}{fg=green!50!black,bg=green!50!black!30!white}

% alertblock
\setbeamercolor{block title alerted}{fg=black,bg=green!50!white}
\setbeamercolor{block body alerted}{fg=green,bg=green!30!white}
\begin{document}
\begin{frame}{ABC}

% Just to verify that alert is working in general
\begin{itemize}[<+->]
 \item a
 \item<+-| alert@2> b
 \item c
\end{itemize}

\begin{block}<alert@2>{Test block}
This block should be alerted in overlay 2.
\begin{itemize}
 \item a
 \item<alert@3> b
 \item c
\end{itemize}
\end{block}

\begin{alertblock}<alert@1>{foo}
Example of an alert block.
\end{alertblock}

\end{frame}
\end{document}
```
Note: On  Slide 2 all item symbols are highlighted. However, the text is not highlighted. In comparison on the 3rd slide only `b` is alerted and here the text is typeset in red as well.

![slides](https://user-images.githubusercontent.com/8202922/81666984-053fac00-9443-11ea-8ec4-9808f1fdb6c0.gif)

**Comment by samcarter** [comment]
@christianlupus Your new problem is caused by the colour scheme you use (indirectly through the Frankfurt theme). You can work around like this:

```
\documentclass[10pt]{beamer}

\useoutertheme[subsection=false]{smoothbars}
\useinnertheme[shadow=true]{rounded}

\setbeamercolor{block title}{use=structure,fg=white,bg=structure.fg!75!black}
\setbeamercolor{block title alerted}{use=alerted text,fg=white,bg=alerted text.fg!75!black}
\setbeamercolor{block title example}{use=example text,fg=white,bg=example text.fg!75!black}

\setbeamercolor{block body}{
%parent=normal text,
use=block title,bg=block title.bg!10!bg}
\setbeamercolor{block body alerted}{parent=normal text,use=block title alerted,bg=block title alerted.bg!10!bg}
\setbeamercolor{block body example}{parent=normal text,use=block title example,bg=block title example.bg!10!bg}

\usecolortheme{whale}

\setbeamerfont{block title}{size={}}


\begin{document}
\begin{frame}

\begin{itemize}[<alert@2>]
 \item a
 \item b
 \item c
\end{itemize}

\begin{block}<alert@2>{}
\begin{itemize}
 \item a
 \item b
 \item c
\end{itemize}
\end{block}

\end{frame}
\end{document}
```

![Screen Shot 2020-05-12 at 21 05 11](https://user-images.githubusercontent.com/43832342/81734768-575ced80-9494-11ea-8f08-0acb9d845695.png)

**Comment by christianlupus** [comment]
OK, I see. 

So am I correct, that all I can do is something like the following?
```
\alt<2>{%
% On second slide use an alertblock
\begin{altertblock}%
Here comes the content
\end{alertblock}%
}{%
% Normally use a normal block
\begin{block}%
Here comes the content
\end{block}%
}
```
In fact I have to rewrite the `Here comes the content` **exactly**?

**Comment by samcarter** [comment]
@christianlupus  I think the easiest approach would be to change the colour on the second overlay:

```
\documentclass[10pt]{beamer}

\usetheme{Frankfurt}


\begin{document}
\begin{frame}

{
\only<2>{\setbeamercolor{block title}{use=alerted text,fg=white,bg=alerted text.fg!75!black}}
\begin{block}{title}
\begin{itemize}[<alert@2>]
 \item a
 \item b
 \item c
\end{itemize}
\end{block}
}

\end{frame}
\end{document}
```

![document](https://user-images.githubusercontent.com/43832342/81961868-41296b80-9613-11ea-8e70-2d2f0f261922.gif)

**Comment by christianlupus** [comment]
OK, thank you.
