### ISSUE TITLE
beamer 3.58 problem with helvet and lmodern - problem with upper-case Greek

### ISSUE THREAD

**Issue by fmirus** [josephwright/beamer#598]
I have a problem similar to the one asked [here](https://tex.stackexchange.com/questions/138898/beamer-3-30-with-helvet-problem-with-upper-case-greek). 
My minimal working example looks like this:
```
\documentclass{beamer}
\usepackage{lmodern}
\usepackage{helvet}
\begin{document}
\begin{frame}
$\Gamma \neq \Theta \neq \Omega$

$\gamma, \theta, \omega$
\end{frame}
\end{document}
```
The result looks like this with lmodern (line 2 in the mwe) in it:

![tex_greek_bad](https://user-images.githubusercontent.com/1374607/81829534-47e4af80-953b-11ea-9164-57c5f0b590f9.png)

and like this without lmodern 

![tex_greek_good](https://user-images.githubusercontent.com/1374607/81829553-50d58100-953b-11ea-9871-3161084609e0.png)

Inserting ```\usefonttheme[]{serif}``` instead of ```\usepackage{lmodern}``` in the example above is a quick workaround (see also [my question here](https://tex.stackexchange.com/questions/543958/beamer-3-58-problem-with-helvet-and-lmodern-problem-with-upper-case-greek)), but it may be still a bug in beamer though. That's why I'm posting it here :)

**Comment by samcarter** [comment]
You need the professionalfonts theme

```
\documentclass{beamer}

\usefonttheme{professionalfonts}
\usepackage{lmodern}
\usepackage{helvet}

\begin{document}
\begin{frame}
$\Gamma \neq \Theta \neq \Omega$

$\gamma, \theta, \omega$
\end{frame}
\end{document}
```

**Comment by fmirus** [comment]
works like a charm. Thanks :slightly_smiling_face:

**Comment by samcarter** [comment]
@fmirus You're welcome!
