### ISSUE TITLE
Broken math mode scoping with \textnormal and others

### ISSUE THREAD

**Issue by Quoor8ee** [josephwright/beamer#599]
Commit 87f1646bd2307010701991129e5a900019b1d48c extended `\textnormal` and a few other `\text*` macros for beamer-aware semantics. This broke the single-token expansion syntax in math mode.
MWE:
```
\documentclass{beamer}
\begin{document}
\begin{frame}
$X_\textnormal{Y}$
\end{frame}
\end{document}
```
Works fine up to TeXLive 2018, but with beamer code younger than one year (TL19 with updates, TL20, trunk) it complains:
```
! Missing { inserted.
<to be read again> 
                   \def 
l.5 \end{frame}
                
? x
No pages of output.
```
As a workaround, one can add braces around the subscript argument, like `$X_{\textnormal{Y}}$`. But math mode syntax (and the principle of least astonishment) are broken for writing/remembering/copy-pasting/importing code from any other documents into beamer presentations (plus editor autocomplete).
Is there a clever way to wrap those macros into a scope so that beamer's descendants of these macros behave more like their counterparts in plain LaTeX?

**Comment by u-fischer** [comment]
Using a subscript without braces is not a supported syntax. It may work but it can also break.  

With braces your example work fine and this not a workaround but the proper input. So always use it.

~~~~
\documentclass{beamer}
\begin{document}
\begin{frame}
$X_{\textnormal{Y}}$
\end{frame}
\end{document}
~~~~

See also https://tex.stackexchange.com/a/342272/2388

**Comment by Quoor8ee** [comment]
It has worked before, and if someone wonders why their documents no longer build correctly, they at least might come here, and know that this is indeed a regression.
But you're right that nobody should rely on gambling if such accidental syntactic sugar works or not.

In the meantime, I am more sensitised about the topic, and I have found a viable way to deal with it in my actual code. So I don't mind if someone still does something around the issue, or decides to close/wontfix it.

**Comment by josephwright** [comment]
I'm closing here: it's not official LaTeX syntax and moreover we have to make a choice.
