### ISSUE TITLE
Stop frame numbering after a slide

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#6]
Originally reported by: **Anonymous**

----------------------------------------

Hi,

(Re-submitting SourceForge feature request. Not //that// important, but I'd appreciate having this in Beamer)

I have a presentation with, say, 47 slides, and 3
"backup slides" that I'll use only if I get questions
about them.

Currently, the last slide is numbered 47/50 (and the
backup slides are 48/50, 49/50 and 50/50). So, when I
show the presentation, the public still expects
something at the end.

I have a dirty hack:

    
    \newcommand{\noframenumber}%
    {\makeatletter\global\advance\c@framenumber
    by-1\relax\makeatother}
    

and the presentation ends with

    
    \noframenumber
    \begin{frame}
      \frametitle{Backup slides}
      
    \end{frame}
    
    \noframenumber
    \begin{frame}
    ...
    \end{frame}
    

But I'd like something cleaner, like
"\stopframenumbering", "\backupslides" or perhaps
"\appendix".

Another option would be to allow

    
    \begin{frame}[nonumber]
    ...
    \end{frame}
    

----------------------------------------
- Bitbucket: https://bitbucket.org/rivanvx/beamer/issue/6

**Comment by josephwright** [comment]
*Original comment by* **Vedran Miletić (Bitbucket: [rivanvx](https://bitbucket.org/rivanvx), GitHub: Unknown)**:

----------------------------------------

Sure. It would be cool to have this.

**Comment by josephwright** [comment]
*Original comment by* **Vedran Miletić (Bitbucket: [rivanvx](https://bitbucket.org/rivanvx), GitHub: Unknown)**:

----------------------------------------

Fixed. The key is noframenumbering (for now; this might change before release, when I come to rethink all new option names).

**Comment by ghost** [comment]
This is basically solved by https://github.com/josephwright/beamer/commit/0a7af8a222ac680946df60ee3afa6328cfa6e2ba
