### ISSUE TITLE
The footline of Boadilla has a gap at the right

### ISSUE THREAD

**Issue by physkets** [josephwright/beamer#604]
The Boadilla theme has a slight gap at the right end of the footline.

**Comment by samcarter** [comment]
Probably a viewer artefact - it looks fine in acrobat. Which viewer do you use?

![Screen Shot 2020-05-19 at 15 35 19](https://user-images.githubusercontent.com/43832342/82333059-828c9300-99e6-11ea-9b5d-8856e4eb5678.png)

**Comment by physkets** [comment]
Okay, so I figured out the problem. It happens due to a custom placement of the logo at the top right. This is a minimal example. Try it with a small image file.

```tex
\documentclass{beamer}
\usepackage{fontspec}
\usepackage{pgf}
\usepackage{graphicx}
\usetheme{Boadilla}

\title{Caw}
\author{Gufaw}
\date{\today}
\logo{\pgfputat{\pgfxy(-0.3,8.03)}{\pgfbox[center,base]{\includegraphics[scale=0.06]{logo.png}}}} % chktex 36

\begin{document}
\begin{frame}
    \titlepage{}
\end{frame}
\end{document}
```

Is there an easier way I could make this change, so that it does not break anything?

**Comment by samcarter** [comment]
You can avoid the problem by using tikz instead of pgf to place your logo:

```
\documentclass{beamer}
\usepackage{fontspec}
\usepackage{tikz}
%\usepackage{graphicx}
\usetheme{Boadilla}

\title{Caw}
\author{Gufaw}
%\date{\today}
\logo{
\begin{tikzpicture}[remember picture,overlay]
\node at (-0.3,8.03) {\includegraphics[scale=0.06]{example-image-duck}};
\end{tikzpicture}
}

\begin{document}
\begin{frame}
\titlepage
\end{frame}
\end{document}
```

unrelated to your problem: you don't need `\usepackage{graphicx}`, beamer already loads  it for you

**Comment by physkets** [comment]
Thanks so very much! It looks perfectly beautiful now. Okay, I'll stop manually loading `graphicx`. Thanks again!
