### ISSUE TITLE
allowframebreaks option split title and body of block

### ISSUE THREAD

**Issue by sjx95** [josephwright/beamer#608]
Hi, I'm trying to enable the "allowframebreaks" option to reduce my works, but found some unexcepted behavior.
Once the rest space in frame is not enough for the next block, the block title will be placed on current page but the block body will be placed on the next.
Just like this:
![image](https://user-images.githubusercontent.com/18415916/83492963-a8d22880-a4e6-11ea-8339-7f2f1a934797.png)

Because the body of the block is already treated as an unbreakable entirety, I think this behavior is a little weird.

BTW I'm using TeX Live 2019 Final, XeLaTeX compiler.
Here is my test code:
```TeX
\documentclass[11pt]{beamer}
\usepackage{lmodern}
\usetheme{default}
\usepackage{lipsum}
\begin{document}
	
	\begin{frame}[allowframebreaks]{Frame Title}
		
		\begin{block}{Block Title 1}
			\lipsum[2]
		\end{block}
		
		\begin{block}{Block Title 2}
			\lipsum[2]
		\end{block}
		
	\end{frame}

\end{document}
```

**Comment by samcarter** [comment]
I don't think this is unexcepted. The user guide is pretty clear that the `allowframebreaks` option is evil and should only used for things like automatically generated bibliographies.

If you insist on using the evil option, you can wrap the block in a minipage to prevent the page break

Unrelated to your question: you don't need to load the default theme, as the name says, this one is loaded by default

**Comment by sjx95** [comment]
Noted with thanks.

I've tried `minipage` earlier, but it doesn't work in this case.
I'm using manually `\pagebreak` in this slides, and avoid to use this option next time.
