### ISSUE TITLE
All BiBTeX keys give the same citation

### ISSUE THREAD

**Issue by jamon-R** [josephwright/beamer#610]
When creating a new presentation, it happened to me that every citation that I included gave the same reference, i.e. my presentation looked partly like this:
![grafik](https://user-images.githubusercontent.com/52488754/84865581-c53e9b00-b078-11ea-83da-fbdc0a0566d8.png)

Obviously, only one of those references should be to Carvalho et al. 2010, all others have other bibtex entries with unique and distinct bibtex keys. In fact, this behaviour is curiously created now even when I re-compile some old presentations that compiled fine even just a week ago. I posted a question on TeX Stackexchange here: https://tex.stackexchange.com/questions/549754/all-bibtex-keys-give-the-same-citation

You will also find an MWE there. Thanks to the help of @moewe we were able to track this down due to the call to `\beamerdefaultoverlayspecification{<.->} ` before the bibliography. So this behaviour was resolved when resetting the overlay specification with `\beamerdefaultoverlayspecification{} `. However, as I said, even just over a week ago, it worked fine with the call being `\beamerdefaultoverlayspecification{<.->} `, so something must have changed that caused this procedure to fail now...

**Comment by samcarter** [comment]
Can you compare the log files from when it was still working to now? Maybe some packages got updated in the mean time

**Comment by jamon-R** [comment]
Yes, this is probably the reason. However, I updated ALL packages after the error occurred, as I thought an update of the packages might resolve the issue. Please see here for the changes in the log file before and after the issue occurred:
https://github.com/jamon-R/Beamer_Error/commit/cfe2646d2fa56bd6672362137c3ac1152ab5a582

**Comment by samcarter** [comment]
I went as far back as texlive2014, I always get the exact same behaviour as with current texlive
