### ISSUE TITLE
Translate Who? Where? From? in bergen theme

### ISSUE THREAD

**Issue by seloumi** [josephwright/beamer#616]
https://github.com/josephwright/beamer/blob/1d82292c286dbbf811ae1657ef79e4e128c43c63/base/themes/inner/beamerinnerthemeinmargin.sty#L57-L59

When using langagues like French or Spanish strings Who, Where, From still  in English. may be the definition of `\insertauthorindicator`, `\insertinstituteindicator` and `\insertdateindicator`  should be 

```latex
\def\insertauthorindicator{\translate{Who?}}
\def\insertinstituteindicator{\translate{From?}}
\def\insertdateindicator{\translate{When?}}
``` 
This requires adding translation of those strings in dictionaries  

# Example with French language

```latex
\documentclass[french]{beamer}
\usepackage{babel}
\usetheme{bergen}

\title{My title}
\author{John Francois}
\institute{Institue des beaux arts Paris - France}

\begin{document}
\begin{frame}
\maketitle
\end{frame}
\end{document}
```
![image](https://user-images.githubusercontent.com/8249073/89304521-d0bc4480-d66d-11ea-8aa3-a382449ac744.png)

Last remark commands `\insertauthorindicator`, `\insertinstituteindicator` and `\insertdateindicator` are not mentioned in class manual, thanks.

**Comment by samcarter** [comment]
I think this is a good idea! I will prepare a pull request for the translator package in a bit.

It would probably be good to collect as many languages as possible here to submit them at once and minimise the work for the `translator` maintainer.

**Comment by samcarter** [comment]
German:

```
\providetranslation{Who?}{Wer?}
\providetranslation{From?}{Woher?}
\providetranslation{When?}{Wann?}
```

**Comment by TorbjornT** [comment]
Norwegian bokmål (corresponds to the `norsk` option for `babel` I believe):

```
\providetranslation{Who?}{Hvem?}
\providetranslation{From?}{Fra?}
\providetranslation{When?}{Når?}
```

Norwegian nynorsk (corresponds to the `nynorsk` option for `babel`):


```
\providetranslation{Who?}{Kven?}
\providetranslation{From?}{Frå?}
\providetranslation{When?}{Når?}
```

**Comment by Rmano** [comment]
Depend if we see the "place" as affiliation (from where) or the place... (where)

```
\providetranslation{Who?}{Chi?}
\providetranslation{From?}{Da?} [where would be, "Dove?"]
\providetranslation{When?}{Quando?}
```

Spanish
```
\providetranslation{Who?}{¿Quién?}
\providetranslation{From?}{¿Desde?}    [where would be, "¿Dónde?"]
\providetranslation{When?}{¿Cuándo?} 
```

If "From" is intended as affiliation, this is more complex. In Italian and Spanish normally you put the affiliation directly... if you want to force a preposition, for example, in my case could have said (in Italian): 

"Romano Giannetti, dall' Universitá di Pisa" but "del Centro di Ricerca Piaggio"

In Spanish the situation is similar. 

But given that this is a question, "Da? / ¿Desde?" seems acceptable to me.

**Comment by samcarter** [comment]
Closing this issue as a couple of translation have been added to the translator package, but if more transations come up either directly make a PR for translator or post them here and I'll make a PR
