### ISSUE TITLE
\framezoom doesn't work correctly in xelatex, Tex Live 2019

### ISSUE THREAD

**Issue by tc-imba** [josephwright/beamer#619]
I found the issue on https://tex.stackexchange.com/questions/148487/beamer-problem-with-framezoom-and-xelatex, which is years ago, but I tested it on Overleaf (and also my Windows) with Tex Live 2019, xelatex, and the navigation still doesn't work.

Here is an Overleaf link: https://www.overleaf.com/read/cyyvktxvmqgp

**Comment by samcarter** [comment]
might be related to https://github.com/josephwright/beamer/issues/332

**Comment by tc-imba** [comment]
> might be related to #332

Thanks, this should be a problem of hyperlink in xetex.

I checked the commit in #136 , and by adding some real text I can have a dirty fix of this.

https://github.com/josephwright/beamer/blob/b941060c0f9613cc22fce98a4dd127e1adac5d3d/base/beamerbaseframesize.sty#L53-L54

I change `\vbox to #7{\hbox to#6{\hfil}\vfil}` into

```latex
\begin{pgfpicture}{0pt}{0pt}{#6}{#7}%
        \pgfsetfillopacity{0}%
        \pgftext[x=0pt,y=0pt]{.}%
        \pgftext[x=#6,y=#7]{.}%
\end{pgfpicture}%
```

I'm not sure whether everything like #136 should be fixed in such a dirty way. If not please close this issue.

**Comment by tc-imba** [comment]
And why do we use `\Acrobatmenu{GoBack}` instead of a normal hyperlink in the zoomed page?

https://github.com/josephwright/beamer/blob/b941060c0f9613cc22fce98a4dd127e1adac5d3d/base/beamerbaseframesize.sty#L101
