### ISSUE TITLE
\emph{} does not apply italic correction automatically

### ISSUE THREAD

**Issue by ghost** [josephwright/beamer#623]
Consider this mwe:
```
\documentclass{beamer}
\usepackage{fontspec}
\begin{document}
\begin{frame}
    \emph{I have a great professor}!
    \textit{I have a great professor}!
\end{frame}
\end{document}
```
`\emph{}` does not apply automatic italic correction after "professor", but `\textit{}` does.
The mwe was compiled with LuaLaTeX from TeXLive 2020 updated on september 14,
running on Windows 10 Pro 1909 64-bit.

**Comment by louisstuart96** [comment]
Seems `beamer` is lazy about this command. 

For now, try this quickfix:
```
\mode<presentation>
{
  \renewcommand<>{\emph}{\only#1{\beameroriginal\emph}}
}
```

**Comment by samcarter** [comment]
This is the same difference as

```
% !TeX TS-program = lualatex

\documentclass{beamer}

\usepackage{fontspec}


\begin{document}
\begin{frame}

{\itshape I have a great professor}!

\textit{I have a great professor}!
\end{frame}
\end{document}

```

**Comment by samcarter** [comment]
If you want to use `\textit` for `\emph`:

```
% !TeX TS-program = lualatex

\documentclass{beamer}

\usepackage{fontspec}

\renewcommand<>{\emph}{\only#1{\beameroriginal{\textit}}}

\begin{document}
\begin{frame}

{\itshape I have a great professor}!

\textit{I have a great professor}!

\emph{I have a great professor}!
\end{frame}
\end{document}
```

**Comment by ghost** [comment]
@samcarter Thanks for your reply! I am surprised that \emph is not defined this way by default.
Also, what is the purpose of "\only" here? From what I understand it is supposed to show certain text only on certain slides,
but discard its argument on any other circumstance.

**Comment by samcarter** [comment]
> Also, what is the purpose of "\only" here?

@bob-marcus  The purpose of only in the definition is that you can do things like `\emph<2->{test}` that will highlight something on specific overlays. You can think of it as more or less `\only<2->{\textit}{test}`, so on the second overlay you get `\textit{test}`, while on the first overlay it is only `{test}`.

**Comment by samcarter** [comment]
> I am surprised that \emph is not defined this way by default.

The advantage of using `\itshape` for emph is that you can do things like 

```
\documentclass{beamer}

\begin{document}
	
\begin{frame}
\emph{
test

test}
\end{frame}	
	
\end{document}
```

**Comment by davidcarlisle** [comment]
you could say the same about `\emph` in the definition in the format but `\emph` was intentionally not defined `\long` and was designed to apply italic correction at whichever end is needed. I would say beamer is wrong here.   as in normal latex you can use

```
{\em
test

test}
```

for the multi-paragraph form.

**Comment by samcarter** [comment]
> beamer is wrong here

Probably, but I think it is a bit late in the game to change that. This could break a lot of existing presentations.

**Comment by josephwright** [comment]
On that basis, I'm going to WONTFIX: it's one of the oddities we are likely stuck with.
