### ISSUE TITLE
Biblatex style=authoryear changes indentation in list environments

### ISSUE THREAD

**Issue by ferdinand-fichtner** [josephwright/beamer#625]
Hi all,

when using biblatex in beamer with the bibliography-style authoryear, the margins in list environments (including e.g. itemize or enumerate environments outside the bibliography) are changed such that the text in the first and the following lines does not start in the same position. This only happens with beamer, not e.g. in an article class. It does not happen with other bibliography-styles (except the ones that are based on authoryear).

This is a new behaviour and seems to be related to a recent update of beamer. Or this is what I am guessing, since the biblatex style file authoryear.bbx has not been changed recently.

The following MWE shows the erroneous behaviour:

```
\documentclass{beamer}
\usepackage[style=authoryear]{biblatex}

\begin{document}
\begin{frame}{Test}
\begin{itemize}
    \item An itemize item with a very long text that breaks in the next line
\end{itemize}
\end{frame}
\end{document} 
```
Changing the bibliography style to standard (or omitting it in the biblatex package options) solves the problem with the uneven list indentation.

Any advise would be appreciated. If I should get in touch with the biblatex team please let me know.

Best 
Ferdinand

**Comment by samcarter** [comment]
The recent change in beamer was meant to fix an alignment problem with biblatex bibliographies, see e.g. https://github.com/josephwright/beamer/issues/531 or  https://github.com/josephwright/beamer/issues/581 for more information about this. Changing the indention of normal lists was not really intended, I'll have a look into this.

For now a workaround:

```
\documentclass{beamer}
\usepackage[style=authoryear]{biblatex}

\setlength  \labelwidth{\leftmargini}
\addtolength\labelwidth{-\labelsep}

\begin{document}
\begin{frame}{Test}
\begin{itemize}
    \item An itemize item with a very long text that breaks in the next line
\end{itemize}
\end{frame}
\end{document} 
```

**Comment by samcarter** [comment]
... maybe I could just delay the changes to `\printbibliography` ...

https://github.com/samcarter/beamer/blob/c893c5338728be38ae84041f03a3a46132a71959/base/beamerbaselocalstructure.sty#L504-L513

... but this makes it more complicate for users to change the indention in the bibliography ....

**Comment by ferdinand-fichtner** [comment]
Thank you for taking care of this and wor the workaround!
Best, Ferdinand

**Comment by samcarter** [comment]
@josephwright  Would it be possible to make a new beamer release? My bug is still causing problems, e.g. https://tex.stackexchange.com/a/572426/36296

**Comment by josephwright** [comment]
@samcarter  Sure: today or tomorrow, depending on other commitments
