### ISSUE TITLE
Links in pdf

### ISSUE THREAD

**Issue by DanielRuf** [josephwright/beamer#627]
It seems a few links in the generated pdf are split or weird.

<img width="155" alt="Bildschirmfoto 2020-09-27 um 14 06 22" src="https://user-images.githubusercontent.com/827205/94364590-baa98e00-00ca-11eb-81df-19645c2b085f.png">

<img width="123" alt="Bildschirmfoto 2020-09-27 um 14 08 49" src="https://user-images.githubusercontent.com/827205/94364620-02c8b080-00cb-11eb-8bc5-315c30df7034.png">

Both links show to the current slide. The arrows next to them are correctly linked. But it looks like the links bteween the arrows are split into two links with the same target.

This is from the https://github.com/josephwright/beamer/blob/master/doc/solutions/conference-talks/conference-ornate-20min.de.tex file.

**Comment by DanielRuf** [comment]
<img width="62" alt="Bildschirmfoto 2020-09-27 um 14 12 18" src="https://user-images.githubusercontent.com/827205/94364678-7d91cb80-00cb-11eb-96b7-4a1f1b4c11b9.png">

This one jumps to the title page / first page. But there is no icon.

**Comment by samcarter** [comment]
Which engine do you use for compilation?

**Comment by DanielRuf** [comment]
I'm not sure if this is the right information.
I use MacTex with the whole TeXLive distribution afaik and use `latexmk -pdf ...` as command on MacOS 10.15 (Catalina).

**Comment by DanielRuf** [comment]
I'm not sure if this is the right information.
I use MacTeX with the whole TeXLive distribution afaik and use `latexmk -pdf ...` as command on MacOS 10.15 (Catalina).

**Comment by samcarter** [comment]
Can you show the first line of your log file?

**Comment by DanielRuf** [comment]
```
Latexmk: applying rule 'pdflatex'...
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./presentation.tex
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-03-06>
(/usr/local/texlive/2020/texmf-dist/tex/latex/beamer/beamer.cls
Document Class: beamer 2019/09/29 v3.57 A class for typesetting presentations

...
```

**Comment by samcarter** [comment]
*(Sorry, I somehow missed your reply)*

Ok, I also use pdflatex, but can't reproduce this. Maybe a viewer issue?

**Comment by DanielRuf** [comment]
If it is relevant, I have used the Preview app / native file viewer on macOS Catalina.
Edit: I mixed something, the yellow markers are only visible in Firefox.

**Comment by samcarter** [comment]
I'm also using preview, just on an older OSX

**Comment by DanielRuf** [comment]
Ah, sorry the yellow markers are from the PDF viewer in Firefox on macOS which makes the issue visible. It is not visible in the native Preview app on macOS but if you move the cursor over the icons you can see the tooltips which show the same.

I have used `latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode test.tex`. The resulting files are in the zip file, including auxiliary files.

[Archiv.zip](https://github.com/josephwright/beamer/files/5410100/Archiv.zip)

**Comment by josephwright** [comment]
This looks like a viewer issue, sorry.

**Comment by DanielRuf** [comment]
I'm not really sure if Firefox uses the same PDF engine because it uses its own (pdf.js) in the browser.

https://github.com/josephwright/beamer/issues/627#issuecomment-712982508

So to me it does not look like a viewer issue. If it is, then pdf.js and MacOS preview have the same bug.
