### ISSUE TITLE
Keep default bullet size consistent when using unicode-math

### ISSUE THREAD

**Issue by ghost** [josephwright/beamer#628]
When using the `unicode-math` package, default bullets might become too big relative to the text.
I imagine this happens because when you use opentype math fonts,
they define their own `\blacktriangleright`, while type-1 fonts do not.
Here is a quick workaround, based on how `beamer` defines bullets by default:
```
\setbeamertemplate{itemize item}{\raise1.25pt\hbox{\scalebox{0.5}{$\blacktriangleright$}}}
```
I am not completely satisfied with it because the `\raise` value must be adjusted for each font,
and I am not sure that this is the right way to do it.
Is there a way to keep the bullet size the same, no matter which font is chosen?

Here is an mwe, if it helps
```
% !TeX TS-program = lualatex
\documentclass{beamer}
\usepackage{unicode-math}
% Try compiling with the two lines below either commented or uncommented to see the difference
\setmathfont{XITS Math}
%\setbeamertemplate{itemize item}{\raise2pt\hbox{\scalebox{0.5}{$\blacktriangleright$}}}            
\begin{document}
\frame{
\begin{itemize}
  \item I like
  \item this itemized
  \item environment
\end{itemize}}
\end{document}
```
Environment: TeXLive 2020 updated on october 1,
running on Windows 10 Pro 1909 64-bit.

**Comment by samcarter** [comment]
In this particular case, you could keep the original computer modern font for the triangle

```
% !TeX TS-program = lualatex
\documentclass{beamer}
\usepackage{unicode-math}
% Try compiling with the two lines below either commented or uncommented to see the difference
\setmathfont{XITS Math}

\setbeamertemplate{itemize item}{{\fontfamily{cmss}\selectfont\raise2pt\hbox{\scalebox{0.5}{$\blacktriangleright$}}}}        
    
\begin{document}
\begin{frame}
\begin{itemize}
  \item I like
  \item this itemized
  \item environment
\end{itemize}
\end{frame}
\end{document}
```

... but with many fonts this won't necessarily give a nice result as they might have different xheights and their own 
triangles might be a better fit

**Comment by ghost** [comment]
**edit**: @samcarter Thanks! By using `\smallblacktriangleright` instead of `\blacktriangleright`, the bullet shrinks to a more reasonable size,
though I am afraid that this solution would only work with fonts that have such glyph.
The solution would look like this:
```
\setbeamertemplate{itemize item}{\raise1.25pt\hbox{$\smallblacktriangleright$}}
\setbeamertemplate{itemize subitem}{\raise1.5pt\hbox{$\smallblacktriangleright$}}
\setbeamertemplate{itemize subsubitem}{\raise1.5pt\hbox{$\smallblacktriangleright$}}

```

**Comment by mdeff** [comment]
The simplest (and best IMO) is to use symbols from the text font (which will match the text in size, style, and position as intended by the font designer) instead of the math font:
```tex
\setbeamertemplate{itemize item}{\blacktriangleright}
\setbeamertemplate{itemize subitem}{\blacktriangleright}
\setbeamertemplate{itemize subsubitem}{\blacktriangleright}
```

Or directly in Unicode:
```tex
\setbeamertemplate{itemize item}{▶}
\setbeamertemplate{itemize subitem}{▶}
\setbeamertemplate{itemize subsubitem}{▶}
```
