### ISSUE TITLE
Problem with `\mathbf`

### ISSUE THREAD

**Issue by samcarter** [josephwright/beamer#630]
As [reported by @Rmano ](https://chat.stackexchange.com/transcript/41?m=55695630#55695630), the following MWE does not give bold font with texlive2020

```
\documentclass{beamer}
\begin{document}
\begin{frame}
$\mathbf{R}\not=R$
\end{frame}
\end{document}
```

### Possible workaround 1

Declaring a font substitution (code by @u-fischer https://chat.stackexchange.com/transcript/41?m=55695847#55695847)

```
\documentclass{beamer}
\DeclareFontShape{OT1}{cmss}{b}{n}{<->ssub * cmss/bx/n}{}
\begin{document}
\begin{frame}
$\mathbf{R}\not=R$
\end{frame}
\end{document}
```

Advantages/disadvantages: ???

### Possible workaround 2

Using `\bfseries@sf` instead of `\bfdefault`

Code in this branch: https://github.com/samcarter/beamer/tree/bold

Disadvantages:

- according to @u-fischer this substitution does not make sense in `\DeclareMathAlphabet{\mathbf}`, but without I don't get bold font
- @josephwright:  "Sounds like a possible, but risky - we'd likely break documents "

**Comment by samcarter** [comment]
@all So, what to do to solve this problem?

**Comment by josephwright** [comment]
I think Ulrike's suggestion is the way to go

**Comment by samcarter** [comment]
OK, I'll add `\DeclareFontShape{OT1}{cmss}{b}{n}{<->ssub * cmss/bx/n}{}` then
