### ISSUE TITLE
Crash if `\end{frame}` of a fragile frame has a non-space trailing character

### ISSUE THREAD

**Issue by e-kwsm** [josephwright/beamer#636]
MWE:
```tex
\documentclass{beamer}
\begin{document}
\begin{frame}[fragile]
\end{frame} %
\end{document}
%\end{frame} \end{document}  % this also causes error
```

```shellsession
$ pdflatex mwe.tex
…
(/opt/texlive/2020/texmf-dist/tex/latex/translator/translator-theorem-dictionar
y-English.dict)
No file mwe.nav.
)
Runaway argument?
! File ended while scanning use of \next.
<inserted text> 
                \par 
<*> mwe.tex
           
? 
```

- beamer 2020/07/22 v3.59
- pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020) 
- XeTeX 3.14159265-2.6-0.999992 (TeX Live 2020)
- LuaHBTeX Version 1.12.0 (TeX Live 2020)

**Comment by samcarter** [comment]
For fragile frames `\end{frame}` must stand alone, that's by design

To quote the beamer user guide:

> To determine the end of the frame, the following rule is used: The first occurrence of a single line containing **exactly** `\end{⟨frame environment name⟩}` ends the frame. The `⟨environment name⟩` is normally frame, but it can be changed using the environment option. This special rule is needed since the frame contents is, after all, not interpreted when it is gathered.

(emphasis mine)

**Comment by e-kwsm** [comment]
Thanks, I didn't notice it.
