### ISSUE TITLE
transparency is additive when used in nested environments

### ISSUE THREAD

**Issue by ilia-kats** [josephwright/beamer#637]
Consider this minimal example:
```
\documentclass{beamer}
\usepackage{lipsum}
\usecolortheme{seagull}
\setbeamercovered{transparent}

\begin{document}
\begin{frame}
    \lipsum[1][1]
    \pause
    \begin{theorem}
        \begin{itemize}
            \item \lipsum[1][2]
            \pause
            \item \lipsum[1][3]
        \end{itemize}
    \end{theorem}
\end{frame}
\end{document}
```
The first slide of this looks like this:
![test1](https://user-images.githubusercontent.com/3499574/97094564-0b72bf00-1656-11eb-8d55-286c299fca3a.png)
You will notice that the first item appears more transparent than the second.

I have tried different permutations of the overlay specification, but none gave the desired result:
```
\begin{frame}
    \lipsum[1][1]
    \begin{theorem}<2->
        \begin{itemize}
            \item \lipsum[1][2]
            \item<3-> \lipsum[1][3]
        \end{itemize}
    \end{theorem}
\end{frame}
```
results in
![test2](https://user-images.githubusercontent.com/3499574/97094590-5391e180-1656-11eb-8375-00ae18293476.png)
and
```
\begin{frame}
    \lipsum[1][1]
    \begin{theorem}<2->
        \begin{itemize}
            \item<2-> \lipsum[1][2]
            \item<3-> \lipsum[1][3]
        \end{itemize}
    \end{theorem}
\end{frame}
```
gives
![test3](https://user-images.githubusercontent.com/3499574/97094607-7a501800-1656-11eb-863d-f8f3de0d3351.png)

**Comment by samcarter** [comment]
Personally I would go with your 3rd solution, but if you want to avoid the double transparency, you could show the items on the first overlay like this: 

```
\documentclass{beamer}
\usepackage{lipsum}
\usecolortheme{seagull}
\setbeamercovered{transparent}

\begin{document}
\begin{frame}
    \lipsum[1][1]
    \pause
    \begin{theorem}
        \begin{itemize}[<1,+->]
            \item \lipsum[1][2]
            \item \lipsum[1][3]
        \end{itemize}
    \end{theorem}
\end{frame}
\end{document}
```

![Screen Shot 2020-10-25 at 13 48 43](https://user-images.githubusercontent.com/43832342/97107636-dce1fc00-16c8-11eb-801c-4593ba51dfa0.png)

**Comment by ilia-kats** [comment]
this works, thanks

**Comment by samcarter** [comment]
@ilia-kats  You're welcome!
