### ISSUE TITLE
Add tableofcontents styles that display frame numbers

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#64]
Originally reported by: **Nicolas M. Thiéry (Bitbucket: [nthiery](https://bitbucket.org/nthiery), GitHub: [nthiery](https://github.com/nthiery))**

----------------------------------------

Add tableofcontents styles that display frame numbers:

    
    A. Généralités . . . . . . . . . . . . . . . . . . . . . . . . .  4
    B. Produit Cartésien . . . . . . . . . . . . . . . . . . . . . .  7
    C. Parties d'un ensemble . . . . . . . . . . . . . . . . . . . .  9
    

For the moment, I hacked this for sections in my lecture notes by changing a bit `\beamer@sectionintoc` to record the frame number in a new macro
`\inserttocsectionstartpage{#3}` (see below).

    
    \def\beamer@sectionintoc#1#2#3#4#5{%
      \ifnum\c@tocdepth>0%
      \ifnum#4=\beamer@showpartnumber%
      {
      \beamer@saveanother%
      \gdef\beamer@todo{}%
      \beamer@slideinframe=#1\relax%
      \expandafter\only\beamer@tocsections{\gdef\beamer@todo{%
          \beamer@tempcount=#5\relax%
          \advance\beamer@tempcount by\beamer@sectionadjust%
          \edef\inserttocsectionnumber{\@Alph\beamer@tempcount}%
          \def\inserttocsection{\hyperlink{Navigation#3}{#2}}%
          % New macro defined here!!!
          \def\inserttocsectionstartpage{#3}%
          \beamer@tocifnothide{\ifnum\c@section=#1\beamer@toc@cs\else\beamer@toc@os\fi}%
          {
            \ifbeamer@pausesections\pause\fi%
            \ifx\beamer@toc@ooss\beamer@hidetext
              \vskip1.5em
            \else
              \vfill
            \fi
            {%
              \hbox{\vbox{%
                  \def\beamer@breakhere{\\}%
                  \beamer@tocact{\ifnum\c@section=#1\beamer@toc@cs\else\beamer@toc@os\fi}{section in toc}}}%
             \par%
            }%
          }%
        }
      }%
      \beamer@restoreanother%
      }
      \beamer@todo%
      \fi\fi%
    }
    
    \setbeamertemplate{section in toc}
    {\leavevmode\inserttocsectionnumber. \inserttocsection \ \dotfill \ \inserttocsectionstartpage \par}
    

----------------------------------------
- Bitbucket: https://bitbucket.org/rivanvx/beamer/issue/64

**Comment by josephwright** [comment]
*Original comment by* **Vedran Miletić (Bitbucket: [rivanvx](https://bitbucket.org/rivanvx), GitHub: Unknown)**:

----------------------------------------

Sorry for not replying earlier. Thanks for the code, I will look into it.

**Comment by tntduong88** [comment]
Hi Joseph, I thank you for sharing your code. But your code only displays frame numbers for sections not for subsections and subsubsections. How can one do the same thing up to subsubsections? Thanks.

**Comment by josephwright** [comment]
Subsubsections are only partially supported by `beamer`: they are far too 'detailed' for a presentation in almost all cases.

**Comment by samcarter** [comment]
@tntduong88  You can find something for subsections here: https://tex.stackexchange.com/a/66230/36296

**Comment by tntduong88** [comment]
> @tntduong88 You can find something for subsections here: https://tex.stackexchange.com/a/66230/36296

Thanks. I knew this post. I don't know that whether or not it is possible to modify that code for subsubsections.

**Comment by tntduong88** [comment]
Hi all, Jasper Habicht gave the answer here (https://tex.stackexchange.com/questions/625573/beamer-tableofcontents-with-page-numbers-up-to-subsubsections). Thanks.
