### ISSUE TITLE
Problems after updating with the old presentations

### ISSUE THREAD

**Issue by nik0380** [josephwright/beamer#642]
Hi all,

I updated packages at November 2020. Recently created presentations to generate with design errors now. Similar problems are observed in MikTex and TexLive.

1. Missing markers in lists (itemize, enumerate and table of contents). Example  for the table of contents view:
![изображение](https://user-images.githubusercontent.com/63895207/99660137-01848600-2a73-11eb-9c01-25a4375af55e.png)

2. A white rectangle is displayed between the blocks on the right side (see fig.).
![изображение](https://user-images.githubusercontent.com/63895207/99660396-5e803c00-2a73-11eb-9dd3-505c48731f34.png)

I use xelatex on Windows 7 (TexLive, MikTex). Default language is Russian, additional -- English.

I have been working with Beamer and Xelatex for several years and there were no such problems before. How do I fix this?

Best wishes,
 Nikolay.

**Comment by josephwright** [comment]
This could be the `pgf` fix, but without a MWE it's hard to say.

**Comment by samcarter** [comment]
@nik0380 Can you check if the problem still occurs with the tikz development version from https://github.com/pgf-tikz/pgf ?

**Comment by nik0380** [comment]
Thank you very much! I have not yet understood how to install the version of TIKZ/PGF Development on Windows. But I shell be try!

My style file (posterex.sty):
----------------------------------------------------------------------------------------------------------------------------

```
\ProvidesPackage{posterex}

\RequirePackage[utf8]{inputenc}

\RequirePackage{lmodern}
%\RequirePackage[russian,english]{babel}

\RequirePackage{xltxtra}
\RequirePackage{polyglossia}
\setdefaultlanguage[spelling=modern]{russian}
\setotherlanguage{english}
\defaultfontfeatures{Ligatures=TeX,Mapping=tex-text}

\setmainfont{Times New Roman}
\setromanfont{Times New Roman} 
\setsansfont{Liberation Sans} 
\setmonofont{Consolas}

\newfontfamily{\cyrillicfont}{Times New Roman} %Times New Roman
\newfontfamily{\cyrillicfontrm}{Times New Roman}
\newfontfamily{\cyrillicfonttt}{Consolas}
\newfontfamily{\cyrillicfontsf}{Liberation Sans}

\newfontfamily{\englishfont}{Times New Roman} 
\newfontfamily{\englishfontrm}{Times New Roman}
\newfontfamily{\englishfonttt}{Consolas}
\newfontfamily{\englishfontsf}{Liberation Sans}

\renewfontfamily{\sf}{DejaVuSansMono}
\newfontfamily{\defaultfonttt}{Consolas}
\newfontfamily{\defaultfontsf}{Liberation Sans}
\renewfontfamily{\tt}{Consolas}

\selectlanguage[spelling=modern]{russian}


% Стиль презентации
\usetheme{Madrid}

% цветовая схема
\usecolortheme{seahorse}
\usefonttheme[onlymath]{serif}
\setbeamertemplate{caption}[numbered]
\useinnertheme{circles} % Удалить когда заработает Beamer

%Выравнивание
\usepackage{ragged2e}

\usetheme{Madrid}

\RequirePackage{amsmath}
\RequirePackage{amssymb}
\RequirePackage{bm}
\RequirePackage{mathtools}
\RequirePackage{amsfonts}
\RequirePackage{textcomp}
\RequirePackage{latexsym}
\RequirePackage{mathptm}
\RequirePackage{graphicx}
\RequirePackage{verbatim}

\RequirePackage{xcolor,colortbl}

\RequirePackage{tabularx, array, longtable}

%Выравнивание
\RequirePackage{ragged2e}
\renewcommand{\raggedright}{\leftskip=0pt \rightskip=0pt plus 0cm}

\RequirePackage{tikz}
\RequirePackage{tkz-euclide}
\usetikzlibrary{shapes, arrows, patterns, calc, positioning, intersections, angles, quotes, babel, decorations.pathreplacing}
\tikzset{>=stealth}

\usepgflibrary {fpu}

\RequirePackage{tkz-euclide}
\RequirePackage{tikz-3dplot}

\RequirePackage[version=4]{mhchem}
\RequirePackage{chemfig}

\RequirePackage{animate}

\RequirePackage{pgfplots}


\pgfplotsset{compat=newest}


%----------------------------------------------------------------------
%\makeatletter
%\newcommand{\gettikzxy}[3]{%
%	\tikz@scan@one@point\pgfutil@firstofone#1\relax
%	\edef#2{\the\pgf@x}%
%	\edef#3{\the\pgf@y}%
%}
%\makeatother
%----------------------------------------------------------------------

\RequirePackage{cancel}
\RequirePackage{ifthen}


%-----------------------------------------------------------------------
```

**Comment by nik0380** [comment]
Thank you so much! 

After installing TIKZ/PGF Development, the problem was solved!

**Comment by samcarter** [comment]
@nik0380 Great to hear!

some tiny comments about your code:

- You don't need

    ```
    \RequirePackage{amsmath}
    \RequirePackage{amssymb}
    \RequirePackage{amsfonts}
    \RequirePackage{graphicx}
    \RequirePackage{xcolor}
    ```
    beamer already loads them for you

- `\RequirePackage[utf8]{inputenc}` is no longer required, this is now included in the kernel

- loading `\usetheme{Madrid}` once is enough

- instead of loading the `colortbl` package, better do `\documentclass[xcolor={table}]{beamer}` to avoid problems with option clashes
