### ISSUE TITLE
tikz format key breaks shading of beamer blocks

### ISSUE THREAD

**Issue by clecap** [josephwright/beamer#643]
Setting the tikz trig format key to rad breaks the shades of beamer blocks.

```
\documentclass{beamer}
\usepackage{tikz}
\tikzset{trig format=rad}% Comment this line to see difference
\useinnertheme[shadow=true]{rounded}
\begin{document}
\begin{frame}
\begin{block}{Titel}Body\end{block}
\end{frame}
\end{document}
```

[latex-test.pdf](https://github.com/josephwright/beamer/files/5568031/latex-test.pdf)

**Comment by josephwright** [comment]
I'm not sure that's exactly a surprise

**Comment by samcarter** [comment]
If you have the tikz development version, you can use this branch https://github.com/samcarter/beamer/tree/resuscitating_transparent_shadows

![Screen Shot 2020-11-19 at 17 13 18](https://user-images.githubusercontent.com/43832342/99692406-95ae1780-2a8a-11eb-9363-5242ead51bc2.png)

**Comment by clecap** [comment]
@josephwright: I'm sure that is a bug. (At least from the perspective of the end user). I just don't know where the correct place is to fix that. Either in beamer or in tikz.

Workaround currently is to set trig format to deg before the blocks and resetting it afterwards. So a modification in beamer would work. But since I do not know whether it is rather a tikz issue I won't make a PR.

@samcarter Thanx. Don't want to mess with tikz too much, not too familiar with it. Looking forward to a fix. Until then I am patching beamer in my preamble.

**Comment by samcarter** [comment]
Quote from the tikz documentation:

> Warning: At the time of this writing, this feature is “experimental”. Please handle it with care: there may be path instructions or libraries in pgf which rely on trig format=deg. The intended usage of trig format=rad is for local scopes – and as option for data visualization.

Breaking things like pgf shadows is expected if you use this globally
