### ISSUE TITLE
Strange rule and box artifact/not nice shadow

### ISSUE THREAD

**Issue by dbitouze** [josephwright/beamer#647]
Good news transparent shadows were re-introduced (#492) with `beamer` 2020/11/26 v3.60!

But still strange phenomenons:

- [x]  If non-empty title block, slim horizontal rule (but nice shadow):
```latex
\documentclass{beamer}
\setbeamertemplate{blocks}[rounded][shadow=true]
\setbeamercolor{background canvas}{bg=red!50}
\begin{document}
\begin{frame}
  \begin{block}{Foo}
    Bar
  \end{block}
\end{frame}
\end{document}
```
![image](https://user-images.githubusercontent.com/1032633/102222864-47066880-3ee4-11eb-86e3-a66f30c06c6a.png)
- [x]  If empty title block, box artifact/not nice shadow:
```latex
\documentclass{beamer}
\setbeamertemplate{blocks}[rounded][shadow=true]
\setbeamercolor{background canvas}{bg=red!50}
\begin{document}
\begin{frame}
  \begin{block}{}
    Bar
  \end{block}
\end{frame}
\end{document}
```
![image](https://user-images.githubusercontent.com/1032633/102223269-c3994700-3ee4-11eb-8075-353eb499751f.png)
- [x]  If empty title block and `kpfonts` loaded, even worse box artifact/shadow:
```latex
\documentclass{beamer}
\setbeamertemplate{blocks}[rounded][shadow=true]
\setbeamercolor{background canvas}{bg=red!50}
\usepackage{kpfonts}
\begin{document}
\begin{frame}
  \begin{block}{}
    Bar
  \end{block}
\end{frame}
\end{document}
```
![image](https://user-images.githubusercontent.com/1032633/102223574-30acdc80-3ee5-11eb-80df-526fc33bb75d.png)
- [x]  If non-empty title block and `kpfonts` loaded, slim horizontal rule and even worse box artifact/shadow:
```latex
\documentclass{beamer}
\setbeamertemplate{blocks}[rounded][shadow=true]
\setbeamercolor{background canvas}{bg=red!50}
\usepackage{kpfonts}
\begin{document}
\begin{frame}
  \begin{block}{Foo}
    Bar
  \end{block}
\end{frame}
\end{document}
```
![image](https://user-images.githubusercontent.com/1032633/102223928-9bf6ae80-3ee5-11eb-8faa-e263e47fae06.png)

**Comment by samcarter** [comment]
> If non-empty title block, slim horizontal rule (but nice shadow)

I can't reproduce this with preview or adobe. I think this an viewer issue with poppler based viewers

> If empty title block, box artifact/not nice shadow

> If empty title block and kpfonts loaded, even worse box artifact/shadow

I can reproduce - will investigate

**Comment by dbitouze** [comment]
> > If non-empty title block, slim horizontal rule (but nice shadow)
> 
> I can't reproduce this with preview or adobe. I think this an viewer issue

I can notice it with Okular at 1600% (not with Evince, limited to 800%).

**Comment by samcarter** [comment]
> If empty title block, box artifact/not nice shadow:

This might be a result of the clipping the shadow has to go through, need to investigate this further

**Comment by samcarter** [comment]
MWE for the kpfonts issue:

```
\documentclass{beamer}

\renewcommand{\sfdefault}{jkpss}
\setbeamertemplate{blocks}[rounded][shadow=true]
\setbeamercolor{background canvas}{bg=red!50}

\begin{document}
\begin{frame}
  \begin{block}{Foo}
    Bar
  \end{block}
\end{frame}
\end{document}
```

**Comment by Tikrass** [comment]
This issue gets even worse, when you change the color black to a dark gray.
```
\documentclass{beamer}

\definecolor{black}{RGB}{30,30,30}
\setbeamertemplate{blocks}[rounded][shadow=true]
\begin{document}
\begin{frame}
    \begin{block}{Example}
    \end{block}
\end{frame}
\end{document}
```
![artifacts](https://user-images.githubusercontent.com/641293/106717756-6aa28100-6600-11eb-971a-acbc0f8b0ff4.png)

**Comment by samcarter** [comment]
@Tikrass Can you please open a new issue?

**Comment by u-fischer** [comment]
@Tikrass transparency in fadings and shadings use the black color, if you set it to gray you are disabling this, see for example 115.3 Specifying a Fading in the pgf documentation.

**Comment by rachitdeshpande** [comment]
@samcarter  Thank you kindly.
I did some testing and found the following:

```

 % !TeX program = lualatex
 \documentclass{beamer}
 \setbeamertemplate{blocks}[rounded][shadow=true]
 \setbeamercolor{background canvas}{bg=red!50}
 \usepackage{fontspec}
 \setmainfont{Cambria}
 \setmonofont{Times New Roman}
 \begin{document}
   \begin{frame}
      \begin{block}{\rmfamily Foo}
         \ttfamily Bar
      \end{block}
   \end{frame}
\end{document}


```
Result:
![snap1_1](https://user-images.githubusercontent.com/17661599/122629005-61114580-d0d7-11eb-9ca0-ddc450890659.jpg)
![snap1](https://user-images.githubusercontent.com/17661599/122628374-548aee00-d0d3-11eb-8439-2bb6db530ed6.jpg)
But now if I add `\setsansfont{}` anywhere before the box then

```
 !TeX program = lualatex
 \documentclass{beamer}
 \setbeamertemplate{blocks}[rounded][shadow=true]
 \setbeamercolor{background canvas}{bg=red!50}
 \usepackage{fontspec}
 \setmainfont{Cambria}
 \setmonofont{Times New Roman}
 \setsansfont{Calibri}
 \begin{document}
    \begin{frame}
      \begin{block}{\rmfamily Foo}
         \ttfamily Bar
      \end{block}
   \end{frame}
\end{document}
```
Result:
![snap2_2](https://user-images.githubusercontent.com/17661599/122629027-9158e400-d0d7-11eb-8f17-842f287fd870.jpg)
![snap2](https://user-images.githubusercontent.com/17661599/122628626-c879c600-d0d4-11eb-82e4-7dcdbc578c9b.jpg)
To add more clarity here is another example

```
 % !TeX program = lualatex
 \documentclass{beamer}
 \setbeamertemplate{blocks}[rounded][shadow=true]
 \setbeamercolor{background canvas}{bg=red!50}
 \usepackage{fontspec}
 \setmainfont{Cambria}
 \setmonofont{Times New Roman}
 \begin{document}
   \begin{frame}
	\begin{block}{\rmfamily Foo}
	   \ttfamily Bar
	\end{block}
 	\setsansfont{Calibri}
 	\begin{block}{\rmfamily Foo}
   	   \ttfamily Bar
 	\end{block}
    \end{frame}
 \end{document}
```
Result:
![snap3_3](https://user-images.githubusercontent.com/17661599/122629053-ca915400-d0d7-11eb-9f9c-3ebb6317e29c.jpg)
![snap3](https://user-images.githubusercontent.com/17661599/122628668-0d056180-d0d5-11eb-8d3a-329f81156c31.jpg)
What I conclude is, 

> If the scope of a new font is the entire box and not just the text inside, then the shadow is strange but if the scope is just the text inside the box then there is no issue. 

It seems that declaring `\setsansfont{}` before the box changes font and spacing of all elements and thus results in weird shadow.
But if it is declared inside the box then there seems to be no issue

```
% !TeX program = lualatex
\documentclass{beamer}
\setbeamertemplate{blocks}[rounded][shadow=true]
\setbeamercolor{background canvas}{bg=red!50}
\usepackage{fontspec}
\setmainfont{Cambria}
\setmonofont{Times New Roman}
\begin{document}
   \begin{frame}
      \begin{block}{\rmfamily Foo}
         \ttfamily Bar
      \end{block}	
      \begin{block}{\rmfamily Foo}
         \setsansfont{Calibri} Bar
      \end{block}
      \begin{block}{\rmfamily Foo}
         Bar
      \end{block}
   \end{frame}
\end{document}
```
Result:
![snap4_4](https://user-images.githubusercontent.com/17661599/122628962-12fc4200-d0d7-11eb-9960-74ea62a6ee3c.jpg)
![snap4](https://user-images.githubusercontent.com/17661599/122629081-f4e31180-d0d7-11eb-9557-98ab8b417079.jpg)
If anyone is using multiple fonts then this is a small _workaorund_ to the problem but if someone just wants to change the font of the entire document (which contains boxes) then it becomes very tedious.

**Comment by samcarter** [comment]
@rachit2606 Thanks for your investigation! 

You could apply the following workaround:

```
% !TeX TS-program = lualatex

\documentclass{beamer}

\usetheme{warsaw}
\title{title}

\usepackage{fontspec}
\setmainfont{Times New Roman}
\setsansfont{Times New Roman}

\makeatletter
\def\endbeamerboxesrounded{%
  \end{minipage}\egroup%
  \bmb@temp=\dp\bmb@box%
  \advance\bmb@temp by.5pt%
  \setbox\bmb@box=\hbox{\raise\bmb@temp\hbox{\box\bmb@box}}%
  \dp\bmb@box=0pt%
  \bmb@boxwidth=\bmb@width%
  \bmb@boxheight=\ht\bmb@box%
  \advance\bmb@boxheight by4bp%
  \advance\bmb@boxheight by\bmb@prevheight%
  \ifbmb@shadow%
    \xdef\beamer@storecolorhook{\beamer@colorhook}
    \xdef\beamer@colorhook{}
    \pgfdeclareradialshading{bmb@shadowball}{\pgfpointorigin}
    {%
      color(0bp)=(pgftransparent!50);
      color(4bp)=(pgftransparent!100)
    }%
    \pgfdeclareradialshading{bmb@shadowballlarge}{\pgfpointorigin}
    {%
      color(0bp)=(pgftransparent!0);
      color(8bp)=(pgftransparent!100)
    }%
    \pgfdeclarehorizontalshading{bmb@shadowhorz\the\bmb@boxheight}{\bmb@boxheight-6bp}
    {%
      color(0bp)=(pgftransparent!0);
      color(8bp)=(pgftransparent!100)
    }%
    \pgfdeclareverticalshading{bmb@shadowvert\the\bmb@boxwidth}{\bmb@boxwidth-4bp}
    {%
      color(0bp)=(pgftransparent!100);
      color(8bp)=(pgftransparent!0)
    }%
    \pgfdeclarefading{bmb@shadowmask\the\bmb@boxwidth\the\bmb@boxheight}
    {%
      \begin{pgfpicture}
        \pgftext[at=\pgfpoint{4bp}{4bp}]{\pgfuseshading{bmb@shadowball}}
        \pgftext[at=\pgfpoint{\bmb@boxwidth}{8bp}]{\pgfuseshading{bmb@shadowballlarge}}
        \pgftext[at=\pgfpoint{\bmb@boxwidth+4bp}{\bmb@boxheight+2bp}]{\pgfuseshading{bmb@shadowball}}
        \pgftext[left, at=\pgfpoint{4bp}{4bp}]{\pgfuseshading{bmb@shadowvert\the\bmb@boxwidth}}
        \pgftext[base, at=\pgfpoint{\bmb@boxwidth+4bp}{8bp}]{\pgfuseshading{bmb@shadowhorz\the\bmb@boxheight}}
        %
        % clipping is needed because shadow is typeset on top of box
        \begin{pgfscope}
          \pgfsetcolor{black}
          \pgfpathrectangle{\pgfpoint{4bp}{8bp}}{\pgfpoint{\bmb@boxwidth-0.2bp}{\bmb@boxheight-2bp}}
          \pgfusepath{fill}
        \end{pgfscope}
      \end{pgfpicture}%
      \hskip4bp%      
    }%
  \fi%
  \bmb@temp=\bmb@width%
  \bmb@dima=\bmb@temp\advance\bmb@dima by2.2bp%
  \bmb@dimb=\bmb@temp\advance\bmb@dimb by4bp%
  \hbox{%
    \begin{pgfpicture}{0bp}{0bp}{0bp}{0bp}
      \ifbmb@shadow%
        \begin{pgfscope}
          \pgfpathrectangle{\pgfpoint{0bp}{-7bp}}
            {\pgfpoint{\bmb@boxwidth+8bp}{\bmb@boxheight+6bp}}
          \pgfsetfading{bmb@shadowmask\the\bmb@boxwidth\the\bmb@boxheight}{%
            \pgftransformshift{\pgfpoint{0.5\bmb@boxwidth+6bp}{0.5\bmb@boxheight-4bp}}}
          \pgfusepath{fill}
        \end{pgfscope}
      \fi%
      \unhbox\bmb@colorbox%
      \pgfpathqmoveto{-4bp}{1bp}
      \pgfpathqcurveto{-4bp}{-1.2bp}{-2.2bp}{-3bp}{0bp}{-3bp}
      \pgfpathlineto{\pgfpoint{\the\bmb@temp}{-3bp}}
      \pgfpathcurveto%
      {\pgfpoint{\the\bmb@dima}{-3bp}}%
      {\pgfpoint{\the\bmb@dimb}{-1.2bp}}%
      {\pgfpoint{\the\bmb@dimb}{1bp}}%
      {
        \bmb@dima=\ht\bmb@box%
        \pgfpathlineto{\pgfpoint{\bmb@dimb}{\bmb@dima}}
        \pgfpathlineto{\pgfpoint{-4bp}{\bmb@dima}}
        \pgfusepath{fill}
      }
    \end{pgfpicture}%
    \box\bmb@box%
  }%
  \ifbmb@shadow%
    \vskip4bp minus 2bp%
  \else%
    \vskip2bp%
  \fi%
  \egroup% of \vbox\bgroup
  \ifbmb@shadow%
    \xdef\beamer@colorhook{\beamer@storecolorhook}
  \fi
}
\makeatother

\begin{document}
	
\begin{frame}
	\titlepage
\end{frame}	

\begin{frame}
test

\begin{block}{title}
content...
\end{block}

test
\end{frame}
	
\end{document}
```

![Screen Shot 2021-06-19 at 16 06 03](https://user-images.githubusercontent.com/43832342/122645016-4f9c5d80-d118-11eb-8fef-85b05af5c4a2.png)

**Comment by samcarter** [comment]
The unescaped line ending after the pgfpicture seems to be the culeprint. This causes a space, which will be different based on different fonts

**Comment by rachitdeshpande** [comment]
@samcarter Thank you.

**Comment by CaSchmidt** [comment]
@samcarter Thank you! The above "workaround" fixed my issues with UniCode+MS Fonts as well! Hope it finds its way into MiKTeX some day...

**Comment by samcarter** [comment]
@CaSchmidt  You're welcome! The code is already in the main branch here on github, so should make its way into miktex with the next beamer release.

**Comment by dbitouze** [comment]
With the 3.64 version, the following MCE still leads to:

- a slim horizontal rule and the shadow is not that nice:
![Capture d’écran_2021-10-20_21-12-29](https://user-images.githubusercontent.com/1032633/138157361-14b4e2ca-908b-43b9-bc5f-a484836ab367.png)
- a gray vertical rule discontinued at the middle, I guess just at the border of the lower (think "text", as opposed to "title") part:
![Capture d’écran_2021-10-20_21-11-41](https://user-images.githubusercontent.com/1032633/138157395-76a9d0ce-d880-4bad-82a4-905713824bb8.png)

```latex
\documentclass{beamer}
\setbeamertemplate{blocks}[rounded][shadow=true]
\setbeamercolor{background canvas}{bg=red!50}
\begin{document}
\begin{frame}
  \begin{block}{Foo}
    Bar
  \end{block}
\end{frame}
\end{document}
```

**Comment by samcarter** [comment]
@dbitouze  Looks fine for me in adobe reader, preview.app and skim.

<img width="570" alt="Screenshot 2021-10-20 at 22 16 45" src="https://user-images.githubusercontent.com/43832342/138165783-3e19bc2d-c3d3-424d-8ccc-9e0a2a051b7e.png">

**Comment by samcarter** [comment]
The small sickle for blocks without titles should now also be gone (at least if the block is at least 10 bp height):

<img width="723" alt="Screenshot 2021-12-02 at 20 59 17" src="https://user-images.githubusercontent.com/43832342/144494138-39722042-332e-49e5-85b9-c6cd7694f149.png">

**Comment by dbitouze** [comment]
The second artifact in https://github.com/josephwright/beamer/issues/647#issuecomment-947963336 isn't present anymore: many thanks! 

I still see the first one with `Okular` at zoom 10000%. The end of the culprit horizontal line seems to be where the vertical line of the block becomes a circle arc.
![okular](https://user-images.githubusercontent.com/1032633/144499383-b7df0354-0fce-4840-8323-77354757115a.png)

**Comment by samcarter** [comment]
@denis That's an artefact of poppler based pdf viewers. 

After compiling a custom version of texstudio from source to enable such insanely large zoom levels, I can reproduce and I think I have a workaround. Will make a PR in a second

**Comment by samcarter** [comment]
@dbitouze  Can you test this PR: https://github.com/josephwright/beamer/pull/741

**Comment by dbitouze** [comment]
(Sorry for the thumbs down emoji (if it's me).)

> @dbitouze Can you test this PR: #741

Much nicer! The horizontal line has been removed. Only the vertical one is left:

![screen-2021-12-02-22-02-12](https://user-images.githubusercontent.com/1032633/144502804-1fc97e31-f16d-4f2b-bb3b-f4792778dbb2.png)

**Comment by samcarter** [comment]
I'll leave the vertical line, if I touch it, I'll break the right edge (again)

**Comment by dbitouze** [comment]
> I'll leave the vertical line, if I touch it, I'll break the right edge (again)

OK, that's good compromise :smile:
