### ISSUE TITLE
\pause in ams math environments

### ISSUE THREAD

**Issue by marmotghost** [josephwright/beamer#648]
I apologize in advance if I am barking at the wrong tree. The documentation on my updated TeXLive 2020 installation (still) says on p. 80 that `\pause` is not supported in `align`, which is consistent with the outcome below. However, I thought that in the old days this even lead to error messages. The reason why I write this message is to find out whether `\pause` has been changed, and if this the case, the updated version is not yet working perfectly. Here is a code to look at:
```
\documentclass{beamer}
\begin{document}
\begin{frame}[t]
\frametitle{W/o patch}
\begin{align*}
 E&=mc^2 \\
 \pause
 &=h\nu \\
 \pause
 &=|\vec E|
\end{align*}
\end{frame}

\makeatletter
\renewrobustcmd{\beamer@@pause}[1][]{%
  \unless\ifmeasuring@%
  \ifblank{#1}%
    {\stepcounter{beamerpauses}}%
    {\setcounter{beamerpauses}{#1}}%
  \onslide<\value{beamerpauses}->\relax%
  \fi
}
\makeatother

\begin{frame}[t]
\frametitle{W patch}
\begin{align*}
 E&=mc^2 \\
 \pause
 &=h\nu \\
 \pause
 &=|\vec E|
\end{align*}
\end{frame}

\end{document}
```
![ani](https://user-images.githubusercontent.com/68924170/103240869-5df68300-4906-11eb-9646-66e5548610d0.gif)

After adding the patch to `\pause` the result is what one would expect. However, I would have thought that the first frame just leads to error messages if `\pause` was the old version (but I did not check because I do not know how to run things on old installations). So the questions are:

- did `\pause` get changed recently?
- is there a chance to add something along the lines of the patch to beamer so that one can just use `\pause` in `align`?

**Comment by marmotghost** [comment]
Hmmh, now I see https://github.com/josephwright/beamer/issues/624#issue-702649592. For some reason I did not find it in the search, so I am totally fine with the above being deleted (even though my questions still persist).

**Comment by samcarter** [comment]
> - did \pause get changed recently?

The only recent change roughly in this area of the code is f8f5c8f33

> - is there a chance to add something along the lines of the patch to beamer so that one can just use \pause in align?

Like you discovered, I logged an issue about this at #624 - but I think this has the potential to break a lot of unexpected things, so excessive testing would need to be carried out before such a change
