### ISSUE TITLE
fleqn issues

### ISSUE THREAD

**Issue by marmotghost** [josephwright/beamer#649]
Since `fleqn` does not seem to get mentioned in the beamer manual, and `texdoc fleqn` does not really provide one with information relevant to the following problem, I'd like to report an issue.
```
\documentclass{beamer}
\usepackage{fleqn}
\begin{document}
\begin{frame}[t]
\frametitle{A tagged equation}
\begin{equation}
 a=b\tag{c}
\end{equation}
\end{frame}
\end{document}
```
yields the error message
```
! Package amsmath Error: \tag not allowed here.

See the amsmath package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.9 \end{frame}
```
Tagging does work if I pass `fleqn` to the options of `beamer`.
```
\documentclass[fleqn]{beamer}
\begin{document}
\begin{frame}[t]
\frametitle{A tagged equation}
\begin{equation}
 a=b\tag{c}
\end{equation}
\end{frame}
\end{document}
```
However, there is another issue. Let's forget about tags for the moment and just look at `fleqn`. 
```
\documentclass[fleqn]{beamer}
\begin{document}
\begin{frame}[t]
\frametitle{An equation}
\begin{equation}
 a=b
\end{equation}
\end{frame}
\end{document}
```
produces
<img width="591" alt="Screen Shot 2020-12-29 at 1 50 06 PM" src="https://user-images.githubusercontent.com/68924170/103316280-db8cc280-49dc-11eb-82b4-67f103a3bcb5.png">

whereas 
```
\documentclass{beamer}
\usepackage{fleqn}
\begin{document}
\begin{frame}[t]
\frametitle{An equation}
\begin{equation}
 a=b
\end{equation}
\end{frame}
\end{document}
```
yields
<img width="581" alt="Screen Shot 2020-12-29 at 1 51 40 PM" src="https://user-images.githubusercontent.com/68924170/103316354-1131ab80-49dd-11eb-9b52-7f2a6df72066.png">

Obviously the vertical space between the title and the equation is very different. While I almost expect a message saying that one should not use `\usepackage{fleqn}` it would be great if this information could be added to the beamer document or something that can be found with `texdoc fleqn`, say. Note also that, if indeed `\usepackage{fleqn}` should not be used, this means that users who used it in the past will now get a different output once they switch to `\documentclass[fleqn]{beamer}`. That is, if they have a large collection of slides produced with `\usepackage{fleqn}` they may run into problems when recompiling things.

**Comment by samcarter** [comment]
About the last two examples with the different spacing: 

I think that's not really related to the `fleqn` package. Try the following example with and without the option

```
\documentclass{article}

\usepackage[
fleqn % comment in and out
]{amsmath} 

\begin{document}

\begin{equation}
 a=b
\end{equation}

\end{document}
```

![document](https://user-images.githubusercontent.com/43832342/117503596-7431e100-af81-11eb-80eb-31c914bf456a.gif)


If ones takes `amsmath` out of the equation, switching between the class option and the `fleqn` package in the following example seems to give the same spacing

```
\documentclass[noamsthm,
%fleqn
]{beamer}

\usepackage{fleqn}

\begin{document}
\begin{frame}[t]
\frametitle{A tagged equation}
\begin{equation}
 a=b
\end{equation}
\end{frame}
\end{document}
```
(with amsmath, all the document option does is `\input{fleqn.clo}`, which is basically the same as the `fleqn` package)

...so I'd say "not beamer's fault"

---

The closest approximation of the `fleqn` package in beamer would be

```
\documentclass[noamsthm,fleqn]{beamer}

\begin{document}
\begin{frame}[t]
\frametitle{A tagged equation}
\begin{equation}
 a=b
\end{equation}
\end{frame}
\end{document}
```
but obviously one wouldn't be able to use any amsmath features in this

**Comment by samcarter** [comment]
Just pushed a commit that mentions the two documentclass options: https://github.com/josephwright/beamer/commit/c257a74236d7fe2338889ae1e8bcd3da23dac150

**Comment by samcarter** [comment]
The one remaining question is if the `fleqn` package should be mentioned in `2.6 Compatibility with Other Packages and Classes`?

### Pro:

- amsmath is loaded automatically and the user might not be aware of that

### Con:

- just loading the package does not cause problems, only when using amsmath specific macros, so the user should be aware that amsmath is used somewhere....
- nothing beamer specific, can just as well be reproduced with article.

(personally I tend towards the con side)

**Comment by dbitouze** [comment]
> The one remaining question is if the `fleqn` package should be mentioned

Is there any  `fleqn` package?

**Comment by samcarter** [comment]
@dbitouze  Yes, it is basically just a wrapper for `\input{fleqn.clo}`

**Comment by dbitouze** [comment]
> @dbitouze Yes, it is basically just a wrapper for `\input{fleqn.clo}`

But I don't see such a [package on the CTAN](https://www.ctan.org/search?phrase=fleqn).

**Comment by samcarter** [comment]
@dbitouze Have a look at /usr/local/texlive/2021/texmf-dist/tex/latex/base/fleqn.sty
