### ISSUE TITLE
LuaLaTeX — Shadows for overlaid blocks no more functioning with v.3.60 

### ISSUE THREAD

**Issue by yrogge** [josephwright/beamer#650]
Using “\useinnertheme[shadow]{rounded}” is broken with new version 3.60.
Everything was fine until v.3.59.
Symptom: back rectangle, without rounding or transparency, put in the foreground of an overlaid block when visible on slide.

**Comment by yguilhem** [comment]
I could reproduce the issue with `pdflatex` and `beamer v3.60` using following MWE:
```tex
\documentclass{beamer}
\useinnertheme[shadow]{rounded}
\setbeamercovered{transparent}
\begin{document}
\begin{frame}
  \begin{block}{Visible block}
  \end{block}
  \begin{block}<2>{Overlaid block}
  \end{block}
\end{frame}
\end{document}
```
Here are the 2 screenshots of the resulting frames:
![2020-12-30-163751_1037x248_scrot](https://user-images.githubusercontent.com/6862940/103364215-78269180-4abd-11eb-9f51-97897ca40d4e.png)
![2020-12-30-163802_1038x245_scrot](https://user-images.githubusercontent.com/6862940/103364231-82489000-4abd-11eb-8cad-b5ef78fe38ce.png)

**Comment by josephwright** [comment]
Could you add `\listfiles` and report the result from you log? I think  you need an updated `pgf`.

**Comment by yrogge** [comment]
Here are the files
[TestBeamer.log](https://github.com/josephwright/beamer/files/5754993/TestBeamer.log)
[TestBeamer.txt](https://github.com/josephwright/beamer/files/5754994/TestBeamer.txt)

**Comment by josephwright** [comment]
> I could reproduce the issue with `pdflatex` and `beamer v3.60` using following MWE:

I definitely _don't_ see it with pdfTeX. I suspect a driver issue in `pgf` with LuaTeX as a result.

**Comment by yguilhem** [comment]
Here is my log with `pdflatex`: [test-beamer.log](https://github.com/josephwright/beamer/files/5755074/test-beamer.log)
My TeXlive distribution is up-to-date, with `pgf v3.1.8b`, but maybe something got wrong with my last update...

**Comment by josephwright** [comment]
Cause is 5c2fde7935886fac8ef3d47507a40cca929180ca, but I think that's 'not our fault': @samcarter ?

**Comment by samcarter** [comment]
> Cause is [5c2fde7](https://github.com/josephwright/beamer/commit/5c2fde7935886fac8ef3d47507a40cca929180ca), but I think that's 'not our fault': @samcarter ?

Oh ****, the notifications for this thread vanished in my spam filter. Sorry for not replying!

**Comment by samcarter** [comment]
@u-fischer's fix for https://github.com/josephwright/beamer/issues/654 seems to also solve this problem

**Comment by yguilhem** [comment]
Thank you @samcarter for the fix. I did not see any beamer or pgf update in TeXlive since then but the MWE is working OK now.
Would it be possible to test the following MWE with the latest commits? Because it is giving poor results with latest TeXlive.
```
\documentclass{beamer}
\useinnertheme[shadow]{rounded}
\setbeamercovered{transparent}
\begin{document}
\begin{frame}
  \begin{block}{Visible block}
  \end{block}
  \begin{block}<2>{Overlaid block}
  \end{block}
  \begin{block}<2>{Overlaid block with itemize list}
    \begin{itemize}
      \item First Item
    \end{itemize}
  \end{block}
\end{frame}
\end{document}
```
Here is the log: [test-beamer-2.log](https://github.com/josephwright/beamer/files/5848216/test-beamer-2.log)
Here is the result:
![2021-01-21-102844_474x337_scrot](https://user-images.githubusercontent.com/6862940/105331379-afc3bd80-5bd3-11eb-8aab-ef5b91ccd7ad.png)
![2021-01-21-102854_475x335_scrot](https://user-images.githubusercontent.com/6862940/105331387-b18d8100-5bd3-11eb-94c7-e534c0c62f45.png)

**Comment by samcarter** [comment]
@yguilhem Your example works fine for me with beamer dev version (in pdflatex, xelatex and lualatex)

![Screen Shot 2021-01-21 at 10 48 21](https://user-images.githubusercontent.com/43832342/105333814-717bcd80-5bd6-11eb-886b-ff82a99cd84c.png)

**Comment by yguilhem** [comment]
OK perfect! I will just wait for the integration of this version in TeXlive.
