### ISSUE TITLE
nested \only commands  xdvipdfmx gives return code 11

### ISSUE THREAD

**Issue by letzfets** [josephwright/beamer#651]
I have a nested structure of only commands like this:
````
\begin{frame}
\only<2-3>{
some code ...
inside an externalised tiki picture:
\only<3>{some more code}
...
}
\only<3>{}
\end{frame}
````

Note: the second and empty \only<3>{} is placed somewhere in the same frame, to avoid another glitch with the externalisation library in tiki-pgf

I'm compiling with xelatex executed by latexmk.
Up to version 3.57 my code worked fine. Now I've updated a bunch of things in my installation and I get the error message

`xdvipdfmx: Command for 'xdvipdfmx' gave return code 11` due to the code above.
Did any of the latest releases influence the behaviour of this code?

Thx 🙏

**Comment by josephwright** [comment]
There's been no fundamental change in `beamer`: we leave the basics here well alone.

**Comment by letzfets** [comment]
Thanks at @josephwright . 👍
I keep debugging then.
