### ISSUE TITLE
\beamer@bibiconwidth already defined on BibLaTeX with authoryear

### ISSUE THREAD

**Issue by dustalov** [josephwright/beamer#652]
I am trying to compile a Beamer 3.60 (r57140) document with two `\printbibliography` calls that uses BibLaTeX 3.16 (r57272) with `authoryear` style. I use this functionality in practice to display heterogeneous parts of the very long bibliography.

```latex
\begin{filecontents}{\jobname.bib}
@misc{beamer,
  url = {https://ctan.org/pkg/beamer},
}
\end{filecontents}

\documentclass{beamer}

\usepackage[style=authoryear]{biblatex}

\addbibresource{\jobname.bib}

\begin{document}

\nocite{*}

\begin{frame}
\printbibliography
\end{frame}

\begin{frame}
\printbibliography
\end{frame}

\end{document}
```

I got the following error message.

```
! LaTeX Error: Command \beamer@bibiconwidth already defined.
               Or name \end... illegal, see p.192 of the manual.
```

Removing the `style=authoryear` option or the second `\printbibliography` call solves the problem, but everything worked fine before the recent TeX Live 2020 updates (in December?)

Could you please suggest a workaround or solution to my problem?

**Comment by samcarter** [comment]
Sorry, my bad! I just merged a bugfix.

As a temporary workaround, you can use the file from https://github.com/josephwright/beamer/blob/752390f57da5383e402a0e230a874bebb2d2471a/base/beamerbaselocalstructure.sty until a new version is released.

**Comment by dustalov** [comment]
Thank you for fixing this. I am glad to confirm that everything is fine now.

**Comment by NMarkgraf** [comment]
:-( --- Will there be a hot fix (3.60a?) soon? Or is a new release scheduled in the near future?

**Comment by samcarter** [comment]
@NMarkgraf  @josephwright  was so nice to do a new release https://www.ctan.org/ctan-ann/id/mailman.4234.1613069579.2532.ctan-ann@ctan.org

**Comment by NMarkgraf** [comment]
Thanks a lot! :-)
