### ISSUE TITLE
transparent overlays break shadowboxes

### ISSUE THREAD

**Issue by samcarter** [josephwright/beamer#654]
Unfortunately transparent overlays break shadowboxes.

Test document:

```
\documentclass{beamer}

\usetheme{Madrid}

\setbeamercovered{transparent}

\begin{document}
\begin{frame}
\pause
      \begin{block}{First block}
        This is the first block.
      \end{block}
\end{frame}
\end{document}
```

![Screen Shot 2021-01-13 at 14 38 51](https://user-images.githubusercontent.com/43832342/104459617-44636580-55ad-11eb-9326-11b13b4e8ead.png)

**Comment by samcarter** [comment]
Half of the problem can be worked around by numbering the shading.

To generate not infinitely many shadings, their name contained their dimension, so that blocks of the same size would reuse the already existing shading. However this also meant that the shadings from the covered boxed from the previous overlay were reused, because they had the same dimensions. By adding a count to the boxes, on forces new shadings to be defined, but of course this will result in a potential huge number of shadings with unknown consequences. 

Proof on concept:

```
\documentclass{beamer}
\makeatletter

\newcount\pgf@shadingboxcnt
\def\endbeamerboxesrounded{%
  \end{minipage}\egroup%
  \bmb@temp=\dp\bmb@box%
  \advance\bmb@temp by.5pt%
  \setbox\bmb@box=\hbox{\raise\bmb@temp\hbox{\box\bmb@box}}%
  \dp\bmb@box=0pt%
  \bmb@boxwidth=\bmb@width%
  \bmb@boxheight=\ht\bmb@box%
  \advance\bmb@boxheight by4bp%
  \advance\bmb@boxheight by\bmb@prevheight%
  \ifbmb@shadow%
    \global\advance \pgf@shadingboxcnt by 1
    \pgfdeclareradialshading{bmb@shadowball}{\pgfpointorigin}
    {%
      color(0bp)=(pgftransparent!50);
      color(4bp)=(pgftransparent!100)
    }%
    \pgfdeclareradialshading{bmb@shadowballlarge}{\pgfpointorigin}
    {%
      color(0bp)=(pgftransparent!0);
      color(8bp)=(pgftransparent!100)
    }%
    \pgfdeclarehorizontalshading{bmb@shadowhorz\the\pgf@shadingboxcnt}{\bmb@boxheight-6bp}
    {%
      color(0bp)=(pgftransparent!0);
      color(8bp)=(pgftransparent!100)
    }%
    \pgfdeclareverticalshading{bmb@shadowvert\the\pgf@shadingboxcnt}{\bmb@boxwidth-4bp}
    {%
      color(0bp)=(pgftransparent!100);
      color(8bp)=(pgftransparent!0)
    }%
    \pgfdeclarefading{bmb@shadowmask\the\pgf@shadingboxcnt}
    {%
      \begin{pgfpicture}
        \pgftext[at=\pgfpoint{4bp}{4bp}]{\pgfuseshading{bmb@shadowball}}
        \pgftext[at=\pgfpoint{\bmb@boxwidth}{8bp}]{\pgfuseshading{bmb@shadowballlarge}}
        \pgftext[at=\pgfpoint{\bmb@boxwidth+4bp}{\bmb@boxheight+2bp}]{\pgfuseshading{bmb@shadowball}}
        \pgftext[left, at=\pgfpoint{4bp}{4bp}]{\pgfuseshading{bmb@shadowvert\the\pgf@shadingboxcnt}}
        \pgftext[base, at=\pgfpoint{\bmb@boxwidth+4bp}{8bp}]{\pgfuseshading{bmb@shadowhorz\the\pgf@shadingboxcnt}}
        %
        % clipping is needed because shadow is typeset on top of box
        \begin{pgfscope}
          \pgfsetcolor{black}
          \pgfpathrectangle{\pgfpoint{4bp}{8bp}}{\pgfpoint{\bmb@boxwidth-0.2bp}{\bmb@boxheight-2bp}}
          \pgfusepath{fill}
        \end{pgfscope}
      \end{pgfpicture}
    }%
  \fi%
  \bmb@temp=\bmb@width%
  \bmb@dima=\bmb@temp\advance\bmb@dima by2.2bp%
  \bmb@dimb=\bmb@temp\advance\bmb@dimb by4bp%
  \hbox{%
    \begin{pgfpicture}{0bp}{0bp}{0bp}{0bp}
      \ifbmb@shadow%
        \begin{pgfscope}
          \pgfpathrectangle{\pgfpoint{0bp}{-7bp}}
            {\pgfpoint{\bmb@boxwidth+8bp}{\bmb@boxheight+6bp}}
          \pgfsetfading{bmb@shadowmask\the\pgf@shadingboxcnt}{%
            \pgftransformshift{\pgfpoint{0.5\bmb@boxwidth+6bp}{0.5\bmb@boxheight-4bp}}}
          \pgfusepath{fill}
        \end{pgfscope}
      \fi%
      \unhbox\bmb@colorbox%
      \pgfpathqmoveto{-4bp}{1bp}
      \pgfpathqcurveto{-4bp}{-1.2bp}{-2.2bp}{-3bp}{0bp}{-3bp}
      \pgfpathlineto{\pgfpoint{\the\bmb@temp}{-3bp}}
      \pgfpathcurveto%
      {\pgfpoint{\the\bmb@dima}{-3bp}}%
      {\pgfpoint{\the\bmb@dimb}{-1.2bp}}%
      {\pgfpoint{\the\bmb@dimb}{1bp}}%
      {
        \bmb@dima=\ht\bmb@box%
        \pgfpathlineto{\pgfpoint{\bmb@dimb}{\bmb@dima}}
        \pgfpathlineto{\pgfpoint{-4bp}{\bmb@dima}}
        \pgfusepath{fill}
      }
    \end{pgfpicture}%
    \box\bmb@box%
  }%
  \ifbmb@shadow%
    \vskip4bp minus 2bp%
  \else%
    \vskip2bp%
  \fi%
  \egroup% of \vbox\bgroup
}
\makeatother
\usetheme{Madrid}

\setbeamercovered{transparent}

\begin{document}
\begin{frame}
\pause
      \begin{block}{First block}
        This is the first block.
      \end{block}
\end{frame}
\end{document}
```
![Screen Shot 2021-01-13 at 14 41 59](https://user-images.githubusercontent.com/43832342/104459795-87bdd400-55ad-11eb-957f-576fb6acfbfe.png)

**Comment by samcarter** [comment]
Now the problem with the colours on the first overlay remains. Probably it would be best to roll back to the old shadow boxes until a fix for this is found.

**Comment by samcarter** [comment]
@u-fischer Just found a workaround for the colour:

```
\documentclass[]{beamer}
\usetheme{Madrid}
\setbeamercovered{transparent}
\usepackage{xpatch}
\makeatletter
\patchcmd{\endbeamerboxesrounded}{\ifbmb@shadow}{\ifbmb@shadow\def\beamer@colorhook{}}{}{\fail}
\makeatother
\begin{document}
\begin{frame}

\pause 
\begin{theorem}
A theorem.
\end{theorem}

\begin{theorem}
Another one theorem.
\end{theorem}
\end{frame}
\end{document}
```

**Comment by u-fischer** [comment]
Something like this seems to work too and would avoid a inconsistent local/global assignment (naturally with a better name than \blub ..)

~~~~
\patchcmd{\endbeamerboxesrounded}{\ifbmb@shadow}{\ifbmb@shadow\xdef\blub{\beamer@colorhook}\xdef\beamer@colorhook{}}{}{\fail}
\apptocmd\endbeamerboxesrounded{\xdef\beamer@colorhook{\blub}}{}{\fail}
~~~~

**Comment by samcarter** [comment]
> Something like this seems to work too and would avoid a inconsistent local/global assignment (naturally with a better name than \blub ..)
> 
> ```
> \patchcmd{\endbeamerboxesrounded}{\ifbmb@shadow}{\ifbmb@shadow\xdef\blub{\beamer@colorhook}\xdef\beamer@colorhook{}}{}{\fail}
> \apptocmd\endbeamerboxesrounded{\xdef\beamer@colorhook{\blub}}{}{\fail}
> ```

Thanks for the suggestion!

**Comment by Factoriellepi** [comment]
Hello, 

I do know that this topic is supposed to have been be closed a while, but I recently had to upgrade my beamer package and face this very problem. I trie implementing the fixes that were proposed in this thread (by simply copy-pasting them), and the issue persists. 

Since it has been around 8 months you discussed this issue and there does not seem to be a fix from the development team, would you know if it is possible to find an older version of Beamer (e.g. v3.59) which did not run into this problem ? 

Thanks in advance for your time

**Comment by samcarter** [comment]
@Factoriellepi  Which version of beamer do you have?

**Comment by Factoriellepi** [comment]
Dear @samcarter, thank you very much for replying to me. 

I have what appears to be the last version, so Beamer v3.63 (I installed it via MikTex earlier this week).

**Comment by samcarter** [comment]
@Factoriellepi It should work fine with v3.63. 

Can you make a minimal working example which fails for you and also show your .log file and a screenshot of the output you get?

**Comment by samcarter** [comment]
@Factoriellepi Wild guess: are you maybe compiling via `latex->dvips->ps2pdf` ?

If yes, you need `ps2pdf -dALLOWPSTRANSPARENCY`, see https://texnique.fr/osqa/questions/9852/pourquoi-les-ombres-sur-le-theme-warsaw-de-beamer-se-mettent-en-premier-plan/9858

**Comment by Factoriellepi** [comment]
@samcarter No I am using the standard PDFLatex. 

Apparently it does indeed work with standard beamer packages (like Madrid or Warsaw), and what seems to be off comes from the use of a personal color package using \mode<presentation>

[Test.log](https://github.com/josephwright/beamer/files/7311098/Test.log)

![TestBeamer](https://user-images.githubusercontent.com/17594029/136553893-f1d19417-b7a2-426c-85fa-03df498ee670.png)
![FaultyPackage1](https://user-images.githubusercontent.com/17594029/136554284-1202b1ca-f5a7-4d8f-84bb-cf820af809d2.png)
![FaultyPackage2](https://user-images.githubusercontent.com/17594029/136554287-1329b865-a1d7-429a-91d2-900fd5017f2e.png)

**Comment by samcarter** [comment]
@Factoriellepi  Can you please copy and paste your minimal working example and the colour theme as text? I'd like to test them. Maybe the colour model is the issue...

**Comment by Factoriellepi** [comment]
@samcarter  

Sure, here is the example 

```
\documentclass[11pt]{beamer}

\mode<presentation>{\usecolortheme{beamer_mes_couleurs}}

\usepackage[utf8]{inputenc}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}

\begin{document}

%\begin{frame}
%\titlepage
%\end{frame}

%\begin{frame}
%\tableofcontents
%\end{frame}

\begin{frame}{Issue with personal colors}

\begin{beamerboxesrounded}[shadow = true]{Title}
Test
\end{beamerboxesrounded}

\end{frame}

\end{document}
```

and here is the color package

```
\ProvidesPackage{beamercolorthemebeamer_mes_couleurs}  % this style was created by Thomas Deselaers an Philippe Dreuw

%\RequirePackage{tangocolors}
\selectcolormodel{cmyk}
\mode<presentation>


\definecolor{ta1}{rgb}{0.67843, 0.49804, 0.65882}		% #ad7fa8
\definecolor{ta2}{rgb}{0.45882, 0.31373, 0.48235}		% #75507b
\definecolor{ta3}{rgb}{0.36078, 0.20784, 0.4}		% #5c3566

\definecolor{cyan1}{rgb}{0, 139, 139}	% #008B8B
\definecolor{cyan2}{rgb}{0.45882, 0.31373, 0.48235}		% #40E0D0
\definecolor{cyan3}{rgb}{0.36078, 0.20784, 0.4}		% #E0FFFF

\definecolor{peach}{rgb}{1., 0.3, 0.05}

\definecolor{ta3peach}{RGB}{211, 40, 31}		% #ad7fa8
\definecolor{ta2peach}{RGB}{251, 123, 106}		% #75507b
\definecolor{ta1peach}{RGB}{252, 200, 156}		% #5c3566

\definecolor{vertpastel}{rgb}{0.64118, 0.95627, 0.30392}	% #8ae234

\mode<presentation>

\setbeamercolor{structure}{fg=peach}

\setbeamercolor*{palette primary}{use=structure,fg=black,bg=structure.fg}
\setbeamercolor*{palette secondary}{use=structure,fg=white,bg=structure.fg!30!white}
\setbeamercolor*{palette tertiary}{use=structure,fg=white,bg=structure.fg!60!white}
\setbeamercolor*{palette quaternary}{fg=white,bg=black}

\setbeamercolor*{sidebar}{use=structure,bg=structure.fg}

\setbeamercolor*{palette sidebar primary}{use=structure,fg=structure.fg}
\setbeamercolor*{palette sidebar secondary}{fg=white}
\setbeamercolor*{palette sidebar tertiary}{use=structure,fg=structure.fg!40}
\setbeamercolor*{palette sidebar quaternary}{fg=white}

\setbeamercolor*{emph}{fg=structure}
%\setbeamercolor*{title}{fg=ta3,bg=structure.fg!50}
%\setbeamercolor*{titlelike}{use=structure,fg=structure.fg}

%\setbeamercolor*{frametitle}{fg=ta3,bg=structure.fg!50}

\setbeamercolor*{separation line}{}
\setbeamercolor*{fine separation line}{}

\mode<all>
```

**Comment by samcarter** [comment]
Note to myself:

mwe

```
\documentclass{beamer}

\selectcolormodel{cmyk}
\useinnertheme[shadow]{rounded}

\begin{document}

\begin{frame}

\begin{block}{Title}
Test
\end{block}

\end{frame}

\end{document}
```

**Comment by samcarter** [comment]
@Factoriellepi  Back to your original question about downgrading

- You can find all the old versions at https://github.com/josephwright/beamer/releases
- unfortunately some changes made to the latex kernel mean that you can't use many old beamer versions in a current tex distribution anymore. You'll need a workaround like this: https://topanswers.xyz/tex?q=1416#a1656

**Comment by Factoriellepi** [comment]
@samcarter Ok thank you very much for taking the time to answer my query. I will try to use a previous version of Beamer for my coming talks.

**Comment by samcarter** [comment]
@Factoriellepi  (did you test if you actually need the `cmyk` colour model or if something like `cmy` or even `rgb` wouldn't work as well?)

**Comment by Factoriellepi** [comment]
@samcarter No I did not, I followed a template to create this colour package and I did not know that these other options existed. I will give it a go.

**Comment by samcarter** [comment]
@Factoriellepi  If you don't explicitly need it, I would just remove the line `\selectcolormodel{...}`.

**Comment by Factoriellepi** [comment]
@samcarter I tried to remove the `\selectcolormodel{...}` and to change `cmyk` by the two options you suggested, but the problem persisted. However, I managed to manually downgrade Beamer to v3.59 and things are going smoothly without extra workarounds
