### ISSUE TITLE
Wrong shadow with rounded blocks in overlays

### ISSUE THREAD

**Issue by calvanese** [josephwright/beamer#657]
After an upgrade from beamer v3.59 to v.3.60, rounded blocks with shadow in overlays have a black bar that covers the block title, and the shadow behind the block is completely black.  The problem appears with \setbeamercovered{transparent} but not with \setbeamercovered{invisible}, and only if there is an overlay.

This is for pdfTeX on a MacBook Pro (with a standard MacTeX 2020 installation of TeX Live).

A minimal example showing the problem is the following:

```
\documentclass{beamer}
\setbeamertemplate{blocks}[rounded][shadow=true]
\setbeamercovered{transparent}
% \setbeamercovered{invisible}

\begin{document}
\begin{frame}

\pause
\begin{block}{Block Title}
  Block body
\end{block}

\end{frame}
\end{document}
```
![block-shadow-problem](https://user-images.githubusercontent.com/34384072/105629740-113e9300-5e45-11eb-87fc-0ed62f34595a.png)

**Comment by samcarter** [comment]
That's already been fixed in the beamer dev version, see issue #654
