### ISSUE TITLE
Loading `hyperref' with option "implicit=false" is not documented

### ISSUE THREAD

**Issue by gaelicWizard** [josephwright/beamer#658]
There's no indication why hyperref is loaded with implicit=false, and neither beamer nor hyperref document what this *means*. Looking at hyperref, it seems like it causes the package to simply \endinput halfway through. Why does beamer do this? What breaks if hyperref is loaded with implicit=true?

**Comment by josephwright** [comment]
The `implicit` option determines whether `hyperref` redefines LaTeX internals. For `beamer`, we have a lot of manual redefinitions, so that is not appropriate. This is not documented in the `beamer` manual as it's essentially a technical aspect for developers: how `beamer`/`hyperref` work together.

**Comment by Explorer-cc** [comment]
> The `implicit` option determines whether `hyperref` redefines LaTeX internals. For `beamer`, we have a lot of manual redefinitions, so that is not appropriate. This is not documented in the `beamer` manual as it's essentially a technical aspect for developers: how `beamer`/`hyperref` work together.

@josephwright  Is there any progress until `2025-03-07` of this issues with the clash of `cleveref` and `hyperref` with option `implicit=false`? A related question more detailed is [here](https://tex.stackexchange.com/questions/481022/hyperlinks-do-not-work-with-cleveref-beamer).

**Comment by josephwright** [comment]
> [@josephwright](https://github.com/josephwright) Is there any progress until `2025-03-07` of this issues with the clash of `cleveref` and `hyperref` with option `implicit=false`? A related question more detailed is [here](https://tex.stackexchange.com/questions/481022/hyperlinks-do-not-work-with-cleveref-beamer).

This is down to the `cleveref` maintainer.
