### ISSUE TITLE
Box shadow artifact, if black is actually gray

### ISSUE THREAD

**Issue by Tikrass** [josephwright/beamer#659]
The shadow of beamer boxes produces a strange artifact, if the color `black` is replaced by some gray. 

Affected  version: `beamer` 2020/11/26 v3.60 

MWE:
```
\documentclass{beamer}
\definecolor{black}{RGB}{30,30,30}
\setbeamertemplate{blocks}[rounded][shadow=true]
\begin{document}
\begin{frame}
    \begin{block}{Example}
    \end{block}
\end{frame}
\end{document}

```
![image](https://user-images.githubusercontent.com/641293/106731201-82353600-660f-11eb-9154-4f768e620dc4.png)

This might be related to #647

**Comment by samcarter** [comment]
@Tikrass As workaround, you could use

```
\documentclass{beamer}

\colorlet{foo}{black}
\usepackage{xpatch}
\xpatchcmd{\endbeamerboxesrounded}{\pgfsetcolor{black}}{\pgfsetcolor{foo}}{}{}

\definecolor{black}{RGB}{100,100,100}
\setbeamertemplate{blocks}[rounded][shadow=true]
\begin{document}
\begin{frame}
\textcolor{black}{text}

    \begin{block}{Ex}
    \textcolor{black}{text}
    \end{block}
    
\textcolor{black}{text}    
\end{frame}
\end{document}
```

![Screen Shot 2021-02-03 at 13 06 45](https://user-images.githubusercontent.com/43832342/106744950-be24c700-6620-11eb-87ac-dab854b7ead5.png)

**Comment by samcarter** [comment]
@Tikrass Just curious, why do you redefine black?

**Comment by samcarter** [comment]
Minimal (non-)working example:
```
\documentclass{article}

\usepackage{tikz}

\definecolor{black}{RGB}{100,100,100}

\begin{document}


    \pgfdeclarehorizontalshading{shadowhorzfoo}{40bp}
    {%
      color(0bp)=(pgftransparent!0);
      color(8bp)=(pgftransparent!100)
    }%
    \pgfdeclarefading{shadowmaskfoo}
    {%
      \begin{pgfpicture}
        \pgftext[base, at=\pgfpoint{\textwidth}{0bp}]{\pgfuseshading{shadowhorzfoo}}
        %
        % clipping is needed because shadow is typeset on top of box
        \begin{pgfscope}
          \pgfsetcolor{black}
          \pgfpathrectangle{\pgfpoint{0bp}{0bp}}{\pgfpoint{\textwidth}{20bp}}
          \pgfusepath{fill}
        \end{pgfscope}
      \end{pgfpicture}
    }%
    \begin{pgfpicture}{0bp}{0bp}{0bp}{0bp}
        \begin{pgfscope}
          \pgfpathrectangle{\pgfpoint{0bp}{0bp}}
            {\pgfpoint{40bp}{40bp}}
          \pgfsetfading{shadowmaskfoo}{%
            \pgftransformshift{\pgfpoint{20bp}{20bp}}}
          \pgfusepath{fill}
        \end{pgfscope}
    \end{pgfpicture}%

\end{document}
```

**Comment by Tikrass** [comment]
Thanks for the Workaround!

> @Tikrass Just curious, why do you redefine black?

Mostly due to corporate design matters. Especially in print you might want to distinguish between various blacks.

**Comment by car222222** [comment]
Like Vantablack ??  :-)

**Comment by samcarter** [comment]
@car222222 

> Like Vantablack ?? :-)

No, no, no, that's too dangerous https://www.miamiherald.com/news/nation-world/world/article217152075.html

:)

**Comment by samcarter** [comment]
@Tikrass 

> Mostly due to corporate design matters.

I see, that makes sense! I actually do something similar in the documentation for some latex packages so the examples have easy to read names like red/green/blue but the output will match the colour scheme.
