### ISSUE TITLE
Weird slide title shadow

### ISSUE THREAD

**Issue by pjrramos** [josephwright/beamer#663]
The warsaw theme ceased to produce the title's shadow correctly after the latest Beamer updates.

Before it was like this:
<img width="372" alt="Good" src="https://user-images.githubusercontent.com/79539364/108895170-286ecd00-760b-11eb-88d5-ec0b701108d1.png">

Now it looks like this:
<img width="414" alt="Bad" src="https://user-images.githubusercontent.com/79539364/108895092-0c6b2b80-760b-11eb-8abf-250a1606f834.png">

**Comment by samcarter** [comment]
@pjrramos Are you using miktex and/or compile via latex->dvips->ps2pdf ?

**Comment by pjrramos** [comment]
Last week I noticed that beamer was producing slides with that problem.
Today i reinstalled mactex and right after that, using texstudio, i compiled it with latex-> DVI-> PS-> PDF.
After that, I made an update with TeX Live Utility and I had the problem again.
That's why I said that the problem may have come up with one of the latest updates from Beamer.

**Comment by samcarter** [comment]
@pjrramos This sounds like a problem that came up with certain ghostscript versions. I'll have a look if I can find the post again.

Meanwhile, do you need to compile via the dvi->ps route? It should work fine if you directly use pdflatex

**Comment by samcarter** [comment]
@pjrramos  Can you try this advise by @agrahn https://tex.stackexchange.com/questions/581523/black-frame-appears-in-beamer-block/581768#581768

> Make sure you have a recent Ghostscript installed (v. 9.52 or newer) and that ps2pdf is invoked with option `-dALLOWPSTRANSPARENCY`

**Comment by pjrramos** [comment]
I made some changes to the way I compile and it seems to solve the problem.
I chose to compile with PDF Chain and the default compiler can be LaTeX or PdfLaTeX because both options seem to solve the problem. Which one should I choose?
Now I got the following:
<img width="492" alt="Captura de ecrã 2021-02-23, às 22 53 32" src="https://user-images.githubusercontent.com/79539364/108918995-2ec07180-762a-11eb-99e2-86dfb4caa86e.png">

Thanks a lot for the help.

**Comment by agrahn** [comment]
There is no need to go the `latex`+`dvips`+`ps2pdf` route for typesetting, unless your documents contains PSTricks graphics. In that case, `ps2pdf` should be invoked with command line option `-dALLOWPSTRANSPARENCY` to get the drop shadows of the `beamer` theme right. And, of course, the current Ghostscript version `9.53.3` must be installed. Otherwise, `pdflatex` or `lualatex` will do.

**Comment by pjrramos** [comment]
Only now I notice that I started to have a problem. I need to put pictures on the slides with eps extension and now they don't appear. That's why I chose that way of compiling.

**Comment by samcarter** [comment]
@pjrramos  Can you make a minimal (non-)working example? pdflatex should convert eps images on the fly.

**Comment by pjrramos** [comment]
I am sorry but I have been doing some more research because I am not very familiar with some of the changes you have suggested.
I've been making changes to the preamble of the file. If I include \usepackage {pstricks}, I chose to compile with PDF Chain and compiled with LaTeX/PdfLaTeX/LuaLaTeX/XeLaTeX.
In the "usual" LaTeX files the figures reappeared and I stopped having problems with pictures with eps extension. In the tests I was doing I realized that if I don't include \usepackage {pstricks} in some documents the eps pictures will not appear. So in this case the problem seems to be solved.

However, there is still a problem when using Beamer. Compiling in the same way as I indicated before, regardless of using \usepackage {pstricks}, all images appear except one: the university logo, which is also an eps file. Before I wrote:
\ pgfdeclareimage [height = 1cm] {iselogo} {iselogo}
\ logo {\ pgfuseimage {iselogo}}
and everything worked fine but now the picture is gone.

**Comment by samcarter** [comment]
@pjrramos  You can use `pstricks` with pdf chains if you use the `auto-pst-pdf` package (need to be compiled with `--shell-escape` enabled). Or on https://texnique.fr/osqa/questions/9852/pourquoi-les-ombres-sur-le-theme-warsaw-de-beamer-se-mettent-en-premier-plan Bernard suggests to use `xelatex --shell-escape` with pstricks.

For your logo: Can you make a small, but compilable test document? Is the eps file of the logo available somewhere?

**Comment by pjrramos** [comment]
Please try this example:
[Arquivo.zip](https://github.com/josephwright/beamer/files/6035573/Arquivo.zip)

**Comment by samcarter** [comment]
@pjrramos  Can you try with the attached file?

[iselogo.pdf](https://github.com/josephwright/beamer/files/6035623/iselogo.pdf)

(there was some problem with the bounding box when converting this with ps2pdf, so I used mac preview.app to convert)

**Comment by pjrramos** [comment]
So your suggestion is that I should start using the university logo in PDF format?

Now everything seems to be fine!

**Comment by samcarter** [comment]
@pjrramos  Yes. Your eps file just contains a (rather low quality) pixel graphic and nothing specific to the eps format. You won't loose any features if you use it as pdf.

**Comment by pjrramos** [comment]
Yes you are right
I was now testing other presentations and with these changes another problem arose with the xy package, but I was also able to resolve this issue.
Thank you so much for your help.
Now I'm going to make these changes to the files I'm using.

**Comment by samcarter** [comment]
You're welcome!

**Comment by rachitdeshpande** [comment]
> I made some changes to the way I compile and it seems to solve the problem.
> I chose to compile with PDF Chain and the default compiler can be LaTeX or PdfLaTeX because both options seem to solve the problem. Which one should I choose?
> Now I got the following:
> <img alt="Captura de ecrã 2021-02-23, às 22 53 32" width="492" src="https://user-images.githubusercontent.com/79539364/108918995-2ec07180-762a-11eb-99e2-86dfb4caa86e.png">
> 
> Thanks a lot for the help.

Were you able to solve the problem in the given image? I am facing the same issue. I am compiling using LuaLaTeX.
![snap](https://user-images.githubusercontent.com/17661599/122590745-9be78f00-d07f-11eb-871d-acb560d55d22.jpg)

**Comment by samcarter** [comment]
@rachit2606 Are you using any special fonts? 

See also this related open issue at https://github.com/josephwright/beamer/issues/647 in case you want to subscribe to it

**Comment by rachitdeshpande** [comment]
> @rachit2606 Are you using any special fonts?
> 
> See also this related open issue at #647 in case you want to subscribe to it
Thank you
Yeah, I am using calibri and times new roman (package used is fontspec).

**Comment by samcarter** [comment]
> > @rachit2606 Are you using any special fonts?
> > See also this related open issue at #647 in case you want to subscribe to it
> > Thank you
> > Yeah, I am using calibri and times new roman (package used is fontspec).

@rachit2606 Then this seems indeed to be the same problem as in #647, unfortunately I did not yet find a solution, sorry!  (Update: this has been fixed)
