### ISSUE TITLE
pdftitle not appearing in PDF file

### ISSUE THREAD

**Issue by juliangilbey** [josephwright/beamer#670]
Hi!  Thanks for maintaining beamer!

With the current TeXLive distribution (Debian version 2020.20210202-3, beamer version 2020/11/26 v3.60), the PDF title field is not being set.  Here's a minimal example:

```latex
\documentclass{beamer}

\title{My excellent talk}
\author{A. U. Thor}
\date{March 2021}

\begin{document}

\begin{frame}
  \titlepage
\end{frame}

\end{document}
```

The resulting PDF has this info:
```
$ pdfinfo beamer-minimal.pdf
Title:          
Subject:        
Keywords:       
Author:         A. U. Thor
Creator:        LaTeX with Beamer class
Producer:       pdfTeX-1.40.21
[...]
```

I know this used to work as advertised; my colleague running an older version of TeXLive on the same document as me does obtain a correct PDF title.

So something has broken somewhere :-(

**Comment by samcarter** [comment]
mmm, the problem seems to be that `\g@addto@macro\beamer@firstminutepatches{...}` stopped working sometime between the TL2020 release and now...

```
\documentclass{beamer}

\makeatletter
\g@addto@macro\beamer@firstminutepatches{
  \typeout{Quack}  
}
\makeatother
\begin{document}

\begin{frame}
  \titlepage
\end{frame}

\end{document}
```

**Comment by samcarter** [comment]
digging further, It seems this hook thingy does not get executed:

https://github.com/josephwright/beamer/blob/main/base/beamerbasecompatibility.sty#L86

**Comment by josephwright** [comment]
Drat: the code we have dates to an older version of the hooks. I'll correct and release.

**Comment by juliangilbey** [comment]
Thanks @josephwright!
