### ISSUE TITLE
Annoying lonely dot displayed when combining "sections numbered" and "firstsection=2" (or more)

### ISSUE THREAD

**Issue by pagiraud** [josephwright/beamer#674]
Hi,
Here is a MWE:
```
\documentclass{beamer}
\setbeamertemplate{section in toc}[sections numbered]
\begin{document}
	\begin{frame}{TOC}
		\tableofcontents[firstsection=2]
	\end{frame}
	\section{Introduction}
	\begin{frame}{dummy title}
dummy
	\end{frame}
	\section{First part}
	\begin{frame}{title}
	dummy
\end{frame}
\end{document}
```
As you can see if you compile this code, in the TOC the word "Introduction" is preceded by a dot. In my opinion, it should not be. I understand that keeping and empty circle, square or ball is the good option, but for `sections numbered` I think the dot, which is only a separator between the (absent) number and the section title, shouldn’t be displayed in this case.

Thanks for taking my suggestion into account.

**Comment by samcarter** [comment]
As a workaround:
```
\documentclass{beamer}
\setbeamertemplate{section in toc}[sections numbered]
\begin{document}
	\begin{frame}{TOC}
		\tableofcontents[]
	\end{frame}
	\section*{Introduction}
  \addtocontents{toc}{\color{structure.fg}Introduction}
	\begin{frame}{dummy title}
dummy
	\end{frame}
	\section{First part}
	\begin{frame}{title}
	dummy
\end{frame}
\end{document}
```

**Comment by samcarter** [comment]
As a workaround:
```
\documentclass{beamer}
\setbeamertemplate{section in toc}[sections numbered]
\begin{document}
	\begin{frame}{TOC}
		\tableofcontents[]
	\end{frame}
	\section*{Introduction}
  \addtocontents{toc}{\color{structure.fg}Introduction}
	\begin{frame}{dummy title}
dummy
	\end{frame}
	\section{First part}
	\begin{frame}{title}
	dummy
\end{frame}
\end{document}
```

**Comment by samcarter** [comment]
Or this template:

```
\documentclass{beamer}

\makeatletter
\setbeamertemplate{section in toc}{%
  \leavevmode%
  \ifnum\beamer@tempcount>0
    \inserttocsectionnumber. 
  \fi%
  \inserttocsection\par}
\makeatother

\begin{document}
	\begin{frame}{TOC}
		\tableofcontents[firstsection=2]
	\end{frame}
	\section{Introduction}
	\begin{frame}{dummy title}
dummy
	\end{frame}
	\section{First part}
	\begin{frame}{title}
	dummy
\end{frame}
\end{document}
```

**Comment by pagiraud** [comment]
Thank you @samcarter 
I already tried that. I even added a `\label` and a `\hyperref` to have clickable links:

```
\documentclass{beamer}
\setbeamertemplate{section in toc}[sections numbered]
\begin{document}
	\begin{frame}{Sommaire}
		\tableofcontents[]
	\end{frame}
	\section*{Introduction}
        \addtocontents{toc}{\color{structure.fg}\hyperref[sec:intro]{Introduction}}
        \label{sec:intro}
	\begin{frame}{Introduction}
dummy
	\end{frame}
	\section{First part}
	\begin{frame}{title}
	dummy
\end{frame}
\end{document}
```
But it fails when, later in the document, using `\AtBeginSection`, I use `\tableofcontents[sectionstyle=show/shaded,subsectionstyle=show/show/hide]`: the `\section*{}` appear as if they were current sections.

**Comment by pagiraud** [comment]
> Or this template:
> 
> ```
> \documentclass{beamer}
> 
> \makeatletter
> \setbeamertemplate{section in toc}{%
>   \leavevmode%
>   \ifnum\beamer@tempcount>0
>     \inserttocsectionnumber. 
>   \fi%
>   \inserttocsection\par}
> \makeatother
> 
> \begin{document}
> 	\begin{frame}{TOC}
> 		\tableofcontents[firstsection=2]
> 	\end{frame}
> 	\section{Introduction}
> 	\begin{frame}{dummy title}
> dummy
> 	\end{frame}
> 	\section{First part}
> 	\begin{frame}{title}
> 	dummy
> \end{frame}
> \end{document}
> ```

That worked perfectly, thank you @samcarter !
