### ISSUE TITLE
[Feature suggestion] Add a lastsection option to \tableofcontents

### ISSUE THREAD

**Issue by pagiraud** [josephwright/beamer#675]
Hi again,
I think it would be great if `\tableofcontents`had a `lastsection` option that could be used in the same way as `firstsection`.
At least in social sciences, the usual TOC start with "Introduction" and ends with "Conclusion". None of them is generally numbered.
The `firstsection=<section number>` option is great to achieve this for Introduction, but Beamer lacks a similar option for excluding eg. conclusions from numbering in TOC.
So, I think a `lastsection=<section number from last>` would be great. For instance, for excluding only last section, it could be `lastsection=2`. Another solution would be to use negative numbers to indicate a count from max value, but I have never seen such a thing in LaTeX.

Thanks for taking my suggestion into account.

**Comment by samcarter** [comment]
Like in #674 I would use an unnumbered section in this case

**Comment by pagiraud** [comment]
Yes, but like in #674 `sectionstyle=show/shaded` would not work correctly.

**Comment by samcarter** [comment]
You could add your own stopping criteria: 

```
\documentclass{beamer}

\newcounter{lastsection}
\setcounter{lastsection}{4}

\makeatletter
\setbeamertemplate{section in toc}{%
  \leavevmode%
  \ifnum\beamer@tempcount>0
    \ifnum\thelastsection>\beamer@tempcount
      \inserttocsectionnumber. 
  \fi\fi%
  \inserttocsection\par}
\makeatother

\begin{document}
	\begin{frame}{TOC}
		\tableofcontents[firstsection=2]
	\end{frame}
	\section{Introduction}
	\begin{frame}{dummy title}
dummy
	\end{frame}
	\section{1 part}
	\begin{frame}{title}
	dummy
\end{frame}

	\section{2 part}
	\begin{frame}{title}
	dummy
\end{frame}

	\section{3 part}
	\begin{frame}{title}
	dummy
\end{frame}

	\section{Summary}
	\begin{frame}{title}
	dummy
\end{frame}

\end{document}
```

**Comment by pagiraud** [comment]
Thanks again, @samcarter that is a very clever workaround… I thought about using the totcount package but I didn’t know what counter I should use. Nevertheless, I still think it could be an interesting feature.

**Comment by pagiraud** [comment]
I modified your workaround using totcount so that one doesn’t have to manually count the sections.
```
\documentclass{beamer}
\usepackage{totcount}

\regtotcounter{section}
\newcounter{lastsection}

\makeatletter
\setbeamertemplate{section in toc}{%
	\leavevmode%
	\ifnum\beamer@tempcount>0
	\ifnum\thelastsection>\beamer@tempcount
	\inserttocsectionnumber. 
	\fi\fi%
	\inserttocsection\par}
\makeatother

\begin{document}
	\begin{frame}{TOC}
		\setcounter{lastsection}{\totvalue{section}}
		\addtocounter{lastsection}{-1}
		\tableofcontents[firstsection=2]
	\end{frame}
	\section{Introduction}
	\begin{frame}{dummy title}
		dummy
	\end{frame}
	\section{1 part}
	\begin{frame}{title}
		dummy
	\end{frame}
	
	\section{2 part}
	\begin{frame}{title}
		dummy
	\end{frame}
	
	\section{3 part}
	\begin{frame}{title}
		dummy
	\end{frame}
	
	\section{Summary}
	\begin{frame}{title}
		dummy
	\end{frame}
	
\end{document}
```
