### ISSUE TITLE
not perferct shadow

### ISSUE THREAD

**Issue by jszhao** [josephwright/beamer#678]
The issue could be replicated by the following code:
```
\documentclass{beamer}
\usetheme{Madrid}

\usepackage{fourier}
\usefonttheme{serif}

\title{\Huge A test}

\begin{document}

\begin{frame}[plain]
   \maketitle
\end{frame}

\end{document}
```

You may notice the vertical white  bar at the right margin of the blue frame.

If we remove `\usefonttheme{serif}` from the above code, the white bar disappear.

![serif](https://user-images.githubusercontent.com/12680518/116020272-8b66f980-a678-11eb-950e-6fecd8443958.png)

This issue may be introduced into beamer with v3.60. I happened to have two PDF file before and after Dec. 14, 2020.
![before and after v3 60](https://user-images.githubusercontent.com/12680518/116020043-17c4ec80-a678-11eb-9568-78a5f1ab2e86.png)

**Comment by samcarter** [comment]
Thanks for reporting! This also happens for some other non-standard fonts, see the duplicate https://github.com/josephwright/beamer/issues/647
