### ISSUE TITLE
The first page contains inconsistent sentences.

### ISSUE THREAD

**Issue by mauler2025** [josephwright/beamer#680]
Type `texdoc beamer` and read the first page. The first page of the documentation shows the following inconsistency. I don't need to post MWE because it does not make sense.

![test](https://user-images.githubusercontent.com/50270635/117761353-67e3a780-b251-11eb-98b7-23d99736137f.png)

Severity: Harmless!

**Comment by samcarter** [comment]
Can you add a minimal working example we can copy&paste to reproduce the issue?

**Comment by mauler2025** [comment]
@samcarter : It does not make sense to ask MWE here. You just need to open the source file of Beamer documentation and change the sentence to match against the rendered output.

**Comment by samcarter** [comment]
Ah, it is from the documentation. That would have been good to know! I thought something was broken....
