### ISSUE TITLE
Overlay specification for \label does not work with beamerarticle

### ISSUE THREAD

**Issue by Boggy-B** [josephwright/beamer#685]
At some point between version 3.58 and version 3.62 of the beamerarticle package, the overlay specification for the \label command stopped working (or was deliberately changed in a way I don't understand). Consider the following example:
```
\documentclass{article}
\usepackage{beamerarticle}
%\documentclass{beamer}
\usepackage{hyperref}

\begin{document}

\section{Name}

\begin{frame}{}
	Text
	
	\only<2>{More text}\label<2>{a}
	
	Ref: \ref{a}
\end{frame}

\end{document}
```
As I understand it, the overlay specification for labels should be ignored in article mode. Instead of that, when I compile this file with the newest version of beamerarticle (v3.62), the reference "a" is undefined. However, when I compile the same file on a system with beamerarticle v3.58, the reference displays 1 (the section number), as intended.

In the analogous beamer file
```
%\documentclass{article}
%\usepackage{beamerarticle}
\documentclass{beamer}
\usepackage{hyperref}

\begin{document}

\section{Name}

\begin{frame}{}
	Text
	
	\only<2>{More text}\label<2>{a}
	
	Ref: \ref{a}
\end{frame}

\end{document}
```
the reference works on both systems.

**Comment by samcarter** [comment]
The problem seems to be starting with commit 877c44c

**Comment by samcarter** [comment]
@josephwright  Could you take a look? I tried without the optional `beamer` argument in 

```
\AddToHook{env/begin/document}{...}
```

but the content still does not get executed with `article` class

**Comment by samcarter** [comment]
@Boggy-B  Thanks for reporting!

in case you need a workaround until this is fixed, you could use

```
\documentclass{article}
\usepackage{beamerarticle}
%\documentclass{beamer}
\usepackage{hyperref}

\makeatletter
\mode
<article>
{
      \let\beamer@origdocument\document
      \def\document{%
        \beamer@origdocument%
        \beamer@lastminutepatches}
}
\makeatother

\begin{document}

\section{Name}

\begin{frame}{}
	Text
	
	\only<2>{More text}\label<2>{a}
	
	Ref: \ref{a}
\end{frame}

\end{document}
```

**Comment by josephwright** [comment]
I see the issue: I've added to the wrong hook. Using
```latex
\makeatletter
\AddToHook{begindocument/end}[beamer]
 {\beamer@lastminutepatches}
\makeatother
```
in the preamble as a fix and I'll adjust the release code to do exactly that.

**Comment by samcarter** [comment]
@josephwright  Thanks!
