### ISSUE TITLE
(Doc) Error in example on usage of templates

### ISSUE THREAD

**Issue by titanic-jb** [josephwright/beamer#687]
The actual manual, v3.63 from 2021-05-26 contains an error.

In chapter 16.3.3, Setting Beamer’s Templates, on page 175, you give in the middle of the page the example, how to use the freshly defined "my shading“ template.

Actually it reads  

`\setbeamertemplate{background canvas}{myshading}{red!10}{blue!10}`

but it must be corrected in

`\setbeamertemplate{background canvas}[my shading]{red!10}{blue!10}`

to get it working.  (The second pair of braces has to be converted to `[]` and `myshading` lacks the space between `my` and `shading`.)

**Comment by samcarter** [comment]
@titanic-jb  Thanks for reporting!
