### ISSUE TITLE
(Doc) typo in User Guide

### ISSUE THREAD

**Issue by titanic-jb** [josephwright/beamer#689]
I found a typo in the user guide.

- On page 213: `“flavors,”`, the comma needs to be outside the quotes.

**Comment by josephwright** [comment]
That's a US vs UK thing - using US conventions, the comma goes inside the quotes even though it's not semantically part of the quoted text.

**Comment by titanic-jb** [comment]
Thank you for this insight.  You'll never stop learning. :-)
