### ISSUE TITLE
Top alignment issues

### ISSUE THREAD

**Issue by kougar** [josephwright/beamer#692]
Hi,

I noticed some alignment issues with beamer, as with my examples here. I'm using top alignment.

1, Seems there's an extra line down with columns, as you can see the difference of P6 and P7, also P10 and P11.
2, It's about one extra line up with pictures drawn by tikzpicture, as showed on P8.
3, Latex equations is also not strictly aligned as others, P9.

What I want is a strict top alignment regardless of columns or text or pictures.
I don't exactly have the beamer version but I'm using EMACS 27.1.

[beamer.pdf](https://github.com/josephwright/beamer/files/6614027/beamer.pdf)
[beamer.tex.txt](https://github.com/josephwright/beamer/files/6614030/beamer.tex.txt)
[beamer.org.txt](https://github.com/josephwright/beamer/files/6614081/beamer.org.txt)

Thanks.

**Comment by samcarter** [comment]
1. vertical position of non-text elements

   you can either 

   - ensure a consistent alignment by using a consistent layout, e.g. also put the non-column frame in a one-column layout 
   - manually add a negative space, see https://topanswers.xyz/tex?q=1822#a2053

2. Tikzpicture alignment

   You are missing the `T` option to top align your columns. This option will ensure that the top of the tikzpicture will be aligned with the top of the first text line.

   ```
   \documentclass[t]{beamer}
   \usepackage{tikz}

   \begin{document}

   \begin{frame}
   \begin{columns}[T,onlytextwidth]
   \begin{column}{0.4\columnwidth}
   This is how normal text looks
   \end{column}
   \begin{column}{0.57\columnwidth}
   \begin{tikzpicture}
   \draw[->] (-3,0) -- (-2,0) arc[radius=0.5cm,start angle=-180,end angle=0] (-1,0) -- (1,0) arc[radius=0.5cm,start angle=180,end angle=0] (2,0) -- (3,0);
   \filldraw (-1.5,0) circle[radius=1mm];
   \filldraw (1.5,0) circle[radius=1mm];
   \end{tikzpicture}
   \end{column}
   \end{columns}
   \end{frame}

   \end{document}
   ```

3. Equations

   not sure how you want to align your equations. They are not next, they have a different height than text and space around them. 


Off-topic:

- you don't need to load `graphicx`, `amsmath`, `amssymb`, `hyperref` -- beamer loads them for you
- with an up-to-date latex distribution, there is little need to load `grffile`
- don't load the same package more than once, e.g. `tikz`, `fontenc`
- you don't need to manually use `\hypersetup{...}`, beamer set all these things like title and author automatically

**Comment by kougar** [comment]
@samcarter Thank you so much for your help!
1, I can make the column alignment work with the negative space, do you know how to do that in org mode? Why does it add this extra line in the first place?
2, It also works after changing the tex file, the same questions is how to add that to the org file?
3, I mean align at the top as normal text or columns, but I can survive if that's not applicable ;)

I'm new to latex and org, just googling around to get pieces here and there, some of them may be outdated.

Really appreciate your off topic suggestions, I don't add them in the org file, as you know the tex file is generated from org. Where do you think they came from? Seems they're from my dot file, but I'm adding them to two different org-latex-classes which are not referred by beamer at all (I do use them when exporting to pdf articles).
[dot_emacs.txt](https://github.com/josephwright/beamer/files/6615264/dot_emacs.txt)

**Comment by samcarter** [comment]
Sorry, I'm not an org user, so can't help with that. 

While I see the appeal to use such a simplified input for normal text documents, I personally would not recommend this approach with beamer. For such a thing like a visual presentation, the frames need to be carefully constructed to best convey your message - this *does* sometimes require a bit of manual tweaking, which is much easier if you can directly interact with the latex code.

**Comment by kougar** [comment]
OK, make sense.
Thanks again.

**Comment by samcarter** [comment]
@kougar  You're welcome!
