### ISSUE TITLE
Undefined Control Sequence when compiling 

### ISSUE THREAD

**Issue by krodolfo** [josephwright/beamer#703]
Hi,
I've recently encountered an "undefined Control Sequence during compilation of my beamer class presentation. I've pinpointed the error in the following .sty file:
**beamerbasetoc.sty**

The error message reads:
**Undefined control sequence.
l.110 \beamer@toclastsection
                            =\maxdimen**

It seems that all of a sudden \maxdimen has become zero.  I'm not sure how to remedy this? Can anyone please help?

**Comment by samcarter** [comment]
Can you please make a minimal working example and show the .log file?

The following example works without problems for me:

```
\documentclass{beamer}

\setbeamertemplate{sections/subsections in toc}[sections numbered]

\begin{document}

\begin{frame}
\tableofcontents[lastsection=1]
\end{frame}

\section{title}
	
\begin{frame}
	abc
\end{frame}	

\section{title}
	
\begin{frame}
	abc
\end{frame}	
	
\end{document}
```

**Comment by samcarter** [comment]
I'm closing this until we get further information.

**Comment by krodolfo** [comment]
I've managed to resolve the issue by reinstalling MikTeX.  Thanks
