### ISSUE TITLE
Change default frame alignment in theme

### ISSUE THREAD

**Issue by BeastyBlacksmith** [josephwright/beamer#705]
I might be doing something stupid, but I try to change the default alignment of frames to top aligned in a custom theme

Currently I do it via
```latex
\beamer@centeredfalse
```
but this has the downside that you can't undo it anymore in the document for single frames with
```latex
\begin{frame}[c]
\end{frame}
```
Is there a better way to do this?

**Comment by samcarter** [comment]
That's the same approach I use for my themes. Can you make a minimal working example that allows us to reproduce your problem with switching back to centred frames? 

The following code seems to work fine:

```
\documentclass{beamer}

\makeatletter
\beamer@centeredfalse
\makeatother


\begin{document}
	
\begin{frame}
	abc
\end{frame}	

\begin{frame}[c]
	abc
\end{frame}	

\begin{frame}
	abc
\end{frame}	
	
\end{document}
```

<img width="350" alt="Screenshot 2021-09-01 at 21 39 35" src="https://user-images.githubusercontent.com/43832342/131733632-7b08f056-daea-4f54-b551-6363ed6599cd.png">

**Comment by BeastyBlacksmith** [comment]
> Yesterday it worked
Today it is not working
Software is like that.

Can't reproduce anymore ^^, thanks for confirming
