### ISSUE TITLE
Odd interaction with polyglossia and ignorenonframetext on xelatex/texlive 2021

### ISSUE THREAD

**Issue by jgm** [josephwright/beamer#706]
Consider the following:
```
\documentclass[
  ngerman,
  ignorenonframetext
]{beamer}
\usepackage{amsmath,amssymb}
\usepackage{unicode-math}
\defaultfontfeatures{Scale=MatchLowercase}
\defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\usetheme[]{metropolis}
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}

% Load polyglossia as late as possible: uses bidi with RTL langages (e.g. Hebrew, Arabic)
\usepackage{polyglossia}
\setmainlanguage[]{german}

\title{Testfolien}
\author{Author}
\date{03.08.2021}

\begin{document}
\frame{\titlepage}

\hypertarget{der-titel}{%
\section{Der Titel}\label{der-titel}}

\begin{frame}{Eine Folie}
\begin{figure}
\centering
IMAGE
\caption{Ein buntes Bild}
\end{figure}
\end{frame}

\end{document}
```

- When compiled with xelatex and the versions of packages in texlive 2020, we get "Abbildung" in the caption.
- Doing the same thing with texlive 2021, we get "Figure" instead of "Abbildung".
- Removing the `ignorenonframetext` class option makes it "Abbildung" again.

This seems to be xelatex/polyglossia specific; with lualatex or pdflatex and babel I don't see the issue.

Anyway, something changed in the packages between texlive 2020 and 2021 that causes this problem.  I have no idea whether the change was in polyglossia or beamer, but reporting it here seems a good start.

See: https://github.com/jgm/pandoc/issues/7539

**Comment by samcarter** [comment]
M(N)WE:

```
\documentclass[
  ignorenonframetext,
]{beamer}

\usepackage{polyglossia}
\setmainlanguage[]{german}

\begin{document}

\begin{frame}
\begin{figure}
\caption{Ein buntes Bild}
\end{figure}
\end{frame}

\end{document}
```

**Comment by samcarter** [comment]
It works if I switch back to an older kernel:
```
% !TeX TS-program = xelatex
\RequirePackage[2020/02/02]{latexrelease}
\documentclass[
  ignorenonframetext,
]{beamer}

\usepackage{polyglossia}
\setmainlanguage[]{german}

\begin{document}

\begin{frame}
\begin{figure}
\caption{Ein buntes Bild}
\end{figure}
\end{frame}

\end{document}
```

**Comment by samcarter** [comment]
... seems to be connected to

https://github.com/josephwright/beamer/blob/ec2ce6ba8a9d93e9ac376fcba651ff2ada204f9f/base/beamerbasecompatibility.sty#L54-L111

If I force the execution of the else branch I do get the correct translation

**Comment by samcarter** [comment]
if I remove the hook from beamer and add it again after `polyglossia`, it also works:

```
% !TeX TS-program = xelatex
%\RequirePackage[2020/02/02]{latexrelease}
\RequirePackage[2020/10/01]{latexrelease}
\documentclass[
  ignorenonframetext,
]{beamer}



\usepackage{polyglossia}
\setmainlanguage[]{german}

\makeatletter
    \AddToHook{begindocument/end}[beamer]%need to be later than spanish.ldf?
      {%
        \@ifundefined{deactivatequoting}{}{\deactivatequoting}%
        % Fix meddline with enumerate items
        \renewcommand\theenumi{\@arabic\c@enumi}%
        \renewcommand\theenumii{\@arabic\c@enumii}%
        \renewcommand\theenumiii{\@arabic\c@enumiii}%
        \catcode`<=12 \catcode`>=12 %% right place??
        \beamer@lastminutepatches
        \ifbeamer@ignorenonframe
         \expandafter\mode\expandafter*%
       \fi
      }%
\makeatother


\begin{document}

\begin{frame}

\begin{figure}
\caption{Ein buntes Bild}
\end{figure}
\end{frame}

\end{document}
```

**Comment by samcarter** [comment]
@josephwright Is there any way to make sure the hook

https://github.com/josephwright/beamer/blob/ec2ce6ba8a9d93e9ac376fcba651ff2ada204f9f/base/beamerbasecompatibility.sty#L68

gets executed after the AtBeginDocument code from  polyglossia?

```
\AtBeginDocument{
  \polyglossia@AtBeginDocument:
}
```

**Comment by samcarter** [comment]
A hack to force the hook to come later https://github.com/samcarter/beamer/commit/c1508289befc4fe669906cd95ccf691355ff1384 , but I hope the hook-magician might have a clean solution...

**Comment by davidcarlisle** [comment]
@samcarter you should be able to use \DeclareHookRule to specify that the ployglossia entry is execured first, but beamers nested structure means finding the right label is interesting something like

`\DeclareHookRule{begindocument}{beamerouterthememetropolis}{after}{polyglossia}`

(except it doesn't work-)

**Comment by davidcarlisle** [comment]
This works I think:

```
\documentclass[
  ngerman,
  ignorenonframetext
]{beamer}

\DeclareHookRule{begindocument/end}{beamer}{after}{polyglossia}
```

**Comment by samcarter** [comment]
@davidcarlisle  Nice! Thanks a lot! 

(This will at least solve the polyglossia problem. Only one trillion other packages out there using `\AtBeginDocument`)
