### ISSUE TITLE
Double "itemize" environment

### ISSUE THREAD

**Issue by pjrramos** [josephwright/beamer#708]
Using beamer, when we put the "itemize" environment inside another "itemize" environment, the font size of the second "itemize" becomes much larger.
<img width="421" alt="Captura de ecrã 2021-09-11, às 11 59 20" src="https://user-images.githubusercontent.com/79539364/132945580-4a6881fa-af51-4b4f-b966-da8d90a5154b.png">

Thank you for your help.

**Comment by samcarter** [comment]
Please make a minimal working example that reproduces the problem. For me the following works fine:

```
\documentclass{beamer}

\begin{document}
	
\begin{frame}
   \begin{itemize}
     \item test
    \begin{itemize}
      \item test
    \end{itemize}
  \end{itemize}
\end{frame}	
	
\end{document}
``` 

<img width="373" alt="Screenshot 2021-09-11 at 13 44 58" src="https://user-images.githubusercontent.com/43832342/132947026-1981edea-2626-4c83-9b37-eaa3cbbeb909.png">

**Comment by pjrramos** [comment]
With your code:
<img width="100" alt="Captura de ecrã 2021-09-11, às 13 42 27" src="https://user-images.githubusercontent.com/79539364/132948258-b7cdf0df-b40d-423b-b6c8-d60b26d45b64.png">

In the header I put:
\documentclass{beamer}

\mode<presentation>
{
  \usetheme{Warsaw}

  \setbeamercovered{transparent}
}

\usepackage[english]{babel}
\usepackage[latin1]{inputenc}
\usepackage{times}
\usepackage[T1]{fontenc}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{mathrsfs}
\usepackage{dsfont}
\usepackage{mathabx}
\usepackage[pdf]{pstricks}

It has the same size?

**Comment by samcarter** [comment]
Your syntax of `\mode` is wrong, you need to tell it which mode you want, e.g.

```
\mode<presentation>{
\usetheme{Warsaw}
\setbeamercovered{transparent}
}
```

If I fix this and use your preamble I get the expected output of a smaller subitem:

```
\documentclass{beamer}

\mode<presentation>{
\usetheme{Warsaw}
\setbeamercovered{transparent}
}

\usepackage[english]{babel}
\usepackage[latin1]{inputenc}
\usepackage{times}
\usepackage[T1]{fontenc}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{mathrsfs}
\usepackage{dsfont}
\usepackage{mathabx}
\usepackage[pdf]{pstricks}

\begin{document}
	
\begin{frame}
   \begin{itemize}
     \item test
    \begin{itemize}
      \item test
    \end{itemize}
  \end{itemize}
\end{frame}	
	
\end{document}
```

<img width="635" alt="Screenshot 2021-09-11 at 14 56 44" src="https://user-images.githubusercontent.com/43832342/132948585-a6b12543-f3df-4ad3-b9d1-cdd9f4a2702f.png">

**Comment by samcarter** [comment]
Unrelated to your question, but

- `\usepackage[latin1]{inputenc}` unless you have a very old operating system and/or editor, your files are probably encoded in utf8 and not latin1. Double check if you are really using the correct option here
- `\usepackage{times}` is obsolete and should no longer be used. Have a look at the mathptmx, helvet (option scaled=.9) or courier packages instead
- `\usepackage{amsmath} \usepackage{amsfonts} \usepackage{amssymb}` not necessary, beamer loads ams for you

**Comment by pjrramos** [comment]
Thank you very much for your help.

The following code was correct:

```
\mode<presentation>{
\usetheme{Warsaw}
\setbeamercovered{transparent}
}
```

I deleted `<presentation>` by mistake.

However, you are absolutely right. My preamble is completely out of date and your suggestions are very helpful. I'll change it and see the final result.

**Comment by samcarter** [comment]
I think I know what's going on. Github won't show `<...>` if not surrounded by backticks to mark it as code. I edited your previous comment to make them visible.

**Comment by samcarter** [comment]
@pjrramos You can find a short intro how to type code in github at https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by FilipDominec** [comment]
@samcarter I would like to reopen this issue, as sub-items do not honour the locally set font size. 

Quite often I need to sort ideas into nested sublists, and to use a smaller font. So a sample document source looks like:

```latex
\documentclass[t]{beamer} 
\begin{document}

\begin{frame}
	
	Text 

	\tiny

	Tiny text 

	\begin{enumerate}
	  \item tiny list
	  \begin{enumerate}
		\item sublist items are big 
		\item again, which is 
		\item unexpected and ugly
	  \end{enumerate}
	  \item tiny list
	\end{enumerate}

\end{frame}

\end{document}
```

The problem is that by default, sublist items in beamer have pre-defined fixed (a bit smaller) font size, which does not respect previous font size settings:

![latex](https://user-images.githubusercontent.com/511950/202907663-94cb781d-910e-4d18-8696-3eb7f8a0ecfa.png)

I could not find any solution to this, except a global setting ``` \setbeamertemplate{itemize/enumerate subbody begin}{\tiny} ```, but this is certainly not the right approach. 

Note that plain LaTeX documents do not suffer this issue.

**Comment by samcarter** [comment]
@FilipDominec You don't need to change the font size globally, you can do it locally:

```
\documentclass[t]{beamer} 
\begin{document}

\begin{frame}
	
	Text 

	\tiny
        \setbeamerfont{itemize/enumerate subbody}{size=\tiny}

	Tiny text 

	\begin{enumerate}
	  \item tiny list
    
	  \begin{enumerate}
		\item sublist items are big 
		\item again, which is 
		\item unexpected and ugly
	  \end{enumerate}
    
	  \item tiny list
	\end{enumerate}

\end{frame}

\end{document}
```

**Comment by FilipDominec** [comment]
I see, but - 
1. This syntax is somewhat bulky and totally redundant to my choice of ```\tiny```,
2. it does not integrate well with pandoc's markdown.

Could this font size change be made just relative to the outer font? Or, if not, could such a feature be disabled by a single command in the header, so that all list levels have font size same the 1st level?

**Comment by samcarter** [comment]
For your personal use, you can use the `relsize` package to define relative font sizes:

```
\documentclass[t]{beamer} 
\usepackage{relsize}
\setbeamerfont{itemize/enumerate subbody}{size=\smaller}
\begin{document}

\begin{frame}
	
	Text 

	\tiny


	Tiny text 

	\begin{enumerate}
	  \item tiny list
    
	  \begin{enumerate}
		\item sublist items are big 
		\item again, which is 
		\item unexpected and ugly
	  \end{enumerate}
    
	  \item tiny list
	\end{enumerate}

\end{frame}

\end{document}
```

**Comment by FilipDominec** [comment]
@samcarter Thank you, these two lines in the preamble solve the problem. I have been trying ```relsize```, too, but was missing the correct syntax so it did no change. 

Surely this trick will be useful for many other beamer users.

**Comment by dbitouze** [comment]
Maybe related: #638.
