### ISSUE TITLE
`kpfonts` requires `professionalfonts` theme

### ISSUE THREAD

**Issue by dbitouze** [josephwright/beamer#711]
Despite:
- 1387b6e,
- what is claimed in the documentation:
  > Note that ʙᴇᴀᴍᴇʀ’s substitution is automatically turned off if one of the following packages, is loaded: [...], `kpfonts`, [...].

`kpfonts` still requires `professionalfonts` theme.

Indeed, the following MCE:

```latex
\documentclass{beamer}
\usepackage{kpfonts}
% \usefonttheme{professionalfonts}
\setbeamertemplate{navigation symbols}{}
\begin{document}
\begin{frame}
  $\implies$
\end{frame}
\end{document}
```
gives (with both `(pdf|xe|lua)latex`), if the `professionalfonts` theme is:
- _not_ loaded:
  ![image](https://user-images.githubusercontent.com/1032633/134807148-13d777b6-fda4-495c-8a78-419f661cd00d.png)
- loaded:
![image](https://user-images.githubusercontent.com/1032633/134807237-dcad85e9-c544-4d7d-8429-2875da82f8f5.png)

Note that `kpfonts-otf`, the OTF versions of `kpfonts`, is not affected.

**Comment by samcarter** [comment]
The code to suppress the font replacement is

```
  \@ifpackageloaded{kpfonts}{\ifbeamer@sansmath\else\beamer@suppressreplacementstrue\fi}{}%
```

so this only kicks in if serif math is used, e.g.

```
\documentclass{beamer}

\usefonttheme[onlymath]{serif}

\usepackage{kpfonts}

\begin{document}
\begin{frame}
 abc $abc \implies$
\end{frame}
\end{document}
```

<img width="331" alt="Screenshot 2021-09-26 at 14 34 52" src="https://user-images.githubusercontent.com/43832342/134808278-67fb9ac9-8b7e-419b-9076-81b3673c012a.png">

On the other hand, the `professionalfonts` theme will always suppress the replacement.

**Comment by dbitouze** [comment]
Good point!

IMHO, since `beamer` automatically switches to sans serif, even for math, the font replacement should always be suppressed.

**Comment by samcarter** [comment]
@dbitouze  Well, that's exactly the problem! 

> since beamer automatically switches to sans serif, even for math

If you suppress the replacement, you won't get sans serif math anymore because kpfonts uses serif math as default. The `\implies` in the comment above only works because it uses the *serif* kp math font  and not the sans serif of the surrounding text.

**Comment by samcarter** [comment]
I think the best approach would be to use the sans serif math font from kpfonts to avoid the problem with mixing serif and sans serif symbols:

```
\documentclass{beamer}

\usepackage{kpfonts}
\mathversion{sf}

\begin{document}
\begin{frame}
 abc $abc \implies$
\end{frame}
\end{document}
```

or

```
\documentclass{beamer}

\usefonttheme{professionalfonts}
\usepackage[sfmath]{kpfonts}

\begin{document}
\begin{frame}
 abc $abc \implies$
\end{frame}
\end{document}
```

**Comment by dbitouze** [comment]
>If you suppress the replacement, you won't get sans serif math anymore.

Well, with the `professionalfonts` theme, that's indeed the case with `(xe|lua)latex`, but not with `pdflatex` :interrobang::

```latex
\documentclass{beamer}
\usepackage{kpfonts}
\usefonttheme{professionalfonts}
\setbeamertemplate{navigation symbols}{}
\begin{document}
\begin{frame}
  abc $abc \implies$
\end{frame}
\end{document}
```
gives with:
- `(xe|lua)latex`:
![image](https://user-images.githubusercontent.com/1032633/134809372-83644b56-f526-4865-863b-2d1e37c58bca.png)
- `pdflatex`:
![image](https://user-images.githubusercontent.com/1032633/134809492-b62a217a-b95e-4674-b332-1868d4804c7b.png)

**Comment by samcarter** [comment]
Your screenshot shows serif math for both cases. 

The difference in text font is because the fonts lualatex wants to use don't exists

```
LaTeX Font Warning: Font shape `TU/jkpss/m/n' undefined
(Font)              using `TU/lmr/m/n' instead on input line 7.
```

**Comment by dbitouze** [comment]
Well, I'm a bit lost.

> I think the best approach would be to use the sans serif math font from `kpfonts` for the arrow tip.

 Do you mean, this should be enabled automatically by `beamer` (OK, this would break existing documents) or by the user ?

**Comment by samcarter** [comment]
@josephwright  What would you think of https://github.com/samcarter/beamer/commit/0a76c53f0c4ae8e865e97193ecd89f435d4a3203 ? 

The font used for sans serif math would still be the same (the one beamer constructed with the letters from the normal text), but symbols like `=` would be taken from the sans serif math series of kpfonts instead of the serif math font [the mixture of serif and sans serif symbols lead to these glitches in combined letters].

![document](https://user-images.githubusercontent.com/43832342/134810501-ac1aca71-2aa5-41b6-9f08-be3f047946ce.gif)


Or just add a note in the user guide?

**Comment by josephwright** [comment]
@samcarter  Looks like the best plan to me
