### ISSUE TITLE
`\footnote` in minipage is wrapped at paper width, not column width

### ISSUE THREAD

**Issue by muzimuzhi** [josephwright/beamer#713]
**Description** 
`beamer` redefines `\@mpfootnotetext` to wrap at `.85\paperwidth`, which is often wider than the width of minipage and will cause problems.
https://github.com/josephwright/beamer/blob/d2109eafba176fb7fcde367eaeb419c8aefc0b17/base/beamerbaseframecomponents.sty#L314-L325

**Example**
```tex
\documentclass{beamer}
\usepackage{lipsum}

\begin{document}

\begin{frame}{Footnote to minipage}
  \begin{minipage}{5cm}
    \lipsum[66]%
    \footnote{footnote to minipage text text text text text text text text}
  \end{minipage}
\end{frame}

\begin{frame}{Footnote to column}
  \begin{columns}
    \begin{column}{.4\textwidth}
      \lipsum[66]%
      \footnote[frame]{footnote to frame aaa aaa aaa aaa aaa aaa aaa aaa}
    \end{column}
    
    \begin{column}{.4\textwidth}
      \lipsum[75]%
      \footnote{footnote to column aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa}
    \end{column}
  \end{columns}
\end{frame}

\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/135316106-932165d4-25fb-4697-be91-33b4ca00eca1.png)

**Proposal**

Use `\hsize.85\columnwidth` or even `\hsize\columnwidth`, which is [what latex2e uses](https://github.com/latex3/latex2e/blob/8048b84a69de739009a84fb33f77fa9c2dcbc54b/base/ltboxes.dtx#L1145-L1157).

```diff
diff --git a/base/beamerbaseframecomponents.sty b/base/beamerbaseframecomponents.sty
index 66f6e53..f9aa11d 100644
--- a/base/beamerbaseframecomponents.sty
+++ b/base/beamerbaseframecomponents.sty
@@ -315,7 +315,7 @@
   \global\setbox\@mpfootins\vbox{%
     \unvbox\@mpfootins
     \reset@font\footnotesize
-    \hsize0.85\paperwidth
+    \hsize\columnwidth
     \@parboxrestore
     \protected@edef\@currentlabel
          {\csname p@mpfootnote\endcsname\@thefnmark}%
```

**Comment by samcarter** [comment]
The usual workaround is to use `\footnotetext` outside of the column/minipage environment. This way the footnote will also be placed nicely at the bottom of the frame.

**Comment by davidcarlisle** [comment]
@samcarter  that would seem wrong here though.  The main feature of `minipage`  (as opposed to say `\parbox`) is that it supports a separate series of footnotes within the box separate from page level footnotes.

**Comment by samcarter** [comment]
@davidcarlisle  This depends whether one considers footnotes to be placed correctly at the end of the minipage

**Comment by davidcarlisle** [comment]
@samcarter  sorry I don't understand that comment? handling box level footnotes is essentially the main feature of minipage certainly almost the only difference from \parbox. So (away from beamer) authors have the choice within a minipage of using `\footnote` and getting box level footnotes from the mpfootnote counter and doing as you suggest and using `\footnotemark` and `\footnotetext` outside the box to get page level footnotes. Using `\pagewidth`  for mpfootins just seems a clear bug.

**Comment by samcarter** [comment]
@davidcarlisle  Box level footnotes might be a main feature of a minipage, but isn't a main feature of footnotes to be placed in the foot (or end)?

**Comment by samcarter** [comment]
Coming back to the original problem:

If the footnotes wrap at the end of the column width, one might have to redefine the rule as well, otherwise it would go beyond the column. Maybe something like this:

```
\documentclass{beamer}

\makeatletter
\renewcommand{\footnoterule}{%
\kern -3\p@ \hrule width .47\columnwidth \kern 2.6\p@%
}
\makeatother

\begin{document}

\begin{frame}
    \footnote{i i i i i i i i i i i i i i i i i i i}
\end{frame}

\begin{frame}
  \begin{minipage}{3cm}
    \footnote{i i i i i i i i i i i i i i i i i i i}
  \end{minipage}
\end{frame}

\end{document}
```

**Comment by muzimuzhi** [comment]
To keep the normal width `2in` unchanged (so this would not be a breaking change), maybe
```tex
\renewcommand{\footnoterule}{%
  \kern -3\p@
  \hrule width \ifdim2in<\dimexpr.75\columnwidth 2in\else.75\columnwidth\fi
  \kern 2.6\p@%
}
```

Full example
```tex
\documentclass{beamer}
\usepackage{lipsum}
\usepackage{xpatch}

\makeatletter
\expandafter\xpatchcmd\csname beamerx@\string\@mpfootnotetext\endcsname
  {\hsize0.85\paperwidth}
  {\hsize\columnwidth}
  {}{\fail}

\renewcommand{\footnoterule}{%
  \kern -3\p@
  \hrule width \ifdim2in<\dimexpr.75\columnwidth 2in\else.75\columnwidth\fi
  \kern 2.6\p@%
}
\makeatother

\begin{document}

\begin{frame}
  \lipsum[1][1-4]\footnote{i i i i i i i i i i i i i i i i i i i}
  \bigskip
  
  \begin{minipage}{3cm}
    \lipsum[1][1-2]\footnote{i i i i i i i i i i i i i i i i i i i}
  \end{minipage}
\end{frame}

\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/135457255-426cc666-7354-4eec-83c3-2af7d80f015e.png)

**Comment by samcarter** [comment]
I'm not sure if dynamically adapting the width is any more a breaking change than changing the width of the footnotes. For the default layout and without columns, the rule would have the same width as before.

**Comment by muzimuzhi** [comment]
But document option `aspectratio` will change the paper width (and height), hence the column width.

Rephrasing: Since the column width changes when different document option `aspectratio` is applied, `.47\columnwidth` is already not a constant width.

**Comment by samcarter** [comment]
Maybe `0.4\columnwidth` would make sense as this would be compatible with standard classes? 

![Screenshot 2021-09-30 at 17 47 18](https://user-images.githubusercontent.com/43832342/135488473-15e7bd58-70e4-4d51-b8fb-ca893b5bce95.png)

**Comment by muzimuzhi** [comment]
Agreed. Just known `\footnoterule` is redefined in standard classes.

**Comment by davidcarlisle** [comment]
> 
> 
> @davidcarlisle Box level footnotes might be a main feature of a minipage, but isn't a main feature of footnotes to be placed in the foot (or end)?

that's why minipage is called minipage and not parbox, it as far as possible inherits page-like features including having footnotes (often used to implement table notes actually)  so within a minipage footnotes go to the end of the (mini)page. that really is the whole point of the environment (or at least of most of its code)

**Comment by samcarter** [comment]
> that's why minipage is called minipage and not parbox, it as far as possible inherits page-like features including having footnotes (often used to implement table notes actually) so within a minipage footnotes go to the end of the (mini)page. that really is the whole point of the environment (or at least of most of its code)

I doubt that's why beamer uses minipages - the ease of controlling the alignment might have been the more important feature.

**Comment by car222222** [comment]
I do not really think that beamer itself can be said to "use minipages".  Nor do I think any assumptions can be made about why/how beamer users "use minipages".  But maybe this is the way that the beamer world works!

**Comment by josephwright** [comment]
@car222222  Frames are made of minipages, that's the point

**Comment by samcarter** [comment]
> I do not really think that beamer itself can be said to "use minipages". Not do I think any assumptions can be made about why/how beamer users "use minipages". But maybe this is the way that the beamer world works!

Internally, minipages are used for beamer columns

**Comment by car222222** [comment]
Aha!  Thanks for the enlightenment.  

So the main original question is mostly about how/where to typeset a footnote that lives in a beamer column.  And not so much about footnotes in explicit minipages in beamer frames.

**Comment by davidcarlisle** [comment]
II think internal minipages used to make frames can do whatever beamer
needs to do, but an explicit in-document minipage with a footnote would be
expected to have footnotes in the box

**Comment by samcarter** [comment]
@car222222 The original question is to make the width of the footnotetext adapt to the column width, but I derailed the discussion, because misplaced footnotetext in columns is probably the most often reported problem with footnotes amonst beamer users and saying "Don't use `\footnote`" is basically an automatic reaction upon seeing the words `\footnote` and `minipage` :)

**Comment by samcarter** [comment]
> II think internal minipages used to make frames can do whatever beamer needs to do, but an explicit in-document minipage with a footnote would be expected to have footnotes in the box

I don't want to change the behaviour of minipages, I'm just telling users not to use `\footnote` inside the minipage to avoid the problem.

**Comment by samcarter** [comment]
> But document option `aspectratio` will change the paper width (and height), hence the column width.
> 
> Rephrasing: Since the column width changes when different document option `aspectratio` is applied, `.47\columnwidth` is already not a constant width.

This will also mean that for other aspect ratios the width of the footnotetext at the bottom of the frame will change as the default margins have fixed widths.
