### ISSUE TITLE
Spacing issue in `enumerate` environments caused by `\label`

### ISSUE THREAD

**Issue by dbitouze** [josephwright/beamer#714]
(Maybe this issue is related to #523.) 

In some circumstances (replacing "Foop" by "Foo" below hides the problem), introducing a `\label` in an `enumerate` list causes a spacing issue, as shown by the following MCE.

```latex
\documentclass[t]{beamer}
\begin{document}
\begin{frame}
  \begin{enumerate}
  \item Foop
  \item\label{foo} Foo
  \end{enumerate}
\end{frame}
\begin{frame}
  \begin{enumerate}
  \item Foop
  \item Foo
  \end{enumerate}
\end{frame}
\end{document}
```

![image](https://user-images.githubusercontent.com/1032633/135880199-198d019d-26c1-4816-9199-14196437d4e7.png)

**Update:** as a workaround, it is enough to put `\label` not at the beginning of the item.

**Comment by samcarter** [comment]
You can use the same workaround as in https://github.com/josephwright/beamer/issues/541#issuecomment-552993755

```
\documentclass[t]{beamer}

\makeatletter
\def\beamer@inserttarget#1{%
  \ifbeamer@inframe%
    #1%
  \else% defer to next frame
    \expandafter\gdef\expandafter\beamer@framehypertargets\expandafter{\beamer@framehypertargets#1}%
  \fi%
}
\makeatother

\begin{document}
\begin{frame}
  \begin{enumerate}
  \item Foop
  \item\label{foo} Foo
  \end{enumerate}
\end{frame}
\begin{frame}
  \begin{enumerate}
  \item Foop
  \item Foo
  \end{enumerate}
\end{frame}
\end{document}
```

![document](https://user-images.githubusercontent.com/43832342/135885937-6e242f4f-56ee-4009-b29d-4e439f008f86.gif)

**Comment by dbitouze** [comment]
@samcarter Thanks! Is it planned to integrate it in `beamer`?

Anyway, another discrepancy (not related to hypertargets), maybe not related to the OP (in such a case, let me know):
```latex
\documentclass[t]{beamer}
\begin{document}

\begin{frame}
  \begin{enumerate}
  \item Foo
  \item Foo
  \item Foo
    \begin{itemize}
    \item Bar
    \end{itemize}
  \end{enumerate}
\end{frame}

\begin{frame}
  \begin{enumerate}
  \item Foo
  \item Foo
  \item Foo
  \end{enumerate}
\end{frame}

\end{document}
```
![image](https://user-images.githubusercontent.com/1032633/135886693-6a2055f6-1092-48c9-b744-8f59931f4e66.png)

**Comment by samcarter** [comment]
> @samcarter Thanks! Is it planned to integrate it in `beamer`?

I don't think I have a good enough overview of what this might break, so no current plan to add this

> Anyway, another discrepancy (not related to hypertargets), maybe not related to the OP (in such a case, let me know):

That's just the usual missing paragraph, see e.g. https://github.com/josephwright/beamer/issues/306
```
\documentclass[t]{beamer}
\begin{document}

\begin{frame}
  \begin{enumerate}
  \item Foo
  \item Foo
  \item Foo

    \begin{itemize}
    \item Bar
    \end{itemize}
  \end{enumerate}
\end{frame}

\begin{frame}
  \begin{enumerate}
  \item Foo
  \item Foo
  \item Foo
  \end{enumerate}
\end{frame}

\end{document}
```


![document](https://user-images.githubusercontent.com/43832342/135888015-e991c453-fe48-4499-baec-7fb3cafe32bd.gif)

**Comment by dbitouze** [comment]
@samcarter OK, thanks again! :smiley:

Same question: is it planned to "add `\par` somewhere to the `itemize`/`enumeration` [and maybe `description`] environments?"

**Comment by samcarter** [comment]
@dbitouze  Same question - same answer :) I did not yet find a good place to add it that would not break something else.

**Comment by davidcarlisle** [comment]
it may be worth mentioning that this is only an issue if `\label` is used in vmode (which has issues even in standard classes)

` \item Foo\label{foo}`

works, as does

`\item \leavevmode\label{foo} Foo`

**Comment by dbitouze** [comment]
@davidcarlisle Interesting! No hope to fix this even in standard classes?

**Comment by davidcarlisle** [comment]
we had some latex3 code in the 1990s, and it survives in xgalley which sort of fixes it in principle but it's incompatible with essentially everything...  You can also see an attempt at "vertical space hacks" which we tried to add at the start of latex2e but never added as not robust enough. Funnily enough I just looked at the latex source and it gives _exactly_ this example.

latex/base/ltspace.dtx has...

```
% The implementation of space hacks etc for vertical mode is another
% major area that needs further attention; my earlier experiments
% did not produce much improvement over the current unsatisfactory
% situation.
%
% One particular problem is what happens when the following very
% natural coding is used (part of the problem here is that this looks
% like an hmode problem, but it is not):
% \begin{verbatim}
%   ... end of text.
%
%   \begin{enumerate}
%     \item \label{item:xxx} Item text.
%   \end{enumerate}
% \end{verbatim}
```



 It's not just `\label` you will see the same from `\color` (but not from `\textcolor` which adds `\leavevmode` for exactly this reason.

**Comment by sim642** [comment]
> `\item \leavevmode\label{foo} Foo`

This seems to cause extra horizontal spacing between the item label and the text. Luckily `\item \leavevmode\label{foo}Foo` does not.

**Comment by car222222** [comment]
Good!
