### ISSUE TITLE
Doc: \renewcommand inside frame environments

### ISSUE THREAD

**Issue by jlaurens** [josephwright/beamer#715]
# Actual
In order to use `\renewcommand` inside a `frame` environment, you have to double the `#` twice.
```
\documentclass{beamer}
\providecommand\myCommand{}
\begin{document}
\begin{frame}
{Frame \insertframenumber}
{Slide \insertslidenumber}
\renewcommand\myCommand[1] {
  /####1/
}
\myCommand{X}
\end{frame}
\end{document}
```
## Expected

Either document this feature as is (in page 88) or mark it as unsupported.
On one hand, marking this usage of `\renewcommand` as unsupported is a safeguard against forthcoming implementation changes, on the other hand, `\renewcommand` and friends are extremely handy even inside frame environments.

**Comment by josephwright** [comment]
This is well-known and I'd say a feature: `beamer` doesn't really support any programming inside frames.

**Comment by samcarter** [comment]
You can avoid the limitation by using a `fragile` frame, this way you avoid the repeated processing a normal frames goes through:

```
\documentclass{beamer}
\providecommand\myCommand{}
\begin{document}
\begin{frame}[fragile]
\frametitle{Frame \insertframenumber}
\framesubtitle{Slide \insertslidenumber}
\renewcommand\myCommand[1]{#1}
\myCommand{X}
\end{frame}
\end{document}
```

(btw, this phenomena is not specific to `\renewcommand`, but also occurs in many other situations, like certain tikz pictures etc.  )
