### ISSUE TITLE
Problem with transparent shadows and cmyk colour model

### ISSUE THREAD

**Issue by samcarter** [josephwright/beamer#718]
from https://github.com/josephwright/beamer/issues/654#issuecomment-938594619

```
\documentclass{beamer}

\selectcolormodel{cmyk}
\useinnertheme[shadow]{rounded}

\begin{document}

\begin{frame}

\begin{block}{Title}
Test
\end{block}

\end{frame}

\end{document}
```

_Originally posted by @samcarter in https://github.com/josephwright/beamer/issues/654#issuecomment-938597634_

**Comment by samcarter** [comment]
... so the problem seems to be that 100% transparent in cmyk is pastel shade instead of invisible:

```
\documentclass{standalone}

\usepackage{pgf}
\selectcolormodel{cmyk}

\pgfdeclareverticalshading{myshade}{3cm}{%
  color(0ex)=(pgftransparent!100);%
  color(1ex)=(pgftransparent!100)
}
\pgfdeclarefading{mymask}{\pgfuseshading{myshade}}

\begin{document}

\fbox{\begin{pgfpicture}
  \pgfsetfillcolor{red}%
  \pgfpathrectangle{\pgfpoint{0pt}{-1ex}}{\pgfpoint{3cm}{1.2ex}}%
  \pgfsetfading{mymask}{\pgftransformscale{2}}%
  \pgfusepath{fill}%
\end{pgfpicture}}

\end{document}
```

![document2](https://user-images.githubusercontent.com/43832342/136560412-823b7cf2-c6d6-40fd-be16-2dfff479e40e.png)

**Comment by u-fischer** [comment]
looks ok with adobe reader, but wrong with sumatra.

**Comment by samcarter** [comment]
@u-fischer  Oh, that is interesting! 

I get baby pink with mac preview.app, skim and the texstudio viewer
