### ISSUE TITLE
Class option `onlyslideswithnotes` undocumented

### ISSUE THREAD

**Issue by joel-coffman** [josephwright/beamer#724]
Section 19.1 ("Specifying Note Contents") states,

> Using the `\note` command inside frames is usually preferably over using them outside, since only commands issued inside frames profit from the class option `onlyslideswithnotes`, see below.

and later

> Outside frames, this command creates a note page. This command is not affected by the option
`notes=onlyframeswithnotes`, see below

Neither of these options are documented elsewhere in the user guide. Moreover, the latter option sentence might contain a mistake, as `onlyframeswithnotes` does not appear elsewhere in the repository.

**Comment by samcarter** [comment]
I'm wondering if this documentclass option is actually supposed to exist? All the other `notes=...` options were moved from the documentclass to `\setbeameroption{...}`.

**Comment by samcarter** [comment]
Wondering if something like

```
\documentclass[
]{beamer}

\makeatletter
\defbeameroption{show only slides with notes}[]%
{
  \beamer@notestrue
  \beamer@frameswithnotesonlytrue
  \nofiles
}
\makeatother

\setbeameroption{show only slides with notes}

\begin{document}
	
\begin{frame}
	abc\pause test
  \note<2>{note text}
\end{frame}	

\begin{frame}
	abcd
\end{frame}	
	
\end{document}
```

wouldn't make more sense. Then one could document the option together with all the other ones.
