### ISSUE TITLE
How to modify madrid or cambridge in order to have a watermark

### ISSUE THREAD

**Issue by ouboub** [josephwright/beamer#730]
Hi

for most of my slides I prefer to use the Cambridge or the Madrid theme. Now I need before uploading these slides (pdf) to add some (copyright) watermark.
here is a very simple madrid theme file:
```\documentclass{beamer}
\usetheme[secheader]{Madrid}
\usepackage{lipsum}
\title{Local existence of solutions}
\date{30-07-2019}
\author{Uwe Brauer}
\begin{document}
\begin{frame}
  \titlepage
\end{frame}

\section{Introduction}
\begin{frame}[<+->]
\lipsum[1]
\end{frame}
\begin{frame}[<+->]
  \frametitle{Block}
  \begin{block}{test}
\lipsum[2]
  \end{block}
\end{frame}
\end{document}
```
and I know to generate a watermark for example like this:
```\documentclass{beamer}
\useoutertheme{infolines}
%\useoutertheme[footline=authortitle]{miniframes}
\usepackage{lipsum}
\usepackage{background}
\backgroundsetup{
    placement=center,
    scale=2,
    contents={
      \parbox{3.5cm}
      {Copyright\newline UCM\newline Cálculo Numérico \newline Uwe Brauer}
  },
    opacity=10
}
\setbeamertemplate{background}{\BgMaterial}
  \title{}
  \date{}
  \author{}
\begin{document}
\begin{frame}[<+->]
\hfill
\end{frame}
\end{document}
```
How can I merge so to speak the copyright watermark into Madrid?
thanks and regards

Uwe Brauer

**Comment by samcarter** [comment]
I would not use the `background` package with beamer, beamer has its own mechanism to alter the background canvas:

```
\documentclass{beamer}

\usetheme[secheader]{Madrid}
\usepackage{lipsum}
\title{Local existence of solutions}
\date{30-07-2019}
\author{Uwe Brauer}

\setbeamertemplate{background}{%
  \rotatebox{20}{%
    \Huge\color{red!50}
    \parbox{10cm}{
    \centering Copyright
    
    UCM
    
    Cálculo Numérico
    
    Uwe Brauer
}}}

\begin{document}
\begin{frame}
  \titlepage
\end{frame}

\section{Introduction}
\begin{frame}[<+->]
\lipsum[1]
\end{frame}
\begin{frame}[<+->]
  \frametitle{Block}
  \begin{block}{test}
\lipsum[2]
  \end{block}
\end{frame}
\end{document}
```

**Comment by ouboub** [comment]
Thanks! much better, still the frame with the block only partially shows the watermark, any possibility to change that and obtain the watermark in foreground of the block?

**Comment by samcarter** [comment]
Ah, sorry I missed the fact that it should be in the foreground and not the background.

Quick hack: you can add your watermark to the top most layer of the frame, the footline:

```
\documentclass{beamer}

\usetheme[secheader]{Madrid}
\usepackage{lipsum}
\title{Local existence of solutions}
\date{30-07-2019}
\author{Uwe Brauer}

\usepackage{tikz}
\addtobeamertemplate{footline}{%
\begin{tikzpicture}[remember picture, overlay]
  \node[red,rotate=20,font=\Huge,text width=10cm,align=center,opacity=0.4] at (current page.center) {
        Copyright
        
        UCM
        
        Cálculo Numérico
        
        Uwe Brauer
};
\end{tikzpicture}}{}

\begin{document}

\begin{frame}
  \titlepage
\end{frame}

\section{Introduction}
\begin{frame}[<+->]
\lipsum[1]
\end{frame}
\begin{frame}[<+->]
  \frametitle{Block}
  \begin{block}{test}
\lipsum[2]
  \end{block}
\end{frame}
\end{document}
```

<img width="512" alt="Screenshot 2021-10-30 at 19 15 44" src="https://user-images.githubusercontent.com/43832342/139542699-2adff16c-b581-4712-9c21-457b8b28ebb4.png">

**Comment by ouboub** [comment]
> Ah, sorry I missed the fact that it should be in the foreground and not the background.
> 
> Quick hack: you can add your watermark to the top most layer of the frame, the footline:
> 
> ```
> \documentclass{beamer}
> 
> \usetheme[secheader]{Madrid}
> \usepackage{lipsum}
> \title{Local existence of solutions}
> \date{30-07-2019}
> \author{Uwe Brauer}
> 
> \usepackage{tikz}
> \addtobeamertemplate{footline}{%
> \begin{tikzpicture}[remember picture, overlay]
>   \node[red,rotate=20,font=\Huge,text width=10cm,align=center,opacity=0.4] at (current page.center) {
>         Copyright
>         
>         UCM
>         
>         Cálculo Numérico
>         
>         Uwe Brauer
> };
> \end{tikzpicture}}{}
> 
> \begin{document}
> 
> \begin{frame}
>   \titlepage
> \end{frame}
> 
> \section{Introduction}
> \begin{frame}[<+->]
> \lipsum[1]
> \end{frame}
> \begin{frame}[<+->]
>   \frametitle{Block}
>   \begin{block}{test}
> \lipsum[2]
>   \end{block}
> \end{frame}
> \end{document}
> ```
> 
> <img alt="Screenshot 2021-10-30 at 19 15 44" width="512" src="https://user-images.githubusercontent.com/43832342/139542699-2adff16c-b581-4712-9c21-457b8b28ebb4.png">

Brillant, thank you so MUCH

**Comment by samcarter** [comment]
@ouboub You're welcome!
