### ISSUE TITLE
beamer+subfiles: tableofcontents for  \part in a subfile

### ISSUE THREAD

**Issue by ouboub** [josephwright/beamer#734]
Hello

I am not sure, who is here the culprit (if there is any) subfiles or beamer.

I am facing the following problem, using beamer+subfiles (the most recent subfiles version).

The structure of the files is as follows (I am simplifying here, the real structure is far more complicated)

    1. main.tex: the file with all subfiles

    2. subfile part1.tex (That should only contain the tableofcontents of that part)

    3. subfile section1.tex

    4. subfile section2.tex

I attached all files just in case. If I compile the file main.tex everything works as expected.

The central point of subfiles is that it enables me to compile, for example, section1.tex

My problem is now, if I only compile part1.tex then the corresponding tableofcontents (regarding section1.tex and section2.tex) are not generated.

Is that possible?

I tried out  xr-hyper but it did not help

Thanks and regards

Uwe Brauer 
[files.zip](https://github.com/josephwright/beamer/files/7481437/files.zip)

**Comment by samcarter** [comment]
If I compile your `part1.tex` file, I do get a table of contents.

![Screenshot 2021-11-05 at 10 47 41](https://user-images.githubusercontent.com/43832342/140491546-20bb1fc6-df3a-4128-9b18-05d9e47b025d.png)


Can you show your output files?

**Comment by samcarter** [comment]
(you should load `xr-hyper` before `hyperref`. As beamer loads `hyperref` automatically, you have to load it before the documentclass)

**Comment by ouboub** [comment]
This is my understanding, but beamer already loads hyperref, so how am I supposed to do it?
and I suppose you mean the main.tex file and all its subfiles?

**Comment by samcarter** [comment]
You can load it before beamer with

```
\RequirePackage{xr-hyper}
\documentclass{beamer}

\begin{document}
content...
\end{document}
```

I'd like to see your .pdf files to understand your problem, because atm I don't see anything wrong with the output. Maybe include the .log files as well.

**Comment by ouboub** [comment]
> If I compile your `part1.tex` file, I do get a table of contents.
> 
> ![Screenshot 2021-11-05 at 10 47 41](https://user-images.githubusercontent.com/43832342/140491546-20bb1fc6-df3a-4128-9b18-05d9e47b025d.png)
> 
> Can you show your output files?

I realised, I uploaded not the correct version of the latex files, so here again the zip and the pdfs
[files.zip](https://github.com/josephwright/beamer/files/7486497/files.zip)

[main.pdf](https://github.com/josephwright/beamer/files/7486499/main.pdf)
[part1.pdf](https://github.com/josephwright/beamer/files/7486501/part1.pdf)

**Comment by ouboub** [comment]
> You can load it before beamer with
> 
> ```
> \RequirePackage{xr-hyper}
> \documentclass{beamer}
> 
> \begin{document}
> content...
> \end{document}
> ```
> 
> I'd like to see your .pdf files to understand your problem, because atm I don't see anything wrong with the output. Maybe include the .log files as well.

that I did (I cannot do this for the subfiles, I have to ask the author to include that feature) in any case it does not help.
I am sorry for the confusion, since it seems that I uploaded a nested version (subfiles that contained subfiles).
that is a possible solution but I would like to avoid it if possible, but if I don't nest that part1.pdf does not contain anymore the tableofcontents

**Comment by samcarter** [comment]
For the subfiles, you can do

```
% !TeX root = part1.tex
\AddToHook{file/before/beamer.cls}{\RequirePackage{xr-hyper}} 
\documentclass[main]{subfiles}
\externaldocument{main}
```

**Comment by samcarter** [comment]
You can trick your part files to include the toc from the main file:

```
\AddToHook{file/before/beamer.cls}{\RequirePackage{xr-hyper}} 
\documentclass{beamer}
\usetheme[secheader]{Madrid}
\makeatletter
\Hy@AtBeginDocument{%
  \def\@pdfborder{0 0 1}% Overrides border definition set with colorlinks=true
  \def\@pdfborderstyle{/S/U/W 1}% Overrides border style set with colorlinks=true
                                % Hyperlink border style will be underline of width 1pt
}
\makeatother

\hypersetup{%
  colorlinks=true,% hyperlinks will be coloured
%  linkcolor=blue,% hyperlink text will be blue
  urlcolor=blue,% hyperlink text will be blue
%  linkbordercolor=red,% hyperlink border will be red
  urlbordercolor=red,% hyperlink border will be red
}

\usepackage{subfiles}

\makeatletter
\ifdefined\preamble@file
\patchcmd{\beamer@tableofcontents}{\@input{\jobname.toc}}{\@input{main.toc}}{}{}
\fi
\makeatother

\begin{document}
\subfile{part1}
\subfile{sec1}
\subfile{sec2}

\end{document}
```

![Screenshot 2021-11-05 at 15 33 03](https://user-images.githubusercontent.com/43832342/140527296-1e586819-978e-4c63-9357-121286493d9f.png)

**Comment by ouboub** [comment]
thanks,
 so if you compile part1.tex in includes the tableofcontents?
I am asking this because I am still using texlive 2019 and cannot compile that file, but if it works for you
I have then a very good reason to upgrade.

**Comment by samcarter** [comment]
Yes, it does (the links will obviously not work). I think you need texlive2021 for the hook stuff to work, it is rather new.

(if your not limited by disk space, you can simply have multiple texlive versions in parallel)

-----

Another idea would be to include the frame with the toc as full-frame image from the main file in your part files....

**Comment by ouboub** [comment]
right, I am a bit short on disk space, but my main concern are my collaborators who stick to version as old as 2016!

in any case, thanks again a lot for you help, that was extremely useful.

your other solution would use a \includegraphics command, right, that might be a solution.
I will close that issue now. thanks

**Comment by ouboub** [comment]
Ha
```
\RequirePackage{xr-hyper}
\documentclass{beamer}
\usetheme[secheader]{Madrid}
\makeatletter
\Hy@AtBeginDocument{%
  \def\@pdfborder{0 0 1}% Overrides border definition set with colorlinks=true
  \def\@pdfborderstyle{/S/U/W 1}% Overrides border style set with colorlinks=true
                                % Hyperlink border style will be underline of width 1pt
}
\makeatother

\hypersetup{%
  colorlinks=true,% hyperlinks will be coloured
%  linkcolor=blue,% hyperlink text will be blue
  urlcolor=blue,% hyperlink text will be blue
%  linkbordercolor=red,% hyperlink border will be red
  urlbordercolor=red,% hyperlink border will be red
}

\usepackage{subfiles}

\makeatletter
\ifdefined\preamble@file
\patchcmd{\beamer@tableofcontents}{\@input{\jobname.toc}}{\@input{main.toc}}{}{}
\fi
\makeatother

\begin{document}
\subfile{part1}
\subfile{sec1}
\subfile{sec2}

\end{document}
```
also works!

the trick was  to use
```
\makeatletter
\ifdefined\preamble@file
\patchcmd{\beamer@tableofcontents}{\@input{\jobname.toc}}{\@input{main.toc}}{}{}
\fi
\makeatother
```

**Comment by samcarter** [comment]
Here a version with image:

```
% !TeX root = part1.tex
\documentclass[main]{subfiles}
\externaldocument{main}


\begin{document}
\part{Topic numeric}
\frame{\partpage}

{
\setbeamertemplate{background canvas}{\includegraphics[width=\paperwidth,page=2]{main}}
\begin{frame}
\frametitle{Summary in part file}

\end{frame}
}

\end{document}
```

the new frametitle/footline will cover up the ones from main file

**Comment by samcarter** [comment]
> the trick was to use

> \makeatletter
> \ifdefined\preamble@file
> \patchcmd{\beamer@tableofcontents}{\@input{\jobname.toc}}{\@input{main.toc}}{}{}
> \fi
> \makeatother
> 

Ah, yes, the hook code was only for using the xr-hyper package. If you don't need it for cross references etc. you can do without

**Comment by ouboub** [comment]
there is even another solution posted by Gernot Salzer the maintainer of the subfiles pkg (in the german Latex list)
\begin{frame}
  \frametitle{Summary}
\def\jobname{main}%
\tableofcontents
\end{frame}
