### ISSUE TITLE
Dots above and below navigation symbols with XeTeX

### ISSUE THREAD

**Issue by Ionic** [josephwright/beamer#738]
With texlive 2021, a MWE produces dots above and below navigation symbols when using XeTeX.

The same MWE does not produce the dots when compiling with luatex.

```latex
\documentclass{beamer}
\begin{document}
\begin{frame}
  This page intentionally left blank.
\end{frame}
\end{document}
```

![xelatex-dots](https://user-images.githubusercontent.com/1229578/143805974-09f31f0b-0bec-48c8-81da-df8518753830.png)

**Comment by Ionic** [comment]
Reverting e35652d0dcb81fcd78741469a5ebe9c0a6a0012d fixes this visually, but also reintroduces #136 in the sense that symbols will be non-clickable.

So the workaround of drawing "real" things leads to an ugly navigation bar (and, interestingly, it also shows that the dots are both misaligned and... that there are too many of them to even begin with?), while removing the workaround leads to a visually pleasing, but otherwise useless navigation bar.

**Comment by Ionic** [comment]
On further investigation, there's probably nothing wrong in `beamer`. It already sets the transparency to full.

I can reproduce this generically with `pgf` only.

I could close this report and bring it up with `pgf` instead, but what about the misalignment and additional dots? Is that working like it's supposed to be?

**Comment by samcarter** [comment]
I can't reproduce this with up-to-date xelatex from texlive 2021, can you show your .log file?

**Comment by Ionic** [comment]
Interesting.

```
XeTeX 3.141592653-2.6-0.999993 (TeX Live 2021 Gentoo Linux)
kpathsea version 6.3.2
Copyright 2021 SIL International, Jonathan Kew and Khaled Hosny.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 69.1; using 69.1
Compiled with zlib version 1.2.11; using 1.2.11
Compiled with FreeType2 version 2.11.0; using 2.11.0
Compiled with Graphite2 version 1.3.14; using 1.3.14
Compiled with HarfBuzz version 2.9.0; using 2.9.0
Compiled with libpng version 1.6.37+apng; using 1.6.37+apng
Compiled with pplib version v2.05 less toxic i hope
Compiled with fontconfig version 2.13.1; using 2.13.1
```

Log file: 
[presentation.log](https://github.com/josephwright/beamer/files/7617077/presentation.log)

**Comment by samcarter** [comment]
Can you test with an up-to-date xelatex, in particular one with the current `xetex.def`? Yours seems to be about half a year old. 

... on the other hand, your file also works fine on overleaf, who also have an older texlive2021 https://www.overleaf.com/read/znxdxxdztkws

**Comment by samcarter** [comment]
To rule out that it is just your pdf viewer, can you test the following pdf?

[document.pdf](https://github.com/josephwright/beamer/files/7617169/document.pdf)

**Comment by Ionic** [comment]
It's certainly not my PDF viewer. Atril is capable of displaying transparency and, yes, your file also displays fine.

Weird, but certainly possible that it's caused by TeXLive 2021 as distributed by my distro (Gentoo).

Like I said, I seem to have a general XeTeX transparency issue, also with [plain pgf](https://github.com/pgf-tikz/pgf/issues/1078).

Overleaf's xetex.def file definitely is newer. My version is probably the first one that was shipped with TL 2021 originally. Gentoo doesn't seem to generally update TL distributions other than between major versions. Doing that manually looks to be a pain, but I guess I could take a stab at it.

**Comment by samcarter** [comment]
> Overleaf's xetex.def file definitely is newer. My version is probably the first one that was shipped with TL 2021 originally. Gentoo doesn't seem to generally update TL distributions other than between major versions. Doing that manually looks to be a pain, but I guess I could take a stab at it.

You could install vanilla texlive instead of your system texlive -- then you would always be up-to-date :)
