### ISSUE TITLE
blocks (environments) and allowframebreaks

### ISSUE THREAD

**Issue by ouboub** [josephwright/beamer#745]
Hi, 

I would like to split a long proof (that is inside a block environment) automatically, or maybe using the \framebreak command.
Alas it does not work, any chance for a solution?
I attach an example (which I admit is not the final version), I had to change the extension to txt (sigh)
[mybeamer-block.txt](https://github.com/josephwright/beamer/files/7691403/mybeamer-block.txt)

**Comment by samcarter** [comment]
tcolorbox offers the possibility to make boxes breakable

**Comment by ouboub** [comment]
Thanks, but it seems not to work, see the attached file
[mybeamer-block.txt](https://github.com/josephwright/beamer/files/7691711/mybeamer-block.txt)

**Comment by ouboub** [comment]
I tried out the option breakable from the tcolorbox manual (page 359) but it does not help

[mybeamer-block2.txt](https://github.com/josephwright/beamer/files/7691968/mybeamer-block2.txt)

**Comment by samcarter** [comment]
Here a quick example:
```
\documentclass{beamer}
\usetheme{Warsaw}

\usepackage{lipsum}
\usepackage{tcolorbox}
\tcbuselibrary{skins,breakable}
\tcbset{breakable}

\begin{document}

    \begin{frame}[allowframebreaks]

         \begin{tcolorbox}[beamer, skin=beamerfirst, colback=blue!5!white, colframe=blue!50!black, title=Something]

            \lipsum[2]
            
            \framebreak
            
            \lipsum[2]

         \end{tcolorbox}

    \end{frame} 


\end{document}
```

![Screenshot 2021-12-10 at 12 23 25](https://user-images.githubusercontent.com/43832342/145566772-6fa07fff-ffee-473e-82ae-96c4a3df85b2.png)

**Comment by samcarter** [comment]
> I tried out the option breakable from the tcolorbox manual (page 359) but it does not help
> 
> [mybeamer-block2.txt](https://github.com/josephwright/beamer/files/7691968/mybeamer-block2.txt)

You are using tcb libaries which you don't load. You can make your code compilable with `\usepackage[most]{tcolorbox}`

**Comment by ouboub** [comment]
Thanks a lot (you have helped me lately so much, that I am thinking of a bottle of wine or a cake....)

Some comments.
the space between the frametitle and the text in the box, starting the second page is very tight. any chance of changing that?

it is impossible to use shrink and allowframebreaks it seems, so I should use \small for example if I would find that appropriate?
[mybeamer-block2.pdf](https://github.com/josephwright/beamer/files/7693077/mybeamer-block2.pdf)

**Comment by samcarter** [comment]
> it is impossible to use shrink and allowframebreaks it seems, so I should use \small for example if I would find that appropriate?

Yes, a lot things don't work with `allowframebreaks` -- there is a reason the user guide documents this option as `evil`. 

In any case, manually setting a suitable font size is always better then `shrink`, you'll have more horizontal space.

**Comment by samcarter** [comment]
> the space between the frametitle and the text in the box, starting the second page is very tight. any chance of changing that?

```
\documentclass[t]{beamer}
\usetheme{Warsaw}

\usepackage{lipsum}
\usepackage{tcolorbox}
\tcbuselibrary{skins,breakable}
\tcbset{breakable}

\begin{document}

    \begin{frame}[allowframebreaks]
        \frametitle{title}
         \begin{tcolorbox}[beamer, skin=beamerfirst, colback=blue!5!white, colframe=blue!50!black, title=Something,enlarge top at break by=1cm]

            \lipsum[2]
            
            \framebreak
            
            \lipsum[2]

         \end{tcolorbox}

    \end{frame} 


\end{document}
```
![Screenshot 2021-12-10 at 15 00 12](https://user-images.githubusercontent.com/43832342/145585555-981d959c-7eea-4ad0-8ce7-5a356f0e6cfd.png)

**Comment by ouboub** [comment]
great, that settles it. thanks again!

**Comment by samcarter** [comment]
@ouboub  You're welcome!
