### ISSUE TITLE
Miniframes cutoff for smaller font sizes

### ISSUE THREAD

**Issue by samcarter** [josephwright/beamer#752]
Starting with commit 01e410012f34bf3ed2a6bb10de5c3e0be5374c82 , miniframes in the headline are cut off if a smaller font is used:

```
\documentclass[10pt]{beamer}
\usetheme{Frankfurt}
\begin{document}
\section{Section 1}
\begin{frame}
\frametitle{title}
content
\end{frame}
\end{document}
```

**Comment by bblacher** [comment]
Currently having the same problem.

**Comment by samcarter** [comment]
@Benibla124  For a quick workaround until I've time to commit a proper solution:

```
\documentclass[10pt]{beamer}
\usetheme{Frankfurt}

\addtobeamertemplate{headline}{}{\vspace*{0.1cm}}

\begin{document}
\section{Section 1}
\begin{frame}
\frametitle{title}
content
\end{frame}
\end{document}
```

**Comment by bblacher** [comment]
@samcarter Thank you very much, very helpful! :)

**Comment by samcarter** [comment]
@Benibla124  You're welcome! And my apologies for the trouble with the cut off miniframes!
