### ISSUE TITLE
colors defined by xcolor[dvipsnames] not working

### ISSUE THREAD

**Issue by vliegeois** [josephwright/beamer#759]
Since version 61684 (3.65), there is compilation error with pdflatex for beamer slides.
Any color defined in xcolor with dvipsnames:` \documentclass[12pt,xcolor={dvipsnames}]{beamer}`
is not recognized.
For instance, when using ForestGreen color with `\textcolor{ForestGreen}{example}` failed with error:
```
! Package xcolor Error: Undefined color `ForestGreen'.
```
This was fine with beamer 60801 (3.64).
I don't have the issue with beamerarticle:
```
\documentclass[12pt,a4paper,dvipsnames]{article}
\usepackage{beamerarticle}
```
Here is a minimal example:
```
\documentclass[11pt,mathserif,xcolor=dvipsnames]{beamer}
%\documentclass[12pt,a4paper,dvipsnames]{article}
%\usepackage{beamerarticle}
\mode<beamer>{%
\usetheme[hideothersubsections,
right,width=1mm]{Goettingen}
\useoutertheme{infolines}
}
\usepackage[utf8]{inputenc}
\title{Title}
\author{Vincent LIEGEOIS}
\date{\today}
\begin{document}
\mode<article>{\maketitle}
\mode<article>{\tableofcontents}
\begin{frame}
\titlepage
\end{frame}
\begin{frame}
  \frametitle{Bug report}
This is a small \textcolor{ForestGreen}{example}.
\end{frame}
\end{document}
```

Best regards

Vincent

**Comment by samcarter** [comment]
@vliegeois Sorry for that! I broke that when adding more flexible aspect ratios. As a temporary fix

```
\RequirePackage[dvipsnames]{xcolor}

\documentclass[11pt]{beamer}

\begin{document}

\begin{frame}
\frametitle{Bug report}
This is a small \textcolor{ForestGreen}{example}.
\end{frame}
\end{document}
```

**Comment by samcarter** [comment]
@vliegeois  Just curious: why do you have all these `\mode` without actually specifying a mode?

**Comment by vliegeois** [comment]
> @vliegeois Just curious: why do you have all these `\mode` without actually specifying a mode?

Which \mode are you referring at? I use \mode<article>  to make the title and the table of content when using beamerarticle but not in beamer <presentation> mode.

Thanks for the fix.
So I can remove this fix when beamer 3.66 will be available?

Thank you for the very quick reply :-)
Regards
Vincent

**Comment by samcarter** [comment]
Sorry about the comment about `\mode`. Before I applied code markup to your post, I could not see them. This is what your post looked like for me:

![Screenshot 2022-02-08 at 13 37 32](https://user-images.githubusercontent.com/43832342/152988589-a5d1a4f4-e1c4-45db-9a20-f5602da9fc61.png)

**Comment by samcarter** [comment]
> Thanks for the fix.
> So I can remove this fix when beamer 3.66 will be available?

I hope so :) I just asked @josephwright  if he can release a new version

**Comment by vliegeois** [comment]
Indeed, there is an issue with markdown and < and > :-)

**Comment by samcarter** [comment]
@vliegeois  If the code is not in a code block, I think they are interpreted as html tag thingies

**Comment by samcarter** [comment]
@vliegeois  Oh, and instead of the `mathserif` option, better use `\usefonttheme[onlymath]{serif}` in your preamble

**Comment by vliegeois** [comment]
Thanks for the tip

**Comment by samcarter** [comment]
@vliegeois  You're welcome!
