### ISSUE TITLE
Identify notes pages in PDF

### ISSUE THREAD

**Issue by Cimbali** [josephwright/beamer#767]
This is more of a question than an issue.

When notes pages are generated, is there any other way of telling that they are notes pages? I mean by some automated way, not by looking, of course. Do these pages contain something that normal pages do not? Or the opposite?

As far as I’ve seen, the same labels are used, which makes them indistinguishable. However repeating labels also occur with overlays, so I can’t use the repetition either. The other slide metadata I can think of (e.g. size) is also the same.

I was hoping maybe some anchors were absent from notes pages, as it doesn’t make a lot of sense to navigate to notes pages, but `pdfinfo -dests` revealed that even those are exactly the same for notes and slides pages.

**Comment by samcarter** [comment]
I don't think there is anything special about notes pages. However you could maybe add something like a hypertarget yourself? 

```
\documentclass{beamer}

\setbeameroption{show notes}

\makeatletter
\addtobeamertemplate{note page}{\hyper@@anchor{note.\the\c@page}}{}
\makeatother

\begin{document}
	
\begin{frame}
	abc\pause test
  \note<1>{Quack}
  \note<2>{Duck}
\end{frame}	


\begin{frame}
content...
\end{frame}
	
\end{document}
```

**Comment by Cimbali** [comment]
Thanks @samcarter. If it requires modifying the document anyway, I think the least effort for my purposes is to force generating notes pages always, even for empty notes, with e.g.
```tex
\makeatother
\def\beamer@framenotesbegin{\gdef\beamer@noteitems{}\gdef\beamer@notes{{}}}% NB it is notes{{}} instead of notes{}
\makeatletter
```

**Comment by samcarter** [comment]
> Thanks @samcarter. If it requires modifying the document anyway, I think the least effort for my purposes is to force generating notes pages always, even for empty notes, with e.g.
> 
> \makeatother
> \def\beamer@framenotesbegin{\gdef\beamer@noteitems{}\gdef\beamer@notes{{}}}% NB it is notes{{}} instead of notes{}
> \makeatletter

This looks very familiar :) I'm using the same trick in my own presentations

**Comment by Cimbali** [comment]
Not sure this needs to stay open. In the end, since it required modifying pages anyways, [we went with](https://github.com/Cimbali/pympress#functionalities) the somewhat more explicit:
```tex
\addtobeamertemplate{note page}{}{\thispdfpagelabel{notes:\insertframenumber}}
```

This prepends `notes:` to every notes page label.
