### ISSUE TITLE
Issues with block shadows after new 3.67 release 

### ISSUE THREAD

**Issue by jotagah** [josephwright/beamer#772]
I guess Beamer last update messes the box shadows ... again.

From Black/gray to white.

[ ]'s,

J.

**Comment by samcarter** [comment]
Please make a minimal working example which allows us to reproduce the problem. 

Shadows seem to work just fine:
![Screenshot 2022-05-18 at 13 27 56](https://user-images.githubusercontent.com/43832342/169028511-ad3b6942-2675-4e1c-92ba-88760ee02007.png)

**Comment by jotagah** [comment]
I could not post a minimal example because I had a hard day.

I used the Manhattan theme, for instance, to show the issue.

```
\documentclass{beamer}
\usetheme{Manhattan}
\definecolor{black}{RGB}{30,30,30}
\setbeamertemplate{blocks}[rounded][shadow=true]
\begin{document}
\begin{frame}
    \begin{block}{Example}
    \end{block}
\end{frame}
\end{document}
```

**Comment by samcarter** [comment]
The Manhattan theme does not seem to be available on ctan. Is the exact version you are using available somewhere on the internet?

**Comment by samcarter** [comment]
That being said: `\definecolor{black}{RGB}{30,30,30}` is not a good idea, the shadows assume that black is black

**Comment by josephwright** [comment]
I'd say redefining `black` is unsupported by any LaTeX package (we have discussed making this impossible in the `l3color` code).

**Comment by samcarter** [comment]
As a workaround (see #659):

```
\documentclass{beamer}
\usetheme{Warsaw}

\colorlet{foo}{black}
\usepackage{xpatch}
\xpatchcmd{\endbeamerboxesrounded}{\pgfsetcolor{black}}{\pgfsetcolor{foo}}{}{}

\definecolor{black}{RGB}{30,30,30}
\setbeamertemplate{blocks}[rounded][shadow=true]
\begin{document}
\begin{frame}
\begin{block}{Example}
\end{block}
\end{frame}
\end{document}
```

**Comment by samcarter** [comment]
closing this issue while waiting for a link to the theme file...
