### ISSUE TITLE
How to make Beamer work with Firestore data

### ISSUE THREAD

**Issue by KimAloy** [josephwright/beamer#774]
This is a question really because I've searched far and wide without finding a solution. Pardon my noviceness but the examples I've found aren't data from Firestore. I seek your help showing me how to overcome this error when I navigate to the next/details screen. 
Here's the router code:
```
routes: {
...
 '/advert/:id': (context, state, data) async {
 final String? propertyId = state.pathParameters['id'];
    final RentalAd cool = await FirebaseFirestore.instance // cool from here
 .collection(kTestRentalAds)
        .doc(propertyId)
        .get()
        .then((DocumentSnapshot doc) => RentalAd.fromFirestore(doc));
    return BeamPage(
      key: ValueKey('adverts-$propertyId'),
 title: 'Advert',
 child: SearchHouseDetailsPage(house: cool), // cool to here
 );
 }
}
```
Here's a link to the same stackoverflow question https://stackoverflow.com/questions/72508741/how-do-you-use-beamer-with-firestore. 
Kindly save me, thanks

**Comment by samcarter** [comment]
@KimAloy You'll probably have a higher chance to get a solution if you ask this somewhere where people know firestore, I don't think beamer expertise can help you with this

**Comment by KimAloy** [comment]
You are right. The problem was with my code not beamer. Thanks for everything and most importantly, thanks for the awesome beamer package.
