### ISSUE TITLE
Footlines in `miniframes` outer-theme makes BAD output with certain colour themes

### ISSUE THREAD

**Issue by CastleStar14654** [josephwright/beamer#775]
## In Short
When using `beaver` colour theme and `miniframes` outer theme with `authortitle` footline, the AUTHOR and PAGE NUMBER in the footline will blend with the background and be hard to recognize. (where AUTHOR and PAGE NUMBER should be are highlighted)
![image](https://user-images.githubusercontent.com/50725189/172376044-fc863d82-ec0c-4118-b191-43b3d4978889.png)

## Long Version
The outer-theme `miniframes` defined several handy footlines. For example, `authortitle`:
https://github.com/josephwright/beamer/blob/561aded831bd0c1b530480b130a2b7b9ea06a2cb/base/themes/outer/beamerouterthememiniframes.sty#L36-L53
The bg colour of the footline keeps being that of `title in head/foot`, while the fg colour *changes* from `title in head/foot` to `author in head/foot` and to `page number in head/foot`, which is unreasonable: what if the original bg colour is very similar to the new fg colour?

`miniframes` defined the colours of `title in head/foot` and  `author in head/foot` as those of `section in head/foot` and `subsection in head/foot`:
https://github.com/josephwright/beamer/blob/561aded831bd0c1b530480b130a2b7b9ea06a2cb/base/themes/outer/beamerouterthememiniframes.sty#L13-L14
For `beaver`, as an example, `section in head/foot` is reg bg, white fg, while `subsection in head/foot` is white bg, red fg.
This finally gives rise to these awful outputs: (from top to bottom: `authorinstitute`, `authortitle`, `institutetitle`, `authorinstitutetitle`. Unrecognizable texts are highlighted; all AUTHOR are linked with blue lines and all INSTITUTE with orange ones)
![image](https://user-images.githubusercontent.com/50725189/172377606-d252de6f-10f5-4985-8df5-6494b9748049.png)

I wonder if it is better not to change the fg colour in the halfway of the colorbox in footline?

**Comment by samcarter** [comment]
With all the possible colour- and outer themes, there will always be combinations for which the default settings are not optimal. Personally I only consider the main themes ready-for-use, for all custom combinations of outer- and colour themes, the users can change colours to avoid such problems.

CambridgeUS is the only main theme which uses the beaver colour theme. As it uses a footline with different background colours, it makes sense that the default values for the foreground colours are also different to be nicely readable.

Removing the different foreground colours from the minifames footline would take away flexibility for the user. For example in one of my themes, the whole footline uses red as foreground colour, just the frame number is dark blue. When I translated this theme from ppt to beamer, I thought this was a just a bug, but the corporate design people insisted that this is a feature. Long story short, the different foreground colours give the necessary flexibility to let beamer do whatever the user needs.
