### ISSUE TITLE
Graphics are offset by a few pixels when using center in some scenarios

### ISSUE THREAD

**Issue by Delzye** [josephwright/beamer#777]
Hi, I have the following problem:
I have three graphics, all have the same size and the content they all share is overlapping perfectly (tested that in GIMP with some transparency, the graphics are fine).

When I use the first two graphics, they overlap perfectly, same for second and third. But when I use all three, The first one is shifted to the left (or the other two to the right).
Unfortunately I don't know how to use demo instead of the actual graphics, since beamer includes the package.

Minimal example:

```
\documentclass{beamer}
\begin{document}
\begin{frame}
    \begin{center}
        \includegraphics<1>[height=0.8\textheight]{./x_square_l1.png}
        \includegraphics<2>[height=0.8\textheight]{./x_square_l2.png}
        \includegraphics<3>[height=0.8\textheight]{./x_square_l2_op.png}
    \end{center}
\end{frame}
\end{document}
```
This is the slides overlapping:
![image](https://user-images.githubusercontent.com/48919898/174446977-93b22648-6771-4557-be6e-4d1f686e120a.png)

This is the images overlapping:
![image](https://user-images.githubusercontent.com/48919898/174447023-519a3ed9-6363-499b-8d73-2203fbcb6bd4.png)

Interestingly, when using onslide* and centering for each image, there is a shift between each image, not just the first and rest:
```
    \onslide*<1>{\centering\includegraphics[height=0.8\textheight]{./x_square_l1.png}}
    \onslide*<2>{\centering\includegraphics[height=0.8\textheight]{./x_square_l2.png}}
    \onslide*<3>{\centering\includegraphics[height=0.8\textheight]{./x_square_l2_op.png}}
```
When using `\vspace{1cm}` instead of centering, the graphics are in the correct positions, no shifting.

**Comment by Delzye** [comment]
I just noticed, this also works using the same image, they don't have to be different.
So using this:
```
    \begin{center}
        \includegraphics<1>[height=0.8\textheight]{./x_square_l1.png}
        \includegraphics<2>[height=0.8\textheight]{./x_square_l1.png}
        \includegraphics<3>[height=0.8\textheight]{./x_square_l1.png}
    \end{center}
```
also produces a shift between the first and second slide.

**Comment by samcarter** [comment]
Missing `%` at the end of lines. This will act like a space. At the point you insert your last image, you will have accumulated multiple spaces.

```
\documentclass{beamer}
\begin{document}
\begin{frame}
    \begin{center}
        \includegraphics<1>[height=0.8\textheight]{example-image}%
        \includegraphics<2>[height=0.8\textheight]{example-image}%
        \includegraphics<3>[height=0.8\textheight]{example-image}%
    \end{center}
\end{frame}
\end{document}
```

**Comment by samcarter** [comment]
About the meta question how to use demo with beamer:

```
\documentclass[demo]{beamer}
```

**Comment by Delzye** [comment]
Thanks for the quick answer!
That indeed fixes it, I did not know about that part of LaTeX/the way that works.

**Comment by samcarter** [comment]
@Delzye  You're welcome!
