### ISSUE TITLE
Side-by-side multiinclude

### ISSUE THREAD

**Issue by MLopez-Ibanez** [josephwright/beamer#779]
```latex
\begin{frame}
\multiinclude[<+->][start=1,format=pdf]{left}
\multiinclude[<.->][start=1,format=pdf]{right}
\end{frame}
```
I was hoping that the above would generate:
```latex
\begin{frame}
\includegraphics{left-1.pdf}
\includegraphics{right-1.pdf}
\end{frame}
```
```latex
\begin{frame}
\includegraphics{left-2.pdf}
\includegraphics{right-2.pdf}
\end{frame}
```
and so on. However, it seems to only generate the sequence for the left graphics and only show right-N.pdf in the last frame.

Is this expected? If so, is there a way to generate the frames as described above?

**Comment by samcarter** [comment]
If you need more control than the standard macros offer, you can use e.g. `pgffor` to create the loop yourself:

```
\documentclass{beamer}

\usepackage{pgffor}

\begin{document}
	
\foreach \x  in {1,...,6}{
\begin{frame}
\includegraphics[width=2cm]{moon-\x}%
\includegraphics[width=2cm]{silly_vector_\x}%
\end{frame}
}
	
\end{document}
```

![document](https://user-images.githubusercontent.com/43832342/176022202-54e5115b-f917-44f1-a9c4-24d04ae4c6f1.gif)

**Comment by samcarter** [comment]
Or with just beamer tools:

```
\documentclass{beamer}

\makeatletter
\newcommand{\slideinframe}{\beamer@slideinframe}
\makeatother

\begin{document}
	
\begin{frame}
\includegraphics[width=2cm]{moon-\the\slideinframe}%
\includegraphics[width=2cm]{silly_vector_\the\slideinframe}%
\pause[6] % <- replace with how many images you have 
\end{frame}

\end{document}
```

**Comment by MLopez-Ibanez** [comment]
> Or with just beamer tools:

These are useful and lead me to this improvement over the solution I was using:

```latex
\documentclass{beamer}
\makeatletter
\newcommand{\slideinframe}{\beamer@slideinframe}
\makeatother
\begin{document}
\begin{frame}
\multiinclude[<+->][start=1,format=pdf]{moon-\the\slideinframe}%
\includegraphics[width=2cm]{silly_vector_\the\slideinframe}%
\pause[6] % <- replace with how many images you have of silly_vector_N 
\end{frame}
\end{document}
```
However, there is still the issue that:

1. I need to specify how many images I have.
2. I cannot specify if the images should completely replace the previous one or be showed on top.

**Comment by samcarter** [comment]
@MLopez-Ibanez  Are you looking for something like this (now using dummy images which should be included in every complete latex distribution, so one can simply copy and paste to test):

```
\documentclass{beamer}

\usepackage{xmpmulti}
\usepackage{pgffor}

\makeatletter
\newcommand{\slideinframe}{\beamer@slideinframe}
\makeatother
\begin{document}
\begin{frame}
\multiinclude[<+->][start=1,format=pdf,graphics={width=2cm}]{kdpcover-vol}%
%
\foreach \x in {1,...,\the\slideinframe}{%
  \rlap{\includegraphics[width=2cm]{kdpcover-vol-\x}}%
}%
\end{frame}
\end{document}
```

![document](https://user-images.githubusercontent.com/43832342/176258579-a03d1db3-bec6-46d9-93bc-f76abe2e69df.gif)


... or if you want to replace the image:


```
\documentclass{beamer}

\usepackage{xmpmulti}

\makeatletter
\newcommand{\slideinframe}{\beamer@slideinframe}
\makeatother
\begin{document}
\begin{frame}
\multiinclude[<+>][start=1,format=pdf,graphics={width=2cm}]{kdpcover-vol}%
\includegraphics[width=2cm]{kdpcover-vol-\the\slideinframe}%
\end{frame}
\end{document}
```

![document](https://user-images.githubusercontent.com/43832342/176258773-ff51656e-0669-4afe-830c-657cfdce89a6.gif)

**Comment by MLopez-Ibanez** [comment]
@samcarter Many thanks for your suggestions!
The last suggestion fails in 2 different ways:
 * If the first sequence has fewer files than the second, then you don't get the whole second sequence (even if you use `[<+->]`).
 * If the second sequence has fewer files than the first one, then you get a compilation error because it tries to read a non-existing image.

These can be worked-around by using some of the previous suggestions that specify the number of files in the second sequence, but it is not a perfect solution.

**Comment by samcarter** [comment]
> - If the first sequence has fewer files than the second, then you don't get the whole second sequence (even if you use [<+->]).
>  - If the second sequence has fewer files than the first one, then you get a compilation error because it tries to read a non-existing image.

Use `\multiinclude` for the sequence with more image, does not matter if it is the first or second sequence and then use `\IfFileExists` to test of the other file exist before including.
