### ISSUE TITLE
Height of non-text link in xelatex

### ISSUE THREAD

**Issue by samcarter** [josephwright/beamer#780]
Since somewhere between TL2016 and TL2017 non-text links are too height, e.g. the navigation symbols and miniframes in [this example](https://tex.stackexchange.com/q/649697/36296):

```
% !TeX TS-program = xelatex
\documentclass[]{beamer}
\usetheme{Berlin}
\title{Test}
\author{Testname}
\institute{Testing University}
\hypersetup{pdfborder=1 1 1}

\begin{document}

\section*{}
\begin{frame}
\titlepage
\end{frame}

\section{SecA}\subsection{sub1}\frame{Hello1a}\frame{Hello1b}\subsection{sub2}\frame{Hello2a}\frame{Hello2b}\subsection{sub3}\frame{Hello3a}\frame{Hello3b}
\section{SecB}\subsection{sub1}\frame{Hello4a}\frame{Hello4b}\subsection{sub2}\frame{Hello5a}\frame{Hello5b}\subsection{sub3}\frame{Hello6a}\frame{Hello6b}
\section{SecC}\subsection{sub1}\frame{Hello7a}\frame{Hello7b}\subsection{sub2}\frame{Hello8a}\frame{Hello8b}\subsection{sub3}\frame{Hello9a}\frame{Hello9b}
\end{document}
```

<img width="407" alt="Screenshot 2022-07-04 at 15 44 29" src="https://user-images.githubusercontent.com/43832342/177167629-f71fa392-945d-483f-b901-0b327dd45582.png">

The current beamer hack to place invisible `.` south west and north east of the non-text element might need to be replaced with https://github.com/josephwright/beamer/issues/332#issuecomment-774659976 , see experiments in this branch https://github.com/samcarter/beamer/tree/780-Height-of-non-text-link-in-xelatex

**Comment by samcarter** [comment]
fixed in #781

**Comment by kvafa** [comment]
I am sorry but this is a bad fix. It breaks right to left beamer documents in XeTeX.

````tex
\documentclass[]{beamer}
\usetheme{Berlin}
\title{Test}
\author{Testname}
\institute{Testing University}
\hypersetup{pdfborder=1 1 1}
\usepackage[RTLdocument]{bidi}
\begin{document}

\section*{}
\begin{frame}
\titlepage
\end{frame}

\section{SecA}\subsection{sub1}\frame{Hello1a}\frame{Hello1b}\subsection{sub2}\frame{Hello2a}\frame{Hello2b}\subsection{sub3}\frame{Hello3a}\frame{Hello3b}
\section{SecB}\subsection{sub1}\frame{Hello4a}\frame{Hello4b}\subsection{sub2}\frame{Hello5a}\frame{Hello5b}\subsection{sub3}\frame{Hello6a}\frame{Hello6b}
\section{SecC}\subsection{sub1}\frame{Hello7a}\frame{Hello7b}\subsection{sub2}\frame{Hello8a}\frame{Hello8b}\subsection{sub3}\frame{Hello9a}\frame{Hello9b}
\end{document}
````

>
<img width="1879" alt="Screen Shot 2022-07-11 at 2 13 17 PM" src="https://user-images.githubusercontent.com/105717562/178187472-9a9a15c3-67e9-49b0-93a4-b99fba437f83.png">

**Comment by samcarter** [comment]
@kvafa  Can you clarify what is broken in RTL documents?

**Comment by kvafa** [comment]
Sure. If you run the minimal example I provided above against your recent changes, you will see the issue in the navigation symbols at the bottom of each frame:

>
<img width="771" alt="Screen Shot 2022-07-11 at 6 09 05 PM" src="https://user-images.githubusercontent.com/105717562/178218445-6a449342-c9f3-434d-9193-779c3ed8d0b2.png">

It seems that your definition of the macro `\beamer@linkspace` in the file `beamerbasenavigation.sty` needs to take care of how TeX--XeT algorithm works.

````tex
    \def\beamer@linkspace#1{%
    \if@RTL
    \else
      \special{dvipdfmx:catch_phantom true height 8pt depth 1.5pt}%
     \fi
      \begin{pgfpicture}{0pt}{-1.5pt}{#1}{5.5pt}
      \end{pgfpicture}
      \if@RTL
      \special{dvipdfmx:catch_phantom true height 8pt depth 1.5pt}%
      \fi
    }
````

**Comment by samcarter** [comment]
@kvafa  Thank you for the clarifications!
