### ISSUE TITLE
listings: line numbers dont show up

### ISSUE THREAD

**Issue by Reissner** [josephwright/beamer#792]
Although, listings work fine inside beamer, line numbers dont show up in the presentation. 
In the handout in contrast all works fine. 

Edit: it seems as if the line numbers do show up but very much outside although in my case hboxes seem not to be overfull.

**Comment by samcarter** [comment]
Can you make a minimal working example? Are you using one of the themes with very narrow left margin, like `CambridgeUS`?

**Comment by samcarter** [comment]
With the default theme, they work fine

```
\documentclass{beamer} 

\usepackage{listings}

\lstset{numbers=left}

\begin{document}

\begin{frame}[fragile]
\begin{lstlisting}
content...
\end{lstlisting}
\end{frame}

\end{document}
```

**Comment by samcarter** [comment]
In case my guess about the narrow margin is true, you can either use a bigger margin 

```
\setbeamersize{text margin left=1cm}
```

or use something like

```
\documentclass{beamer} 

\usepackage{listings}
\usetheme{CambridgeUS}

\lstset{numbers=left,xleftmargin=0.5cm}

\begin{document}

\begin{frame}[fragile]
\begin{lstlisting}
content...
\end{lstlisting}
\end{frame}

\end{document}
```

**Comment by samcarter** [comment]
closing while waiting for further details
