### ISSUE TITLE
lstset does not work

### ISSUE THREAD

**Issue by Reissner** [josephwright/beamer#793]
In presentation, not in layout, of package listings the \lstset command has no effect on lstinputlisting 
if this is used within frame. 
Instead one has to repeat general settings again and again. 

Seems as if frame is a kind of border. I use fragile option.

**Comment by samcarter** [comment]
Please make a compilable minimal working example so we can reproduce your problem.

Each frame is its own group. If you want settings to affect all frames, you can move them to the preamble.

**Comment by samcarter** [comment]
closing while waiting for further details
