### ISSUE TITLE
When will the new version be released to CTAN?

### ISSUE THREAD

**Issue by GitPinkRabbit** [josephwright/beamer#798]
Sorry for pointing out, but it seems that we are having sufficient amount of commits compared with v3.67.

(In fact, I'm the one who can’t wait to use the new official version.) :joy:

**Comment by samcarter** [comment]
@josephwright  What do you think? Getting the (hopefully) repaired miniframes out might be nice for xelatex users.

**Comment by josephwright** [comment]
Sure, I'll look at it

**Comment by samcarter** [comment]
@josephwright  Great! Thanks!

**Comment by josephwright** [comment]
Done
