### ISSUE TITLE
[Feature request] allow regular expressions in \includeonlyframes

### ISSUE THREAD

**Issue by jlaurens** [josephwright/beamer#799]
Using labels is a convenient method to selectively include sets of frames.
The argument of \includeonlyframes is a list of static frame labels.
Turning this into a list of regular expressions would be very handy.
To ensure backwards compatibility, an \includeonlyframes* variant could be used for that purpose.

**Comment by josephwright** [comment]
Sorry, labels generally are simple strings.

**Comment by jlaurens** [comment]
Consider
```
\begin{frame}[label=f1]
...
\end{frame}
\begin{frame}[label=g1]
...
\end{frame}
\begin{frame}[label=f2]
...
\end{frame}
\begin{frame}[label=g2]
...
\end{frame}
```

With `\includeonly*{f.*}` it would be equivalent to
```
\begin{frame}[label=f1]
...
\end{frame}
\begin{frame}[label=f2]
...
\end{frame}
```
Whereas with `\includeonly*{g.*}` it would be equivalent to
```
\begin{frame}[label=g1]
...
\end{frame}
\begin{frame}[label=g2]
...
\end{frame}
```

**Comment by samcarter** [comment]
I don't know what your actual usecase is, but maybe have a look at the https://www.ctan.org/pkg/beameraudience package. This allows you to conditionally switch on/off groups of frames.
