### ISSUE TITLE
 The manual should mention that beamer loads package translator automatically

### ISSUE THREAD

**Issue by EvanAad** [josephwright/beamer#812]
Section 2.6 *Compatibility with Other Packages and Classes* of the manual should state that `beamer` loads package `translator` automatically, and that it loads the following dictionaries, provided by package `beamer`, automatically: `translator-basic-dictionary`, `translator-bibliography-dictionary`, `translator-environment-dictionary`, `translator-months-dictionary`, `translator-numbers-dictionary`, and `translator-theorem-dictionary`. See [here](https://github.com/josephwright/beamer/blob/865a19d4ec64f4c8e4935c19e162b8f4fd5aa190/base/beamerbasetranslator.sty).

**Comment by josephwright** [comment]
I'm not seeing why we'd need to: this is not about _compatibility_, rather _dependencies_. Loading `translator` won't interfere with any other packages as far as I know.
