### ISSUE TITLE
The file tl_packages is missing an entry for dependency amsthm

### ISSUE THREAD

**Issue by EvanAad** [josephwright/beamer#813]
The package `amsthm` is loaded by `beamer` immediately after `amsmath`, as can be seen [here](https://github.com/josephwright/beamer/blob/865a19d4ec64f4c8e4935c19e162b8f4fd5aa190/base/beamerbasetheorems.sty#L18), yet `amsthm`, unlike `amsmath`, isn't mentioned in [this list](https://github.com/josephwright/beamer/blob/c171ed2c6abfc2fb99378a0cf8655981cef0b855/.github/tl_packages) of packages that `beamer` depends on. I suggest that `amsthm` be included in this list of dependencies.

**Comment by samcarter** [comment]
The file you link to is an internal helper file for the github action job, which e.g. builds the user guide for testing. This is not a curated list of dependencies of the beamer class.

It contains several packages which have nothing to do with beamer, but are used by the user guide, e.g. makeindex.

**Comment by josephwright** [comment]
The two have different purposes, as @samcarter  says.
