### ISSUE TITLE
Advise (or at least document) the new way of creating document commands and environments

### ISSUE THREAD

**Issue by dbitouze** [josephwright/beamer#828]
Maybe it's time to advise (or at least document) the new way of creating document commands and environments. For instance, page 85 (of the current (3.68)) documentation, the example:
```latex
\newcommand<>{\makered}[1]{{\color#2{red}#1}}
```
could be replaced by:
```latex
\NewDocumentCommand{\newmakered}{ d<> m }{{\color<#1>{red}#2}}
```
More generally, the syntax:
```latex
\newcommand<>{⟨command name⟩}[⟨argument number⟩][⟨default optional value⟩]{⟨text⟩}
```
could be replaced by:
```latex
\NewDocumentCommand{⟨command name⟩}{ d<> ⟨arg spec⟩}{⟨text⟩}
```
with the description changed accordingly.

**Comment by samcarter** [comment]
There is already an example with `\NewDocumentCommand` on p. 86

https://github.com/josephwright/beamer/blob/7ea4816f890851abb425b972ca29b5c0b8bfa05a/doc/beamerug-overlays.tex#L548-L553

**Comment by dbitouze** [comment]
Oooops, sorry for the noise!

**Comment by samcarter** [comment]
For the time being, I'd also favour using beamer's adapted version of  `\renewcommad<>` etc.  over `\NewDocumentCommad` as the later does not retain the original definition.

```
\documentclass{beamer}

\usepackage{mdframed}

\renewenvironment<>{mdframed}[1][]{%
  \begin{originalmdframed}[#1]\color{red}%
}{%
  \end{originalmdframed}%
} 
  
\begin{document}
\begin{frame}
    \begin{mdframed}
        test
    \end{mdframed}
\end{frame}
\end{document}
```
