### ISSUE TITLE
Documentation's instruction for tableofcontents/subsubsectionstyle seems to be absurd

### ISSUE THREAD

**Issue by GitPinkRabbit** [josephwright/beamer#832]
It said that:

> `subsubsectionstyle=⟨style for current subsubsection⟩/⟨style for other subsubsections in current subsection⟩/⟨style for subsubsections in other subsections in current section⟩/⟨style for subsubsections in other subsections in other sections⟩` specifies how subsubsections should be displayed. The same styles as for the `sectionstyle` option may be given. You can omit the **last** style, in which case the **second** also applies to the last, and you can omit the **last two**, in which case the **first** applies to all. This option operates in an analogous manner to `subsectionstyle`.

Note the four places I wrote in bold. It seems that the text is just copied from `subsectionstyle` without any changes, and the words “second” and “first” do not seem right. And there's lacking a situation when omitting the last three styles.

**Comment by samcarter** [comment]
@GitPinkRabbit  Thanks for the report! I updated the wording to

> You can omit styles from the end of the list, in which case the last given style will also be applied to the omitted styles.
