### ISSUE TITLE
beamer and utf8x inputenc leads to Runaway argument error

### ISSUE THREAD

**Issue by ebuchlin** [josephwright/beamer#842]
Hello,

Beamer and inputenc with utf8x encoding have recently become incompatible, with this file:
```tex
\documentclass{beamer}
\usepackage[utf8x]{inputenc}

\begin{document}
\end{document}
```
producing errors starting by:
```
! Argument of � has an extra }.
<inserted text> 
                \par 
l.4 \begin{document}
                    
Runaway argument?
! Paragraph ended before � was complete.
<to be read again> 
                   \par 
l.4 \begin{document}
                    
! Argument of � has an extra }.
<inserted text> 
                \par 
l.4 \begin{document}
                    
Runaway argument?
! Paragraph ended before � was complete.
<to be read again> 
                   \par 
l.4 \begin{document}
                    
! Argument of � has an extra }.
<inserted text> 
                \par 
l.4 \begin{document}
(...)
```

A similar code worked last month. It still works with utf8 instead of utf8x. It still works with utf8x but with another class such as article (so it is not a utf8x inputenc-specific issue).

About my system:

* Up-to-date Ubuntu 22.10 PC
* LaTeX installation from Ubuntu packages:
  * pdflatex (pdfTeX 3.141592653-2.6-1.40.24) and inputenc.sty (2021/02/14 v1.3d) from texlive-latex-base 2022.20220722-1
  * beamer.cls (2022/05/17 v3.67) from texlive-latex-recommended 2022.20220722-1
  * utf8x.def (2004/10/17) from texlive-latex-extra 2022.20220722-2

**Comment by josephwright** [comment]
There are significant technical issues with the `utf8x` code, and it is not recommended for use at all. I do not plan to make any changes in `beamer` to try to keep it working.

**Comment by ebuchlin** [comment]
OK, I will use utf8 instead... Still an additional information for readers of this issue: although the packages seem not to have changed from last summer (at least), I have recently updated from Ubuntu 22.04 to 22.10.

**Comment by josephwright** [comment]
@ebuchlin  It's not your Ubunut version that's important, it's the LaTeX kernel release that you have; that will likely have been updated

**Comment by josephwright** [comment]
BTW, your example compiles fine with the latest TeX Live installation (TL'22 or TL'23-pretest)
