### ISSUE TITLE
animate.sty bug

### ISSUE THREAD

**Issue by si-me** [josephwright/beamer#851]
There is an error in the animate.sty

Here is a minimal example:
```
\documentclass{beamer}    
\usepackage[buttonsize=10pt,buttonbg=0.3,buttonfg=0.7]{animate}
\begin{document}
\begin{frame}\frametitle{Title}
Hello!
\end{frame}
\end{document}
```
and the relevant part of the log-file:
```
(/usr/local/texlive/2023/texmf-dist/tex/latex/ocgx2/ocgbase.sty)
Runaway argument?
.7:\@nil \global \let \@anim@@fgcolour \@anim@colour \ifnum \if@anim@dvips \ETC
.
/usr/local/texlive/2023/texmf-dist/tex/latex/animate/animate.sty:3626: Paragrap
h ended before \@anim@@colours was complete.
<to be read again> 
                   \par 
l.3626 
       
? 
```

Deactivating the line 3625  `\ProcessKeyOptions[anim@pkg]` eliminates the bug, i.e., the above example does not show the bug anymore.

**Comment by samcarter** [comment]
The same error occurs with article class, so it seems not directly connected to beamer:

```
\documentclass{article}
\usepackage[buttonsize=10pt,buttonbg=0.3,buttonfg=0.7]{animate}
\begin{document}
Hello!
\end{document}
```

You might want to report this to https://gitlab.com/agrahn/animate

**Comment by samcarter** [comment]
It seems this has already been reported: https://gitlab.com/agrahn/animate/-/issues/19
