### ISSUE TITLE
Frametitle of previously slide shown overlapped in next slide with new \frametitle{}

### ISSUE THREAD

**Issue by DDuck007** [josephwright/beamer#853]
Version 3.70 shows following problem:
The content of \frametitle{...} of the previous slide is also shown in the next slide - overlapped to the new \frametitle{...}.
Removing the command `\beamer@calculateheadfoot%` in line 456 solves the problem.

**Comment by samcarter** [comment]
Can you please add a minimal working example which reproduces the problem?

A simple 

```
\documentclass{beamer}

\begin{document}

\begin{frame}
\frametitle{title}
\end{frame}

\begin{frame}
\frametitle{abc}
\end{frame}


\end{document}
```

seems to work fine

**Comment by DDuck007** [comment]
... you are right, minimal example works => just removed the company-specific theme and it´s also ok - sorry ...

**Comment by samcarter** [comment]
If you could boil down your custom theme to a MWE which reproduces the problem, I could take a look if the problem can be avoided.

**Comment by DDuck007** [comment]
I will check the sty-files - but to be honest I am not sure if I can make a MWE ...

**Comment by DDuck007** [comment]
After some testing I think I was able to strip it down to a minium working example - see attachment.
[MWE_frametitle.zip](https://github.com/josephwright/beamer/files/11589287/MWE_frametitle.zip)

**Comment by samcarter** [comment]
Ah, the problem is that your theme sets the frametitle in the headline instead of using the frametitle template. 

I would recommend to set the frametitle in the frametitle template and not in the headline.

If you really must set it in the headline, you could work around the problem with 

```
\documentclass{beamer}
\usetheme{my_theme}
\usepackage[ngerman]{babel}

\AtBeginEnvironment{frame}{\gdef\insertframetitle{}}


\begin{document}

\begin{frame}
  \frametitle{Slide 1 - 1111}

  \LaTeX{} 

\end{frame}

%%%%%

\begin{frame}
  \frametitle{Slide 2 - 2222}

  \LaTeX{}
\end{frame}

\end{document}
```

**Comment by DDuck007** [comment]
I have no idea why the frametitle was placed in the headline - will check with my colleagues ...
Thank you very much for your help - works like a charm ;-).
