### ISSUE TITLE
Index page numbers in user guide should be hyperlinks

### ISSUE THREAD

**Issue by dbitouze** [josephwright/beamer#856]
It would be nice for index page numbers to be hyperlinks.

**Comment by samcarter** [comment]
Which package and tool do you use to create the index? Please add a MWE.

**Comment by dbitouze** [comment]
Sorry for being imprecise: I meant that index page numbers, _in the `beamer` documentation_, should be hyperlinks.

**Comment by samcarter** [comment]
ahhh, I would have never guessed that :)

**Comment by samcarter** [comment]
Enabling links in the index does not seem trivial. `hypdoc` seems to load hyperref with the `hyperindex=false` option.
