### ISSUE TITLE
Warning against using nonexistent templates

### ISSUE THREAD

**Issue by leingang** [josephwright/beamer#858]
I ran into a [problem](https://tex.stackexchange.com/q/689878/1402) today where I was browsing the source code for version 3.70 while using 3.69 on my machine. I was using templates that didn't exist and wondering why I was getting no output. Scanning the log file didn't give me any clues that that was the problem.

What about issuing a class warning that gets issued when the user `\use`s a template that hasn't been `\set`?

**Comment by samcarter** [comment]
I think a warning would be very inconvenient. Some templates are only defined by certain themes. If there were a warning, one would need to know which themes a user will load later to use them...
