### ISSUE TITLE
runcmd and ren in build.lua

### ISSUE THREAD

**Issue by SwitWu** [josephwright/beamer#861]
Sorry for this kindof off-topic question. In `build.lua` there are `runcmd` and `ren`.  Are they lua functions? I can not find them in the [lua 5.4 reference manual](https://www.lua.org/manual/5.4/).

**Comment by samcarter** [comment]
They are documented in [`l3build.pdf`](https://texdoc.org/serve/l3build/0):

> `ren(⟨dir⟩, ⟨source⟩, ⟨destination⟩)`:
> Renames the `⟨source⟩` file to the `⟨destination⟩` name within the `⟨dir⟩`; returns an error level.

---

> `runcmd(⟨cmd⟩,⟨dir⟩,{⟨envvars⟩})`:
> A generic function which runs the `⟨cmd⟩` in the `⟨dir⟩`, first setting up all of the environmental variables specified to point to the local and working directories. This function is useful when creating non-standard typesetting steps.

**Comment by SwitWu** [comment]
thanks!
