### ISSUE TITLE
`\appendix` throws hyperref warning

### ISSUE THREAD

**Issue by dcampagnari** [josephwright/beamer#864]
Using the example code on page 103 of the manual or even a simple
```
\documentclass{beamer}
\begin{document}
\appendix
\end{document}
```
gives the warning
```
Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `\translate ' on input line 4.
```
I haven't used `beamer` in a while so sadly I can't pinpoint the moment when this started `:-(`

**Comment by samcarter** [comment]
Duplicate https://github.com/josephwright/beamer/issues/449

**Comment by dcampagnari** [comment]
Uh, I definitely missed that. Sorry for the noise.

**Comment by samcarter** [comment]
@dcampagnari  No worries :)

**Comment by samcarter** [comment]
@dcampagnari  No worries :)
