### ISSUE TITLE
overlayarea takes space even with height 0

### ISSUE THREAD

**Issue by gqqnbig** [josephwright/beamer#868]
```latex
\documentclass{beamer}

\begin{document}
\begin{frame}[t]
%
\begin{overlayarea}{0pt}{0pt}\gdef\x{Hello}\end{overlayarea}%
\begin{overlayarea}{0pt}{0pt}\gdef\y{World}\end{overlayarea}%
\begin{overlayarea}{0pt}{0pt}something else\end{overlayarea}%
\begin{overlayarea}{0pt}{0pt}\end{overlayarea}%
\begin{overlayarea}{0pt}{0pt}\end{overlayarea}%
\begin{overlayarea}{0pt}{0pt}\end{overlayarea}%
\begin{overlayarea}{0pt}{0pt}\end{overlayarea}%
\begin{overlayarea}{0pt}{0pt}\end{overlayarea}%
%
\x \y

\end{frame}
\end{document}
```

The output is this

![texstudio_JDEHidq81h](https://github.com/josephwright/beamer/assets/614159/5f0aaf42-2b28-46d1-85bf-e9438d5d1e7b)

The environment overlayarea certainly occupies space.

But since I specify the height 0pt, it should in my opinion take 0pt height.

Can you fix this bug?

**Comment by samcarter** [comment]
You can switch off the space between new lines like this:

```
\documentclass{beamer}

\begin{document}
\begin{frame}[t]

\offinterlineskip
\begin{overlayarea}{0pt}{0pt}\gdef\x{Hello}\end{overlayarea}%
\begin{overlayarea}{0pt}{0pt}\gdef\y{World}\end{overlayarea}%
\begin{overlayarea}{0pt}{0pt}something\end{overlayarea}%
\begin{overlayarea}{0pt}{0pt}\end{overlayarea}%
\begin{overlayarea}{0pt}{0pt}\end{overlayarea}%
\begin{overlayarea}{0pt}{0pt}\end{overlayarea}%
\begin{overlayarea}{0pt}{0pt}\end{overlayarea}%
\begin{overlayarea}{0pt}{0pt}\end{overlayarea}
\strut\color{red}\x \y

\end{frame}
\end{document}
```

![document-1](https://github.com/josephwright/beamer/assets/43832342/edbc23af-4fbc-49c5-9e54-1f707562cb60)

**Comment by gqqnbig** [comment]
beameruserguide only says "Everything within the environment will be placed in a rectangular area of the specified size."

Probably my fundamentals are not solid, but the user guide doesn't mention the margin of the rectangular area. 

Can you add some text like "the margin (or line skip) of the area is determined by xxxx, even if you specify the height of the area to 0pt"?

**Comment by davidcarlisle** [comment]
The overlay area is not adding a margin, the space is the space added in the source file, just as `X X`  is wider than `XX` or closer to the example

```
X
X
```

is wider than

```
X%
X
```

Here the letter X is not adding a mrgin it just has or does not have a space after it.  The overlay area is the same (except it has no width)

**Comment by gqqnbig** [comment]
The command \offinterlineskip for sure works like a charm. It's defined in latex2e to change a bunch of lineskip thingummy. 

Is my understanding correct that overlayarea will create a paragraph and vertical space will be created?

I'm not sure whether all environments in latex create a paragraph, if not, probably it's worth noting it in the user guide.

**Comment by samcarter** [comment]
`overlayarea` internally uses a `\vbox`, so it basically boils down to https://tex.stackexchange.com/questions/274147/extra-interline-glue-between-vboxes
