### ISSUE TITLE
`allowframebreaks` is not honored for labeled slides

### ISSUE THREAD

**Issue by amonakov** [josephwright/beamer#872]
Noticed while investigating #866 

```latex
\documentclass{beamer}
\begin{document}
\begin{frame}[label=x,allowframebreaks]
1
  \vskip20cm
2
\end{frame}
\begin{frame}[allowframebreaks]
1
  \vskip20cm
2
\end{frame}
\end{document}
```
The second slide is broken up, the first is not.

**Comment by samcarter** [comment]
`allowframebreaks` also causes problems with some other options. There *is* a reason that the beamer user guide has the following to say about the option:

> The use of this option is evil.
