### ISSUE TITLE
appendixframenumber does not work with frame numbers

### ISSUE THREAD

**Issue by jolars** [josephwright/beamer#875]
It seems like the `appendixframenumber` option to the `page number in head/foot` template has no effect when it is used together with the `frame number` option of the `footline` template. Here is a working example:

```latex
\documentclass{beamer}

\setbeamertemplate{page number in head/foot}[appendixframenumber]
\setbeamertemplate{footline}[frame number]

\begin{document}

\begin{frame}
  \frametitle{A Slide Before the Appendix}
\end{frame}

\appendix

\begin{frame}
  \frametitle{A Slide In the Appendix}

  This slide is in the appendix and is (incorrectly?) counted towards the total number of main frames.
\end{frame}

\end{document}
```

The first slides looks like this:

![image](https://github.com/josephwright/beamer/assets/13087841/ee29b53c-e466-4ba3-bd28-930e7e8f0388)

But I would expect the frame numbering to be 1/1 here, not 1/2.

The last slide looks like this:

![image](https://github.com/josephwright/beamer/assets/13087841/cca1eab7-1f1e-48fc-91db-d16b5d7c2237)

The frame numbering is 2/2 but I would expect it to be 2/1.

If I use `\setbeamertemplate{footline}[page number]` instead, then it works as expected (I get 1/1 and 2/1), but I would assume that this would work when using frame numbers also. I am using beamer 3.69.

**Comment by samcarter** [comment]
With an up-to-date beamer version it works if you first set the `footline` template and then adjust the `page number in head/foot` template to your liking:

```
\documentclass{beamer}

\setbeamertemplate{footline}[frame number]
\setbeamertemplate{page number in head/foot}[appendixframenumber]


\begin{document}

\begin{frame}
  \frametitle{A Slide Before the Appendix}
\end{frame}

\appendix

\begin{frame}
  \frametitle{A Slide In the Appendix}

  This slide is in the appendix and is (incorrectly?) counted towards the total number of main frames.
\end{frame}

\begin{frame}
  \frametitle{A Slide In the Appendix}

  This slide is in the appendix and is (incorrectly?) counted towards the total number of main frames.
\end{frame}

\end{document}
```

![document-1](https://github.com/josephwright/beamer/assets/43832342/73996360-0849-4889-becc-6aa1f929c003)

**Comment by jolars** [comment]
If you mean that changing the order of the commands would matter, then I think not. And I already tried it. I still get 1/3, 2/3, and 3/3.

**Comment by samcarter** [comment]
Changing the order works with beamer v3.70 or newer. And yes, the order of the commands does matter because `\setbeamertemplate{footline}[frame number]` will set the `page number in head/foot` and thus overwrite what you previously set.

**Comment by jolars** [comment]
> Changing the order works with beamer v3.71. And yes, the order of the commands does matter because `\setbeamertemplate{footline}[frame number]` will set the `page number in head/foot` and thus overwrite what you previously set.

Alright, thanks! I couldn't find anything in the changelog regarding this so I figured it bug would still be around. Okay, thanks again!
