### ISSUE TITLE
in article mode, \newline fails if ragged2e is used

### ISSUE THREAD

**Issue by u-fischer** [josephwright/beamer#900]
In the second frame the `\newline` doesn't produce a new line anymore:

~~~~
\documentclass{article}
\usepackage{ragged2e}
\usepackage{beamerarticle}

\begin{document}
\begin{frame}
aaaa\newline bbbb
\end{frame}

\begin{frame}
\RaggedRight
aaaa\newline bbbb
\end{frame}
\end{document}
~~~~

![image](https://github.com/josephwright/beamer/assets/4047173/d2ac4430-60a8-47c7-b30d-6f2e07574993)

The problem is that with `\ragged2e` `\newline` uses internally `\@centercr`  which is redefined by beamer. 

A possible fix would be to redefine the ragged2e definition to use the beamer variant of `\@centercr`:

~~~~
\documentclass{article}
\usepackage{ragged2e}
\usepackage{beamerarticle}
\makeatletter
\def\@raggedtwoe@centercrNoindent{%
  \AddToHookNext{para/begin}{%
    \ifx\@raggedtwoe@everyselectfont\relax\else
      \OmitIndent
    \fi
  }%
   \beamer@origbreakcenter
}
\makeatother
\begin{document}
\begin{frame}
aaaa\newline bbbb
\end{frame}

\begin{frame}
\RaggedRight
aaaa\newline bbbb
\end{frame}
\end{document}
~~~~

![image](https://github.com/josephwright/beamer/assets/4047173/a490caa1-64a9-4692-b40e-575ef3df972b)

**Comment by samcarter** [comment]
Thanks for the report!

**Comment by samcarter** [comment]
fixed in https://github.com/josephwright/beamer/pull/901/commits/f44f62ecc6f7e5a0ff0dd6fe5035589c741865d0
