### ISSUE TITLE
Some issues in the doc

### ISSUE THREAD

**Issue by SwitWu** [josephwright/beamer#909]
Here are some issues that I found in the documentation:

- [x] Section 12.4: the complete list lacks `lemma`, `problem`, `solution`,`Proof`, `Theorem`, `Corollary`, `Example`, `Examples` and `Definition`.
- [x] Section 4.6.2: "The easiest way to print a presentation is to user *(user should be use)*"
- [x] "This options" should be "This option", I found five places by searching tool.
- [x] Section 9.3: in the last of this section, the second newline `\\` in the `align` environment is redundant since it will produce a new empty equation line with tag `(3)`
- [ ] Section 18.3.1: at the start of this section, "As for colors, every beamer element, like the frame titles, the document title, the footnotes, and so on has a certain beamer-font *(font should be color)*. As for colors *(colors should be fonts)*, on the one hand you can specify the font of each element individually"
- [x] Section 12.1: "`\insertsubsubenumlabel` inserts the current number of the second-level *(second should be third)* enumeration"
- [x] Section 12.2: "This text is inserted at the beginning of a *(a should be deleted)* an `alertenv` environment."
- [x] Section 12.4: "At the end of the theorem *(theorem should be proof)*"
- [x] Section 12.4: "The default \qed symbol is an open circle *(circle should be square)*"
- [x] Section 12.5: at the start of this section, "you can use LATEXs *(should be LATEX's)* standard command `\fbox`"

**Comment by samcarter** [comment]
Thanks for spotting these issues!

>  Section 18.3.1: at the start of this section, "As for colors, every beamer element, like the frame titles, the document title, the footnotes, and so on has a certain beamer-font (font should be color). As for colors (colors should be fonts), on the one hand you can specify the font of each element individually"

I think `beamer-font` is correct here. I understand it in the sense: "Like explained for beamer colours in the previous section, every element also has a certain beamer-font". Reworded it a bit to make it clearer.

**Comment by SwitWu** [comment]
+ [x] Section 9.6.3: "Some overlay specification-aware commands cannot (*should be can*)"
+ [ ] Section 11.2: the first example should be `\begin{itemize}[<alert@+>]`
+ [x] Section 18.2.1: "extsize" should be "extsizes" (several places)

**Comment by samcarter** [comment]
Thanks!

> Section 11.2: the first example should be `\begin{itemize}[<alert@+>]`

This seems to be equivalent to the current code, any particular reason why it should be changed?

**Comment by SwitWu** [comment]
> Thanks!
> 
> > Section 11.2: the first example should be `\begin{itemize}[<alert@+>]`
> 
> This seems to be equivalent to the current code, any particular reason why it should be changed?

Sorry for this. I spotted these issues according to the HTML manual (https://www.beamer.plus/Structuring-Presentation-The-Interactive-Global-Structure.html#sec-11.2) and did not notice that the HTML version lacks the alert specifications which exist in the PDF version. Please ignore my second suggestion. :-)

**Comment by samcarter** [comment]
That's not an official version of the beamer manual.

**Comment by SwitWu** [comment]
I'm the author and maintainer of this HTML manual. 😜

**Comment by samcarter** [comment]
> I'm the author and maintainer of this HTML manual. 😜

The version number `Version 3.7.0` looks wrong.

**Comment by SwitWu** [comment]
> The version number `Version 3.7.0` looks wrong.

Thanks! I'll fix that.
