### ISSUE TITLE
Incompatibility between beamer and ucs

### ISSUE THREAD

**Issue by rlaboiss** [josephwright/beamer#921]
I found a corner case that causes an error when combining beamer with the ucs package. Compilation of the following file:
```tex
\documentclass{beamer}
\usepackage{ucs}
\title{\\}
\begin{document}
\end{document}
```
fails with this error message:
```
! Missing } inserted.
<inserted text> 
                }
l.4 \begin{document}
```
This following two files compile correctly:
```tex
\documentclass{beamer}
\title{\\}
\begin{document}
\end{document}
```
```tex
\documentclass{beamer}
\usepackage{ucs}
\title{\newline}
\begin{document}
\end{document}
```

These are the versions that I am using:

- LaTeX2e <2024-11-01>
- beamer 2024/01/06 v3.71
- ucs 2023/11/09 v2.4

**Comment by samcarter** [comment]
Do you actually need the ucs package? There might be better solutions to whatever made you use it.

**Comment by davidcarlisle** [comment]
The ucs package is incompatible with latex's support for input encodings, it is maintained for legacy compatibility for some documents that were specifically using its commands but it should not be used with new documents.

**Comment by rlaboiss** [comment]
@samcarter and @davidcarlisle, thanks for your replies. Feel free to close this issue.
